### ISSUE TITLE
"ui:template" schema option

### ISSUE THREAD

**Issue by loganvolkers** [mozilla-services/react-jsonschema-form#1010]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

For more theming control a `"ui:template"` option would be helpful. From what I can tell this would be a fairly simple matter to integrate three places:
 - `SchemaField`
 - `ObjectField`
 - `ArrayField`

This would build on the work in #304.

#### Expected behavior

People could use custom templates to customize layout. This would be the most pertinent for objects and arrays, but can only be useful for leaf nodes too.

```
const uiSchema = {
  "ui:template": GroupedObjectTemplate,
  title: {
    "ui:template": InlineField
  }
  done: {
    "ui:template": ErrorsInTooltip
  },
  comments: {
    "ui:template": InlineArray
  }
};
```

### Alternative 1 - External plugin

Currently as a workaround this behaviour can be (almost) achieved externally. The biggest blocker to making it easier to achieve externally is that the default template objects are not exported.

```
import React from "react";
// TODO: Would be useful to 
import {
  DefaultObjectFieldTemplate,
  DefaultFieldTemplate,
  DefaultArrayItem
} from "./DefaultTemplates";

export function FieldTemplate(props) {
  const Template = props.uiSchema["ui:template"];
  if (
    Template &&
    // TODO: LV: Seems strange that this is required to be plugged in... oh well
    props.schema.type !== "object" &&
    props.schema.type !== "array"
  ) {
    return <Template {...props} />;
  } else {
    return <DefaultFieldTemplate {...props} />;
  }
}

export const ObjectFieldTemplate = defaultOrComponent(
  DefaultObjectFieldTemplate
);
export const ArrayFieldTemplate = defaultOrComponent(DefaultArrayItem);

function defaultOrComponent(DefaultTemplate) {
  return function(props) {
    const Template = props.uiSchema["ui:template"];
    if (Template) {
      console.error("Can't render", Template, props);
      return <Template {...props} />;
    } else {
      return <DefaultTemplate {...props} />;
    }
  };
}
```
And then use that on your `Form`
```
  import * as UiTemplate from "...";
  
  const fm = <Form
    schema={schema}
    uiSchema={uiSchema}
    onChange={log("changed")}
    onSubmit={log("submitted")}
    onError={log("errors")}
    transformErrors={log("transformErrors")}
    liveValidate={true}
    formContext={{
      templates: Templates.GroupTemplates
    }}
    {...UiTemplate}
  >
```

### Alternative 2 - "ui:field"

"ui:field" is very powerful, but it requires too much re-implementation of core behaviour to get right, particularly for things like arrays and objects.

## Recommendation

I would recommend tackling this in phases, getting simpler functionality merged in earlier, and complex functionality merged in later.

*Phase 1* allow templates as objects

 - Before: `const Template = registry.ObjectFieldTemplate || DefaultObjectFieldTemplate;`
 - After: `const Template = uiSchema["ui:template"] || registry.ObjectFieldTemplate || DefaultObjectFieldTemplate;`

*Phase 2* allow templates as strings, add `templates` to registry, allow custom templates map, add default templates to default registry

*Phase 3* themes for other ui libraries

## Resolution

If the maintainers of this repository are on-board, then I can work on a pull request.

**Comment by MatejMazur** [comment]
Something like [this](https://github.com/MatejMazur/react-jsonschema-form)? 

Related issue: #899

**Comment by loganvolkers** [comment]
Yes, exactly!

How do we help get that merged?

**Comment by MatejMazur** [comment]
I don't know @glasserc didn't response yet. 

But I'm afraid that this is a lot of changes so it's not so easy to just merge completely restructured library (my version is split into multiple packages: core, bootstrap and in the future there will be boilerplate package for third party themes). 

But you can use it today. It's just published under `@react-schema-form/bootstrap` (or if you want to build a completely custom theme then you can use directly `@react-schema-form/core`, [here is guide](https://github.com/MatejMazur/react-jsonschema-form#as-a-npm-based-project-dependency)).

If you find any issues, don't hesitate and tell me it.

**Comment by loganvolkers** [comment]
If you can create a pull request, I would highly recommend it, even with
the substantial rewrite. Fragmentation sucks.

It would just need to be documented as a major version change. I'd be happy
to help contribute to integrating you work.

On the other hand if for some reason it doesn't get integrated, happy to
contribute the smaller patch required to just add this feature, but I might
steal your naming `ui:FieldTemplate` instead of or as an alternative to
`ui:template`.

**Comment by MatejMazur** [comment]
Ok, but I need to update readme because there are some differences like replaced `Form.props.FieldTemplate` with `Form.props.templates.FieldTemplate` and etc.

The problem is that readme is so looong. :smile: 

Oh and btw I've changed my mind with `ui:FieldTemplate` because it's not so useful. I'm just using something like this:

`./myTemplates/MyFieldTemplate.js`
```js
import { templates } from '@react-schema-form/bootstrap'

const FieldTemplate = props => {
  if (myCondition) {
    return <MyFieldTemplate {...props} />;
  }
  return <templates.FieldTemplate {...props} />;
};

export default FieldTemplate;
```

`./MyForm.js`
```js
import Form from '@react-schema-form/bootstrap';

import myTemplates from './myTemplates';

export default props => <Form templates={myTemplates} {...props} />;
```

**Comment by MatejMazur** [comment]
I think I've found the way how to keep codebase the same and still support everything what I've done. :slightly_smiling_face: 
But I need some time for it.

**Comment by loganvolkers** [comment]
Nice, looks promising. Now we wait for contributors...

**Comment by loganvolkers** [comment]
@epicfaace I think this feature would have a small API surface area change, but also give a lot of power for theming.

In particular, this is useful for doing object layouts and array layouts from left right, or with wrapper elements, or custom styles.

![image](https://user-images.githubusercontent.com/1157086/51505955-854d8880-1d9e-11e9-8fc0-144556e7e2cb.png)

**Comment by epicfaace** [comment]
@loganvolkers Yes, `ui:template` is a great idea and it also wouldn't break backwards compatibility so it would be easier to merge than @MatejBransky 's PR.

**Comment by loganvolkers** [comment]
@epicfaace Great I'll work on getting something wired up.

**Comment by epicfaace** [comment]
Do you think it would be useful to have a `ui:TitleField` and `ui:DescriptionField`? This would be for the use case in which one wants to override a title / description field for a specific field, but doesn't want to necessarily override the entire field template. I'm thinking specifically of #1146 .
