### ISSUE TITLE
Safari macos. Date(Datepicker) does not work correctly. The calendar is not displayed.

### ISSUE THREAD

**Issue by iiefremov** [mozilla-services/react-jsonschema-form#1011]
![screen shot 2018-08-24 at 5 42 49 am](https://user-images.githubusercontent.com/18754340/44562101-add64580-a760-11e8-9112-cafa6b6dafd4.png)

**Comment by glasserc** [comment]
Safari appears not to support `date` or `datetime` input types. https://caniuse.com/#search=date
