### ISSUE TITLE
Don't re - draw, when update `UiSchema`

### ISSUE THREAD

**Issue by valjusha** [mozilla-services/react-jsonschema-form#1012]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Don't update form from UiSchemas

### Steps to Reproduce

When updating the 'hubsVariants' (from props), the form gets a new description, but does not change UiSchema. Why?
The re-rendering of the render occurs and the circuit is generated anew.

```
import Form from 'react-jsonschema-form'

const GeneralInfoUiSchema = {}; // default UiSchema (for example - empty)

class General extends React.PureComponent<IProps, {}> {
    render() {
        return this.form;
    }


    get form() {
        return Form<IGeneralInfo>(this.formProps);
    }

    get formProps() {
        const { formData } = this.props;

        return {
            uiSchema: this.uiSchema,
            // ... another properties
        };
    }

    get uiSchema(): UiSchema {
        const { hubsVariants } = this.props;
        const generalUiSchema = { ...GeneralInfoUiSchema };

        if (this.isHubs) {
            delete generalUiSchema.HubId['ui:field'];
            generalUiSchema.HubId['ui:options'] = {
                Hubs: this.treeHubs(hubsVariants),
            };
        } else {
            generalUiSchema.HubId['ui:field'] = Fields.WireFramingFieldTemplate;
        }
    }

    get isHubs(): boolean {
        return this.props.hubsVariants.length > 0;
    }
}
```

#### Expected behavior

replace template (ui:field) for `generalUiSchema.HubId`

#### Actual behavior

Nothing.

I tried to update the state of the component, but this did not solve the problem. I see that the new 'UiSchemas'  are applied in the form. But she does not react in any way. Why is that?

### Version

1.0.2

**Comment by loganvolkers** [comment]
Could you create a [SSCCE](http://sscce.org/) on Codesandbox.io to reproduce this behaviour? That will help diagnose any bug.

**Comment by valjusha** [comment]
I created an example (in a vacuum), and everything works there.
Therefore, the error is somewhere in my code.
