### ISSUE TITLE
Proposal: move the playground into the CodeSandbox

### ISSUE THREAD

**Issue by MatejBransky** [mozilla-services/react-jsonschema-form#1015]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I think that CodeSandbox would be a better choice in these days because you don't need to use a custom editor component, you'll have all the needed tools for editing and it can be connected with a custom GitHub repository. By the way development would be less stressful as you don't need to worry about the strange behavior in the actual playground (it's quite normal that development in the new project is working but in the playground not because there are problems with JSX in uiSchema or two way data binding which goes against the React principles).

This change would require to separate playground from this repository. If you want to develop something in the library you can clone both repositories (library and playground) and link the local version of library in the playground so you can watch all the changes immediately.

[Here is an example](https://codesandbox.io/s/2416l7z45j?module=%2Fsrc%2Fexamples%2Fsimple.js) of my first attempt to create a similar playground with Bootstrap 4 (it's not identical but it can be).

What do you think?

I can make a PR.

**Comment by epicfaace** [comment]
Looks good @MatejBransky ! It does look better than the playground, feel free to do a PR.

@glasserc

**Comment by glasserc** [comment]
The whole point of the project is to support React, which means that when the schema changes, the components should adapt. That's easy to do in the current playground but I don't see how you could do it using CodeSandbox. I also really like how easy it is to click from example to example to make sure there's nothing wrong with any of them.

Neither of the above are strong objections so feel free to overrule them if you like.

**Comment by epicfaace** [comment]
> The whole point of the project is to support React, which means that when the schema changes, the components should adapt. That's easy to do in the current playground but I don't see how you could do it using CodeSandbox. I also really like how easy it is to click from example to example to make sure there's nothing wrong with any of them.
> 
> Neither of the above are strong objections so feel free to overrule them if you like.

That's right, I didn't realize that CodeSandbox didn't let you update the schema easily, so we probably shouldn't do this. (As to the second point, the code sandbox does have a dropdown with different examples, though.)

**Comment by epicfaace** [comment]
I'll close this then; I don't think we should go with this, but @MatejBransky if you have more thoughts feel free to comment.
