### ISSUE TITLE
Tips & Tricks don't seem to work with 1.0.4 release

### ISSUE THREAD

**Issue by struankl** [mozilla-services/react-jsonschema-form#1022]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Try out any of the tips & tricks links to jsfiddle. None work and error in console: 
Uncaught ReferenceError: JSONSchemaForm is not defined

Downgrading to 1.0.3 the fiddles work as expected.

**Comment by loganvolkers** [comment]
Is this related? https://github.com/mozilla-services/react-jsonschema-form/issues/991

**Comment by glasserc** [comment]
I also think this is a duplicate of #991.
