### ISSUE TITLE
Reading schema from file

### ISSUE THREAD

**Issue by veeral-patel** [mozilla-services/react-jsonschema-form#1029]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hi! I'm wondering if it's possible to read the schema in from a file, say `schema.json`.

I'd like to be able to write something like this -

```
Form schema={"./schema.json"}
```

And have it render the form.

I have gotten the form to render by importing JSON from the file, eg -

```
import * as schema from './schema.json`

const Foo = (props) => Form schema={schema};
```

But imagine if I'm conditionally rendering one of two forms -

```
const Foo = (props) => {
    if (props.form1 === true) {
        import * as schema1 from 'schema1.json';
        return <Form schema={schema2} />;
   } else {
       import * as schema2 from 'schema2.json'
       return <Form schema={schema2} />;
   }
}
```

This feels really hacky...is there a better way? Amazing job on this project by the way!

**Comment by llamamoray** [comment]
I don't think it's too hacky but you could probably clean up your code a little. I'd write it something like this:

Store the schemas in a js file so you can define them as exports:

```JS
// schemas.js

export const specialSchema = { title: 'Choc caramel pecan ice cream', .... };
export const defaultSchema = { title: 'Vanilla ice cream', ... };
```

then import where you want to use them:

```JS
// IcecreamForm.jsx

import Form from 'react-jsonschema-form';
import { specialSchema, defaultSchema } from './schemas'

export default function ({ isSpecialIcecream }) {
  return <Form schema={ isSpecialIcecream ? specialSchema : defaultSchema } />;
}
```

**Comment by glasserc** [comment]
I think it's unlikely that rjsf will add special support for reading schema from a file. I think @llamamoray 's suggestion is good and hope it's suitable.
