### ISSUE TITLE
enums with one choice fail

### ISSUE THREAD

**Issue by schatzmanj** [mozilla-services/react-jsonschema-form#1032]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by schatzmanj** [comment]
The issue seems to be whether a type that is an enum containing a single choice should be any different from a specific (non-enum) type.

**Comment by schatzmanj** [comment]
Ethan-

Sure. It throws exceptions and does not render the form.

We can go about this from another direction.

1) What is the exact supported oneOf Json schema and data?

2) How does this change in the case where the oneOf reduces to a single option? It may well be that there is a way to get the Jsonschema Form Builder to work with enums of one choice but what is the supported schema?

3) An different but related question but which crops up in implementing oneOfs is why does Jsonschema Form Builder not support refs instead of explicit types in the oneOf?  This seems to mean that if the type options are complex then serious schema bloat results because the type definitions have to be spelled out redundantly...

Thanks!




________________________________________

**Comment by glasserc** [comment]
I was unable to reproduce exceptions using this schema:

```
{
  "title": "Person",
  "type": "object",
  "properties": {
    "Do you have any pets?": {
      "type": "string",
      "enum": [
        "Yes: One"
      ],
      "default": "Yes: One"
    }
  },
  "required": [
    "Do you have any pets?"
  ],
  "dependencies": {
    "Do you have any pets?": {
      "oneOf": [
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: One"
              ]
            },
            "How old is your pet?": {
              "type": "number"
            }
          },
          "required": [
            "How old is your pet?"
          ]
        }
      ]
    }
  }
}
```

I was also unable to reproduce exceptions with this schema:

```

{
  "title": "Person",
  "type": "object",
  "properties": {
    "Do you have any pets?": {
      "type": "string",
      "enum": [
        "Yes: One"
      ],
      "default": "Yes: One"
    }
  }
}
```

Without a reproducible case or even description of the exception, I can't really help with this.

Per the [FAQ](https://github.com/mozilla-services/react-jsonschema-form#q-does-rjsf-support-oneof-anyof-multiple-types-in-an-array-etc), `oneOf` is not generally supported. There is a specific exception for something called "schema dependencies", which see [here](https://github.com/mozilla-services/react-jsonschema-form#schema-dependencies). (This is what I used in my first example, above.)

Hope this helps.
