### ISSUE TITLE
Issue in understanding reference

### ISSUE THREAD

**Issue by Mike-Branham** [mozilla-services/react-jsonschema-form#1036]
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

It is likely my lack of knowledge in how references are suppose to work.  Please let me know if this is not the proper place for this.

I have a very large form that has many repeating items, that I want to not have to copy and paste elements over and over.  Below is a sample with just 2 elements in the initial drop down, the first element in the drop down works, because it really does nothing.  The second one has 2 references (there would be more items, just simplifying here.

The goal is about 50 items in the drop down that has various dynamic elements based on what was selected.

When I select the second item, nothing happens, so there is obviously something wrong.

Hoping the experts here can help point me in the right direction, and also that there is actually a solution.  I can certainly paste all the repeating items in each one (there are about 5 of them), however believed that was the reference would do.

Thanks
-Mike

{
  "title": "Operations",
  "type": "object",
  "properties": {
    "operator": {
      "title": "Select Operation",
      "$ref": "#/definitions/operator"
    }
  },
  "definitions": {
    "check_box": {
      "type": "object",
      "properties": {
        "type": "boolean",
        "title": "Some check box",
        "default": false
      }
    },
    "options": {
      "type": "object",
      "properties": {
        "type": "string",
        "enum": [
          "option1",
          "option2",
          "option3",
          "option4"
        ],
        "enumNames": [
          "Option 1",
          "Option 2",
          "Option 3",
          "Option 4"
        ],
        "default": "option1",
        "title": "Output Option"
      }
    },
    "operator": {
      "title": "Operation",
      "type": "object",
      "properties": {
        "Operation": {
          "type": "string",
          "enum": [
            "operator1",
            "operator2"
          ],
          "enumNames": [
            "Operation 1",
            "Operation 2"
          ],
          "default": "operator1"
        }
      },
      "required": [
        "Operation"
      ],
      "dependencies": {
        "Operation": {
          "oneOf": [{
              "properties": {
                "Operation": {
                  "enum": [
                    "operator1"
                  ]
                }
              }
            },
            {
              "properties": {
                "Operation": {
                  "enum": [
                    "operator2"
                  ]
                },
                "get_check": {
                  "$ref": "#/definitions/check_box"
                },
                "get_options": {
                  "$ref": "#/definitions/options"
                }
              }
            }
          ]
        }
      }
    }
  }
}

**Comment by glasserc** [comment]
Reformatting your schema:

```
{
  "title": "Operations",
  "type": "object",
  "properties": {
    "operator": {
      "title": "Select Operation",
      "$ref": "#/definitions/operator"
    }
  },
  "definitions": {
    "check_box": {
      "type": "object",
      "properties": {
        "type": "boolean",
        "title": "Some check box",
        "default": false
      }
    },
    "options": {
      "type": "object",
      "properties": {
        "type": "string",
        "enum": [
          "option1",
          "option2",
          "option3",
          "option4"
        ],
        "enumNames": [
          "Option 1",
          "Option 2",
          "Option 3",
          "Option 4"
        ],
        "default": "option1",
        "title": "Output Option"
      }
    },
    "operator": {
      "title": "Operation",
      "type": "object",
      "properties": {
        "Operation": {
          "type": "string",
          "enum": [
            "operator1",
            "operator2"
          ],
          "enumNames": [
            "Operation 1",
            "Operation 2"
          ],
          "default": "operator1"
        }
      },
      "required": [
        "Operation"
      ],
      "dependencies": {
        "Operation": {
          "oneOf": [
            {
              "properties": {
                "Operation": {
                  "enum": [
                    "operator1"
                  ]
                }
              }
            },
            {
              "properties": {
                "Operation": {
                  "enum": [
                    "operator2"
                  ]
                },
                "get_check": {
                  "$ref": "#/definitions/check_box"
                },
                "get_options": {
                  "$ref": "#/definitions/options"
                }
              }
            }
          ]
        }
      }
    }
  }
}
```

Your schema has a problem, but it's nothing to do with references. Pasting it into the playground shows some validation errors from ajv, which validates the schema itself before using it to check data.

The problem is that in your use of the `"properties"` property. The value of `"properties"` should be an object with the keys being the name of the property and the value being the schema of the property. So you should have something like

```
{
  "properties": {
    "someProp": {
      "type": "whatever", ....
    }
  }
}
```

Here's a schema that is what I think you might be going for:

```
{
  "title": "Operations",
  "type": "object",
  "properties": {
    "operator": {
      "title": "Select Operation",
      "$ref": "#/definitions/operator"
    }
  },
  "definitions": {
    "check_box": {
      "type": "boolean"
    },
    "options": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "option1",
          "option2",
          "option3",
          "option4"
        ],
        "enumNames": [
          "Option 1",
          "Option 2",
          "Option 3",
          "Option 4"
        ],
        "default": "option1",
        "title": "Output Option"
      }
    },
    "operator": {
      "title": "Operation",
      "type": "object",
      "properties": {
        "Operation": {
          "type": "string",
          "enum": [
            "operator1",
            "operator2"
          ],
          "enumNames": [
            "Operation 1",
            "Operation 2"
          ],
          "default": "operator1"
        }
      },
      "required": [
        "Operation"
      ],
      "dependencies": {
        "Operation": {
          "oneOf": [
            {
              "properties": {
                "Operation": {
                  "enum": [
                    "operator1"
                  ]
                }
              }
            },
            {
              "properties": {
                "Operation": {
                  "enum": [
                    "operator2"
                  ]
                },
                "get_check": {
                  "$ref": "#/definitions/check_box"
                },
                "get_options": {
                  "$ref": "#/definitions/options"
                }
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by Mike-Branham** [comment]
Perfect, thank you so much.  Learned a bit more as well from this.
