### ISSUE TITLE
Override ArrayFieldTemplate for a specific case

### ISSUE THREAD

**Issue by fbring** [mozilla-services/react-jsonschema-form#1038]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
I tried to customize the rendering of an array.

I found that I can use [ArrayFieldTemplate](https://github.com/mozilla-services/react-jsonschema-form#array-field-template) for a general manipulation, which works great, but I need to customize each array on it´s own.

In my example there is a `images` and a `persons` array. I would like to have a "base" rendering for arrays, but I would like to override it for the case of `images`. In this case I tried to override it with the `ui:field` key of the `uiSchema`.

Maybe it´s just me and I didn't understand the docs, but I spent a lot of time to figure things out and still do not achieved the expected behavior.

### Steps to Reproduce
1. Open [my example](https://codesandbox.io/s/m8qoy5nl8)
2. Open the console in your dev-tools.
3. Compare both logs.

#### Expected behavior
I would expect to get access to the same props in my `uiSchema.images['ui:field']` as I have access to in the general `ArrayFieldTemplate`.

#### Actual behavior
The `uiSchema` has totally different props than `ArrayFieldTemplate`

### Version
1.0.4

**Comment by glasserc** [comment]
When using `ui:field`, you aren't using a template, but rather a custom field. It has the same props as ArrayField.

**Comment by fbring** [comment]
Ah, thanks @glasserc I did not know that.

But do you know the solution for my problem, is there any other way I can override the template for a specific case?

**Comment by glasserc** [comment]
No, there is no way at present.

**Comment by fbring** [comment]
I found a workaround, which might be helpful to other people.

First of all I create a custom key/value pair inside of `'ui:options'`:
``` js
const uiSchema = {
  image: {
    images: {
      'ui:options': {
        myTemplate: 'image',
      },
    },
  },
};
```

And inside my `ArrayFieldTemplate()` I check whether this key is set and matches or it doesn't.

``` js
function ArrayFieldTemplate(props) {
   if (props.uiSchema['ui:options'].myTemplate === 'image') {
      // render image-specific template
   } else {
      // render default template
   }
}
```

I don't know if this is the best solution, but it works for me.

**Comment by chertkovalex** [comment]
Hi @fbring ! Thanks for your workaround. A've also tried something like this, and it works.
Now can you please post more expanded example?
How do you choose a right template from several templates?
And what is returned as default template?
