### ISSUE TITLE
No default value on nested field

### ISSUE THREAD

**Issue by perusopersonale** [mozilla-services/react-jsonschema-form#1043]
### Prerequisites

- [ x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I have a complex schema that is something like this:
```
{
 	"type": "object",
 	"properties": {
 		"type": {
 			"title": "Test",
 			"enum": ["foo", "bar"]
 		}
 	},
 	"dependencies": {
 		"type": {
 			"oneOf": [{
 					"properties": {
 						"type": {
 							"enum": ["foo"]
 						},
 						"algo_params": {
 							"$ref": "#/definitions/foo_params"
 						}
 					}
 				},
 				{
 					"properties": {
 						"type": {
 							"enum": ["bar"]
 						},
 						"algo_params": {
 							"$ref": "#/definitions/bar_params"
 						}
 					}
 				}
 			]
 		}
 	},
 	"additionalProperties": false,
 	"definitions": {
 		"foo_params": {
 			"type": "object",
 			"properties": {
 				"basic": {
 					"type": "object",
 					"properties": {
 						"test1": {
 							"type": "integer",
 							"default": 50,
 							"minimum": 1,
 							"maximum": 1000000
 						}
 					},
 					"additionalProperties": false,
 					"required": ["test1"]
 				},
 				"advanced": {
 					"type": "object",
 					"properties": {},
 					"additionalProperties": false
 				}
 			},
 			"additionalProperties": false,
 			"required": ["basic", "advanced"]
 		},
 		"bar_params": {
 			"type": "object",
 			"properties": {
 				"basic": {
 					"type": "object",
 					"properties": {
 						"test2": {
 							"type": "number",
 							"title": "",
 							"default": 0.1,
 							"minimum": 0,
 							"maximum": 1
 						}
 					},
 					"additionalProperties": false,
 					"required": ["test2"]
 				},
 				"advanced": {
 					"type": "object",
 					"properties": {
 						"test3": {
 							"type": "number",
 							"default": 1,
 							"minimum": 0,
 							"maximum": 1
 						}
 					},
 					"additionalProperties": false,
 					"required": ["test3"]
 				}
 			},
 			"additionalProperties": false,
 			"required": ["basic", "advanced"]
 		}
 	}
 }
```
When I use on Playground and select a type default values are correctly populated,
when I'm trying to use on my project default values are not shown.

Working example [Playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0eXBlIjoiZm9vIiwiYWxnb19wYXJhbXMiOnsiYmFzaWMiOnsidGVzdDIiOjAuMSwidGVzdDEiOjUwfSwiYWR2YW5jZWQiOnsidGVzdDMiOjF9fX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0eXBlIjp7InRpdGxlIjoiVGVzdCIsImVudW0iOlsiZm9vIiwiYmFyIl19fSwiZGVwZW5kZW5jaWVzIjp7InR5cGUiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsidHlwZSI6eyJlbnVtIjpbImZvbyJdfSwiYWxnb19wYXJhbXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvZm9vX3BhcmFtcyJ9fX0seyJwcm9wZXJ0aWVzIjp7InR5cGUiOnsiZW51bSI6WyJiYXIiXX0sImFsZ29fcGFyYW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL2Jhcl9wYXJhbXMifX19XX19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsImRlZmluaXRpb25zIjp7ImZvb19wYXJhbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYmFzaWMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGVzdDEiOnsidHlwZSI6ImludGVnZXIiLCJkZWZhdWx0Ijo1MCwibWluaW11bSI6MSwibWF4aW11bSI6MTAwMDAwMH19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInJlcXVpcmVkIjpbInRlc3QxIl19LCJhZHZhbmNlZCI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6e30sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZX19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInJlcXVpcmVkIjpbImJhc2ljIiwiYWR2YW5jZWQiXX0sImJhcl9wYXJhbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYmFzaWMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidGVzdDIiOnsidHlwZSI6Im51bWJlciIsInRpdGxlIjoiIiwiZGVmYXVsdCI6MC4xLCJtaW5pbXVtIjowLCJtYXhpbXVtIjoxfX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZSwicmVxdWlyZWQiOlsidGVzdDIiXX0sImFkdmFuY2VkIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRlc3QzIjp7InR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJtaW5pbXVtIjowLCJtYXhpbXVtIjoxfX0sImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjpmYWxzZSwicmVxdWlyZWQiOlsidGVzdDMiXX19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInJlcXVpcmVkIjpbImJhc2ljIiwiYWR2YW5jZWQiXX19fSwidWlTY2hlbWEiOnt9fQ==)

Test repo where default values are not shown:
https://jsfiddle.net/w1Lom0av/2

I'm not understanding why have different behavior.
#### Expected behavior

Default values shown. What I'm missing??

**Comment by perusopersonale** [comment]
Ok if I handle onChange, update state, this rerender form and it works.
I think this should be the default behavior without the need to refresh form.

**Comment by epicfaace** [comment]
@perusopersonale  -- the jsfiddle you sent is no longer working at all

**Comment by epicfaace** [comment]
Let me know if you have any other problems.
