### ISSUE TITLE
Error in componentWillReceiveProps

### ISSUE THREAD

**Issue by isychev** [mozilla-services/react-jsonschema-form#1045]
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
In componentWillReceiveProps, this is called  this.props.onChange(nextState) but onChange takes the formData 
https://github.com/mozilla-services/react-jsonschema-form/commit/9813483ab19f235690b85f9337610a4189979d73#diff-07a63ede6fe55fca89398d42da737369R33

componentWillReceiveProps must called  this.props.onChange(nextState.formData);
also problem in constructor

### Version
1.0.5

**Comment by llamamoray** [comment]
Hi @isychev,

What makes you think this? On change has always been called with state here: https://github.com/mozilla-services/react-jsonschema-form/blob/9813483ab19f235690b85f9337610a4189979d73/src/components/Form.js#L132 

Is there a specific problem that you're seeing?

**Comment by llamamoray** [comment]
The documentation states that I change receives the same props as onSubmit which is am object with a formData attribute.

**Comment by isychev** [comment]
@llamamoray  You're right. Thanks.  It is necessary to work less in the evening )
