### ISSUE TITLE
Custom Array Template no props.items

### ISSUE THREAD

**Issue by romanzpolski** [mozilla-services/react-jsonschema-form#1050]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I used template referenced in documentation to create custom array template, but some how items is not available in props so the thing is not displaying children elements.

### Steps to Reproduce

1. Go to sandbox: [SandBox](https://nrnzwql3qp.codesandbox.io/dnd-form)

2. Open developer tools

<img width="421" alt="screen shot 2018-10-16 at 23 11 19" src="https://user-images.githubusercontent.com/16594772/47051061-946adc00-d19a-11e8-8682-948a9b81fe83.png">

3. Here is [Custom Array Field Template File](https://github.com/romanzpolski/react-app/blob/master/src/Components/DndArrayField/DndArrayFieldTemplate.js)

4. And here schemas
```javascript

const schema = {
    type: "object",
    required: ["lat", "lon"],
    title: "form title",
    properties: {
        lat: {
            title: "raz",
            type: "number"
        },
        lon: {
            title: "dwa",
            type: "number"
        },
        arrayDnd: {
            type: "array",
            items: {
                title: "title",
                type: "string"
            }
        }
    }
};

const uiSchema = {
    "arrayDnd": {
        "ui:field": "dnd"
    }
};
const fields = {
    dnd: DndArrayFieldTemplate
};

```

#### Expected behavior
props.items not available in custom array field template

#### Actual behavior
props.items available in custom array field template

### Version
1.0.5

Please help

**Comment by loganvolkers** [comment]
So looks like you've switched up **Custom Field** versus **Custom Template** for array fields.

 Field  | Template  
------------ | -------------
Overrides all behaviour  | Only overrides layout
------------ | -------------
"ui:field": "dnd" |  `<Form schema={schema} ArrayFieldTemplate={ArrayFieldTemplate} />`
------------ | -------------
https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#field-props | https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#array-field-template

**Comment by romanzpolski** [comment]
Thank you for coming back to me and for good explanation of this difference.
