### ISSUE TITLE
Custom field empty field validation should work as default  field

### ISSUE THREAD

**Issue by ritchieanesco** [mozilla-services/react-jsonschema-form#1052]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Custom string field validation should work as per the default inputs. When a user populates a custom field and then clears it there is no error messaging.

### Steps to Reproduce

1. Click on the submit button under "Form with custom input".
2. Error messages should appear.
3. Add a single character into the field under "Form with custom input". Click submit button.
4. Error messages have been removed.
5. Clear the field under "Form with custom input". Click submit button.

https://codesandbox.io/s/mq514nn8r8

#### Expected behavior

Error messaging should be displayed when custom inputs are empty and required, as per the default input fields.

#### Actual behavior

No error messaging is displayed once a user clears the field.

### Version
1.0.5

**Comment by glasserc** [comment]
We've had a long and storied history of what an empty form element "means". See e.g. #289 and #539. Your custom widget calls `onChange()` with an empty string but in the case where the contents are missing, it should probably call it with an `emptyValue` like the builtin `BaseInput` does.
