### ISSUE TITLE
Single select field with multiple select option

### ISSUE THREAD

**Issue by usmanarif** [mozilla-services/react-jsonschema-form#1062]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Currently I have a requirement of using single select box allowing user to select multiple values. For now only checkbox is allowing me to select multiple value at one go but bot select box. For now user can add multiple select box and can select the unique item each time.
Is there any way to add only one select box providing the feature to select and add multiple values?

**Comment by glasserc** [comment]
The builtin `ArrayField` uses `isMultiSelect` from `utils.js` to check whether it should render an array as a `<select multiple>`. It seems the basic logic is "is the schema `"type": "array"` with `"uniqueItems": "true"` and `items` with `enum`". You can see it in action by going to the "Arrays" section of the playground and clearing the `ui:widget` from the `multipleChoicesWidget` field.

**Comment by cnwangjie** [comment]
Is it possible to use single my custom multiple select widgets without enum? I hope the multiple select components allow a user to enter any content, like [this](https://codepen.io/anon/pen/BXQvJQ?&editable=true&editors=001).

I tried to set `ui:field ` but I can't use the original label. How can I make it and I can use the original label part?
