### ISSUE TITLE
Submit form programmatically

### ISSUE THREAD

**Issue by stuartwhitehall** [mozilla-services/react-jsonschema-form#1075]
Is this working in 1.0.5? I don't seem to have a submit method on my form.

**Comment by glasserc** [comment]
No, this feature is not available in 1.0.5.

**Comment by thomaskleiven** [comment]
@glasserc, do you know why this feature is not available? Thank you in advance.

**Comment by glasserc** [comment]
The feature was implemented after v1.0.5.
