### ISSUE TITLE
Split Form.js

### ISSUE THREAD

**Issue by isychev** [mozilla-services/react-jsonschema-form#1080]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Good afternoon. Thank you for the wonderful library. I have a proposal for optimization. React-jsonschema-form is not friends with redux because Form.js is a very smart component. Can you split the Form.js into two components: silly component (only renders props) and smart component - makes the validation and manages state. If you agree, I can make a PR and discuss.

**Comment by llamamoray** [comment]
I use the library with redux. Wrap the form in a react-redux container and hook up the onChange, onSubmit, onError props to call action creators. 

Unless there's something I'm missing with your use case?

**Comment by isychev** [comment]
if you have asynchronous validation? It is very difficult to add errors to fields

**Comment by glasserc** [comment]
I'm not really interested in maintaining that. rjsf is already too complicated. It sounds like what you want is a generic form library. rjsf isn't that.
