### ISSUE TITLE
CheckboxesWidget - Disabled support per Enum.

### ISSUE THREAD

**Issue by skyckp123** [mozilla-services/react-jsonschema-form#1081]
https://github.com/mozilla-services/react-jsonschema-form/blob/a9afe48adf5791c2054b58b851e51a9634a2f96e/src/components/widgets/CheckboxesWidget.js#L23

Currently array of checkboxes with enum. The disabled property for each checkbox is taken from base component.

We need support for disable per enum.

There is a ui:enumDisabled property in uiSchema which is not propagated to CheckboxesWidget.

(RadioWidget.js has this support.)

**Comment by epicfaace** [comment]
Fixed in #1082 .
