### ISSUE TITLE
Reference data from other property 

### ISSUE THREAD

**Issue by paintedbicycle** [mozilla-services/react-jsonschema-form#1083]
Hello,

I'm struggling to find out if it is possible to not only reference the _structure_ of a node as in the example below, but also the **data** in one of the answers to the form.

From your examples:
```
  "properties": {
    "billing_address": {
      "title": "Billing address",
      "$ref": "#/definitions/address"
    },
    "shipping_address": {
      "title": "Shipping address",
      "$ref": "#/definitions/address"
    },
```

So, let's say that I take the above example and now want a new section, called "Addresses" that is an array (comprised of both types of addresses since the follow exactly the same structure) and lists the data that was entered in the other sections of the form. It would in this case be duplicate data, yes, but I have a need for it. Is it possible?

In my case, I want the person to be able to enter _investment asset_ data - data that contains both the asset itself (think a mortgage with a total value) as well as the inherent _debt_. In the example of a mortgage, the property is an asset, but the remaining amount left that you must continue to pay off is a debt. So in the case of a mortgage, it is both an asset _and_ a debt.

Now, in a different form (or different part of the same form) I want to allow the user to list (in an array) all their debts. I'd like my form to include (pre-populate) the debt information from the mortgage, so they don't enter it twice.

How I can put the the asset info (the mortgage) also (repeated) into the debt section using only the json form schema (rather than manipulating the form data)? Is it possible?

I'd like the reference to be "live". i.e., I'd like it, that if you edit the duplicated data, it would update it back in the original location in the form.

Thanks!

Paul

**Comment by glasserc** [comment]
As far as I know, JSON Schema does not offer a way for one field to refer to the value of another field.
