### ISSUE TITLE
can't make input array in a single field

### ISSUE THREAD

**Issue by ioterateam** [mozilla-services/react-jsonschema-form#1103]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Is there a way to produce **array input** in a **single field**? Because I already use your library, but for array input, it create a new field for every single array.

#### Expected behavior

I expected array input will be shown like this

![image](https://user-images.githubusercontent.com/29442149/49779047-92587000-fd3a-11e8-8a75-b640c32f60bd.png)

#### Actual behavior

But its show like this

![input array](https://user-images.githubusercontent.com/29442149/49779333-15c69100-fd3c-11e8-9b5a-ee318eeefca2.PNG)

### Version

Currently i used version : "react-jsonschema-form": "^1.0.6"

**Comment by glasserc** [comment]
rjsf doesn't offer many options for how to display form data. Any customization of the HTML generated should happen in your code. It sounds like you could achieve what you want using a [custom field](https://github.com/mozilla-services/react-jsonschema-form#custom-field-components).
