### ISSUE TITLE
Minor Validation issue with Numbers

### ISSUE THREAD

**Issue by Sushil231088** [mozilla-services/react-jsonschema-form#1106]
There is a minor validation issue with the Number field. 

AR: When you type in decimals with additional zero at the end it shows error and as soon as you type any number after the zero, the error goes away. Please refer to the screenshots.
![formvalidationfornumbers-1](https://user-images.githubusercontent.com/25085564/49858271-7b894a80-fe1a-11e8-930b-21d6841672d2.png)
![formvalidationfornumbers-2](https://user-images.githubusercontent.com/25085564/49858274-7d530e00-fe1a-11e8-98ea-8ecc51627fca.png)

ER: If the input field has an additional zero digit at the end of a decimal, no error should be shown.

**Comment by glasserc** [comment]
JavaScript does not have any way to distinguish the number `3.0` from `3`. As a result, if a user types `3.0`, we treat it as a string to make sure that we preserve user input. While this is unfortunate, I don't have a solution in mind. Closing in favor of #674.
