### ISSUE TITLE
Why not pass props.registry to ArrayFieldTemplate?

### ISSUE THREAD

**Issue by gigahunter** [mozilla-services/react-jsonschema-form#1113]
I write my own ArrayFieldTemplate, and add new Widget.
But, I can't find my new Widget in ArrayFieldTemplate, because ArrayField not pass the props.registry to ArrayFieldTemplate.

Can anyone tell me why not pass props.registry to ArrayFieldTemplate?
And suggest a way to do the situation.

**Comment by epicfaace** [comment]
I have a use case for this -- I need to render a dropdown widget on an ArrayFieldTemplate in which the user selects the number of items, and I'd like to use the SelectWidget from the registry for this.
