### ISSUE TITLE
Custom Array and Custom Object Examples Broke on GitHub Pages Site

### ISSUE THREAD

**Issue by agilliam-cmg** [mozilla-services/react-jsonschema-form#1114]
### Description

I'd like more clarity on how to implement a react-jsonschema-form custom array template or a custom object template, however, the **UISchema** for these examples don't show on https://mozilla-services.github.io/react-jsonschema-form/ page.  Instead, the UISchema of the last example selected shows when clicking on either the "Custom Array" or "Custom Object" links.  Please update these examples so I may be enlightened :)

### Steps to Reproduce

1. Navigate to https://mozilla-services.github.io/react-jsonschema-form/ in browser
2. Click on "Custom Array" example link
3. Click on "Custom Object" example link

#### Expected behavior

The UISchema for these two examples to be displayed in the UISchema pane

#### Actual behavior

The UISchema of the previously clicked on example displays instead

### Version

This seems to have been happening since February 2018 and possibly before...

**Comment by glasserc** [comment]
There are no `uiSchema` for either example, which is why the previous `uiSchema` sticks around. I've pushed a "fix" which provides a `uiSchema` of `{}` if none is provided.

**Comment by agilliam-cmg** [comment]
Thanks for responding @glasserc. I'm not a contributor to this project, but I'm pretty sure the Custom Array and Custom Object examples are supposed to have a uiSchema. That's what makes them custom, right? Is there a way that I can see the code (uiSchema) in the playground area on GitHub Pages that makes the Custom Array form look different than the default. It looks like a uiSchema is being used somewhere...

**Comment by glasserc** [comment]
Like I said, there is no `uiSchema` for either the custom array or custom object example. What makes them custom is their use of a [field template](https://github.com/mozilla-services/react-jsonschema-form#field-template). The code for the playground is in this same repository that contains the code for the library -- here is [customArray](https://github.com/mozilla-services/react-jsonschema-form/blob/master/playground/samples/customArray.js) and [customObject](https://github.com/mozilla-services/react-jsonschema-form/blob/master/playground/samples/customObject.js).

**Comment by agilliam-cmg** [comment]
THANKS @glasserc ! Very helpful info!
