### ISSUE TITLE
Find a better name for this lib

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#112]
We're getting a lot of negative feedback with the name of this lib (long, hard to remember, hard to type, typo prone, etc.)

Could you guys come with a better, simpler, shorter name?

**Comment by n1k0** [comment]
Ideas: 

- reform, reforms
- refield
- formidable

**Comment by magopian** [comment]
- rjsf
- schemaform

**Comment by Natim** [comment]
- react-forms

**Comment by matiaslarsson** [comment]
* jsform

**Comment by n1k0** [comment]
* refill
* refuel
* formwesome
* reschema

**Comment by matiaslarsson** [comment]
Or maybe just drop -form and call it "react-jsonschema"?

**Comment by n1k0** [comment]
- conformed, conformism, conformist
- formalized, formalism, formalist, formalistic
- formally
- filiform
- formable
- reformat, reformate
- formatters
- formidably
- formlessly
- formulary
- formulation
- formworks
- informal
- informed
- informs
- omniform
- reformable, reformed, reformist, reformism
- transforms
- uniformed
- uniforms

**Comment by MoOx** [comment]
react-json-form or react-jsonform

**Comment by apkoponen** [comment]
As an outsiders note: I probably found this lib only because it matched my search "react json schema forms".

**Comment by n1k0** [comment]
@apkoponen tbh that was exactly my initial intent ;)

So... Maybe the name is actually okay after all. Serious and boring, but okay.

**Comment by MoOx** [comment]
Maybe react-json-schema-form is better (the additional dash might help).

**Comment by mohsen1** [comment]
The name of this project is good IMO. It made it super easy for me to find it.

**Comment by n1k0** [comment]
> The name of this project is good IMO. It made it super easy for me to find it.

I agree. People find and know about us. Closing this.
