### ISSUE TITLE
Content Security Policy (CSP) reporting unsafe eval usage 

### ISSUE THREAD

**Issue by alexbrazhenko** [mozilla-services/react-jsonschema-form#1121]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

CSP returns the following error 

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src ....."
```

Error comes from 

```
var makeValidate = new Function('self', 'RULES', 'formats', 'root', 'refVal', 'defaults', 'customRules', 'co', 'equal', 'ucs2length', 'ValidationError', sourceCode);
```

Is this by design? Any plans to change that behavior? 

### Steps to Reproduce

1. Add Content-Security-Policy header with value "script-src 'self' " to response.
2. Try to submit any form 

#### Expected behavior

No CSP errors

#### Actual behavior

Got this error 

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src ....."
```

### Version

1.0.5

**Comment by glasserc** [comment]
The code you cite comes from [ajv](https://github.com/epoberezkin/ajv), which we use to validate data against a JSON schema. It probably generates code as an optimization to make schema validation fast. I don't have any plans to change that dependency.

**Comment by samclearman** [comment]
You should remove ajv as a dependency - allowing unsafe eval is irresponsible.

**Comment by fstn** [comment]
Same here I'm blocked because of that, my project doesn't allow unsafe eval
