### ISSUE TITLE
looking for select all checkbox implementation 

### ISSUE THREAD

**Issue by somnathswami33** [mozilla-services/react-jsonschema-form#1122]
### Prerequisites
Select All checkbox  do true to multiple check boxes
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior
Select All checkbox  do true to multiple check boxes
[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by glasserc** [comment]
I'm sorry, I don't understand.

**Comment by somnathswami33** [comment]
@glasserc Please find the attached image 
![checkbox](https://user-images.githubusercontent.com/46105358/51099813-e3a3c580-17f8-11e9-9645-df2d089bf0ba.png)
once user checked on select all then i want all the listed checkbox need to be checked.
that kind of implementation i needed for developing dynamic form generation application

**Comment by glasserc** [comment]
react-jsonschema-form is not likely to offer this functionality natively. You can probably implement it yourself using a custom widget similar to `CheckboxesWidget`.
