### ISSUE TITLE
0 integers return as undefined

### ISSUE THREAD

**Issue by Y-Less** [mozilla-services/react-jsonschema-form#1128]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When I have a numeric input as 0 with no default set in the schema (or enum input), it is returned as `undefined`.  I've tracked the problem to this line:

https://github.com/mozilla-services/react-jsonschema-form/blob/b5a286af95a917f3bc52ea825544d448bb71cb8e/src/utils.js#L190

`formData` is `0`, so despite being valid the undefined `defaults` is returned instead.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

Returns `0`.

#### Actual behavior

Returns `undefined`.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
Closing this, but @Y-Less , let me know if you have any more information.
