### ISSUE TITLE
Old version (rjsf) is still on npm

### ISSUE THREAD

**Issue by epicfaace** [mozilla-services/react-jsonschema-form#1136]
The library `rjsf` is still published on npm, with version 1.0.4. Can we either remove this library or sync it with `react-jsonschema-form`? https://www.npmjs.com/package/rjsf

**Comment by glasserc** [comment]
I don't think I have permissions on that project. @edi9999 ?

**Comment by edi9999** [comment]
Indeed, I had published this package.

I have just deprecated the package with following message : 

`'This package is deprecated in favor of the "react-jsonschema-form" package which is maintained.'`
