### ISSUE TITLE
Set up a documentation site

### ISSUE THREAD

**Issue by epicfaace** [mozilla-services/react-jsonschema-form#1138]
We should transition away from using a very long README.md for docs and generate a documentation site instead. 

I was thinking https://readthedocs.org/ -- any other suggestions? @glasserc @edi9999

**Comment by edi9999** [comment]
+1 for readthedocs, it provides clean documentation, with also documentation per version, PDF export.

One example on another project I maintain : https://docxtemplater.readthedocs.io/en/latest/

**Comment by epicfaace** [comment]
I don't have admin access to this repo, so @glasserc you may need to set it up with readthedocs.

**Comment by pubudu-ranasinghe** [comment]
Please consider bringing back the docs in readme. The separate site makes it extremely difficult to navigate. Having everything in one page with the ToC made it so much easier to quickly navigate and find the references.
IMO the docs are not large enough to warrant a different website.

**Comment by epicfaace** [comment]
@pubudu-ranasinghe the docs _are_ really long, it was getting unwieldy to keep it in a README.

Could you explain a bit more about what difficulties you are facing? The categories on the sidebar may definitely need to be better reorganized, but I had just copied over the same title from the README for the time being when doing the docs. The docs site does have a "Search..." feature -- does that not work for your navigation/references need?

**Comment by pubudu-ranasinghe** [comment]
I guess you are right. It is too long. In the readme I knew where everything was(almost from muscle memory)
For example,
One tricky thing I always come back to is how to use `oneOf` It was somewhat difficult to find. I have to come to the repo. Scroll down to find the doc site link. Go there and find the definitions.

But this is unavoidable I guess.
