### ISSUE TITLE
schema should be object or boolean

### ISSUE THREAD

**Issue by Ab1d** [mozilla-services/react-jsonschema-form#1151]
### Prerequisites

- [* ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

I am getting this error while importing From from "react-jsonschema-from", its says "schema should be object or boolean", can anyone help me how to solve this?

### Steps to Reproduce

1. import Form from "react-jsonschema-form"
2. go to console and see the error

#### Expected behavior

form to be rendered

#### Actual behavior

breaks the code

### Version

1.2.0

**Comment by LucianBuzzo** [comment]
Could you please post some code or a minimum reproduction? Here is a starter project you could use https://codesandbox.io/s/wy52wnz4w5

**Comment by Ab1d** [comment]
<img width="772" alt="screenshot 2019-01-23 at 10 37 49 am" src="https://user-images.githubusercontent.com/3349621/51584423-30735480-1efb-11e9-893f-d86ca0e80c12.png">
<img width="1440" alt="screenshot 2019-01-23 at 10 38 09 am" src="https://user-images.githubusercontent.com/3349621/51584427-3701cc00-1efb-11e9-879b-dae5ed16a8e5.png">

**Comment by LucianBuzzo** [comment]
@Ab1d I updated the codesandbox to match the code you've shown in the screenshot and I don't see an error - Is there aynthing I'm missing? https://codesandbox.io/s/wy52wnz4w5

**Comment by epicfaace** [comment]
It's been a while so I'm closing this issue, but @Ab1d if you have additional questions feel free to comment here.
