### ISSUE TITLE
support for wildcard in conditional schema dependency

### ISSUE THREAD

**Issue by KKS1** [mozilla-services/react-jsonschema-form#1155]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

On the conditionals schema dependencies, how can I achieve having the conditional schema be displayed if corresponding enum array "contains" a value. Right now, it seems its only doing equality check and not supporting wildcards "*" etc.

### Steps to Reproduce

For eg, in the schema, I have this property
```
"usageOptions": {
      "type": "array",
      "title": "Loan Usage Options",
      "items": {
        "type": "string",
        "enum": [
          "Other Home Addresses",
          "Refinance",
          "Home Improvement",
          "Education",
          "Other"
        ]
      },
      "uniqueItems": true
    },
```

And the conditional dependencies schema as

```
"dependencies": {
    "usageOptions": {
      "oneOf": [
        {
          "properties": {
            "usageOptions": {
              "items": {
                "enum": [
                  "Other"
                ]
              }
            },
            "othersDes": {
              "type": "string",
              "title": "Please describe others"
            }
          }
        }
      ]
    }
  }
```
#### Expected behavior

I want `othersDes` text field to appear when selected enum values "contains" `Other` option. So, in the multiple select list, no matter what user selects, if `Other` is part of selection, then, `othersDes` text field should display.

#### Actual behavior

The `othersDes` text field is appearing when only `Other` is selected.

### Version

latest version "^1.2.0"

**Comment by epicfaace** [comment]
You can use the `pattern` attribute to filter by a regular expression, such as `other*`. In this case, `pattern: "Other"` will suffice to make sure that the field contains the word "other." [Playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ1c2FnZU9wdGlvbnMiOlsiT3RoZXIgSG9tZSBBZGRyZXNzZXMiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ1c2FnZU9wdGlvbnMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJMb2FuIFVzYWdlIE9wdGlvbnMiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPdGhlciBIb21lIEFkZHJlc3NlcyIsIlJlZmluYW5jZSIsIkhvbWUgSW1wcm92ZW1lbnQiLCJFZHVjYXRpb24iLCJPdGhlciJdfSwidW5pcXVlSXRlbXMiOnRydWV9fSwiZGVwZW5kZW5jaWVzIjp7InVzYWdlT3B0aW9ucyI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJ1c2FnZU9wdGlvbnMiOnsiaXRlbXMiOnsicGF0dGVybiI6Ik90aGVyIn19LCJvdGhlcnNEZXMiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiUGxlYXNlIGRlc2NyaWJlIG90aGVycyJ9fX1dfX19LCJ1aVNjaGVtYSI6e319)

**Comment by epicfaace** [comment]
You can use the `contains` keyword for this: [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ1c2FnZU9wdGlvbnMiOlsiUmVmaW5hbmNlIiwiT3RoZXIiXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ1c2FnZU9wdGlvbnMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJMb2FuIFVzYWdlIE9wdGlvbnMiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPdGhlciBIb21lIEFkZHJlc3NlcyIsIlJlZmluYW5jZSIsIkhvbWUgSW1wcm92ZW1lbnQiLCJFZHVjYXRpb24iLCJPdGhlciJdfSwidW5pcXVlSXRlbXMiOnRydWV9fSwiZGVwZW5kZW5jaWVzIjp7InVzYWdlT3B0aW9ucyI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJ1c2FnZU9wdGlvbnMiOnsiY29udGFpbnMiOnsicGF0dGVybiI6Ik90aGVyIn19LCJvdGhlcnNEZXMiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiUGxlYXNlIGRlc2NyaWJlIG90aGVycyJ9fX1dfX19LCJ1aVNjaGVtYSI6e319)

**Comment by KKS1** [comment]
Thank you so much @epicfaace . I used a combination of your suggestions to solve, and works like a charm. Here is how the dependency looks like, for anyone else facing this issue

```
dependencies: {
    usageOptions: {
      oneOf: [
        {
          properties: {
            usageOptions: {
              contains: {
                enum: ["Other"]
              }
            },
            othersDes: {
              type: "string",
              title: "Please describe others"
            }
          }
        }
      ]
    }
  }
```
This will make sure that conditional schema kicks in only when specifically, one if the enum options ( in this case `Other` is included the enum array.

**Comment by epicfaace** [comment]
Great, glad it works @KKS1 !

**Comment by xyy7260** [comment]
@KKS1   hi ,How does the content of multiple options appear?

**Comment by KKS1** [comment]
@xyy7260 not sure if got your question ?
