### ISSUE TITLE
safeRenderCompletion documentation

### ISSUE THREAD

**Issue by Steffan-Ennis** [mozilla-services/react-jsonschema-form#1164]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Should document the purpose of the safeRenderCompletion prop

When onChange has been invoked it should invoke props.onChange with the formData taken from it's arguments. Instead if props.safeRenderCompletion !== true, props.onChange is invoked outside of the component.setState callback.

This creates issues because the state change may not have been resolved before props.onChange has been invoked.

**Comment by epicfaace** [comment]
Merging this into #1197.
