### ISSUE TITLE
Release the recent `anyOf`/`oneOf` changes

### ISSUE THREAD

**Issue by cyplo** [mozilla-services/react-jsonschema-form#1165]
Heya, sorry for opening an issue for this but I haven't found any better way of communicating this in the docs.

I would like to take advantage of the recent changes in `rjsf`, especially in the `anyOf`/`oneOf` space - e.g. https://github.com/mozilla-services/react-jsonschema-form/pull/1129 and https://github.com/mozilla-services/react-jsonschema-form/pull/1133

Would it be possible to cut a new release from the freshest `master` ? 

thank you so much !

**Comment by glasserc** [comment]
I have released [v1.2.1](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v1.2.1), although I think some of the changes you mention were in 1.2.0.

**Comment by cyplo** [comment]
Thank you so much !
