### ISSUE TITLE
Broken behaviour for oneOf inside array

### ISSUE THREAD

**Issue by LucianBuzzo** [mozilla-services/react-jsonschema-form#1168]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Using `oneOf` inside an array, where one branch is an integer and the other branch is an object is broken. When selecting the second option, the correct fields are not rendered at all.

```
{
  "type": "object",
  "properties": {
    "myArray": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "object",
            "properties": {
              "elt1": {
                "type": "integer"
              },
              "elt2": {
                "type": "string"
              }
            },
            "required": [
              "elt1",
              "elt2"
            ]
          }
        ]
      }
    }
  }
}
```

[playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJteUFycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7Im9uZU9mIjpbeyJ0eXBlIjoiaW50ZWdlciJ9LHsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZWx0MSI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJlbHQyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImVsdDEiLCJlbHQyIl19XX19fX0sInVpU2NoZW1hIjp7fX0=)

Originally reported by @Rasstrelnikov here https://github.com/mozilla-services/react-jsonschema-form/issues/1141#issuecomment-460835801

**Comment by PhilipK2** [comment]
How do I signup to be notified when this functionality is complete?

**Comment by LucianBuzzo** [comment]
@PhilipK2 You can "watch" the repo to be notified of activity on it.
