### ISSUE TITLE
Issue with nesting oneOf inside an array that is inside of an object. 

### ISSUE THREAD

**Issue by PhilipK2** [mozilla-services/react-jsonschema-form#1173]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am attempting to use oneOf to create an array, which will be filled with objects. These objects will have a string along with an array. 
this is the expected formData or object I want to receive on the backend:
```
{
typeProp: 'verify',
verifications: [
  {
    service: 'myService',
    endpoints: [
      {
        Description: 'myService1',
        Id: ''
      },
      {
        Description: 'myService2',
        Id: ''
      },
      {
        Description: 'myService3',
        Id: ''
      }
    ]
  },
  {
    serviceName: 'yourService',
    endpoints: [
      {
        endpointDescription: 'yourService1',
        endpointId: ''
      },
      {
        endpointDescription: 'yourService2',
        endpointId: ''
      }
    ]
  }
]
}
```

I am trying to use a dropdown on my typeProp, which would then show a dropdown for the service, once a selection is made for the service, I need the endpoints to show and also be a dropdown. Basically, all 3 fields will need to be a oneOf dropdown. 

Now, oneOf seems to be the best solution for me. However, the oneOf functionality does not seem to be able to be nested. Is there a way around this? Does anyone have a solution to my problem, or is this a bug in the code that will need to be reviewed? Any help is greatly appreciated

I'm not sure how to add a playground, but here is the code I currently have. I have tried every thing imagine-able of where to put the next oneOf but cannot find a solution.

Here is my code: 
```
{
      title: 'New,
      description: 'Create',
      type: 'object',
      properties: {
        type: {
          type: 'string',
          title: 'Type',
          enum: [
            'verification',
            'subscription'
          ]
        }
      },
      dependencies: {
        type: {
          oneOf: [
            {
              properties: {
                type: {
                  enum: ['verification']
                },
                verification: {
                  type: 'array',
                  title: 'Verifications',
                  items: {
                    type: 'object',
                    properties: {
                      serviceName: {
                        type: 'string',
                        title: 'Service Name',
                        enum: ['myService']
                      },
                      endpoints: {
                        type: 'array',
                        title: 'End Points',
                        items: {
                          type: 'object',
                          properties: {
                            endpointDesc: {
                              type: 'string',
                              title: 'EP Name',
                              enum: ['MyServiceEP']
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
```

**Comment by LucianBuzzo** [comment]
@PhilipK2 On the playground, there is a "share" button, clicking that will give you a link you can paste here.
Its a bit difficult to understand your intention, as the example data and the schema you posted don't quite match up. My understanding is that you want to present a different set of options based on the initial `type` value. This schema should work:
```
{
  "type": "object",
  "properties": {
    "type": {
      "enum": [
        "verification",
        "subscription"
      ]
    }
  },
  "dependencies": {
    "type": {
      "oneOf": [
        {
          "properties": {
            "type": {
              "enum": [
                "verification"
              ]
            },
            "verifications": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "serviceName": {
                    "type": "string"
                  },
                  "endpoints": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "description": {
                          "type": "string"
                        },
                        "id": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```
You can see a [working example here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0eXBlIjoidmVyaWZpY2F0aW9uIiwidmVyaWZpY2F0aW9ucyI6W3siZW5kcG9pbnRzIjpbeyJkZXNjcmlwdGlvbiI6ImZvbyIsImlkIjoiYmFyIn1dLCJzZXJ2aWNlTmFtZSI6Im15U2VydmljZSJ9XX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0eXBlIjp7ImVudW0iOlsidmVyaWZpY2F0aW9uIiwic3Vic2NyaXB0aW9uIl19fSwiZGVwZW5kZW5jaWVzIjp7InR5cGUiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsidHlwZSI6eyJlbnVtIjpbInZlcmlmaWNhdGlvbiJdfSwidmVyaWZpY2F0aW9ucyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzZXJ2aWNlTmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImVuZHBvaW50cyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJkZXNjcmlwdGlvbiI6eyJ0eXBlIjoic3RyaW5nIn0sImlkIjp7InR5cGUiOiJzdHJpbmcifX19fX19fX19XX19fSwidWlTY2hlbWEiOnt9fQ==).

**Comment by PhilipK2** [comment]
@LucianBuzzo  When I hit share, it replaces my code with what was already in place. How would I save it to share here?
Yes, I am trying to present different options after the first type value, but then different options on each subsequent field as well.

**Comment by bdgeise** [comment]
Any possible workarounds here?  I'm having a similar issue where we need to nest a oneOf to an unknown degree.  Our use case is similar to below where the field structure can be deeply nested. 

`"value": [
            {
              "value": "field1",
              "alias": "my_field1_alias"
            },
            {
              "value": [
                {
                  "value": "field2",
                  "alias": "my_field2_alias"
                },
                {
                  "value": [
                    {
                      "value": "field3",
                      "alias": "my_field3_alias"
                    }
                  ]
                }
              ],
              "alias": "struct_alias"
            }
          ]`

**Comment by LucianBuzzo** [comment]
@bdgeise Would you be able to provide an example of what you are trying to achieve using either the live playground or https://codesandbox.io/ ?

**Comment by bdgeise** [comment]
@LucianBuzzo - Definitely.
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ2YWx1ZSI6W119LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiZmllbGRFaXRoZXIiOnsidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoic3RyaW5nIn0sImFsaWFzIjp7InR5cGUiOiJzdHJpbmcifX19LHsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsidHlwZSI6InN0cmluZyJ9LCJhbGlhcyI6eyJ0eXBlIjoic3RyaW5nIn19fX0sImFsaWFzIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInZhbHVlIl19XX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWVsZEVpdGhlciJ9fX19LCJ1aVNjaGVtYSI6e319

In the playground example you can go 1 level deep.  I need to be able to nest oneOf in the 2nd oneOf object in the items array.
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ2YWx1ZSI6W3sidmFsdWUiOlt7fV19XX0sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJmaWVsZEVpdGhlciI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InZhbHVlIjp7InR5cGUiOiJzdHJpbmcifSwiYWxpYXMiOnsidHlwZSI6InN0cmluZyJ9fX0seyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWVsZEVpdGhlciJ9fSwiYWxpYXMiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsidmFsdWUiXX1dfX0sInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InZhbHVlIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL2ZpZWxkRWl0aGVyIn19fX0sInVpU2NoZW1hIjp7fX0=

**Comment by LucianBuzzo** [comment]
@bdgeise Thanks for the clear examples, I'll dig into this soon

**Comment by bdgeise** [comment]
Thanks @LucianBuzzo - I found this error is thrown when trying the 2nd option `bundle.js:22 Uncaught TypeError: o.map is not a function
    at t.value (bundle.js:22)
    at t.value (bundle.js:22)
    at l._renderValidatedComponentWithoutOwnerOrContext (bundle.js:20)
    at l._renderValidatedComponent (bundle.js:20)
    at l.performInitialMount (bundle.js:20)
    at l.mountComponent (bundle.js:20)
    at Object.mountComponent (bundle.js:6)
    at Object.updateChildren (bundle.js:20)
    at X._reconcilerUpdateChildren (bundle.js:20)
    at X._updateChildren (bundle.js:20)`

**Comment by bdgeise** [comment]
@LucianBuzzo - I believe the UI for generating the form is actually working correctly.  See https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ2YWx1ZSI6W3sidmFsdWUiOiJ0ZXN0IiwiYWxpYXMiOiJ0ZXN0In0sbnVsbF19LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiZmllbGQiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsidHlwZSI6InN0cmluZyJ9LCJhbGlhcyI6eyJ0eXBlIjoic3RyaW5nIn19fSwiZmllbGRFaXRoZXIiOnsidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyJ0aXRsZSI6IlNpbXBsZSBmaWVsZCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL2ZpZWxkIn0seyJ0aXRsZSI6IkNvbXBsZXggZmllbGQiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWVsZEVpdGhlciJ9XX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWVsZEVpdGhlciJ9fX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX19 as I can keep selecting the complex field option further nesting.  But as soon as I type it switches back to a simple field.  I believe this mihgt be related to #1244.  Thoughts?
