### ISSUE TITLE
Fields ordering in UISchema throw an error when the field is inside oneOf

### ISSUE THREAD

**Issue by nocmar** [mozilla-services/react-jsonschema-form#1175]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Fields ordering in UISchema throw an error when the field is inside oneOf

### Steps to Reproduce

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsibG9yZW0yIjp7InR5cGUiOiJzdHJpbmcifSwibG9yZW0xIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImxvcmVtMSJdfSx7InByb3BlcnRpZXMiOnsiaXBzdW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiaXBzdW0iXX1dfSwidWlTY2hlbWEiOnsidWk6b3JkZXIiOlsibG9yZW0xIiwibG9yZW0yIl19fQ==

#### Expected behavior

Skip the fields which are not currently in the schema because different one of option was selected.

#### Actual behavior

Throw an error __Invalid root object field configuration:uiSchema order list contains extraneous properties/_

**Comment by epicfaace** [comment]
Hmm... @nocmar thanks for your report, do you think it might be better to be able to have different `ui:order` lists defined for each `oneOf` branch?

**Comment by nocmar** [comment]
@epicfaace maybe just not throw an error when the field is missing in current schema, I will do a PR.

**Comment by epicfaace** [comment]
I believe this issue is fixed by #814 -- sorry I didn't notice that one at the time. Thanks for your contribution and bug report though!
