### ISSUE TITLE
Select Box from enums have empty value if indexed from 0 and using 0 as default

### ISSUE THREAD

**Issue by MatinF** [mozilla-services/react-jsonschema-form#1177]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Select Box from enums have an empty value at the top of the dropdown when indexing the enums from 0 and setting a default value. If indexing from 1, the blank field is not there.

### Steps to Reproduce

[Example playground with indexing from 0 (incl. blank field)](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbnVtb2JqZWN0Ijp7InNlbGVjdGlvbiI6MH19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZW51bW9iamVjdCI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzZWxlY3Rpb24iOnsidGl0bGUiOiJTZWxlY3QgTW9kZSIsInR5cGUiOiJpbnRlZ2VyIiwiZGVmYXVsdCI6MCwiYW55T2YiOlt7InRpdGxlIjoiQXV0byIsImVudW0iOlswXX0seyJ0aXRsZSI6IlNpbXBsZSIsImVudW0iOlsxXX1dfX0sImRlcGVuZGVuY2llcyI6eyJzZWxlY3Rpb24iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsic2VsZWN0aW9uIjp7ImVudW0iOlswXX19fSx7InByb3BlcnRpZXMiOnsic2VsZWN0aW9uIjp7ImVudW0iOlsxXX19fV19fX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19fQ==)

[Example playground with indexing from 1 (excl. blank field)](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbnVtb2JqZWN0Ijp7InNlbGVjdGlvbiI6MX19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZW51bW9iamVjdCI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzZWxlY3Rpb24iOnsidGl0bGUiOiJTZWxlY3QgTW9kZSIsInR5cGUiOiJpbnRlZ2VyIiwiZGVmYXVsdCI6MSwiYW55T2YiOlt7InRpdGxlIjoiQXV0byIsImVudW0iOlsxXX0seyJ0aXRsZSI6IlNpbXBsZSIsImVudW0iOlsyXX1dfX0sImRlcGVuZGVuY2llcyI6eyJzZWxlY3Rpb24iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsic2VsZWN0aW9uIjp7ImVudW0iOlsxXX19fSx7InByb3BlcnRpZXMiOnsic2VsZWN0aW9uIjp7ImVudW0iOlsyXX19fV19fX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19fQ==)

#### Expected behavior

We would expect the dropdown to not have the blank field when setting a default value - regardless of whether we index from 0 or 1. We'd like to index from 0, so if this is indeed a bug it would be nice to fix.

#### Actual behavior

In practice, indexing from 0 creates the blank dropdown field - which we'd like to avoid.

**Comment by epicfaace** [comment]
This issue also exists when default is equal to `""`.

**Comment by glasserc** [comment]
Now that #1163 has been merged, is this fixed?

**Comment by epicfaace** [comment]
It should be!
