### ISSUE TITLE
formData properties are not in the same order as in the schema

### ISSUE THREAD

**Issue by MatinF** [mozilla-services/react-jsonschema-form#1178]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

We're using the RJSF to create a configuration file (i.e. the formData), based on a schema. For our use case (an IoT data logger), it's critical that the property fields are ordered in exactly the same way as in our schema file. This is the case in the Live Playground formData window - but not in the console output when hitting submit. 

### Steps to Reproduce

The difference in property orders vs. the formData window and the console output can be seen in the default playground view: https://mozilla-services.github.io/react-jsonschema-form/

#### Expected behavior

We expected that the console output formData would be ordered similarly to the schema order. At least since this is the case for the playground formData window that live-updates with each change.

#### Actual behavior

In practice, the order of properties in the console differs from the schema and the formData window.

Is it possible to define somewhere in the output settings that we want the formData fields ordered similarly to the schema? We're thinking there must be a way since it's achieved in the formData window of the Live Playground - but we're unsure what the right way is to implement this.

Martin

**Comment by epicfaace** [comment]
Hey @MatinF , for me, the order of properties in the console seems to be correct. I'm using Chrome 72.0.3626.96.

![image](https://user-images.githubusercontent.com/1689183/52536310-b241eb00-2d0d-11e9-99e0-d342732f6a2c.png)

Do you mind sending a screenshot of what you see? What browser are you using?

**Comment by MatinF** [comment]
That's strange - see attached screenshot. 

I'd expect firstName to be the first entry, but I'm getting age as the first one in the console for example.
I'm using Chrome browser.

![formdataconsole](https://user-images.githubusercontent.com/26184427/52536647-a1b96100-2d5d-11e9-9373-2959b05282cd.PNG)

**Comment by epicfaace** [comment]
How does it look like before you click the arrow to expand it on the console?

**Comment by MatinF** [comment]
It seems I must have been seeing ghosts - I'm not able to replicate this anymore. Sorry for opening this up on a wrong basis. I'll let you know if it reoccurs.

**Comment by LucianBuzzo** [comment]
Just to add some color to this issue - *you cannot guarantee or rely on the order of keys in a javascript object*. See https://stackoverflow.com/a/5525820/8583153 for more information:
> **4.3.3 Object**
> An object is a member of the type Object. **It is an unordered collection of properties** each of which contains a primitive value, object, or function. A function stored in a property of an object is called a method.

**Comment by epicfaace** [comment]
That's true, but it seems that in ES6 objects _do_ have traversal orders defined: http://exploringjs.com/es6/ch_oop-besides-classes.html#_traversal-order-of-properties
