### ISSUE TITLE
Do not render two equivalent labels for checkboxes

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#119]
Ref https://github.com/mozilla-services/react-jsonschema-form/pull/51#issuecomment-205296474

![](https://cloud.githubusercontent.com/assets/546692/14249441/1048f9ce-fa7a-11e5-83b1-6c8cf362ff8f.png)

Makes me think, for visual consistency the checkbox label (the one next to the checkbox itself) should be in bold.

**Comment by almet** [comment]
Thanks @n1k0 !
