### ISSUE TITLE
Add the source mappings for debugging 

### ISSUE THREAD

**Issue by CodeGains** [mozilla-services/react-jsonschema-form#1203]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

When I was trying to debug some code in the playground I found that there were no source mappings so I could only step through the compiled code which is not very helpful. The source mappings can be added this one config in `webpack.config.dev.js` from:

`devtool: eval`

to

`devtool: eval-source-map`

Everything else in the playground seems to work just fine after changing it. Any reason not to have this as the default setting?

### Version

1.2.1

**Comment by epicfaace** [comment]
That's a good idea. But building the playground currently uses `webpack.config.prod.js` though

**Comment by CodeGains** [comment]
Oh I meant the playground that runs locally with `npm start`, but I suppose I could add it to the production one too.

**Comment by epicfaace** [comment]
Oh that makes sense -- it makes more sense to add this change to the local playground first; the production would be a second priority but not as important. A PR doing this change for one or both makes lots of sense!
