### ISSUE TITLE
uiSchema + Dependencies

### ISSUE THREAD

**Issue by dustinHyden** [mozilla-services/react-jsonschema-form#1206]
Hello,

Quick question, I tried searching the issue board and read through all the documentation but I can't seem to find a solution to my issue. The question is: 

When using dependencies, to add different inputs based on a chosen value, how can I also tell react-jsonschema-forms to use a specific widget for the new input? 

Currently, my solution is to just create a giant ui object. But! This means I cannot have duplicate entries. (Let's say i have two that are both labeled 'collections', they would both get the same ui-widget even if that wasn't intended)

Cheers,
Hyden

**Comment by epicfaace** [comment]
You can't do that as of now. The best you can do is to create a custom widget that changes the input type based on a schema property that changes, such as `title`.

Can you explain more about what you mean when you say "a giant ui object"?

**Comment by dustinHyden** [comment]
Thanks for the reply!

That's shocking to me though, it seems highly counter productive. Instead of being able to pass the ui widgets through dependencies, I should instead pass the ui value in the schema object instead, then in my default input component I manually type out which component to show based on the widget I passed in the schema.  So, I essentially have to recreate the default functionality just because I want to dynamically add an input. I'll need to think of a different option, else there would be no point in using this package, instead of coding my own xD 

If react-jsonschema-form is already looking at the dependencies to determine what inputs to create, it seems like a good place to implement the ability to choose that inputs widget... That would then remove any potential conflicts, and the need for a giant ui object.

In my example, I basically created a bunch of different 'product' types, so the user could choose between which product type the new 'entry' will be. When they choose a new product type, the rest of the form appears based on that products schema in my database. 

I added each ui:widget to an object (as the more product types I have, the more ui widgets I might have). I don't like this method as the list grows as I get more product types overtime. 

But if any of the products have the same id values, then the most recent ui:widget added for the id would apply to all potential entries with that id (because when I dynamically added every single ui:widget, the newest product type would override) 

I suppose I could add a flag to the end of every id in my product types that would differentiate any potential conflicts. Aka image_imageWidget and also image_boolean. Then when I create my ui list, all the image_imageWidget would just override the previous image_imageWidget but that wouldn't change anything negatively. 

Anyways, thanks for the help, it definitely got my brain going and got me to a solution (albeit I will check every patch note to see if this gets addressed because this my solution currently feels like a hack)

**Comment by epicfaace** [comment]
@dustinHyden I'm kind of unclear as to what exactly your solution was, do you mind posting a code sample?

**Comment by epicfaace** [comment]
Merging this into #701.

**Comment by kokkoon** [comment]
Is there already a solution on this? for allowing dependencies in the uiSchema..
