### ISSUE TITLE
Document (or remove) anyOf title

### ISSUE THREAD

**Issue by epicfaace** [mozilla-services/react-jsonschema-form#1207]
It appears that there is a `title` attribute that can be added in a subschema when using `anyOf`, which is used to customize the options shown in the dropdown box (see the "any of" example on the playground).

![image](https://user-images.githubusercontent.com/1689183/53832442-336e5580-3f3b-11e9-88b9-cdecc4a14478.png)

This doesn't seem to be part of JSON Schema. Also, it isn't documented. I think we should either document it, or perhaps we should move it to the uiSchema.

@LucianBuzzo or others, any thoughts?

**Comment by LucianBuzzo** [comment]
@epicfaace Why do you think it isn't part of JSON schema? AFAIK `title` is a valid keyword here. We should document this, though if you feel that the behaviour is unintuitive then we can discuss some ideas on how to improve it.

**Comment by epicfaace** [comment]
Oh, I see, the value for the `title` keyword shows up in the `<legend>` element. I guess I didn't intuitively think at first that the same `title` keyword shows up for the dropdown as well, but it makes sense.

Perhaps there should be a way to customize the dropdown text so that it's different from the actual title that shows up from `title` -- do you have any suggestions as to how that could be accomplished?

**Comment by epicfaace** [comment]
Perhaps `ui:title` should be able to be supported?

**Comment by epicfaace** [comment]
Closing this in favor of #1141
