### ISSUE TITLE
Form fields are not populated with default values when using oneOf

### ISSUE THREAD

**Issue by MoshiMoshi0** [mozilla-services/react-jsonschema-form#1229]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJCYXIiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiQ29uc3QiOnsiY29uc3QiOiJCYXIiLCJkZWZhdWx0IjoiQmFyIn0sIkJhclAiOnsidHlwZSI6ImludGVnZXIifX19LCJCYXoiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiQ29uc3QiOnsiY29uc3QiOiJCYXoiLCJkZWZhdWx0IjoiQmF6In0sIkJhelAiOnsidHlwZSI6ImludGVnZXIifX19fSwidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyJ0aXRsZSI6IkJhciIsIiRyZWYiOiIjL2RlZmluaXRpb25zL0JhciJ9LHsidGl0bGUiOiJCYXoiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9CYXoifV19LCJ1aVNjaGVtYSI6e319) demonstrating the issue.

### Description

1. When using `oneOf` the form fields are not populated with the their specified default values. 
2. Changing the selected option does not update the fields with the default value.

#### Expected behavior

The fields should have their contents populated with the default value.

#### Actual behavior

The fields are empty.

**Comment by mishaschwartz** [comment]
I am also running into this issue, though I noticed that the playground link you shared seems to be failing for other reasons to do with the reference.
Here is an updated version that doesn't use references that still demonstrates the bug:

[playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InRpdGxlIjoiQmFyIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiQ29uc3QiOnsiY29uc3QiOiJCYXIiLCJkZWZhdWx0IjoiQmFyIn0sIkJhclAiOnsidHlwZSI6ImludGVnZXIifX19LHsidGl0bGUiOiJCYXoiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJDb25zdCI6eyJjb25zdCI6IkJheiIsImRlZmF1bHQiOiJCYXoifSwiQmF6UCI6eyJ0eXBlIjoiaW50ZWdlciJ9fX1dfSwidWlTY2hlbWEiOnt9fQ==)
