### ISSUE TITLE
Can't render null fields

### ISSUE THREAD

**Issue by faissalMT** [mozilla-services/react-jsonschema-form#1232]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Providing a schema with a property of type 'null' will yield the error '*Unknown field type null*', this is inspite of it being able to validate this property.

### Steps to Reproduce

1. Create a schema in which one of the properties has type null, such as:  
```
{
  "type": "object",
  "properties": {
    "static": {
      "type": "null",
      "title": "Age"
    }
  }
}
```
2. Render it via RJSF

#### Expected behavior

The title 'Age' is rendered and nothing else for that property.  

#### Actual behavior

The title is rendered but the following error appears:  

>Unsupported field schema for field root_static: *Unknown field type null*.

### Version

v1.3.0

**Comment by epicfaace** [comment]
react-jsonschema-form has not previously supported null fields. I think the behavior you described (rendering the title and nothing else) makes sense, though. Could you make a PR implementing this?

**Comment by faissalMT** [comment]
I don't have much time on my hands unfortunately, you'd have to give me a week or two.
