### ISSUE TITLE
File object becomes a basic js object

### ISSUE THREAD

**Issue by oterral** [mozilla-services/react-jsonschema-form#1233]
### Description
When we use the From component in a wrapper component and pass formData via props., the Form component transforms Props to State in `componentWillReceiveProps ` . Problem is when we use a custom widget with an input file, the `File` object is transformed to a basic object in [mergeObjects function](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L242) because the  `File` object is detected as an object.

I guess the solution is to exclude File from [isObject](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L232) function. 

Do you think it's the way to go? I don't see any exception than `File` object which could be bad detected.

### Steps to Reproduce

1. Open https://codesandbox.io/s/n4mlxwq3ml
2. Open the browser console
3. Choose a file
4. See in the console onChange event is triggered twice and the File object changes.

#### Expected behavior
The File object stays a File object

#### Actual behavior

The File object becomes a basic js object

### Version

1.3.0

**Comment by epicfaace** [comment]
@oterral , yes, that makes sense, you can just add a check to see if the input is an instance of `File`. I'd merge a PR that does this!

**Comment by oterral** [comment]
@epicfaace sorry to bother you with this. When is the next release planned ?

**Comment by epicfaace** [comment]
@oterral Likely next week. For now, you could just do `npm install -S git+https://github.com/mozilla-services/react-jsonschema-form.git#0f4889c22457edeb57991f48a88d8d32b2a93ca7` to get the changes from the latest commit.
