### ISSUE TITLE
Hide widget conditionally

### ISSUE THREAD

**Issue by MatveyNeyman** [mozilla-services/react-jsonschema-form#1236]
Hi there,

as far as I read from documentation the only way to hide a widget is to pass 'hidden' value to 'ui:widget' prop in the uiSchema.
My case is to hide widget conditionally depending of value. For example, hide widget if no value presented. Now I check for null in the widget and render null that produces an ugly empty divs in the DOM.
Would be nice to implement feature to pass 'hidden' prop in the runtime.

Thanks!

**Comment by epicfaace** [comment]
Good point -- for now you could work around this by making a custom widget.

**Comment by MatveyNeyman** [comment]
> Good point -- for now you could work around this by making a custom widget.

That's what I said -- I put check for null/undefined value in the custom widget and render null if this is true. The only problem is this is not properly handled, and I got empty field's wrapper div in the html tree.

**Comment by Fronix** [comment]
I'd also like a better solution to this. Currently creating my own widget isn't proving very good since we rely on generating forms completely from the schema. A "Hide if a field has value or is true" would be nice.

**Comment by epicfaace** [comment]
Yes, this would be solved by doing #701 or #1206

**Comment by epicfaace** [comment]
Merging this into #701.
