### ISSUE TITLE
Star Rating field

### ISSUE THREAD

**Issue by mtm-mouadh** [mozilla-services/react-jsonschema-form#1247]
### Prerequisites

- [+] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description
I want add Star Rating field in form. So do we have any example or schema details for same?

**Comment by epicfaace** [comment]
I would make a field of type number with enum, such as:

```
{
    type: "number",
    enum: [1,2,3,4,5]
}
```

And then create a custom widget for it.

**Comment by mtm-mouadh** [comment]
But how can I do this ? According to the existing doc , when you custom a widget, all widgets in the form will be changed

**Comment by epicfaace** [comment]
@mtm-mouadh no, you can use the `ui:widget` property to make your own widget; you don't have to override the default widgets.

See: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-widget-components

**Comment by mtm-mouadh** [comment]
Thanks brother for help, I have succeeded in doing and I have use a library ant.design
<img src="https://i.ibb.co/DbZVpV1/thnks.jpg" width="200" height="400" />

**Comment by epicfaace** [comment]
Great, let me know if you have any other issues.
