### ISSUE TITLE
Supporting another UI framework (i.e. SemanticUI)

### ISSUE THREAD

**Issue by cguedes** [mozilla-services/react-jsonschema-form#125]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

I want to use this lib in a project that is built with [SemanticUI](http://semantic-ui.com/) instead of Bootstrap.

The documentation is pretty extensive in how to customize Froms to create aditional widgets, fields, themes, and so on. But the core components are (I guess) tight to Bootstrap HTML/classnames. 

How should I proceed to use another UI library like semantic UI.
Can/should I for instance change the default widgets used for strings/dates/booleans/etc...

**Comment by n1k0** [comment]
As far as I can see, SemanticUI relies on [jQuery and mutable observers](http://semantic-ui.com/introduction/integrations.html), which worries me at the highest level and is something we don't plan to support in any way in the future.

If you're only speaking of CSS here, and admitted that SemanticUI supports a pure CSS mode, the plan would indeed be to craft custom components (SchemaField, fields and/or widgets) to reflect the expected HTML semantics.

**Comment by cguedes** [comment]
Hi. I am only interested in html and css part for now. 
I will follow your recommendation. Tanks.

**Comment by rafaelmaruta** [comment]
I think my question is related to this post.

In my case I'd like to use another UI lib, the [https://ant.design/](https://ant.design/). How can I replace Bootstrap?

**Comment by zenflow** [comment]
I'm looking at https://github.com/nilportugues/react-jsonschema-form-semanticui .. will try to circle back around and share what i find

**Comment by sidaw** [comment]
@zenflow curious what your findings are
