### ISSUE TITLE
Add a select example

### ISSUE THREAD

**Issue by swordsreversed** [mozilla-services/react-jsonschema-form#1254]
### Prerequisites

- [] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

No real mention of using a select.

### Steps to Reproduce

1. Read the docs
2. Look through the examples
3. Search the page for 'select'

#### Expected behavior

See a very simple example of a select eg a list in a dropdown that is not just a weird boolean or numbers or something.

#### Actual behavior

Pain, fruitless googling

### Version

Latest.

Putting this here for people who are new to this (great) project. It's not covered anywhere (at least not a non-obscure way), so if you want to see an example of a select box, put this is the live playground JSONSchema box:

```
{
	"title": "A registration form",
	"description": "A simple form example.",
	"type": "object",
	"required": [
		"firstName",
		"lastName"
	],
	"properties": {
		"destination": {
			"type": "string",
			"title": "Where are you headed?",
			"enum": [
				"canada",
				"usa",
				"international"
			],
			"enumNames": [
				"Canada",
				"USA"
			]
		}
	}
}
```

**Comment by epicfaace** [comment]
Hmm, it is covered here (https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#custom-labels-for-enum-fields), but perhaps it's not very easily navigable.

I'd be glad to merge a PR that adds an example of this to the docs/playground!

**Comment by swordsreversed** [comment]
> Custom labels for enum fields

Exactly what i mean. I've never referred to a select as an enum field, maybe it's common parlance elsewhere? 

https://www.google.com/search?biw=1370&bih=766&ei=n2i2XNiZIMbprQG_75uIBA&q=enum+fields+forms

Maybe not?

I'll put together an example for the docs :)

**Comment by swordsreversed** [comment]
https://github.com/mozilla-services/react-jsonschema-form/pull/1257

**Comment by glasserc** [comment]
> Exactly what i mean. I've never referred to a select as an enum field, maybe it's common parlance elsewhere?

`enum` is the name of a [validation keyword](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.2) in the JSON Schema spec. Conceptualizing it as "a way to render a `<select>` makes me think you probably do not want/need something like react-jsonschema-form which is capable of rendering a form for an arbitrary schema. Instead it sounds like you want to design a single specific form. I suspect another library would be a better fit for you.

**Comment by swordsreversed** [comment]
So I am using json to render out a form in react.  I adapted this form to your schema:

```
{
  "name": "ticketFormV2",
  "title": "ticketFormV2",
  "scoring": [],
  "formSchema": {
    "title": "Add Ticket",
    "name": "ticketFormV2",
    "description": "",
    "type": "object",
    "required": [
      "subject",
      "priority",
      "status"
    ],
    "properties": {
      "subject": {
        "type": "string",
        "title": "Subject"
      },
      "status": {
        "type": "string",
        "title": "Status",
        "enum": [
          "Open",
          "In Progress",
          "Completed",
          "Cancelled",
          "Unresolvable"
        ]
      },
      "priority": {
        "type": "string",
        "title": "Priority",
        "enum": [
          "Low",
          "Medium",
          "High",
          "Emergency"
        ]
      },
      "action": {
        "type": "string",
        "title": "Action",
        "enum": [
          "Call",
          "Text",
          "Email",
          "Referral",
          "Other"
        ]
      },
      "description": {
        "type": "string",
        "title": "Description"
      },
      "dueAt": {
        "type": "string",
        "format": "date"
      }
    }
  },
  "uiSchema": {
    "description": {
      "ui:widget": "textarea"
    }
  }
}
```

Interestingly [jsonforms.io](https://jsonforms.io) have an example right on their front page using json schema on a select without unnecessarily obscuring the issue, so i'll be switching to them. Cheers for the heads up.
