### ISSUE TITLE
I get error when I use file type.

### ISSUE THREAD

**Issue by NuruddinBadawi** [mozilla-services/react-jsonschema-form#1260]
### Description
I follow the documentation, to add single file input,
I get this error

"Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded."

![Screen Shot 2019-04-20 at 12 11 53 AM](https://user-images.githubusercontent.com/5736522/56444336-eedb2580-6300-11e9-9ad2-279db23ec14d.png)

```
"dependencies": {
    "aws-amplify": "^1.1.11",
    "aws-amplify-react": "^2.1.5",
    "date-fns": "^1.29.0",
    "element-react": "^1.4.25",
    "element-theme-default": "^1.4.13",
    "react": "^16.6.3",
    "react-crud-admin": "^1.0.47",
    "react-dom": "^16.6.3",
    "react-jsonschema-form": "^1.5.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.8"
  },
```

**Comment by epicfaace** [comment]
Could be related to https://github.com/netlify/gotrue-js/issues/13

@NuruddinBadawi can you link to an example on jsfiddle or codepen in which this is happening? Thanks!

**Comment by epicfaace** [comment]
Closing this issue for now, but if you have more info please feel free to comment.

**Comment by stephenmdangelo** [comment]
I stumbled upon this ticket 3 years later... here's my solution in case anyone else runs into it.

I had the same issue, it was because my JSON object had an empty string for the file value. It needs to be at least an empty data-url: "data:;,"
