### ISSUE TITLE
Default type to `object` if undefined

### ISSUE THREAD

**Issue by domharrington** [mozilla-services/react-jsonschema-form#1265]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Can we default the `type` to `object` if it's undefined? We accept user submitted JSON Schemas and this is a common thing that people miss. I'm not 100% sure if it's valid JSON Schema or not, but https://www.jsonschemavalidator.net/ appears to say the following is valid:

```json
{
  "properties": {
    "a": {
      "type": "string"
    }
  }
}
```

But when passing that into this module, we get the following error:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/848223/56678613-ff302f00-6677-11e9-9a1b-6a74f7408b02.png">

Playground link: https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImEiOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7fX0=

### Steps to Reproduce
1. Pass in a JSON Schema without a `type`
2. Observe that the [UnsupportedField](https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/components/fields/UnsupportedField.js) is instantiated

#### Expected behavior
Default `type` to `object` if it is undefined
If `type` is set to something that is unknown, still create the `UnsupportedField` e.g. `type: 'someothertype'`

Affected blocks of code:
Could check for undefined in here and return `object`: https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/utils.js#L68-L84

This is where it will bubble up to, but I don't think this code would have to change at all: https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/components/fields/SchemaField.js#L49-L59

Happy to send over a PR for this if it'll get accepted! 

### Version
v1.5.0

**Comment by epicfaace** [comment]
Yes, I believe that makes sense.

Why would you make the default type `object` when undefined? Wouldn't it be enough just to make the type default to `object` _only_ if a `properties` keyword is defined as well?

**Comment by domharrington** [comment]
Yeah that would also work, though you'd then also have to check for `additionalProperties` as well. Any other edge cases you can think of?

**Comment by epicfaace** [comment]
I think that's it!
