### ISSUE TITLE
cannot find a simple example running in the browser

### ISSUE THREAD

**Issue by bwl21** [mozilla-services/react-jsonschema-form#1278]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I try ti make the example in https://react-jsonschema-form.readthedocs.io/en/latest/#usage work in a browser

### Steps to Reproduce

1. [First Step]

Ceate an index.html

```html
<html>
<head>

</head>
<body>
  <p>json schema forms demo</p>
  <div id="app"></div>

  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

  <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-jsonschema-form/dist/react-jsonschema-form.js"></script>

  <script type="text/babel">

    import React, { Component } from "react.development";
    import { render } from "react-dom";
    import Form from "react-jsonschema-form";

    const schema = {
      title: "Todo",
      type: "object",
      required: ["title"],
      properties: {
        title: {type: "string", title: "Title", default: "A new task"},
        done: {type: "boolean", title: "Done?", default: false}
      }
    };

    const log = (type) => console.log.bind(console, type);

    render((
      <Form schema={schema}
    onChange={log("changed")}
    onSubmit={log("submitted")}
    onError={log("errors")} />
    ), document.getElementById("app"));
  </script>
</body>
</html>
```

2. [Second Step]
3. [and so on...]

#### Expected behavior

Should show the page as described in the documentation.
I would appreciate an example how to use jsonscheam-form in a vanilla html - Page.

#### Actual behavior

ended up in 

```
VM285:3 Uncaught ReferenceError: require is not defined
    at <anonymous>:3:14
    at i (babel.min.js:24)
    at r (babel.min.js:24)
    at o (babel.min.js:24)
    at u (babel.min.js:24)
    at f (babel.min.js:1)
    at babel.min.js:1
```

**Comment by epicfaace** [comment]
You can't use `require` in the browser unless you bundle your code using webpack. To make your example work, try:

```
<html>
<head>

</head>
<body>
  <p>json schema forms demo</p>
  <div id="app"></div>

  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

  <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-jsonschema-form/dist/react-jsonschema-form.js"></script>

  <script type="text/babel">

    const Form = JSONSchemaForm.default;

    const schema = {
      title: "Todo",
      type: "object",
      required: ["title"],
      properties: {
        title: {type: "string", title: "Title", default: "A new task"},
        done: {type: "boolean", title: "Done?", default: false}
      }
    };

    const log = (type) => console.log.bind(console, type);

    ReactDOM.render((
      <Form schema={schema}
    onChange={log("changed")}
    onSubmit={log("submitted")}
    onError={log("errors")} />
    ), document.getElementById("app"));
  </script>
</body>
</html>
```

**Comment by v1vendi** [comment]
You probably could even do this example with React.createElement instead of JSX so it doesnt need webpack or babel at all :)
`<p>json schema forms demo</p>
<div id="app"></div>

<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
<script src="https://unpkg.com/react-jsonschema-form/dist/react-jsonschema-form.js"></script>

<script>

  const Form = JSONSchemaForm.default;

  const schema = {
    title: "Todo",
    type: "object",
    required: ["title"],
    properties: {
      title: {type: "string", title: "Title", default: "A new task"},
      done: {type: "boolean", title: "Done?", default: false}
    }
  };

  const log = (type) => console.log.bind(console, type);
  const element = React.createElement(
    Form, 
    {
      schema,
      onChange: log("changed"),
      onSubmit: log("submitted"),
      onError: log("errors")
    } 
  )
  ReactDOM.render(element, document.getElementById("app"));
</script>
`
still I don't believe it's possible to do something useful enough without building

**Comment by epicfaace** [comment]
Thanks @v1vendi . It seems like both these examples would help with your issue @bwl21, so I'm closing this issue for now.

**Comment by tmendesilva** [comment]
How can I add a theme like "material-ui" using this syntax?
