### ISSUE TITLE
Issue with default values in anyOf/oneOf dependencies [PG example included]

### ISSUE THREAD

**Issue by MatinF** [mozilla-services/react-jsonschema-form#1293]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

As mentioned previously in issue #975, there seems to be a bug related to using default values in combination with anyOf/oneOf dependency fields. In issue #975 epicfaace asked that we provide a working playground example, which is now available below.

### Steps to Reproduce

See playground example:
[default values playground example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJydGMiOnsic3luYyI6MH19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicnRjIjp7InRpdGxlIjoiQ29uZmlndXJlIENsb2NrIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic3luYyI6eyJ0aXRsZSI6IlRpbWUgU3luYyBUeXBlIiwidHlwZSI6ImludGVnZXIiLCJkZWZhdWx0IjowLCJhbnlPZiI6W3sidGl0bGUiOiJSZXRhaW4gdGltZSIsInR5cGUiOiJpbnRlZ2VyIiwiZW51bSI6WzBdfSx7InRpdGxlIjoiQXV0byB0aW1lIiwidHlwZSI6ImludGVnZXIiLCJlbnVtIjpbMV19XX19LCJkZXBlbmRlbmNpZXMiOnsic3luYyI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJzeW5jIjp7ImVudW0iOlswXX19fSx7InByb3BlcnRpZXMiOnsic3luYyI6eyJlbnVtIjpbMV19LCJ0b2xlcmFuY2UiOnsidGl0bGUiOiJUaW1lIHN5bmMgdG9sZXJhbmNlIiwidHlwZSI6ImludGVnZXIiLCJtaW5pbXVtIjoxLCJtYXhpbXVtIjozNjAwLCJkZWZhdWx0IjozMH19fV19fX19fSwidWlTY2hlbWEiOnt9fQ==)

#### Expected behavior

When the user selects the "Auto time" field in the dropdown, a new field appears called "Time Sync Tolerance". In our Schema, this field has a default value of 30 - and thus we'd expect this to be the value in the field by default.

#### Actual behavior
In practice, the field is blank - and this is a general issue with these type of anyOf/oneOf dependent fields. Fixing this would be a great help for several real-life applications.

@epicfaace Hope the above is what you're looking for in regards to an example - else please let me know.

Best,
Martin

**Comment by jane88nausicaa** [comment]
#default value does not work in oneOf

**Comment by MatinF** [comment]
> #default value does not work in oneOf

This is also what we observe - but I assume this is a bug, rather than working as intended?

I would assume that fixing this would help a lot of use cases where more complex JSON Schemas are used. If we can do further to provide examples or similar, let us know.

**Comment by MatinF** [comment]
I think some form of error has sneaked in as part of the latest release 1.6.0. 

For us, all fields that have dependencies now cause the editor to break - incl. the playground sample shared above (you can verify this by copying the Schema into a new playground and observe that it does not render). 

In contrast, the [same example will still render if I completely remove the "dependencies" tab](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJydGMiOnsic3luYyI6MH19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicnRjIjp7InRpdGxlIjoiQ29uZmlndXJlIENsb2NrIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic3luYyI6eyJ0aXRsZSI6IlRpbWUgU3luYyBUeXBlIiwidHlwZSI6ImludGVnZXIiLCJkZWZhdWx0IjowLCJhbnlPZiI6W3sidGl0bGUiOiJSZXRhaW4gdGltZSIsInR5cGUiOiJpbnRlZ2VyIiwiZW51bSI6WzBdfSx7InRpdGxlIjoiQXV0byB0aW1lIiwidHlwZSI6ImludGVnZXIiLCJlbnVtIjpbMV19XX19fX19LCJ1aVNjaGVtYSI6e319) - but of course that's probably not the intention. I assume some issue has arisen during the implementation of a fix for default values.
