### ISSUE TITLE
[Question] oneOf boolean not showing properties on selection

### ISSUE THREAD

**Issue by choweiyuan** [mozilla-services/react-jsonschema-form#1326]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Hi, I am trying to use "oneOf" of type "boolean". However, oneOf with type:"boolean" does not support properties on selection, works if I use "object" - see [here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InByb3BlcnRpZXMiOnsibG9yZW0iOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsibG9yZW0iXX0seyJwcm9wZXJ0aWVzIjp7Imlwc3VtIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImlwc3VtIl19XX0sInVpU2NoZW1hIjp7fX0=)

I want a behaviour that supports collapsible field on toggle to make my form less convoluted, I'm open to workarounds or suggestions. Many thanks in advance.

### Steps to Reproduce

1. Go to https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6ZmFsc2UsInNjaGVtYSI6eyJ0aXRsZSI6IlRvZ2dsZSIsInR5cGUiOiJib29sZWFuIiwib25lT2YiOlt7ImNvbnN0Ijp0cnVlLCJwcm9wZXJ0aWVzIjp7IkFscGhhYmV0cyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJhYmMiLCJkZWYiXX0sIkFscGhhYmV0MiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJkZWYiLCJnaGkiXX19fSx7InRpdGxlIjoiRGlzYWJsZSIsImNvbnN0IjpmYWxzZX1dfSwidWlTY2hlbWEiOnt9fQ==
2. Check "Toggle"
3. No additional properties show up. Was expecting Alphabets and Alphabets2 to show up when I toggle

#### Expected behavior

Expand and show additional properties when I set toggle to true

#### Actual behavior

Additional properties/schemas did not show when I set toggle to true

### Version
v1.6.1

**Comment by epicfaace** [comment]
That's not a valid schema for oneOf. Since the type of the entire form is "boolean", it's not possible to store properties in it unless the type of the form is "object".

You might want to check out the "Schema dependencies" example for something closer to what you want: https://react-jsonschema-form.readthedocs.io/en/latest/dependencies/#dynamic

**Comment by choweiyuan** [comment]
Thanks @epicfaace , had a look at your suggestion and came up with this which is pretty much what I want.
[Sample here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnRydWUsInNpbXBsZSI6eyJuYW1lIjoiUmFuZHkifSwiY29uZGl0aW9uYWwiOnsiRG8geW91IGhhdmUgYW55IHBldHM/IjoiTm8ifSwiYXJyYXlPZkNvbmRpdGlvbmFscyI6W3siRG8geW91IGhhdmUgYW55IHBldHM/IjoiWWVzOiBPbmUiLCJIb3cgb2xkIGlzIHlvdXIgcGV0PyI6Nn0seyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOiJZZXM6IE1vcmUgdGhhbiBvbmUiLCJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOmZhbHNlfV0sImZpeGVkQXJyYXlPZkNvbmRpdGlvbmFscyI6W3siRG8geW91IGhhdmUgYW55IHBldHM/IjoiTm8ifSx7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6IlllczogT25lIiwiSG93IG9sZCBpcyB5b3VyIHBldD8iOjZ9LHsiRG8geW91IGhhdmUgYW55IHBldHM/IjoiWWVzOiBNb3JlIHRoYW4gb25lIiwiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Ijp0cnVlfV19LCJzY2hlbWEiOnsidGl0bGUiOiJQZXJzb24iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJEbyB5b3UgaGF2ZSBhbnkgcGV0cz8iOnsidHlwZSI6ImJvb2xlYW4ifX0sInJlcXVpcmVkIjpbIkRvIHlvdSBoYXZlIGFueSBwZXRzPyJdLCJkZXBlbmRlbmNpZXMiOnsiRG8geW91IGhhdmUgYW55IHBldHM/Ijp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJjb25zdCI6ZmFsc2V9fX0seyJwcm9wZXJ0aWVzIjp7IkRvIHlvdSBoYXZlIGFueSBwZXRzPyI6eyJjb25zdCI6dHJ1ZX0sIkhvdyBvbGQgaXMgeW91ciBwZXQ/Ijp7InR5cGUiOiJudW1iZXIifX19XX19fSwidWlTY2hlbWEiOnsic2ltcGxlIjp7ImNyZWRpdF9jYXJkIjp7InVpOmhlbHAiOiJJZiB5b3UgZW50ZXIgYW55dGhpbmcgaGVyZSB0aGVuIGJpbGxpbmdfYWRkcmVzcyB3aWxsIGJlIGR5bmFtaWNhbGx5IGFkZGVkIHRvIHRoZSBmb3JtLiJ9fSwiY29uZGl0aW9uYWwiOnsiRG8geW91IHdhbnQgdG8gZ2V0IHJpZCBvZiBhbnk/Ijp7InVpOndpZGdldCI6InJhZGlvIn19LCJhcnJheU9mQ29uZGl0aW9uYWxzIjp7Iml0ZW1zIjp7IkRvIHlvdSB3YW50IHRvIGdldCByaWQgb2YgYW55PyI6eyJ1aTp3aWRnZXQiOiJyYWRpbyJ9fX0sImZpeGVkQXJyYXlPZkNvbmRpdGlvbmFscyI6eyJpdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX0sImFkZGl0aW9uYWxJdGVtcyI6eyJEbyB5b3Ugd2FudCB0byBnZXQgcmlkIG9mIGFueT8iOnsidWk6d2lkZ2V0IjoicmFkaW8ifX19fX0=)
Will close this now!
