### ISSUE TITLE
Removing or reordering an ArrayField breaks app

### ISSUE THREAD

**Issue by louisbyrne89** [mozilla-services/react-jsonschema-form#1333]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I've created a jsfiddle here: https://jsfiddle.net/louisbyrne/q6yghz04/34/

Issue 1: When removing or reordering the "list 1" item in my jsfiddle (which uses the ArrayField component) I recieve the following console error:
`ArrayField.js:370 Uncaught TypeError: n.map is not a function
    at t.value (ArrayField.js:370)
    at t.value (ArrayField.js:343)
    at p._renderValidatedComponentWithoutOwnerOrContext (react.min.js:13)
    at p._renderValidatedComponent (react.min.js:13)
    at p._updateRenderedComponent (react.min.js:13)
    at p._performComponentUpdate (react.min.js:13)
    at p.updateComponent (react.min.js:13)
    at p.receiveComponent (react.min.js:13)
    at Object.receiveComponent (react.min.js:15)
    at Object.updateChildren (react.min.js:13)`

This is because, the following item, which is a string field, now uses the ArrayField component. As the default value is a string and not an array, it breaks the component when it tries to map over the default value. 

I've created a second jsfiddle here: https://jsfiddle.net/louisbyrne/ed7jvx01/2/
Delete the "string 1" entry. Now all other entries are using the enum field's widget (two should still be using the string fields widget

It seems that the fields components are not correctly updating when the formData array items are being updated.

I feel this may be related to #1046 

#### Expected behavior
Fields components correctly update when formData changes

#### Actual behavior
When updating an array, the components are not being updated correctly, resulting in the app breaking due to incorrect data being passed into components.

### Version
1.6.1

**Comment by epicfaace** [comment]
Can you see if you can reproduce this on the playground? both on https://mozilla-services.github.io/react-jsonschema-form/ and then https://deploy-preview-1335--trusting-agnesi-d3347d.netlify.com/ That way we can see if #1335 fixes it.

**Comment by louisbyrne89** [comment]
Yes this fixes the issue. Thanks!
