### ISSUE TITLE
anyOf/oneOf properties don't show default value

### ISSUE THREAD

**Issue by choweiyuan** [mozilla-services/react-jsonschema-form#1334]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
When using oneOf/anyOf, I expect my properties to display the default value specified, and formData to reflect according after selecting one of the options.

See [here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwiYW55T2YiOlt7InRpdGxlIjoiRmlyc3QgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifX19LHsidGl0bGUiOiJTZWNvbmQgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJpZENvZGUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiSUQgY29kZSJ9fX1dfSwidWlTY2hlbWEiOnt9fQ==)

### Steps to Reproduce
See [here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwiYW55T2YiOlt7InRpdGxlIjoiRmlyc3QgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifX19LHsidGl0bGUiOiJTZWNvbmQgbWV0aG9kIG9mIGlkZW50aWZpY2F0aW9uIiwicHJvcGVydGllcyI6eyJpZENvZGUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiSUQgY29kZSJ9fX1dfSwidWlTY2hlbWEiOnt9fQ==)
1. Select First method of identification

#### Expected behavior

"First name" should populate "Chuck" and formData should contain "Chuck" after selecting First method of identification

#### Actual behavior

formData is empty, and" Chuck" is not populated in "First name"

### Version

1.6.1

**Comment by epicfaace** [comment]
Fixed by #1338.
