### ISSUE TITLE
What is the project's release cadence?

### ISSUE THREAD

**Issue by TheNando** [mozilla-services/react-jsonschema-form#1351]
### Description

There is a bug fix in master that would really help our team out for our project. We are considering just temporarily bundling a build, but it seems you may be close to a release.

**Comment by epicfaace** [comment]
@TheNando we'll release soon, but in the meantime you can just do this to install from a specific commit:

```
npm i -S git+https://github.com/mozilla-services/react-jsonschema-form.git#07b07b1ec648f49d7eb361e655728b4a50f4856b
```

**Comment by TheNando** [comment]
Thanks
