### ISSUE TITLE
Separate the fields component into another repository

### ISSUE THREAD

**Issue by videni** [mozilla-services/react-jsonschema-form#1359]
please make the fields component generic, so we can use it with other library, such as [AntDesign](https://github.com/ant-design/ant-design). 

we are trying to use it with Ant Design, however those field components are  not generic enough,  we have to do a similar work like this library.

**Comment by epicfaace** [comment]
Take a look at [this proposal](https://github.com/mozilla-services/react-jsonschema-form/issues/1222#issuecomment-511054781).

**Comment by videni** [comment]
@epicfaace , thanks,  your proposal is what I want, this can be closed.
