### ISSUE TITLE
Can $ref support be added in uiSchema as well

### ISSUE THREAD

**Issue by KKS1** [mozilla-services/react-jsonschema-form#1368]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I see $ref reference based definitions support is added in schema. Can the same be extended for uiSchema as well.
https://github.com/mozilla-services/react-jsonschema-form/pull/69

### Steps to Reproduce

Try putting definitions and referencing them. ( all under uiSchema )

#### Expected behavior

$ref should be able to abstract the snippet and attach it for uiSchema underlying field.

#### Actual behavior

$ref with definitions only work under schema and not uiSchema.

### Version

^1.5.0

**Comment by epicfaace** [comment]
It may be difficult, because uiSchema isn't really a JSON Schema (it's not structured the same way). Perhaps the best way to do this would be to implement a way to embed `ui:` attributes in the JSON schema, as mentioned in #701.

**Comment by epicfaace** [comment]
Closing this and we'll track the issue in #701, then.

**Comment by arjan** [comment]
I [implemented](https://gist.github.com/arjan/bf90aa09808d4aa0be15f798c900d6fc) a basic method to add a `$ref` syntax within the UI schema to resolve references.

The idea is that you preprocess the UI schema before passing it in to the `Form` component:

    <Form uiSchema={resolveUiSchemaReferences(uiSchema)} ...>
