### ISSUE TITLE
non required number type field starts off with a value of 0

### ISSUE THREAD

**Issue by alexmnguyen** [mozilla-services/react-jsonschema-form#137]
### Description

When a field has a type number and is not required, the starting value for the field is 0. Since 0 is possibly a legitimate value, shouldn't this field be empty by default instead?

Here is the output for JSON.stringify(props):
```
{"name":"temperature",
"required":false,
"schema":{"description":"Temperature of the asset in CELSIUS.","type":"number"},
"idSchema":{"id":"root_temperature"},
"formData":0,
"registry":{"fields":{},"widgets":{},"definitions":{}}}
```

#### Expected behavior

The field should start off as an empty field.

#### Actual behavior

The field starts off with a value of 0.

### Version

"react-jsonschema-form": "^0.21.0"

**Comment by alexmnguyen** [comment]
I tried again with another approach. This time I tried specifying the type in the JSON schema as:
```
"type":["number","null"] 
```
Since it looks like anyOf is still an open issue. However, this doesn't seem to work either. Basically, I'd like this particular field to accept either number or null as a valid value. I also get an error if I try to specify the type as just being "null". I receive unsupported field schema errors in both situations:
```
Unsupported field schema { "description": "description", "type": "null" }.
```
```
Unsupported field schema { "description": "description", "type": [ "null", "number" ] }.
```
The full JSON schema looks like this:
```
{
  "description": "The temperature",
  "properties": {
    "temperature": {
      "description": "description",
      "type": [
        "null",
        "number"
      ]
    }
  },
  "type": "object"
}
```
Is defining a field type as both number or null currently possible with this react component? Great work on the component by the way, everything else seems to work for me.

Thanks.

**Comment by n1k0** [comment]
You're right, a non-required number shouldn't have a default of `0`. This is a bug.

As for composite types, they're indeed not supported atm and neither the `"null"` type is, as it would be useless to support it without them (I think?).

We're accepting contribs btw ;)

**Comment by alexmnguyen** [comment]
@n1k0 
Thanks for the quick turnaround. I did an npm update to get to `"react-jsonschema-form": "^0.24.0"`and tried it against my schema. It looks like non required fields are no longer populated by default, but when I try to submit the form, the validation still runs against the non required field. In this case, it tells me that the value in the field is not a number. I think that the desired behavior would be to allow submission when these fields are empty. What do you think?

**Comment by n1k0** [comment]
@alexmnguyen could you please paste a sample schema reproducing your issue?

**Comment by alexmnguyen** [comment]
@n1k0 sure, the subsection of the schema that is affected looks like this:
```
{
  "properties": {
    "temperature": {
      "description": "Temperature of the asset in CELSIUS.",
      "type": "number"
    }
  },
  "type": "object"
}
```

The full schema looks like this:
```
{
	"description": "A set of fields that constitute the writable fields in an asset's state. AssetID is mandatory along with at least one writable field. In this contract pattern, a partial state is used as an event.",
	"properties": {
		"assetID": {
			"description": "The ID of a managed asset. The resource focal point for a smart contract.",
			"type": "string"
		},
		"carrier": {
			"description": "transport entity currently in possession of asset",
			"type": "string"
		},
		"extension": {
			"description": "Application-managed state. Opaque to contract.",
			"properties": {},
			"type": "object"
		},
		"location": {
			"description": "A geographical coordinate",
			"properties": {
				"latitude": {
					"type": "number"
				},
				"longitude": {
					"type": "number"
				}
			},
			"required": [
				"latitude",
				"longitude"
			],
			"type": "object"
		},
		"temperature": {
			"description": "Temperature of the asset in CELSIUS.",
			"type": "number"
		},
		"timestamp": {
			"description": "RFC3339nanos formatted timestamp.",
			"type": "string"
		}
	},
	"required": [
		"assetID"
	],
	"type": "object"
}
```
I've tried it out on the live playground, but I'm not sure if it is possible force a submit button to show up there. Basically, the validation error only appears once I click submit. Please check screenshot below if you want to see what it looks like after clicking submit.

![image](https://cloud.githubusercontent.com/assets/12763793/14567963/a09489d4-0304-11e6-8aec-eb535709982d.png)

**Comment by n1k0** [comment]
I've just published a new version of the playground which allows to submit the form to get onSubmit validation, and couldn't reproduce the issue you describe using your sample schema. Could you please try again?

**Comment by alexmnguyen** [comment]
@n1k0 Sorry about that, the issue was on my end. I had tried modifying the default field on the schema directly earlier when I originally wrote the issue, but forgot to remove it when trying out your update. It looks like your update fixed the issue. Thanks for the help.
