### ISSUE TITLE
User-submitted data loss with an additionalProperties object when a title is present 

### ISSUE THREAD

**Issue by erunion** [mozilla-services/react-jsonschema-form#1382]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If there is an `additionalProperties` object present that has a `title` contained within it, the input for that title is overridden whenever you click out of the input.

### Steps to Reproduce

```
{
  "title": "A customizable registration form",
  "description": "A simple form with additional properties example.",
  "type": "object",
  "additionalProperties": {
    "type": "object",
    "properties": {
      "code": {
        "type": "integer"
      },
      "text": {
        "type": "string"
      }
    },
    "title": "This is a custom title"
  }
}
```

1. Click to add a new object
2. In the "This is a custom title" input box, type "TKTK".
3. Click out of the input
4. Input reverts to "This is a custom title" and neither the key, nor the headers the get updated to "TKTK Key" nor "TKTK".
5. Remove `"title": "This is a custom title"` from the JSON Schema, repeat steps, everything works as expected.

See this playground link for a quick example: https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkEgY3VzdG9taXphYmxlIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIHdpdGggYWRkaXRpb25hbCBwcm9wZXJ0aWVzIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNvZGUiOnsidHlwZSI6ImludGVnZXIifSwidGV4dCI6eyJ0eXBlIjoic3RyaW5nIn19LCJ0aXRsZSI6IlRoaXMgaXMgYSBjdXN0b20gdGl0bGUifX0sInVpU2NoZW1hIjp7fX0=

#### Expected behavior

The data that is input into the key input should be retained.

#### Actual behavior

Input data is lost.

### Version

dev-master

**Comment by epicfaace** [comment]
@erunion I see you made a fix for this in your work -- would you be able to add a PR upstream to this repo?

**Comment by erunion** [comment]
@epicfaace yep! should have a PR this weekend for y'all.
