### ISSUE TITLE
Array of objects data entry not working with liveOmit

### ISSUE THREAD

**Issue by epicfaace** [mozilla-services/react-jsonschema-form#1396]
### Description

Array of objects data entry not working with liveOmit.

### Steps to Reproduce

1. Go to [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6e30sInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ1aVNjaGVtYSI6e319)
2. Type in a value for "name".

#### Expected behavior

The form data should be

```
[{name: "asdasd"}]
```

#### Actual behavior

The form data is `{}` -- somehow liveOmit is not adding in the data properly.

![image](https://user-images.githubusercontent.com/1689183/62828438-44cb2600-bb9b-11e9-8b48-a7d90b7d759a.png)

### Version

1.7.0+ (latest version from master)

This seems to be a regression added by PR #1371 .

[PR #1371 demo](https://deploy-preview-1371--trusting-agnesi-d3347d.netlify.com/#eyJmb3JtRGF0YSI6eyJzaG93Ijp0cnVlfSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2hvdyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwiZGVwZW5kZW5jaWVzIjp7InNob3ciOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsic2hvdyI6eyJjb25zdCI6dHJ1ZX0sInBhcnRpY2lwYW50cyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19fX19XX19fSwidWlTY2hlbWEiOnt9fQ==)
[
PR #1372 demo (right before #1371)](https://deploy-preview-1372--trusting-agnesi-d3347d.netlify.com/#eyJmb3JtRGF0YSI6eyJzaG93Ijp0cnVlfSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2hvdyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwiZGVwZW5kZW5jaWVzIjp7InNob3ciOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsic2hvdyI6eyJjb25zdCI6dHJ1ZX0sInBhcnRpY2lwYW50cyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19fX19XX19fSwidWlTY2hlbWEiOnt9fQ==)

**Comment by Tonexus** [comment]
It looks like the lodash `_pick` call here is causing the issue

https://github.com/mozilla-services/react-jsonschema-form/blob/20ff3b97a18c061e08bc157fd3851cf4ba7101c6/src/components/Form.js#L136-L143

According to the lodash docs, `_pick` will always return an object, which will mess up validation if the root type of the schema is an array.

**Comment by epicfaace** [comment]
@tonexus hmm, thanks... Do you have a way in mind that might fix it?

**Comment by Tonexus** [comment]
I created a PR that fixes part of the issue, but I found a second problem. The current usage of `_pick` doesn't seem able to preserve an empty object (or an empty array) inside of an array, so your specific example will still be bugged, as the objects containing the text fields will be immediately removed. I don't have time to look more in depth right now, but a workaround would be to have some default value for the text field and otherwise making sure that the object is never empty.

**Comment by Tonexus** [comment]
@epicfaace Ok, it looks like there is only one case of nesting that does get preserved by omitExtraData. When there is an empty object inside of an object (compared to empty array in object, empty object in array, and empty array in array), `_pick` removes the inside object, but it looks like it gets readded in `getDefaultFormState` in `utils.js`.

Should the same be happening for arrays? My main concern is that once `_pick` is called, you lose the array, so you don't know how many array elements you need to build again, so you would have to propagate that info. The alternative would be to do something else (or in addition) when `_pick` is called.

**Comment by epicfaace** [comment]
It's also broken without dependencies: [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6W10sInNjaGVtYSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0In19LCJ1aVNjaGVtYSI6eyJsaXN0T2ZTdHJpbmdzIjp7Iml0ZW1zIjp7InVpOmVtcHR5VmFsdWUiOiIifX0sIm11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9LCJmaXhlZEl0ZW1zTGlzdCI6eyJpdGVtcyI6W3sidWk6d2lkZ2V0IjoidGV4dGFyZWEifSx7InVpOndpZGdldCI6InNlbGVjdCJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InVpOndpZGdldCI6InVwZG93biJ9fSwidW5vcmRlcmFibGUiOnsidWk6b3B0aW9ucyI6eyJvcmRlcmFibGUiOmZhbHNlfX0sInVucmVtb3ZhYmxlIjp7InVpOm9wdGlvbnMiOnsicmVtb3ZhYmxlIjpmYWxzZX19LCJub1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19LCJmaXhlZE5vVG9vbGJhciI6eyJ1aTpvcHRpb25zIjp7ImFkZGFibGUiOmZhbHNlLCJvcmRlcmFibGUiOmZhbHNlLCJyZW1vdmFibGUiOmZhbHNlfX19LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjp0cnVlLCJsaXZlT21pdCI6dHJ1ZX19)

**Comment by MatinF** [comment]
We're seeing this issue as well in our form with the latest commit.
