### ISSUE TITLE
Playground URL should serialize checkboxes as well

### ISSUE THREAD

**Issue by epicfaace** [mozilla-services/react-jsonschema-form#1400]
### Description

Currently, if I check a checkbox such as "Live validation" or "Omit extra data" and then copy a link from a playground, the link does not encode that I have checked the checkbox. It only encodes the schema, uiSchema, and formData.

### Solution

Encode the checkbox values as well, so that links can be more easily shared.

**Comment by GrooChu** [comment]
Hi @epicfaace Please check my PR for this issue. #1403 I have tested the changes in my local env and it is working as expected. Let me know if you need anything else. Thanks
