### ISSUE TITLE
Seperating Date and DateTime widgets.

### ISSUE THREAD

**Issue by plasmashadow** [mozilla-services/react-jsonschema-form#142]
Instead of having DateTime widget. Can you guys separate out date and date-time widgets. The reason i am saying this is because if i want to get the date of birth at that moment date-time widgets seems to be not meaningful. 

Or is there any way i can get only date widget?

**Comment by n1k0** [comment]
Makes sense, will do.

**Comment by plasmashadow** [comment]
+1

**Comment by plasmashadow** [comment]
It seems when used {format: "date"} it causing some problems. I am getting
``` Uncaught Error: No alternative widget "date" for type string/date```. Should i use format name to some other than "date".
