### ISSUE TITLE
Validation password fields

### ISSUE THREAD

**Issue by Chachaproper** [mozilla-services/react-jsonschema-form#144]
Fields: password and repeat-password. How to validate this? And how to return errors in form from backend?

**Comment by n1k0** [comment]
> Password and repeat-password. How to validate this? 

This is likely to need #79 to be addressed.

> And how to return errors in form from backend?

This lib is intended to use client-side validation only. We don't have use cases for propagating errors from server side validation, so if you want this to happen that's likely to require contribution :)

**Comment by n1k0** [comment]
Side note: Of course you can always add two password fields in your schema and perform validation when the form is submitted, but you then admittedly have no way to render error messages contextually to the form (meaning notifying the user outside of the form itself).

**Comment by Chachaproper** [comment]
> We don't have use cases for propagating errors from server side validation.
Hmm. Example: user registers and enters a username already contained in the database, it is logical to return an error in form.

**Comment by n1k0** [comment]
I know there are legitimate use cases for password validation in the real world, just here we're dealing with a client side librariy which has no plan on supporting server side rendering nor validation anytime sound. I'm just suggesting that if you want to see this happening, you should probably start to get involved by participating in the reflexion process how should it be done, eg by providing feedback on the issue I've just filed for your specific need in #145?

**Comment by Chachaproper** [comment]
Thanks for answers!

**Comment by n1k0** [comment]
Also filed #146 to initiate a conversation about async external validation.

**Comment by n1k0** [comment]
@Chachaproper I've started an experiment in #163 about that, feedback welcome.

**Comment by n1k0** [comment]
The fix has landed as part of [v0.30.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.30.0).
