### ISSUE TITLE
"ui:widget": "date" to native input type=date ?

### ISSUE THREAD

**Issue by kaihendry** [mozilla-services/react-jsonschema-form#150]
### Description

The date widget imo seems like a steps backwards in usability.

<img src=http://s.natalian.org/2016-04-20/1461122399_1406x1404.png>

Not sure how to use the native https://html.spec.whatwg.org/multipage/forms.html#date-state-(type=date) instead.

### Steps to Reproduce

1. http://s3.jptdev.com/2016-04-20/date.html
2. Marvel at dropdown selectors to choose a date
3. Wonder if it's possible to use type=date instead

#### Expected behavior

<img src=http://s.natalian.org/2016-04-20/1461122715_2558x1404.png>

Use the native browser date picker.
http://caniuse.com/#feat=input-datetime

#### Actual behavior

Drop down select boxes

### Version

https://npmcdn.com/react-jsonschema-form@0.25.0/dist/react-jsonschema-form.js

**Comment by n1k0** [comment]
Re date widget, you didn't use any styles, not even bootstrap or any specific style at all. It's a little like saying a webpage is ugly when disabling its stylesheet (try on github, it's fun).

The problem with `type=date` and `type=time` HTML inputs is that they're not currently supported in Firefox, which is a problem as this is a Mozilla lib.

I agree leveraging standards when they exist is a great idea though, so I'll try to figure out how to provide these by default and move the current date widgets to alternative ones so all cases would be covered.

Thanks for the report.

**Comment by kaihendry** [comment]
Thank you, I was hoping there would be some straightforward example how I could create my own widget to implement what I want on the HTML side. Perhaps I've misunderstood "widget"?

**Comment by n1k0** [comment]
You can definitely create your own widget for implementing this, as it's documented in the README.

**Comment by kaihendry** [comment]
Ok, I think I see it now. Sorry for the bother. https://github.com/mozilla-services/react-jsonschema-form#custom-widget-components
