### ISSUE TITLE
Have automatic default "title" by "humanizing" camelCase or under_scored_fields

### ISSUE THREAD

**Issue by nuclearspike** [mozilla-services/react-jsonschema-form#154]
I find myself doing a lot of:

`first_name: {title: "First Name"}`

When it should be able to "humanize" my field names by default and I should only have to define it when it breaks the obvious pattern. The underscore lib has a humanize function that could be ripped or referenced to do what I'm interested in.

BTW: I really like this component and how flexible it is!

**Comment by n1k0** [comment]
I think preprocessing of the schema should be done outside of this lib. Closing.
