### ISSUE TITLE
Required Validation styling

### ISSUE THREAD

**Issue by andymrussell** [mozilla-services/react-jsonschema-form#159]
### Description

I am having issues with required validation not actually working.
### Steps to Reproduce
1. Create a simple form with 1 required field
2. Add a novalidate attribute to the form tag (to avoid using built in HTML5 form validation)
3. Submit the form
#### Expected behavior

I expect the submit method not to be called, and the errors method should be called.
#### Actual behavior

Submit method is called claiming the form is valid.
### Version

Version: 0.26.1

**Comment by n1k0** [comment]
I don't get what you're trying to do, nor how; how are you adding a novalidate attribute to the form?

Could you please paste some code or ideally setup some gist? Thanks.

**Comment by andymrussell** [comment]
I added the novalidate to the form manually only as a test to see how validation is handled.
What I am trying to achieve is showing styled errors like you currently do, but if a required field is empty.
Currently if you specify required fields, they only get validated as HTML5 validation rather than anything regarding react.

Essentially you cant style required field failed validation in the same way you do for other validation.

**Comment by n1k0** [comment]
> Essentially you cant style required field failed validation in the same way you do for other validation.

That's more clear indeed. What's the problem with HTML5 validation for required fields? Is this only a styling issue, or something else?

**Comment by andymrussell** [comment]
Yeh, I would say its a styling thing.

**Comment by magopian** [comment]
I did a quick test using https://mozilla-services.github.io/react-jsonschema-form/ (in the "errors" form): I used the inspector to manually add the `novalidate` attribute to the form, and the behavior is as expected I believe:

With `novalidate`:
<img width="572" alt="screen shot 2016-04-25 at 11 07 14" src="https://cloud.githubusercontent.com/assets/167767/14778901/d90ceeb8-0ad5-11e6-9319-387342b2b19d.png">

Without `novalidate`:
<img width="587" alt="screen shot 2016-04-25 at 11 07 53" src="https://cloud.githubusercontent.com/assets/167767/14778914/eab9f4d0-0ad5-11e6-892a-bb6f34c20ebf.png">

So it seems the html5 default validation is properly disabled using the `novalidate` attribute, but still the react-jsonschema-form validation error is displayed.

Am I missing something?

**Comment by n1k0** [comment]
As mentionned previously I think this is mostly about getting rid of the default HTML5 styling and using the lib error styling for required fields instead. Am I right @andymrussell?

**Comment by andymrussell** [comment]
@magopian That validation is for min length, not required field.
@n1k0 You are 100% correct.

**Comment by uglow** [comment]
So is there a way to turn off HTML5 validation (by adding novalidate to the <Form> component)?

**Comment by epicfaace** [comment]
Closing this issue, but feel free to reopen it if you have any additional questions!
