### ISSUE TITLE
React.render() schema/uiSchema not working on Android device

### ISSUE THREAD

**Issue by jashachik** [mozilla-services/react-jsonschema-form#160]
Good evening,

Prerequisites
react-jsonschema-form version: 0.25.0
react version: 15.0.1
Desktop Chrome Versions: v43 & v50.0.2661.87 (current stable)
Android Chrome Versions: v49 (current stable) , v50 beta
Windows 7 64-bit
Samsung S2 Android 5.1.1

Currently in our implementation we have our JSON schema:

```json
"schema": {
  "type": "object",
  "properties": {
    "username": {
       "type": "string",
       "title": "Username"
     },
     "password": {
        "type": "string",
        "title": "Password"
      }
     }
   }
```

```js
import React from "react";
import Form from "react-jsonschema-form";
import LoginSchema from "../../LoginSchema.json";

export default class Login extends React.Component {
  constructor(){
   this.state = {
     formSchema: LoginSchema
   }
  }

render() {
 return(
  <div class="container">
     <div class="col-sm-12">
      <Form schema={this.state.formSchema.schema}/>
   </div>
  </div>
  );
  }

}
```

Using this code i am able to see the form render perfectly on my desktop browser with chrome version 50, version 43 was not able to render successfully. When i build and include this code into my phonegap application and build a .apk i am able to see alert messages display before the render return statement but then just a white screen is displayed. Please let me know if you need me to provide any more configuration settings, thank you in advance

James

**Comment by n1k0** [comment]
Does the [playground](http://mozilla-services.github.io/react-jsonschema-form/) work with your Chrome 43 installation?

**Comment by jashachik** [comment]
Hey n1k0,

I'm not sure if that works with older version of chrome, works with the latest, our issue is specific to this not working on an Android device


james

**Comment by jashachik** [comment]
To include in our phonegap app we compile the project into a JS file using webpack then call that file when the Android application is launched from index.html

**Comment by n1k0** [comment]
Not sure what to ask here. Also it seems to be related to some rather very specific target platform we never really intended to support. I'm closing this, but feel free to reopen if you feel this should definitely be addressed.

**Comment by jashachik** [comment]
Hey n1k0,

We tracked the issue down to the Android System Webview. Do you know what version of Webview is required for this to work? We have tested on Android 4.4.4 Kitkat and it does not work. On Android 5.1.1 it does. Please let me know if you need me to specify anything else

**Comment by n1k0** [comment]
> Do you know what version of Webview is required for this to work?

I don't have a clue, and I'm not into android/phonegap development so I don't even know what should be investigated here; sorry :/
