### ISSUE TITLE
Create horizontal forms ?

### ISSUE THREAD

**Issue by wogeard** [mozilla-services/react-jsonschema-form#166]
Hello,

I like this library very much, it is very convenient when you have many forms to handle.
I didn't manage to create form with an horizontal alignement.

It may be a stupid question but is this an available feature ?

Thank you

**Comment by n1k0** [comment]
Nope. You can either tweak the styles by providing your own CSS rules, or wait for *someone* to add native support for it :)

**Comment by wogeard** [comment]
Okay let's try the first option ! Thank you very much for your quick answer.

**Comment by n1k0** [comment]
I'm closing this, though feel free to reopen with along a PR if you plan on providing support for this feature.
