### ISSUE TITLE
Radio widget selection for enumerated string

### ISSUE THREAD

**Issue by kaihendry** [mozilla-services/react-jsonschema-form#169]
### Description

Just experimenting with widget types & I couldn't figure out how to change a select type box to a radio type selection. What am I missing?

### Steps to Reproduce

http://s.natalian.org/2016-04-26/radio.html

#### Expected behavior

Expecting to see a radio button selection

#### Actual behavior

Still a select box

### Version

https://npmcdn.com/react-jsonschema-form@0.27.0/dist/react-jsonschema-form.js

**Comment by n1k0** [comment]
Here you go: https://jsfiddle.net/f2y3fq7L/2/.
