### ISSUE TITLE
Relationship to json-schema-form standard

### ISSUE THREAD

**Issue by apkoponen** [mozilla-services/react-jsonschema-form#170]
The developers of [angular-schema-form](https://github.com/json-schema-form/angular-schema-form) are aiming to produce some type of a [standard](https://github.com/json-schema-form/angular-schema-form/wiki/Recent-developments) for generating forms out of json-schema. Would supporting something like this suit this library?

**Comment by n1k0** [comment]
That'd be a possibility, though this isn't part of any of our plans atm. Feel free to reopen if you want to work on a compatibility layer.
