### ISSUE TITLE
Error message showing after correcting validation error

### ISSUE THREAD

**Issue by kaihendry** [mozilla-services/react-jsonschema-form#176]
### Description

Confusing error message despite updating field.

### Steps to Reproduce

1. Navigate to http://s3.jptdev.com/2016-04-28/string.html
2. Submit form
3. Update age to a number like 132
4. Fails to correct validation error

http://s.natalian.org/2016-04-28/1461831222_1150x1404.png

#### Expected behavior

No error message

#### Actual behavior

Error message doesn't disappear

### Version

https://npmcdn.com/react-jsonschema-form@0.28.0/dist/react-jsonschema-form.js

**Comment by n1k0** [comment]
Seems to work just fine there: https://jsfiddle.net/f2y3fq7L/4/

Could you please check that you're using the latest version?

**Comment by kaihendry** [comment]
I'm using the same version. If I take away liveValidate, I see my issue: https://jsfiddle.net/kaihendry/1ap5cd53/1/

**Comment by n1k0** [comment]
I see. Will fix.

**Comment by n1k0** [comment]
Fix landed and released as part of [v0.28.1](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.28.1).
