### ISSUE TITLE
date format validation does not play with type=date

### ISSUE THREAD

**Issue by kaihendry** [mozilla-services/react-jsonschema-form#180]
### Description

type=date format validation is not working

### Steps to Reproduce

1. Navigate to https://jsfiddle.net/kaihendry/08d3reth/ in Chrome or some other browser that implements type=date http://caniuse.com/#feat=input-datetime
2. Choose a date
3. See a validation error http://s.natalian.org/2016-05-03/1462255048_2558x1404.png

#### Expected behavior

Should be considered a valid date

#### Actual behavior

    does not conform to the "date" format

### Version

https://npmcdn.com/react-jsonschema-form@0.28.1/dist/react-jsonschema-form.js

**Comment by n1k0** [comment]
jsonschema seems to have [strong expectations](https://github.com/tdegrunt/jsonschema/blob/master/test/formats.js#L55-L64) for the date string format, which should be YYYY-MM-DD.

I'm surprised we missed a failing test case.

**Comment by n1k0** [comment]
I know; there's currently no support for `"date"` string format as [it's not part of the current draft-v4 spec](http://json-schema.org/latest/json-schema-validation.html#anchor104) (only `"date-time"` is).

Hence why expecting a datetime it fails here. I'll probably add support for a `"date"` format though as datetimes are definitely overkill for birth dates.

**Comment by Natim** [comment]
>  I'll probably add support for the "date" string format though, as datetimes are definitely overkill for birth dates. 

:+1:

**Comment by kaihendry** [comment]
Hmm, https://npmcdn.com/react-jsonschema-form/dist/react-jsonschema-form.js still points to 0.28.1. Is there an automatic build of this change? Thank you !

**Comment by n1k0** [comment]
[v0.29.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.29.0) has just been released featuring this change.

**Comment by akaDPR** [comment]
should match format date . error when I try to submit the form .

**Comment by epicfaace** [comment]
> Can somebody Please help me with how to change the date format? for eg - by default it take "YYYY-MM-DD" and I want "MM-DD-YYYY".

We currently don't support a different date format with the default date widget.
