### ISSUE TITLE
Autofill fail

### ISSUE THREAD

**Issue by kaihendry** [mozilla-services/react-jsonschema-form#184]
### Description

Not 100% sure this is a bug in react-jsonschema-form, but I noticed then when using auto form fillers like https://chrome.google.com/webstore/detail/form-filler/bnjjngeaknajbdcgpfkgnonkmififhfo and submitting the form for validation, the form is cleared & invalid.

### Steps to Reproduce

1. Navigate to http://s3.jptdev.com/2016-05-04/autofillfail.html
2. **AutoFill** with dummy data http://s.natalian.org/2016-05-04/1462347676_2558x1404.png
3. Submit form http://s.natalian.org/2016-05-04/1462347691_2558x1404.png

#### Expected behavior

Auto-filled form populated and valid

#### Actual behavior

Auto-filled form cleared

### Version

https://npmcdn.com/react-jsonschema-form@0.29.0/dist/react-jsonschema-form.js

**Comment by n1k0** [comment]
This is because this extension programmatically attaches a value property to the DOM input element, which react can't be aware of, so it basically desynchronizes the field state from the actual DOM value.

Mutating DOM elements generated by React is never a good thing to do.

We're not gonna support this use case, so I'm closing this.

**Comment by kaihendry** [comment]
Is there some workaround to make react aware of it before it gets cleared?

**Comment by n1k0** [comment]
> Is there some workaround to make react aware of it before it gets cleared?

Not any I'm aware of, sorry.

> Or how else does one test large forms?

As the `Form` element accept a convenient `formData` object which can be some large form data set and have them rendered accordingly, it should be possible to expose some hook in your page/app environment so sample data could be propagated to the component props. Possibly from some browser extension, but not *AutoFill* in its current state.

**Comment by revolunet** [comment]
Here's a dirty workaround that you can use in componentDidMount :


```js
const autofillValues = {
  username: node.querySelector("#root_username") && node.querySelector("#root_username").value,
  password: node.querySelector("#root_password") && node.querySelector("#root_password").value
};

this.setState({
  formData: autofillValues
});
```
