### ISSUE TITLE
Field type for file upload widget?

### ISSUE THREAD

**Issue by ducwings** [mozilla-services/react-jsonschema-form#191]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

I couldn't find an example about file upload widget so I created one but formData doesn't give me the file content.

```
const schema = {
  type: 'object',
  required: ['name'],
  properties: {
    name: { type: 'string', title: 'Name', default: ' },
    file: { type: 'string', title: 'File' }
  }
}
const uiSchema = {
  file: {
    'ui:widget': (props) => {
      return (
        <input type="file"
               required={props.required}
               onChange={(event) => props.onChange(event.target.value)} />
      )
    }
  }
}
```
I guess I'm using file "type" incorrectly? Should it be 'object' and how can I get the file content?
Please help. Thanks.
- Duc

### Steps to Reproduce

Described above

#### Expected behavior

How to get file content for uploading?

#### Actual behavior

Throw error if I use 'object' type
formData doesn't have file content

### Version

0.29.1

**Comment by n1k0** [comment]
You should learn about how to process file data, and here's a [good introduction](http://stackoverflow.com/questions/28804095/html5-restrict-file-upload); also, I've set up a jsfiddle for you https://jsfiddle.net/f9vcb6pL/1/.

I don't have a clear picture how what native support for file uploads should look like in this lib, and I'll take some more time to think about it.

Closing this.
