### ISSUE TITLE
Add a file widget

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#192]
Refs #191. 

We should add a default `FileWidget` component, capable of mapping the file contents to their dataURL string representation. Other use cases should be dealt with custom field/widget components I think.

Nice to have:

- Single or multiple files (`string` or `array` of `string`s schema)
- Preview for pictures
- Multiple files handling (mapping to an array of dataURLs)

Sample fiddle: https://jsfiddle.net/f9vcb6pL/1/

**Comment by nbasu02** [comment]
Having this added would be really helpful on my end.  Will this be included in the next release?

**Comment by n1k0** [comment]
We're gonna need this for some Mozilla projects very soon, so be assured it will eventually land.

**Comment by mohsen1** [comment]
In other tools `format: file` is usually used to indicate a file schema:

```json
{
  "type": "string",
  "format": "file"
}
```

**Comment by n1k0** [comment]
> In other tools format: file is usually used to indicate a file schema

Which other tools?
