### ISSUE TITLE
With liveValidate set to false, deleting an array item preserves error at the previous index 

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#195]
Steps to reproduce:

1. Head to the [playground](http://mozilla-services.github.io/react-jsonschema-form/)
2. Disable live validation 
3. Go to the *Errors* tab
4. Submit the form
5. Delete one of the second item of the *skills* array

Result:

The second listed field is now marked in error, while the value it holds is valid.

**Comment by nuclearspike** [comment]
+1 I've been having this issue ever since the latest npm update.

**Comment by n1k0** [comment]
The fix has landed as part of [v0.30.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.30.0).
