### ISSUE TITLE
Custom asynchronous validation

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/react-jsonschema-form#197]
Allow the `validate()` function to return a promise so that custom validation can be asynchronous.

The whole process of validation (and display of errors in state) should now be asynchronous.

**Comment by nuclearspike** [comment]
For anyone who wants something close to this... the workaround I've done is to add a 'ref' property to the Form component, then after it attempts an AJAX submission that fails (Rails 422 response with "errors: {field_name: [array of errors]}", I have it do a this.refs.form.setState({errorSchema}) where I've reformatted the response to match what is expected and everything works fine.

**Comment by nuclearspike** [comment]
UPDATE: Unfortunately, some other changes to the component have made my workaround stop working.

**Comment by knilink** [comment]
A short demo of implementation with "[redux-saga](https://github.com/redux-saga/redux-saga)/takeLatest"
https://jsfiddle.net/z299ynsz/4/
Validation will be applied after user stop editing for more then 500ms. 
Validation will fail and error message will be display, if input is less then 10 characters.

**Comment by elisechant** [comment]
@knilink I like where your solution is heading, but I thought a feature of the library was to stay out of Redux?

**Comment by knilink** [comment]
@elisechant Agreed, above was just quick prototyping. : )

**Comment by epicfaace** [comment]
Continue discussion on this wrapper issue: #1389
