### ISSUE TITLE
Is there any chances to get support for oneOf?

### ISSUE THREAD

**Issue by harshal123** [mozilla-services/react-jsonschema-form#200]

**Comment by n1k0** [comment]
I'm sorry, what's the question precisely? We have a checkbox widget already.

**Comment by harshal123** [comment]
Hi Nicholas,

Thanks for getting back quickly.

json-schema supports four keywords *anyOf, allOf, oneOf, not * intend to
bring logical processing primitives to JSON Schema validation.

They would allow to get rid of:

   - schemas in type;
   - the disallow keyword;
   - the extends keyword.

Here are the complete details.
https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not

I am working on json-schema which has oneOf functionality simple checkbox
can't be enough i guess.

Can you help me in this?



On Tue, May 10, 2016 at 6:56 PM, Nicolas Perriault <notifications@github.com

**Comment by n1k0** [comment]
Lol, for some reason I read *on/off* and not *oneOf*, I must be tired :D

We already have an issue filed about this in #52, so i'll close this as it's a duplicate.

Side note, bringing support for this is not in our current priorities, but we do certainly accept patches ;)
