### ISSUE TITLE
Array Widget Without Add/Delete buttons

### ISSUE THREAD

**Issue by jashachik** [mozilla-services/react-jsonschema-form#202]
While working with the array widget I did not see a way that you could disable/remove the add/delete buttons. I was able to add the HTML tag for submit button to have that hidden, is there a similar feature for these buttons?

**Comment by n1k0** [comment]
Fixed items arrays already don't show the Add/Delete buttons (see the example in the *Arrays* section of the playground). Otherwise, yes, you have these by default. If you want to hide them, you have to do so using CSS, or by creating your own custom component.

**Comment by jashachik** [comment]
I am looking to populate the array object with dynamic data so we had to rule out fixed items. You mentioned hiding with CSS, I was able to suppress the submit button with matching the 'type' with button object and using a CSS class to make it hidden, is it similar with the add/delete? can you point to/provide an example of this?

**Comment by n1k0** [comment]
> is it similar with the add/delete? 

Sounds like what I'd do, yes.

> can you point to/provide an example of this?

Unfortunately, we didn't encountered this use case yet.

**Comment by jashachik** [comment]
I'll try out a couple options and let you know what fails and if any work, thanks again for your help!

**Comment by jashachik** [comment]
So the solution i came up with is overriding the CSS classes in my custom CSS.

Something easy like:

.btn-info {
  display: none;
}

.btn-danger {
  display: none;
}

Works since we aren't using those anywhere else
