### ISSUE TITLE
[MS IE 11] Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by alex-perfilov-reisys** [mozilla-services/react-jsonschema-form#206]
### Description

[MS IE 11] Object doesn't support property or method 'assign'

### Steps to Reproduce

1. Open any MS Internet Explorer (I used IE 11)
2. Open playground https://mozilla-services.github.io/react-jsonschema-form/

#### Expected behavior

Form is shown

#### Actual behavior

SCRIPT438: Object doesn't support property or method 'assign'

### Version

branch `gh-pages`

**Comment by alex-perfilov-reisys** [comment]
possible solution https://www.npmjs.com/package/object-assign

**Comment by n1k0** [comment]
The build files ensure a polyfill for `Object.assign` through babel. If you're producing your own custom builds, it's up to you to install the right polyfills targeting the right platforms in your project.

**Comment by n1k0** [comment]
Wait. You say *branch gh-pages*, that means the playground doesn't work on IE 11? I'm reopening.

**Comment by n1k0** [comment]
I'm really surprised as the [bundle.js](http://mozilla-services.github.io/react-jsonschema-form/bundle.js) file clearly shows a polyfill being defined in the source. 

![](http://i.imgur.com/hcWgts2.png)

Can you confirm this is happening with the playground hosted at http://mozilla-services.github.io/react-jsonschema-form/?

**Comment by n1k0** [comment]
We could also load [polyfill.io](http://polyfill.io/) polyfills by default in the playground.

**Comment by alex-perfilov-reisys** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#https://mozilla-services.github.io/react-jsonschema-form/

Confirm, it's for github playground only




On Wed, May 18, 2016 at 2:36 PM -0700, "Nicolas Perriault" <notifications@github.com<mailto:notifications@github.com>> wrote:


We could also load polyfill.io<http://polyfill.io/> polyfills by default in the playground.

-

**Comment by alex-perfilov-reisys** [comment]
Looks like some cases were not transformed
<img width="222" alt="screenshot 2016-05-18 18 59 21" src="https://cloud.githubusercontent.com/assets/6089683/15377582/bcc8cde6-1d2a-11e6-8001-c489be78ecdc.png">

**Comment by NaomiN** [comment]
I got the same issue as well as problems with find and findIndex methods for arrays. What should be my code in IE instead?

**Comment by n1k0** [comment]
As mentioned in https://github.com/mozilla-services/react-jsonschema-form/issues/206#issuecomment-220165629 you could load specific polyfills for IE. Didn't that work for you?

**Comment by NaomiN** [comment]
I am not sure how should I do that and will it work for other people? In the meantime I already implemented workaround.

**Comment by n1k0** [comment]
Just add `<script src="//cdn.polyfill.io/v2/polyfill.min.js"></script>` to your html document.

**Comment by sbinder** [comment]
n1k0,

Adding the CDN polyfill above causes:

    SCRIPT5022:  Exception thrown and not caught
    polyfills.bundle.js (830,34)

**Comment by n1k0** [comment]
Does this happen on https://mozilla-services.github.io/react-jsonschema-form/ as well?

**Comment by xmaryposax** [comment]
try this https://github.com/aspnet/JavaScriptServices/wiki/Supporting-Internet-Explorer-11-(or-older)
