### ISSUE TITLE
uiSchema (ui:widget) for nested schema values 

### ISSUE THREAD

**Issue by michaelryancaputo** [mozilla-services/react-jsonschema-form#208]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

Can't seem to select fields in nested values to be used with ui:widget

Schema:
```
    faq: {
      type: 'array',
      title: 'Faq',
      items: {
        type: 'object',
        required: ['question', 'answer'],
        properties: {
          question: {
            type: 'string',
            title: 'Question',
            placeholder: 'Why is the sky blue...'
          },
          answer: {
            type: 'string',
            title: 'Answer',
            placeholder: 'Because I said so...'
          }
        }
      }
    },
```

uiSchema (have tried each)

```
    question: {'ui:widget': 'customTextInput'},
    answer: {'ui:widget': 'customTextInput'}
```
and
```
  faq: {
    question: {'ui:widget': 'customTextInput'},
    answer: {'ui:widget': 'customTextInput'}
  },
```
and
```
  faq: [
    question: {'ui:widget': 'customTextInput'},
    answer: {'ui:widget': 'customTextInput'}
  ],
```

### Steps to Reproduce

1. Create a form using the schema above,
2. use the uiSchema values as stated above

#### Expected behavior

I would expect to be able to apply my ui:widget to nested schema fields.

#### Actual behavior

The field retained the basic styling that I am not using.

### Version

0.30.1

**Comment by n1k0** [comment]
We already answered this in #201, we'll have to update docs asap. The syntax is:

```js
faq: {
  items: {
    question: {'ui:widget': 'customTextInput'},
    answer: {'ui:widget': 'customTextInput'}
  }
}
```

Can you confirm it works? Thanks.

**Comment by n1k0** [comment]
Code sample added to docs in #209.

**Comment by michaelryancaputo** [comment]
Appreciate it very much, thank you.

**Comment by michaelryancaputo** [comment]
Confirmed that it works.
