### ISSUE TITLE
Allow extending form builder by exposing a method that allows overriding components 

### ISSUE THREAD

**Issue by mohsen1** [mozilla-services/react-jsonschema-form#216]
Currently the only way to use my own widget/components is to fork this repo and build it from scratch. I want to propose an API that allows overriding any component with my own. Here how I think it should look like:

```js

import Form from "react-jsonschema-form";
import MyColorWidget from "./color-widget";

cosnt MyForm = Form.extend({
  ColorWidget: MyColorWidget
});

// ...
render((
  <MyForm schema={schema} // ...
```

**Comment by n1k0** [comment]
I'm confused as this is already possible by creating and registering custom fields and widgets https://github.com/mozilla-services/react-jsonschema-form#advanced-customization

What's missing?

**Comment by mohsen1** [comment]
I missed that part of the README. Although it's a different API, what I'm asking for is totally doable with your API. Closing the issue as it's already exists.
