### ISSUE TITLE
Description for boolean field

### ISSUE THREAD

**Issue by bodnia** [mozilla-services/react-jsonschema-form#218]
Now no description for boolean type is displayed - only title and rewriting the DescriptionField doesn't affect boolean type.
Is it possible to add support of description to boolean type?

**Comment by n1k0** [comment]
> Now no description for boolean type is displayed

Does that mean it was working and doesn't anymore? As far as I can tell the only support we always had for descriptions on boolean fields was to apply a *title* attribute on the widget.

Why don't you use the `ui:help` uiSchema directive to provide contextual information to the field?

**Comment by bodnia** [comment]
Sorry for confusing you. I meant that for boolean properties there is only title with description and no description (from json property) text above/under description.

**Comment by n1k0** [comment]
Okay now I get it. It's indeed a good idea to offer the opportunity to render a description field above widgets for all field types. I'll work on this, thanks for your report.

**Comment by webron** [comment]
@n1k0 - Thanks for looking into this. I was hoping to get an update from you if you had a chance to work on it. If not, we can try to look into submitting a PR for this feature as well, if that's acceptable (we don't have a working solution for this so it's not going to be immediate).

**Comment by n1k0** [comment]
Released in [v0.36.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.36.0).

**Comment by bodnia** [comment]
@n1k0 after adding the description in `Wrapper` in arrays now there are 2 description instead of one, and for whole form there are 2 descriptions too.

**Comment by n1k0** [comment]
> @n1k0 after adding the description in Wrapper in arrays now there are 2 description instead of one, and for whole form there are 2 descriptions too.

I've just created #265 about this; could you please check about it and provide some feedback? Thanks.

**Comment by bodnia** [comment]
@n1k0 thanks, looks all fixed

**Comment by n1k0** [comment]
@bodnia the fix has been released in [v0.36.1](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.36.1).
