### ISSUE TITLE
Investigate why we have a `value` property in Multiple ChoiceField tests.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/react-jsonschema-form#219]
https://github.com/mozilla-services/react-jsonschema-form/blob/e6079b1b155ad0faec7549c5bcffb400075f6184/test/ArrayField_test.js#L191

**Comment by n1k0** [comment]
Dead code. Fixed by https://github.com/mozilla-services/react-jsonschema-form/commit/277e7ee122579f0aff68057fd98ef70cc06aab69
