### ISSUE TITLE
Restrict accepted mimetypes in file widget

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/react-jsonschema-form#226]
See https://davidwalsh.name/accept-attribute

**Comment by epicfaace** [comment]
@leplatrem are you interested in doing a PR for this?

**Comment by leplatrem** [comment]
Why not! But I must admit that it'd be very low in my priority list...

**Comment by epicfaace** [comment]
@gr8pathik would you be interested in taking this on?

**Comment by epicfaace** [comment]
Fixed by #1246.
