### ISSUE TITLE
Form Submitted on initialization when i create form with formdata

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [mozilla-services/react-jsonschema-form#227]
i am try to create form to edit my data.
i am created and passed formdata in form.
but on initialization of form, form submitted automatically..

what can i do to stop that ??

i want submit form when form data is changed by user...

**Comment by n1k0** [comment]
Hard to tell without any code to look at. Please provide an example as well as the version you're using and reproduction steps.

**Comment by nilaybrahmbhatt** [comment]
const schema = {
      title: "",
      type: "object",
      required: ["firstname"],
      properties: {
        firstname: {type: "string", title: "First Name"},
        lastname: {type: "string", title: "Last Name"},
        address: {type: "string", title: "Address"},
        landmark: {type: "string", title: "Land Mark"},
        direction: {type: "string", title: "Direction"},
        city: {type: "number", title: "City"},
        area: {type: "number", title: "Area"},
        pincode: {type: "number", title: "Pincode"},
        addresstype: {type: "number", title: "Address Type",
              enum: [0,1, 2],
              enumNames: ["Home", "Office", "Other"]
            },
        company: {type: "string", title: "Company/other"},
        defaultaddress: {type: "boolean", title: "Default Address"},
        }
      };


var formData = {
          firstname:address.firstname,
          lastname: address.lastname,
          address: address.address_1,
          direction: address.direction,
          city:address.city_id,
          area:address.area_id,
          pincode:address.pincode_id,
          addresstype:address.type,
          company:address.company,
        };

const schema = {
      title: "",
      type: "object",
      required: ["firstname"],
      properties: {
        firstname: {type: "string", title: "First Name"},
        lastname: {type: "string", title: "Last Name"},
        address: {type: "string", title: "Address"},
        landmark: {type: "string", title: "Land Mark"},
        direction: {type: "string", title: "Direction"},
        city: {type: "number", title: "City"},
        area: {type: "number", title: "Area"},
        pincode: {type: "number", title: "Pincode"},
        addresstype: {type: "number", title: "Address Type",
              enum: [0,1, 2],
              enumNames: ["Home", "Office", "Other"]
            },
        company: {type: "string", title: "Company/other"},
        defaultaddress: {type: "boolean", title: "Default Address"},
        }
      };

handleSubmit(data) {
    //console.log(this.props);
    console.log('Submission received!', data);
  }

<Form schema={schema}
            uiSchema={uiSchema}
            formData={formData}
            widgets={widgets}
            onChange={console.log("changed")}
            onSubmit={()=>this.handleSubmit(formData)}
            />

**Comment by n1k0** [comment]
I'm sorry, can you please write a few sentences describing what's happening precisely, what's expected, what are the steps to reproduce? Please, please, please report this issue as you'd like it being reported to you.

**Comment by nilaybrahmbhatt** [comment]
i create onSubmit event on form named  handleSubmit() and passed formdata...
at initialization of form i fetch data from state and passed to formdata schema

but form automatically called handleSubmit() with blank data on loading form...
i want that when user clicked on submit..

**Comment by nilaybrahmbhatt** [comment]
please view these image

(https://cloud.githubusercontent.com/assets/6310631/15799443/5d2c0f12-2a7a-11e6-95d4-caa0d1b7d769.JPG)

**Comment by n1k0** [comment]
I still don't get it. Feel free to reopen with a sample minimal reproducible test case.
