### ISSUE TITLE
additionalProperties support

### ISSUE THREAD

**Issue by bodnia** [mozilla-services/react-jsonschema-form#228]
Is it possible to add support of additionalProperties like it's described [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties) the spec for [swagger](https://github.com/swagger-api/swagger-ui)
I wonder if I can create a PR with implementation so that if the code is fine to merge it? Otherwise we'll need to extend the form with custom schema (which could cause difficulties with upgrading the form to major versions in future).

Please let me know if this makes sense.

**Comment by n1k0** [comment]
This is a very interesting and powerful feature indeed. We'd be thrilled to have a PR for it :)

**Comment by jManji** [comment]
@bodnia Have do you have any update on this? I would be very interested in any kind of progress! Otherwise I might need to either implement it (which will take a long time) or maybe try to create a custom solution.

**Comment by bodnia** [comment]
@jManji now I don't have the solution for this.

**Comment by epicfaace** [comment]
This was resolved by PR #1021.
