### ISSUE TITLE
File widget failure

### ISSUE THREAD

**Issue by dpwrussell** [mozilla-services/react-jsonschema-form#229]
### Prerequisites

- [ x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

File widget is not able to render.

Perhaps it is transcoding related? I am unsure.

### Steps to Reproduce

I copied and pasted the Files example JSON Schema and UI from the playground into my application.

```jsx
        <Form
          schema={ activeForm.jsonSchema }
          uiSchema={ activeForm.uiSchema }
          formData={ activeForm.formData }
          onSubmit={ this.submitForm }
        />
```
The JSON is loaded from a JSON encoded string in my server side database, but all the other playground examples are working perfectly so I don't think this is the issue. In this instance `formData` will be undefined as there is none.

#### Expected behaviour

Render the file-chooser the same as the playground.

#### Actual behaviour

When trying to render the files form I get:

```
bundle.js:2199 Warning: FilesInfo(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

bundle.js:7682 Uncaught TypeError: inst.render is not a function

bundle.js:5639 Uncaught TypeError: Cannot read property '_currentElement' of null
```

### Version

0.33.1

**Comment by n1k0** [comment]
> FilesInfo(...): No `render` method found on the returned component instance

That's a very strange warning as `FilesInfo` is a [functional stateless component](https://github.com/mozilla-services/react-jsonschema-form/blob/512704e06ec7afc32f47862ae315449f5cf5d4b7/src/components/widgets/FileWidget.js#L30-L47), so it obviously doesn't have a `render()` method.

What version of React are you using?

**Comment by dpwrussell** [comment]
I was on 0.14.8, but I have just jumped forward to 15.1.0.

Problem solved, thanks!

**Comment by n1k0** [comment]
Sure, will update requirements.
