### ISSUE TITLE
"title" is auto-added to custom components when nested but not top-level

### ISSUE THREAD

**Issue by nuclearspike** [mozilla-services/react-jsonschema-form#230]
I have a custom field editor for a multi-select dropdown (react-select) and with a somewhat recent change to react-jsonschema-form lib, the titles are no longer showing up on their own for properties at the top-most level. However, when nested fields are using the same editor, the titles *are* added. My solution originally was to add the label to the custom component, which fixes the top-most level, but then the nested ones now have double titles.

**Comment by n1k0** [comment]
Would you mind trying to provide a reproducible example, ideally a [jsfiddle](https://github.com/mozilla-services/react-jsonschema-form/issues/181)?

**Comment by nuclearspike** [comment]
Everything works great! thanks for the speedy resolution!
