### ISSUE TITLE
IE 11 "Object expected" exception on form validation error

### ISSUE THREAD

**Issue by alex-perfilov-reisys** [mozilla-services/react-jsonschema-form#236]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

In IE 11 form validation errors are triggering "Object expected" exception. IE Edge works fine.
The exception is thrown only after babel transformations of function toErrorSchema https://github.com/mozilla-services/react-jsonschema-form/blob/770e5a4c7496824bff77bac14fb5a7749ada3bdf/src/validate.js#L24

It exists both in this github playground and npm dependencies, since the code there is already transformed by babel. 
Here's [`validate.js`](https://github.com/mozilla-services/react-jsonschema-form/blob/770e5a4c7496824bff77bac14fb5a7749ada3bdf/src/validate.js) from npm (playground uses same code, but obfuscated):
https://gist.github.com/alex-perfilov-reisys/d50d53bc2f15a1195ebf9a4d416d92f0#file-validate-js-original-bad-compilation-L86
So the problematic line is 86, in the `toErrorSchema` function.

I'm not sure which plugin is spoiling it, but I was able to fix it for myself [ugly way for now]. 
I took all the [`validate.js`](https://github.com/mozilla-services/react-jsonschema-form/blob/770e5a4c7496824bff77bac14fb5a7749ada3bdf/src/validate.js) and compiled it using https://babeljs.io/repl/ website online, that's the result:
https://gist.github.com/alex-perfilov-reisys/c060b6509660fdb32f929872ee09e29e

And saved it in my node_modules. As I said, I know that's wrong. But it works. 

### Steps to Reproduce

1. Open IE 11
2. Go to playground https://mozilla-services.github.io/react-jsonschema-form/
3. Click "Errors" tab

#### Expected behavior

The form is shown with validation errors

#### Actual behavior

Form is not rendered at all, Exception thrown.
![image](https://cloud.githubusercontent.com/assets/6089683/16064218/207ca39c-326d-11e6-95b9-59426b551583.png)

![image](https://cloud.githubusercontent.com/assets/6089683/16064227/378f633a-326d-11e6-805d-a6576b16bfb9.png)

### Version

any

**Comment by n1k0** [comment]
As we don't plan to add official support for IE11 anytime soon, this is probably a fix you'll have to propose as a PR if you want to see it addressed :)

**Comment by n1k0** [comment]
I'm closing this. Feel free to reopen if you plan to work on a fix.

**Comment by oliver-bauer** [comment]
As of May 2017, the report of alex-perfilov-reisys is still vaild: RJSF seems to still have the issue reported here with IE11, even on the playground https://mozilla-services.github.io/react-jsonschema-form/ 

For all those looking for support of IE11 (and do not look for highest efficiency), use import "babel-polyfill" at the beginning of the app - and the error disappears... ;)

**Comment by n1k0** [comment]
@oliver-bauer this is probably worth adding a note about that in the README; would you be willing to take care of this work?

**Comment by cvrabie** [comment]
@oliver-bauer babel-polyfill doesn't seem to do the trick for me. I get the exact same error. Neither is including polyfills with polyfill.io. Any idea what was the specific polyfill that fixed this for you?

**Comment by glasserc** [comment]
Related also to #206.
