### ISSUE TITLE
Support with redux

### ISSUE THREAD

**Issue by theWaR13** [mozilla-services/react-jsonschema-form#238]
I am wonder if i can use this module together with redux. 
For example, when i have a simple input, i write something like this:

`<input type="password" onChange={ this.handleInput.bind(this, 'password-input' }/>
`

So i can get an information about user is filling the password field and update the certain state in redux. Is there any way to do something like this with this module? Thanks.

**Comment by n1k0** [comment]
Using this library along redux shouldn't be a problem as you have clearly defined I/O for your form data; it's mostly matter of dispatching actions notifying that you have a new form state available, and this can be achieved by subscribing to either the `onChange` or `onSubmit` events.

Though what you're asking for here is to watch for a given single field when it changes, and there's no specific event you can listen to in this lib atm. What you'd like to have is something like `onFieldChange(fieldPath, callback)` I guess, which is something we mentioned in the past [in #45](https://github.com/mozilla-services/react-jsonschema-form/issues/45#issuecomment-192196519).

I have no immediate plan to implement this atm but feel free to send a PR.

**Comment by n1k0** [comment]
I'm gonna close this. Feel free to reopen if you feel this is something you'd feel to work on.
