### ISSUE TITLE
ArrayField uiField customization 

### ISSUE THREAD

**Issue by cfitz** [mozilla-services/react-jsonschema-form#241]
Hi,

I was working on something like #235 with something here 
https://cfitz.github.io/react-jsonschema-form/
https://github.com/cfitz/react-jsonschema-form/blob/master/playground/app.js

But I don't think this the right way to do this. What I am needing to do essentially is add something to the ArrayField so that the Autocomplete field is inserted in the list but then the list items are only rendered once. 

Any suggestions on this? I've been moving stuff around a bit but can't seem to get something that I feel works. I guess I should just make my own ArrayField type module to do this? 

Thanks for the help.

**Comment by cfitz** [comment]
Hi, 

So I think I figured this out:

https://github.com/cfitz/react-jsonschema-form/blob/master/playground/app.js
https://cfitz.github.io/react-jsonschema-form/

Suggestions def. welcome! Thanks.

**Comment by n1k0** [comment]
Not closing this but I don't have the time to investigate your specific use case codebase; could you please try to bring a sample minimal reproducible test case so I can provide an answer? Thanks.

**Comment by cfitz** [comment]
hi, closing this. I was able to figure it out using a custom field. thanks.

**Comment by VanessaRLewis** [comment]
@cfitz How did you do this with custom field? Could you show an example?
