### ISSUE TITLE
Add text field from multi-select

### ISSUE THREAD

**Issue by bteepell** [mozilla-services/react-jsonschema-form#244]
### Description
Question
I would like to dynamically add a field based on select of a list.  Each time the user selects an entry from the list it will remove that entry from the list and add a text filed with the name of that entry from an add button.  

Any suggestion?

**Comment by n1k0** [comment]
I don't clearly understand the use case here, but dynamic updates of the schema can be achieved by simply passing a new `schema` prop to the Form component, which you can forge by listening to form data changes using the `onChange` event listener. This has been discussed and demonstrated in #181.

**Comment by bteepell** [comment]
Yes that is what I thinking.  Thanks for the fast reply.
