### ISSUE TITLE
Question:  Bootstrap Icons

### ISSUE THREAD

**Issue by bteepell** [mozilla-services/react-jsonschema-form#245]
Is there a way to add glyphicon glyphicon-plus to the add buttons for arrays?

**Comment by n1k0** [comment]
Nope, we'd need *templates* for that, eg. see #237. Translations could also address that in some quirky way, see #205.

You could also use CSS to override the button styles though.

**Comment by n1k0** [comment]
Side note, #247 is about to introduce the use of unicode symbols for array action buttons.

**Comment by bteepell** [comment]
Thanks.
