### ISSUE TITLE
Hidden Does Not Hide Array Field

### ISSUE THREAD

**Issue by ClockerZadq** [mozilla-services/react-jsonschema-form#248]
### Prerequisites

- [yes] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

I have seen this behavior in my application and was able to replicate in the playground

### Description

I am attempting to control the display/lack of of Array fields with no success. Adding a "ui:widget" : "hidden" to a field of type array does not hide the field. It does, however, hide the title if there is any.

### Steps to Reproduce

1. Playground -> Array
2. Add "ui:widget" : "hidden" to the UISchema directive

#### Expected behavior

I was expecting the field to disappear however it doesn't

#### Actual behavior

The title is the only thing that seems to go away

### Version

I am using 0.33.3

**Comment by n1k0** [comment]
[Docs say](https://github.com/mozilla-services/react-jsonschema-form#hidden-widgets):

> Hiding widgets is only supported for  `boolean`, `string`, `number` and `integer` schema types;

Closing. Please reopen with a PR if you plan on working with implementing this feature :)

**Comment by Matt-Hill-Harness** [comment]
Is there a work around to eliminate a string from my uischema?
I want the ui elements to not be shown.
I don't need the data either.
Thanks.

**Comment by mkkeffeler** [comment]
same use case, we just need to specify an empty list and so it makes no sense for the user to have to see it on the form

**Comment by sparmboy** [comment]
Workaround:

```
const hidden = () => <div/>

const uiSchema: UiSchema = {
    "myArrayFieldThatIWantToHide": {
        "ui:field": hidden   
    }
};
```
