### ISSUE TITLE
Confirmation on Submit

### ISSUE THREAD

**Issue by bteepell** [mozilla-services/react-jsonschema-form#249]
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description
Has anyone done a popup confirmation onSubmit?

**Comment by n1k0** [comment]
How about this? (untested)

```jsx
<Form schema={schema}>
  <input type="submit" onClick={(event) => {
    if (!confirm("u sure")) {
      event.preventDefault();
    }
  }} />
</Form>
```

**Comment by n1k0** [comment]
Tested, it works. Closing.
