### ISSUE TITLE
Support enumNames for enums

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#25]
We should probably offer support for `enumNames`, which is draft v5 atm:

```js
"obj": {
  "enum": [{a: 1}, {b: 1}, {c: 1}],
  "enumNames": ["a", "b", "c"]
}
```

**Comment by matiaslarsson** [comment]
+1 for enumNames.

**Comment by magopian** [comment]
Seems [oneOf](https://github.com/json-schema/json-schema/wiki/enumNames-%28v5-proposal%29#concerns) would also do? Not sure if we want both?

**Comment by cedricmessiant** [comment]
Great, thanks !
