### ISSUE TITLE
Turn off Error at top of form

### ISSUE THREAD

**Issue by bteepell** [mozilla-services/react-jsonschema-form#251]
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description
Is there a way to only do inline validation on submit.  For me the Error list at the top is not required and I would like to turn it off.

**Comment by rpoitras** [comment]
I'm new to this excellent little library.  Took a quick look at the code.

The error display at the top is coming from the ErrorList component. In Form.js there is a renderErrors() call that passes the errors encountered on the form to ErrorList as a prop. The ErrorList is then added to the form jsx before the first field in the schema. I don't see a way to suppress this.  Maybe by using your own custom validate(). However if you withhold the error list that will likely mess up the error statements at the field level.

May be best to fork and do some backend changes that make the top list optional or omit it altogether.

**Comment by n1k0** [comment]
We're also accepting PRs.

**Comment by garywong89** [comment]
I submitted a PR for the issue with a optional prop topBar that you can pass on to hide the display of the topbar

**Comment by n1k0** [comment]
Fixed by #269.

**Comment by n1k0** [comment]
Released in [v0.38.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.38.0).

**Comment by ioterateam** [comment]
for version _1.0.6++_ use props showErrorList inside Form, then set it _false_
