### ISSUE TITLE
Enums have to be changed to be applied

### ISSUE THREAD

**Issue by sekistner** [mozilla-services/react-jsonschema-form#27]
When I have an enum without a default value it looks like the first one is selected, but actually I have to change it to another and the first one again so it's set.

The first item in the select box should be something like "please select" then.

**Comment by n1k0** [comment]
Actually it depends if a value is required for that field; I'll be looking into that.

**Comment by magopian** [comment]
This is because the schema default value isn't used unless the user did an explicit action (as discussed in #48). This is going to change by fixing #48, so closing this one as a dupe.

Thanks for reporting the issue, it helped spot/investigate the problem!
