### ISSUE TITLE
NPM update

### ISSUE THREAD

**Issue by garywong89** [mozilla-services/react-jsonschema-form#270]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

I was wondering would it be possible to update the package on NPM to include the showErrorList prop. Thank you

**Comment by n1k0** [comment]
Released in [v0.38.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.38.0).
