### ISSUE TITLE
Default widget for each field instance

### ISSUE THREAD

**Issue by amarnus** [mozilla-services/react-jsonschema-form#272]
### Description

I thought that it will be helpful to have a root-level prop `defaultWidgets` that stores the default widget type for each field  (We should have sensible defaults, of course). This could be especially useful after #225 is merged in.

**Example**:

The key will be the field type and the value will be a component registered as a widget.

``` javascript
{
  "object": "CollapsibleFieldset",
  "array": "fieldset"
}
```

**Comment by n1k0** [comment]
To be noted, there's an ongoing effort to support this in #283.

**Comment by LucianBuzzo** [comment]
Resolved by https://github.com/mozilla-services/react-jsonschema-form/pull/371
