### ISSUE TITLE
Description is hidden when being set to empty

### ISSUE THREAD

**Issue by vinhlh** [mozilla-services/react-jsonschema-form#273]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

Description is hidden when being set to empty

### Steps to Reproduce

1. Create a SchemaField with Custom DescriptionField
2. When editing the description field, set its value to an empty string.
3. Description field is hidden

#### Expected behavior

Should show placeholder, and visible.

#### Actual behavior

Description field is hidden

I found that Kinto demo has the same problem https://kinto.github.io/formbuilder/#/builder

### Version

0.35

**Comment by vinhlh** [comment]
Found this one https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/ObjectField.js#L121-L125

**Comment by n1k0** [comment]
What is the use case of setting a description to an empty string and wanting it to be rendered withing a paragraph? Is it to add to vertical space? If so, couldn't you use CSS for that?

**Comment by vinhlh** [comment]
@n1k0 when it is in editing mode, just like Kinto formbuilder.

**Comment by n1k0** [comment]
> @n1k0 when it is in editing mode, just like Kinto formbuilder.
> We need to show input, textarea elements

I don't get the relation between the title and description texts and the inputs. Could you please provide a code sample, or a screenshot so I can see what the problem looks like? Thank you.

**Comment by vinhlh** [comment]
@n1k0 
Try to set the form's description to empty on https://kinto.github.io/formbuilder/#/builder

**Comment by n1k0** [comment]
Ok so I guess this is rather an issue to file against the formbuilder repository. Rendering empty descriptions makes no sense in this lib imho.

**Comment by vinhlh** [comment]
But this is about the APIs of SchemaField, should belong to this library. I don't use formbuilder.
@n1k0

**Comment by vinhlh** [comment]
One more thing, I think we should give the Custom Component (CustomTitleField, CustomDescriptionField) the permission to decide what will be rendered in the empty case.
Maybe we want to render something like `No available description`.

**Comment by vinhlh** [comment]
A hack for anyone has same problem
```
const DESCRIPTION_IS_EMPTY = 'DESCRIPTION_IS_EMPTY'

{
  getFormData() {
    const { description } = this.props

    if (description === DESCRIPTION_IS_EMPTY) {
      return {
        description: ''
      }
    }

    return {
      description
    }
  }

  handleChange(formData) {
    const { description } = formData.formData
    if (description) {
      return this.props.onChange(description)
    }
    this.props.onChange(DESCRIPTION_IS_EMPTY)
  }
}

```
