### ISSUE TITLE
How to set autoFocus for a property

### ISSUE THREAD

**Issue by vinhlh** [mozilla-services/react-jsonschema-form#281]
How to set autoFocus for a property of a Form. Example: focus on an input.

**Comment by pabloen** [comment]
I would love to have this feature too!

**Comment by n1k0** [comment]
How would you implement that?

**Comment by pabloen** [comment]
Wouldn't a boolean `ui:autofocus: true` in the uiSchema that set the `autoFocus` HTML attribute  be enough?

**Comment by vinhlh** [comment]
okay, let me try.

**Comment by glasserc** [comment]
I believe this can be closed now.
