### ISSUE TITLE
how to use with typescript

### ISSUE THREAD

**Issue by oreon** [mozilla-services/react-jsonschema-form#286]
I want to use this great library with typescript, where can I find the typings

**Comment by n1k0** [comment]
There is none but you can contribute (and maintain) them.

**Comment by spallister** [comment]
I was just looking for typings myself, and found some over at DefinitelyTyped.  So you can do:

`typings install dt~react-jsonschema-form --global --save`

I'm not doing anything complex at this point (just wanted to get up and running), but these ones seem to be working just fine so far.

**Comment by oreon** [comment]
Thanks worked for me too.
