### ISSUE TITLE
What is the best way to represent large number of lookup objects 

### ISSUE THREAD

**Issue by oreon** [mozilla-services/react-jsonschema-form#291]
If I have an order object , in which order item contains a lookup to a Proudct and there are thousands of products , what is the best way to represent it as per json schema and json schema form

My vision for the renderred widget is to be an autocomplete select type.

**Comment by mplis-jetsetter** [comment]
The best you can do with out-of-the-box functionality would be what you see on the Large tab on the [playground](https://mozilla-services.github.io/react-jsonschema-form/), so you'll probably need a custom widget to get the functionality you're looking for.

You can have a schema like `{"enum": [{"productId": 1, "name": Foo}, ...]}`, a uiSchema like `{"ui:widget": "autosuggest"}`, and then make a custom widget that pulls the values out of the enum, and passes them to something like [react-autocomplete](https://github.com/reactjs/react-autocomplete).

**Comment by epicfaace** [comment]
It looks like @mplis-jetsetter has answered your question, @oreon, but let us know if you have any more questions.
