### ISSUE TITLE
There is strange behaviour with field that named address

### ISSUE THREAD

**Issue by volodimirian** [mozilla-services/react-jsonschema-form#296]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

I try to make form with your plugin. And I found strange behaviour when I try to add field that called address and add bootstrap classes through uiSchema classNames.
### Steps to Reproduce

I use next objectes:

``` javascript
  schema: {
    title: "Предприятие",
    type: "object",
    required: ["title"],
    properties: {
      category: {
        type: "number",
        title: "Категория",
        enum: [1, 2, 3],
        enumNames: [222, 333, 444],
        default: 1
      },
      subcategory: {
        type: "number",
        title: "Подкатегория",
        enum: [1,2,3],
        enumNames: [222, 333, 4444],
        default: 1
      },
      name: {
        type: "string",
        title: "Название предприятия"
      },
      city: {
        type: "number",
        title: "Город",
        enum: [1,2,3],
        enumNames: [111,222,333],
        default: 1
      },
      addr: {
        type: "string",
        title: "Адрес"
      },
      description: {
        type: "string",
        title: "Описание"
      },
      done: {type: "boolean", title: "Done?", default: false}
    }
  },
```

and 

``` javascript
 uiSchema: {
    category: {
      classNames: 'col-xs-6  col-sm-6  col-md-6  col-lg-6',
      /*"ui:readonly": true,
      "ui:disabled": true*/
    },
    subcategory: {
      classNames: 'col-xs-6  col-sm-6  col-md-6  col-lg-6'
    },
    city: {
      classNames: 'col-xs-12  col-sm-12  col-md-12  col-lg-12'
    },
    addr: {
      classNames: 'col-xs-12  col-sm-12  col-md-12  col-lg-12'
    },
    name: {
      classNames: 'col-xs-12  col-sm-12  col-md-12  col-lg-12'
    },
    description: {
      "ui:widget": 'textarea',
      classNames: 'col-xs-12  col-sm-12  col-md-12  col-lg-12'
    }
  },
```
#### Expected behavior

I can enter some data in generated fields
#### Actual behavior

It seems that form is frozen. I can't select any data in select fields and can't enter any data in inputs. 
Also I can't make textarea bigger.
### Version

I use 0.38.0 version

**Comment by mplis-jetsetter** [comment]
I don't have the time right now to come up with a solution, but I think I've at least identified the problem. I believe it's related to [this](http://stackoverflow.com/questions/19192672/my-bootstrap-form-has-two-un-clickable-inputs-cant-figure-out-why) StackOverflow question.

It seems like there's a div somewhere that's covering your form inputs for some reason. You can confirm this by inspecting the page, setting the `z-index` of the `div`s with your added classes to something higher than 0, and observing that they are now selectable.

As a temporary solution, you could try adding another class to your `classNames` and setting the `z-index` on that class to something higher than 0.

**Comment by epicfaace** [comment]
@volodimirian, if you give a `col-xs-12  col-sm-12  col-md-12  col-lg-12` class to the `done` field, it should work as in the below example:

https://jsfiddle.net/epicfaace/4rjyv65t/
