### ISSUE TITLE
how to display nested elements inline ( as  a single row )

### ISSUE THREAD

**Issue by oreon** [mozilla-services/react-jsonschema-form#301]
Currently they render as one element per row while we want to display all the widgets on a single line ,how to specify bootstrap style for nested arrays.

**Comment by n1k0** [comment]
You'll either have to heavily override default bootstrap styles or wait for the templating feature (#284) I guess.

**Comment by n1k0** [comment]
Note that meanwhile you could also write your own [custom fields](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#custom-field-components).

**Comment by n1k0** [comment]
Now #304 has landed you should give it a go.
