### ISSUE TITLE
How to pre populate/'ui:placeholder' an input of format 'date-time'?

### ISSUE THREAD

**Issue by diegocasmo** [mozilla-services/react-jsonschema-form#309]
I have a form which requires an input of format 'date-time'. I would like to be able to pre populate it with the current date (whatever today is). I have tried simply passing the current date as a string to the ``uiSchema`` as such:
``` javascript
const schema = {
  title: 'Title',
  type: 'object',
  required: ['myDateField'],
  properties: {
    myDateField: {
      type: 'string',
      title: 'Date',
      format: 'date-time'
    }
  }
};

const uiSchema = {
  myDateField: {
    'ui:placeholder': (new Date()).toString() // Does not work
  }
};
```
I have searched both in the documentation, current and old issues and can't find an answer to that. I was wondering if anyone could give me hand with this.

**Comment by n1k0** [comment]
Either set formData with the current date or dynamically define it as a default value for that field in the schema.

**Comment by n1k0** [comment]
Closing, feel free to reopen if this didn't fix your issue.

**Comment by diegocasmo** [comment]
Thank you so much, I ended up setting the formData.
