### ISSUE TITLE
Calculated fields, displaying as table [Help wanted]

### ISSUE THREAD

**Issue by dulguun0225** [mozilla-services/react-jsonschema-form#316]
### Description
Hello I'm trying to accomplish something like spreadsheet application with this library. 

### Questions

1.  How to have table or spreadsheet appearance?
2.  How to have calculated fields?

Forgive me if it's a bad place to ask.

**Comment by Natim** [comment]
I never though that this library would be a candidate for a spreadsheet app, what make you think that?

**Comment by dulguun0225** [comment]
Do you know any ReactJS library that does spread sheet with formulas?

**Comment by dulguun0225** [comment]
Not exactly a spreadsheet app, but looks similar to it.

**Comment by Natim** [comment]
You might want to have a look at https://react.rocks/example/react-spreadsheet

**Comment by n1k0** [comment]
Yes. Also, we're not planning to offer such functionality on this project nor to provide guides to achieve it, sorry :) Closing.
