### ISSUE TITLE
Object.assign polyfill is not being transformed correctly

### ISSUE THREAD

**Issue by gabarmas-ibm** [mozilla-services/react-jsonschema-form#317]
### Prerequisites
- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

When loading the form in an ES5 browser, I get the standard "Undefined is not a function" due to the Object.assign in https://github.com/mozilla-services/react-jsonschema-form/blob/3f36b18cb3a5c233def17747bc4145142ec3d955/src/components/Form.js#L125

In issue #206 it sounds like there is a consensus that babel should be transforming those polyfills, but I .babelrc doesn't seem to have any plugin that tackle Object.assign. 
Prob this is the reason you had to load a polyfill specifically.

I wonder if that's intentional. I could use a polyfill library, but I'd prefer if your official npm build transforms that polyfill as well.

I'm using babel with babel transform-runtime on my side, but not recompiling any of the nodes_modules.
### Steps to Reproduce
1. Create a simple react component that uses Form
2. Run it without any polyfill libraries in an ES5 browser (I'm using an old chromium version)
#### Expected behavior

The form actually loading
#### Actual behavior

"Undefined is not a function" due to the Object.assign (and no polyfill being loaded)
### Version

0.40 (latest)

**Comment by makosblade** [comment]
Any workaround for this?

**Comment by lekansogunle** [comment]
@makosblade  Maybe you can try the babel-plugin-transform-object-assign work around here https://github.com/react-toolbox/react-toolbox/issues/45 .

**Comment by dalgard** [comment]
Considering that most users of `react-jsonschema-form` will have to support IE11 for still some time, doing a transform of `Object.assign` is simply a no-brainer. It will save everyone a good deal of frustration and unnecessary complexity with no appreciable downsides.

It seems to only be a matter of prepending this to the list of plugins in `.babelrc`:

```json
    "transform-object-assign",
```

I encourage you to just get it over with, so you can close this issue 🙏

**Comment by graingert** [comment]
We've fixed it already @dalgard

**Comment by dalgard** [comment]
That's great news 👍👍

I was just about to make the concession that IE11 appears to need several other things besides `Object.assign` to run `react-jsonschema-form`.

I'll look for the latest version, then. How did you fix it?

**Comment by dalgard** [comment]
You should probably bump the minor version number, since supporting IE11 is a new feature.

**Comment by graingert** [comment]
https://github.com/mozilla-services/react-jsonschema-form/pull/982

**Comment by glasserc** [comment]
I guess we can close this.

**Comment by AtNovember** [comment]
try to reset IE11 cache,
i got the same problem. 
Included 
"transform-object-assign" in .babelrc file

tryed npm start, and.. it didnot transpiled also, i upset, went drink coffee, 
get back and i started work! Suddenly!

> Considering that most users of `react-jsonschema-form` will have to support IE11 for still some time, doing a transform of `Object.assign` is simply a no-brainer. It will save everyone a good deal of frustration and unnecessary complexity with no appreciable downsides.
> 
> It seems to only be a matter of prepending this to the list of plugins in `.babelrc`:
> 
> ```json
>     "transform-object-assign",
> ```
> 
> I encourage you to just get it over with, so you can close this issue 🙏
