### ISSUE TITLE
Array type - Add / Reorder / Delete buttons not rendering well on mobile

### ISSUE THREAD

**Issue by mbeaudru** [mozilla-services/react-jsonschema-form#318]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

When I try to use an array type with multiple fields on mobile, it seems that the buttons are not rendering well as you can see in the picture below (mainly, the + icon is not well centered inside the button and most importantly there is a horizontal scroll appearing, which is not something very nice).

![image](https://cloud.githubusercontent.com/assets/8942633/18391628/da4e5fa6-76ae-11e6-870d-e8c1f6c5f60b.png)
### Steps to Reproduce
1. [Go in the "array" playground section](https://mozilla-services.github.io/react-jsonschema-form/)
2. Use Chrome DevTools to mimick a mobile size (for instance iPhone 6 Plus)
3. See the results
### Version

0.40.0

**Comment by n1k0** [comment]
We've updated the styling of these buttons lately, could you please test against latest v0.41.0 to see if it's better for you?

**Comment by mbeaudru** [comment]
It seems okay on my side with this new version 😄 Great job by the way 👍
