### ISSUE TITLE
New property to override default submit button text

### ISSUE THREAD

**Issue by rafmar** [mozilla-services/react-jsonschema-form#32]
In current solution you always end up with button with label "Submit". It will be nice if you provide possibility of changing this label via "schema" object.

**Comment by n1k0** [comment]
Yup, true. That could be an option supported by the uiSchema.

**Comment by cedricmessiant** [comment]
It would be great to be able to use multiple buttons in the form. Maybe we could pass them via children ?

**Comment by cedricmessiant** [comment]
You can now use your own buttons (see https://github.com/mozilla-services/react-jsonschema-form/pull/34)
So maybe we could close this issue ?

**Comment by n1k0** [comment]
Sure!
