### ISSUE TITLE
Why is hiding widgets not supported for array schema types?

### ISSUE THREAD

**Issue by tiemevanveen** [mozilla-services/react-jsonschema-form#322]
Thanks for the lib! 

I've read the doc's, they're quite clear, but I'm wondering why this is the case:

> note: 
> 
> > Hiding widgets is only supported for boolean, string, number and integer schema types;

Is it really harder to hide those arrays? I could work on a PR if you like. Let me know, I need to be able to hide some checkboxes in some cases. 
### Version

0.40.0

**Comment by n1k0** [comment]
I don't quite remember why we have a limitation here; feel free to send a PR if you think you can support more types :)

**Comment by tiemevanveen** [comment]
Figured it out. The limitation is due to the `<input type="hidden" ... />` input field that is used for hidden fields. Probably to support forms that don't submit with React? 

I've made a PR to demonstrate some things, shall we continue that discussion there? 

https://github.com/mozilla-services/react-jsonschema-form/pull/324

**Comment by n1k0** [comment]
Closing as we won't implement this feature. Feel free to reopen if you feel strongly against this decision.
