### ISSUE TITLE
Fetching foreign schemas over HTTP

### ISSUE THREAD

**Issue by jprogermphasis** [mozilla-services/react-jsonschema-form#323]
Hello,

I am a big fan of react-json-schema, and I would like to extend it by myself to support fetching foreign schemas over HTTP (you said you were not planning to do it any time soon in the doc)

I am planning to use fetch for this.

Do you have any advice for me ?

Poke @MoOx

**Comment by Natim** [comment]
You might want to have a look at how we did that in [the formbuilder](https://github.com/Kinto/formbuilder)

**Comment by jprogermphasis** [comment]
Thanks for your answer Natim, but I don't want yet to build form with drag'n drop. My first issue is to build a form with JsonSchema. Maybe later :)

**Comment by Natim** [comment]
I wasn't talking about drag'n'drop but more about how to fetch the JsonSchema with HTTP.

**Comment by jprogermphasis** [comment]
ho ok, thx,

I should dig deeper :)

**Comment by Natim** [comment]
Actually are you planning on using a specific JavaScript framework yet?

**Comment by leplatrem** [comment]
I'm not sure about the status of your conversations, but it looks out of scope to me.

**Comment by kav** [comment]
We do this. we use the [RefParser](https://github.com/BigstickCarpet/json-schema-ref-parser) library to pre-fetch and parse down the schema before we hand off to schema-form. Works like a charm.

**Comment by n1k0** [comment]
I'm gonna close this as we don't currently have any near/long-term plans to support schema fetching for this lib.
