### ISSUE TITLE
Is it necessary to call setState() in onChange handlers for custom fields?

### ISSUE THREAD

**Issue by pablen** [mozilla-services/react-jsonschema-form#328]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

I'm trying to build several custom fields to implement special features like disabling/hiding a field/fieldset and came across several issues with text fields updates and cursor position for inputs inside my custom fields. E.g. if you place the cursor in the middle of a text input value and press a key, the value is inserted in the correct position but afterwards the cursor is moved to the end of the field, which is quite annoying. I'm following the example shown here https://github.com/mozilla-services/react-jsonschema-form#custom-field-components

This behavior seems to be caused by setState() when you update the field state, but I fail to see why do you need to do that. Is it ok to just call this.props.onChange() and let the component update when it receives the new props? Should the documentation be adjusted or at least contain a comment about this issue?

Below is a sample of my code:

``` jsx
const schema = {
  type: 'object',
  properties: {
    type: {
      type: 'string',
      enum: ['basic', 'bearer']
    },
    username: { type: 'string' },
    password: { type: 'string' },
    token: { type: 'string' }
  }
};
```

``` jsx
const uiSchema = {
  'ui:field': 'ConditionalField',
  username: {
    'ui:visibleIf': fieldData => fieldData.type === 'basic'
  },
  password: {
    'ui:visibleIf': fieldData => fieldData.type === 'basic',
    'ui:widget': 'password'
  },
  token: {
    'ui:visibleIf': fieldData => fieldData.type === 'bearer'
  }
};
```

``` jsx
import SchemaField from 'react-jsonschema-form/lib/components/fields/SchemaField';
import React from 'react';

export class ConditionalField extends React.Component
{
  onChange (name) {
    const { onChange, formData } = this.props;
    return fieldData => onChange(Object.assign({}, formData, {[name]: fieldData}));
  }

  render () {
    const { errorSchema, formContext, uiSchema, idSchema, formData,
      registry, required, schema, name } = this.props;

    return (
      <fieldset>
        { Object.keys(schema.properties).map(name => {
          const isVisible = !uiSchema[name] ||
            !uiSchema[name]['ui:visibleIf'] ||
            uiSchema[name]['ui:visibleIf'](formData);

          return !isVisible ? null : (
            <SchemaField
              formContext={ formContext }
              errorSchema={ errorSchema[name] }
              onChange={ this.onChange(name) }
              uiSchema={ uiSchema[name] }
              idSchema={ idSchema[name] }
              formData={ formData[name] }
              registry={ registry }
              schema={ schema.properties[name] }
              name={ name }
              key={ name }
            />
          );
        }) }
      </fieldset>
    );
  }
}

```

**Comment by n1k0** [comment]
Could you please try something? Basically not waiting for the UI reflecting the new state before propagating the change event up the tree. Basically, with the custom field component example from the docs:

```jsx
  onChange(name) {
    return (event) => {
      this.setState({[name]: parseFloat(event.target.value)});
      setImmediate(() =>  this.props.onChange(this.state));
    };
  }
```

If that fixes the issue we should update the docs accordingly.

**Comment by pablen** [comment]
Sorry about the ultra-late response, but after trying your suggestion the initial issue is still present.

We've been using the custom field from my example with no problems until version 0.44.0 broke it. I thinks it's related to the `shouldComponentUpdate` change made [here (#490)](https://github.com/mozilla-services/react-jsonschema-form/pull/490). Now when you edit a field, the changes made to the other fields are lost (except for the very first change), I think it's because `formData` doesn't update in subsequent changes.

**Comment by epicfaace** [comment]
This seems really inactive, so I'm closing. @pablen feel free to reopen if you still see this issue in 1.3.0 though.
