### ISSUE TITLE
Select box should allow option to have nothing selected by default rather than the first enum in the list

### ISSUE THREAD

**Issue by ifitzpatrick** [mozilla-services/react-jsonschema-form#333]
When user has not chosen an item in a select box, the select box starts off with the first item selected.
If we want the form to send updates on "change" instead of "submit", and a user wishes to select the first item, the user has to change the selection twice to get a change event to fire with the choice they actually want. 

The solution we propose is to have the first item in the select box be blank instead of selecting an item to start with. Once a user has made a choice the blank item could be removed from the list.

version: 0.38.0

**Comment by leplatrem** [comment]
> The solution we propose is to have the first item in the select box be blank instead of selecting an item to start with.

You could indeed prepend an empty choice to the enum.

> Once a user has made a choice the blank item could be removed from the list.

Not sure about that. Let's leave it among the choices so that the submitted value can be *emtpy* if necessary.

**Comment by chadrik** [comment]
>> Once a user has made a choice the blank item could be removed from the list.

> Not sure about that. Let's leave it among the choices so that the submitted value can be emtpy if necessary.

I can't see why would we want to give the user the ability to *revert* their choice back to an invalid option.  The value, once chosen, must be one of the enumerated choices.  To put it another way, the input begins in an unchosen state (always invalid), and then progresses to a chosen state (always valid), but never back.

**Comment by leplatrem** [comment]
> The value, once chosen, must be one of the enumerated choices.

I see, this applies to field were the value is mandatory. I was thinking of optional fields sorry.

The feature makes sense, don't hesitate to draft a PR!

**Comment by epicfaace** [comment]
It looks like this feature has already been implemented. Closing
