### ISSUE TITLE
React 15 warning: 'value' prop on 'input' should not be null

### ISSUE THREAD

**Issue by mbeaudru** [mozilla-services/react-jsonschema-form#336]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

Since React 15 there is a warning using react-jsonschema-form poping:

![image](https://cloud.githubusercontent.com/assets/8942633/19189686/a1437e84-8c99-11e6-916d-c39a1e9ad861.png)

#### Expected behavior

The default props 'value' of an input should be an empty string in order to run nicely with react 15

```javascript
const value = undefined;
return <input type="text" value={value || ''}/>; // <-------- good (controlled)
```
#### Actual behavior

The input receives "null" as a default "value" props which raises an error with React 15.

```javascript
const value = undefined;
return <input type="text" value={value}/>; // <-------- bad (uncontrolled)
```

### Warnings
Be aware that passing a default string could be an issue if the propType wanted by the component is not a string.
See [this discussion](https://github.com/erikras/redux-form/issues/703) for more informations

### Version

react-jsonschema-form: 0.40.0
react: 15.0.2

**Comment by mbeaudru** [comment]
Ok, I'm sorry this is on me, when defining the schema there was a default props setted to null passed to the fields.

**Comment by n1k0** [comment]
Wait, we may want to convert passed null to undefined, at least at the
react input level.

I'll think about it.

Le 7 oct. 2016 2:40 PM, "BEAUDRU Manuel" <notifications@github.com> a
écrit :

**Comment by adamroldfield** [comment]
@n1k0  I think that would be best, since JSON doesn't support undefined, it always passes null instead.

**Comment by agnihotriketan** [comment]
Using **defaultValue** attribute worked for me in case of onblur.

**Comment by NikulGoyani369** [comment]
yes, I   also solved with your solution. 

` value={this.state.door.inet || ' ' }`
