### ISSUE TITLE
Ugly ➕ icon for array-item-add

### ISSUE THREAD

**Issue by mbeaudru** [mozilla-services/react-jsonschema-form#337]
### Prerequisites
- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

Can someone explain why the normal + has been ditched for this one ? It doesn't look good to me but I might be wrong or missing something.

[Commit that changes the symbol](https://github.com/mozilla-services/react-jsonschema-form/commit/d83a1b1c2744c6febf68afab817a5b262d8edb51)
### Steps to Reproduce

[See how it renders](https://mozilla-services.github.io/react-jsonschema-form/)
#### Expected behavior

![image](https://cloud.githubusercontent.com/assets/8942633/19213418/748f4318-8d6c-11e6-9aaa-a8b8561e91db.png)
#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/8942633/19213412/50eec0aa-8d6c-11e6-8c51-e65c98d363f0.png)
### Version

0.40.0

**Comment by n1k0** [comment]
The thing is, the updated icon looks slightly better on my Linux laptop, but not at all like on your screenshot. And I don't know with other OSes.

I'll take some time to investigate this, thanks for the report :)

**Comment by mbeaudru** [comment]
Oh I see ! Didn't expected that 😄 

For the record, I've checked on my Android phone and it looks different, but not good:

![image](https://cloud.githubusercontent.com/assets/8942633/19245788/4d6dd6ce-8f23-11e6-84ba-55ad4c95cd36.png)

> Friendly parenthesis: I did let the entire screenshot in order to stress out that there is an issue with the centering of the icon on the button too. It was already there before, and I [opened up a ticket about that](https://github.com/mozilla-services/react-jsonschema-form/issues/318) 👍

**Comment by maartenth** [comment]
There are two problems with using emoji as icons: they look different on every system and they don't respond to text color, which is a problem with restyling. (Currently, the styling is `color: #fff` but the plus is black on my macOS system.)

Since the library uses bootstrap anyway, is it an idea to simply use glyphicons?

```<span class="glyphicon glyphicon-plus"></span>```

Also, the padding left and right should be removed to keep the icon centered on narrow screens.

**Comment by n1k0** [comment]
> Since the library uses bootstrap anyway, is it an idea to simply use glyphicons?

This would heavily couple this library to bootstrap, as the glyphicon font and related styles would be required to render icons. We'd like to keep the lib as agnostic as we can wrt css styling, hence why we went with emojis. Maybe we should switch back to texts?

**Comment by maartenth** [comment]
Yes, I think the 'text plus' would look better on many systems, and would integrate better with custom styling.

> This would heavily couple this library to bootstrap

I understand your point. In the long term it may be an option to split out all widgets and fields into components and containers, where containers only contain the business logic and components only dom nodes. Then components can be made for different css frameworks in different libraries, e.g. called
- `react-jsonschema-bootstrap-components` for Bootstrap,
- `react-jsonschema-react-bootstrap-components` for react-bootstrap,
- and even `react-native-jsonschema-components` for react-native.

In angular-schema-form for example, the bootstrap templates were recently split out to a different library to decouple it completely from Bootstrap.

**Comment by maartenth** [comment]
I updated the icon on my fork and improved the normal '+' with a css transform to make it bigger and more in line with the other buttons. If you are OK with a css transform in the library, I will submit this as a pull request.

**Comment by n1k0** [comment]
The lib doesn't ship with any css file at all, and I'd like to keep it that way.

I'm stunned we can't find a plus icon/char compatible across platforms. There must be a way :)

**Comment by maartenth** [comment]
Yes I updated the existing inline style, I did not add a css file. :)

**Comment by n1k0** [comment]
That's interesting. Could you submit a PR so I see how that looks?

**Comment by n1k0** [comment]
After giving all this some thinking, I think we could go with just using glyphicons and document a way to override the way they look; if we use something like

```js
<button type="button" class="btn btn-info btn-plus col-xs-12" tabindex="-1">
  <i class="glyphicon glyphicon-plus"/>
</button>
```

Then it's easy to do something in CSS like

```css
.btn-plus > i {
  display: none;
}
.btn-plus:after {
  content: "Add";
}
```

**Comment by mbeaudru** [comment]
I thought you didn't wanted to use glyphicons ? :confused: 

I'm not really sure I understand the benefits of a "plus" glyphicon against a "+" character eventually customized with css to look good.

**Comment by n1k0** [comment]
> I'm not really sure I understand the benefits of a "plus" glyphicon against a "+" character

Consistency across rendering platforms, easy to override, and I'm not super fond of inline styling as they've always been tricky to deal with from outside components in my experience.

But I'm still open to other suggestions!

**Comment by mbeaudru** [comment]
As long as you are good with using glyphicons I think your proposal is just fine :+1:

**Comment by n1k0** [comment]
@mbeaudru @maartenth I've created #375 so we can challenge this approach.
