### ISSUE TITLE
Boolean checkbox can't send false

### ISSUE THREAD

**Issue by stubar** [mozilla-services/react-jsonschema-form#338]
### Prerequisites
- [ x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

Boolean checkbox's require you to tick the box, you cannot send a false.  
### Steps to Reproduce

Create a  form where a boolean field is required
#### Expected behavior

Either a unticked / ticked state will be accepted
#### Actual behavior

Only a ticked box is accepted.  

I'm using a jsonschema-form to send a  json to an api that uses https://github.com/geraintluff/tv4 as a validator using the same schema.  tv4's interpretation of a required boolean is it can be true or false as long as it is present.  Which implementation is right?
### Version

^0.38.0

**Comment by n1k0** [comment]
From what I can test in the playground with the following schema, it works exactly as you expect:

```json
{
  "title": "Widgets",
  "type": "object",
  "required": [
    "test"
  ],
  "properties": {
    "test": {
      "type": "boolean",
      "title": "required chedkbox"
    }
  }
}
```

http://i.imgur.com/5sEBdqm.png

http://i.imgur.com/ebEV9JI.png

http://i.imgur.com/NHooyc8.png

**Comment by stubar** [comment]
If I tick and untick the checkbox I still can't submit my form because the checkbox has a required attribute and html5 validation is kicking in.  I have managed to work around this by using a radio widget in the uiSchema.

**Comment by n1k0** [comment]
> I still can't submit my form because the checkbox has a required attribute and html5 validation is kicking in

You mean you have an HTML5 triggered event preventing to submit the form? Which browser (+version) are you using?

**Comment by stubar** [comment]
I am in Chrome Version 51.0.2704.106 (64-bit)

https://jsfiddle.net/nvx0rjd5/ What I mean is HTML5 validation prevents an unchecked checkbox being submitted.

**Comment by leplatrem** [comment]
Related #350

**Comment by WM-Almadfaa** [comment]
checkbox{
type: ‘boolean’,
default: null,
enum: [null, true],
}
