### ISSUE TITLE
Inline checkboxes and radios

### ISSUE THREAD

**Issue by frassinier** [mozilla-services/react-jsonschema-form#346]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

I would like to display inputs with `type="radio"` or `type="checkbox"` with [inline markup from Bootstrap](http://getbootstrap.com/css/#inline-checkboxes-and-radios). 

Is there a way to add option like `{ "ui:inline": true }` to enable this flag or I have to override the whole widget?    

### Version

0.40.0

**Comment by n1k0** [comment]
There's no way currently, you indeed either have to override some CSS styles or to write your own custom widget. I may work add an option though.

**Comment by frassinier** [comment]
I can propose something ASAP if this kind of option is acceptable?

**Comment by n1k0** [comment]
No need to, I have a patch at hand:

![demo](https://cloud.githubusercontent.com/assets/41547/19487448/251a8b7c-9563-11e6-94e7-105d8b5d19d1.gif)

**Comment by n1k0** [comment]
Released in [v0.41.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.41.0).
