### ISSUE TITLE
What range DatePicker can be used with the plugin?

### ISSUE THREAD

**Issue by wzup** [mozilla-services/react-jsonschema-form#35]
Can you provide a suggestion on what DatePicker that supports range select can be used with the plugin?

**Comment by n1k0** [comment]
We didn't meet that use case just yet, though keep us informed if you find something useful.

**Comment by Natim** [comment]
@wzup did you had a look at http://onefinestay.github.io/react-daterange-picker/ yet?

**Comment by n1k0** [comment]
We're not planning on providing such high level widgets to this lib. You may want to create a custom SchemaField, maybe simply a custom widget, for handling these.
