### ISSUE TITLE
Showing inline validation errors within Custom Field Components

### ISSUE THREAD

**Issue by ericj17** [mozilla-services/react-jsonschema-form#351]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

Is it possible to show validation errors under each individual input 'widget' within a Custom Field Component?

In my sample code, I have a Custom Field Component, 'MailingAddressField', that has several text inputs.

P.s. I also have some nested 'form-group field field-object' div classes generated which doesn't seem quite right to me. Do you see any issues with the way I've implemented the Custom Field Component?

Welcome any advice and Thank you for your support!
Eric
### Steps to Reproduce

``` jsx
import * as React from "react";

export class MailingAddressField extends React.Component<any, any> {
  constructor(props) {
    super(props);
    this.state = props.formData;
  }

  onChange(name) {
    return (event) => {
      this.setState({
        [name]: event.target.value
      }, () => this.props.onChange(this.state));
    };
  }

  render() {
    const { country, address1, address2, city, province, postalCode } = this.state;

    return (
      <div>
        <div className="form-group">
          <label>Country</label>
          <input className="form-control" type="string" value={country} onChange={this.onChange("country")} />
        </div>
        <div className="form-group">
          <label>Address 1</label>
          <input className="form-control" type="string" value={address1} onChange={this.onChange("address1")} />
        </div>
        <div className="form-group">
          <label>Address 2 (Optional)</label>
          <input className="form-control" type="string" value={address2} onChange={this.onChange("address2")} />
        </div>
        <div className="form-group">
          <label>City</label>
          <input className="form-control" type="string" value={city} onChange={this.onChange("city")} />
        </div>
        <div className="form-group">
          <label>Province</label>
          <input className="form-control" type="string" value={province} onChange={this.onChange("province")} />
        </div>
        <div className="form-group">
          <label>Postal Code</label>
          <input className="form-control" type="string" value={postalCode} onChange={this.onChange("postalCode")} />
        </div>
      </div>
    );
  }
}
```

``` jsx
import { MailingAddressField } from "./MailingAddressField";
import * as React from "react";
import Form from "react-jsonschema-form";

const customSchema = {
  type: "object",
  required: ["mailingAddress"],
  properties: {
    "mailingAddress": {
      type: "object",
      properties: {
        country: { type: "string" },
        address1: { type: "string" },
        address2: { type: "string" },
        city: { type: "string", maxLength: 26 },
        province: { type: "string" },
        postalCode: { type: "number", maxLength: 11 },
      }
    }
  }
};

// Define the custom field components to register; here our "MailingAddressField"
// custom field component
const customFields = { mailingAddress: MailingAddressField };

// Define the custom field component to use for the root object
const customUISchema = {
  "mailingAddress": {
    "ui:field": "mailingAddress",
  },
};

const customFormData = {
  "mailingAddress": {
    "country": "Canada",
    "address1": "",
    "address2": "",
    "city": "",
    "province": "",
    "postalCode": "Not a number",
  }
}

// Render the form with all the properties we just defined passed
// as props
export default class TestForm extends React.Component<any, void> {
    public render() {
        return <div> 
          <Form
            schema={customSchema}
            uiSchema={customUISchema}
            fields={customFields}
            formData={customFormData}
            liveValidate={true}
          />
        </div>
    }
}
```
#### Expected behavior

I was expecting the validation error message to show under each individual widget (input field) within a Custom Field Component. E.g. if I enter letters within the Postal Code input field I should see 'is not of a type(s) number' under the Postal Code input field.
#### Actual behavior

However, I only see the validation error message in my Errors list at the top of my Custom Field Component after I hit the enter key.

![custom-field-component-validation](https://cloud.githubusercontent.com/assets/4195650/19542717/73ffbe7a-9625-11e6-9b26-43085aaa61bd.png)
### Version

"react-jsonschema-form": "^0.40.0",

**Comment by n1k0** [comment]
Two things:

1. You may be interested in [field templates]()
2. If you go with a custom field component, you're being passed an `errorSchema` prop which contains the current validation errors for the current field data.

Does that help?

**Comment by ericj17** [comment]
Hi n1k0,

Thanks for your suggestions. They helped :) I parsed the errorSchema and outputted the error per the nested properties within the "mailingAddress" custom field component (the Left red box in the attached screenshot is my "MailingAddressField" custom field component). I did come across 2 other issues while building the custom field component.

1) I noticed that for "requires property ..." errors, they are not associated with a particular property within the errorSchema object. Would it make sense to move the "requires ..." error message to be nested within each property in the errorSchema? This would be helpful when looping through each property's errors in the errorSchema to pick up the "requires..." error. (The right red box in the attached screenshot). I suppose I could parse the requires error message string for the property name separately though.

2) If one of the required fields nested within "mailingAddress" is not populated, the entire MailingAddressField component is red. However, I have fields that are optional, but they are also being highlighted red. Is there a way to change this behaviour to not highlight the optional fields red?

Thank you very much. I appreciate your support and building/maintaing this useful library :)
Eric

![custom-field-component-error-messages-marked](https://cloud.githubusercontent.com/assets/4195650/19714899/8ba2429c-9b06-11e6-862e-8966daaa9c90.png)

**Comment by ericj17** [comment]
Hi Just an update on point 2 above. I realized all fields of an "object" type field will be highlighted red if one of its nested properties fails the requires validation. I suppose this was a design decision?

I made a quick edit to 'SchemaField.js' below to have a separate list of classNames applied to fields of type "object" to not apply "has-error" and "field-error" class names, but only have the error classes applied on the individual children properties of an object field. 

```
  var classNamesForObjects = ["form-group", "field", "field-" + type, uiSchema.classNames].join(" ").trim();
  var classNames = ["form-group", "field", "field-" + type, errors && errors.length > 0 ? "field-error has-error" : "", uiSchema.classNames].join(" ").trim();

  var fieldProps = {
    description: _react2.default.createElement(DescriptionField, { id: id + "__description",
      description: description,
      formContext: formContext }),
    help: _react2.default.createElement(Help, { help: help }),
    errors: _react2.default.createElement(ErrorList, { errors: errors }),
    id: id,
    label: label,
    hidden: hidden,
    required: required,
    readonly: readonly,
    displayLabel: displayLabel,
    classNames: type === "object" ? classNamesForObjects : classNames,
    formContext: formContext
```

However, the child fields that do not pass the "required" validation no longer gets highlighted as an error. I think this goes back to my point 1 above where the "requires" error is not nested under the offending property itself in the errorSchema (highlighted in the screenshot above, the right red square). Do you have any suggestions on how we could make modifications to nest the "requires" error under the property itself?

Thanks and Best Regards

**Comment by n1k0** [comment]
> I realized all fields of an "object" type field will be highlighted red if one of its nested properties fails the requires validation. I suppose this was a design decision?

Most likely an unexpected, surpising side effect to be honest; so we need to fix this situation, but that requires finding a good working UX. I think you're on the right track with your approach.

> Do you have any suggestions on how we could make modifications to nest the "requires" error under the property itself?

That probably means hooking on the validation results jsonschema sends back to us and altering the errorSchema accordingly; would you want to work on that?

**Comment by n1k0** [comment]
I'm gonna close this issue so we can focus on #384, which is covering the same use case.
