### ISSUE TITLE
jsonValidate can't handle 'undefined' value properly

### ISSUE THREAD

**Issue by hengchenvoon** [mozilla-services/react-jsonschema-form#352]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

In `utils.js`, function `computeDefaults(schema, parentDefaults, definitions={})`, you are defaulting the fields that have no explicitly default value to be `undefined`. However, the `jsonValidate` function used in `validate.js` can't handle the fields with value as `undefined` properly. If it tried to validate field which give `undefined` as current value, the `"instance"` property that it returns will not map to any fields. i.e. Instead of `"instance.photos"`, it will return it as `"instance"`.
### Steps to Reproduce
1. Go to https://mozilla-services.github.io/react-jsonschema-form/, in the Files tab.
2. Set 'files' as 'required' in formSchema.
3. Click submit button.
#### Expected behavior

Highlight only the file widgets and error `<ul>` list display at the bottom of the widget.
#### Actual behavior

Highlight the whole form and error `<ul>` list display at the bottom of the form.

**Comment by n1k0** [comment]
Could you please post sample validation code and the schema you used? Ideall, a jsfiddle would greatly help ([template](https://jsfiddle.net/n1k0/f2y3fq7L/6/)).

Thanks!

**Comment by hengchenvoon** [comment]
> Could you please post sample validation code and the schema you used? Ideally, a jsfiddle would greatly help (template).
>
>Thanks!

Is this sufficient for you? https://jsfiddle.net/f2y3fq7L/7/
Currently, I can only reproduce it on file widget, since any other empty input with `required` property will be intercepted by form's own validation, thus any incorrect error will not be shown.

**Comment by n1k0** [comment]
I'm sorry, I still don't understand; in the capture below, could you please point me at what's wrong and what should be changed in the UI to properly reflect what you expect? Thanks!

![](http://i.imgur.com/VbFnmQy.png)

**Comment by hengchenvoon** [comment]
I readjusted the position of the widgets so that it might look clearer.
![screen shot 2016-10-20 at 4 06 27 pm](https://cloud.githubusercontent.com/assets/22535321/19551711/37b21c78-96df-11e6-8964-a58f9e5d677e.png)

In this screenshot, I had 2 required field, the text field and the file input, and both of them does not satisfy the schema's requirement.

First of, you can see that while error info of the text field is displayed directly below the text field, while the file input's error info is at the bottom of the form, this is because the form interpret the error meant for file input as the error for the whole form itself.

Also, in the error panel, the error displayed for the text input is "instance.name", but not the one for file input, which displayed only as "instance". This will cause the form to think that the error from file input is form-level error, and thus highlighting the whole form in red.

So, to answer your question, I expected the error to highlight only the fields that are not satisfying the validation, without highlighting the whole form, in the behavior such as below:
![screen shot 2016-10-20 at 4 13 07 pm](https://cloud.githubusercontent.com/assets/22535321/19551961/63087970-96e0-11e6-9dfc-1044e347194b.png)

**Comment by n1k0** [comment]
> In this screenshot, I had 2 required field, the text field and the file input, and both of them does not satisfy the schema's requirement. There's also an empty description field, which is optional. But it still got highlighted as error.

Oh, I see, that's a known issue (see #196). Basically, the whole root jsonschema `object` definition is failing here, as the `required` property is scoped at this root object level; hece why we're displaying the object validation error at the same place as any other field, below it. 

> Also, in the error panel, the error displayed for the text input is "instance.name"

Same, that's because the actual field in error is the root object one, not the field itself; that's how the jsonschema spec works, the lib isn't overriding this behavior which should stay standard I think. Though I agree this is highly confusing UX, so I'm all ears to any suggestion about how to improve the UX situation here.

**Comment by hengchenvoon** [comment]
Is it possible to not use `undefined` as default empty value for fields? I was planning to work around it in my last [pull request](https://github.com/mozilla-services/react-jsonschema-form/pull/343) by having converting all `undefined` to `null`. It might allow `jsonValidate`to work as expected.

**Comment by n1k0** [comment]
> Is it possible to not use undefined as default empty value for fields?

`undefined` is the only value type we can use to detect if a value has been entered for a field or not (`null` is not an option as it's also a valid jsonschema type).
