### ISSUE TITLE
Render react-bootstrap instead of Bootstrap markup

### ISSUE THREAD

**Issue by frassinier** [mozilla-services/react-jsonschema-form#356]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme)
### Description

I would like to render all fields with [react-bootstrap](http://react-bootstrap.github.io/) instead of Bootstrap markup since I don't want to let jQuery and Bootstrap.js deal with DOM changes next to React. So, I plan to rework all pure components in order to support react-bootstrap.
I'm aksing myself if you would like this kind of changes too or if I fork this project? 
### Version

0.40.0

**Comment by n1k0** [comment]
This library doesn't load bootstrap's javascript code at all. Also, we think react-bootstrap would introduce a lot of overhead and wouldn't bring enough benefit to the project. I'm closing this.
