### ISSUE TITLE
checkboxes list

### ISSUE THREAD

**Issue by sunnyzhang66** [mozilla-services/react-jsonschema-form#357]
Hi 
I try to add a checkboxes list to jsonSchema
sample:
  items: {
          "type": "string",
          "enum": ["foo",
          "bar",
          "fuzz"]
        }

UISchema:"
multipleChoicesList": {
    "ui:widget": "checkboxes"
  },

but I also need value and name together , NOT just name show up to list of checkboxes.
do you know how do I need value to schema?

Thank you so much for help!

**Comment by glasserc** [comment]
Maybe `enumNames` is what you are looking for? https://github.com/mozilla-services/react-jsonschema-form#custom-labels-for-enum-fields

**Comment by n1k0** [comment]
yes.
