### ISSUE TITLE
Handle reset button type

### ISSUE THREAD

**Issue by talend-glorieux** [mozilla-services/react-jsonschema-form#360]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
### Description

The [reset button type](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type) doesn't seem to be handled at all by the component. Is there any plan to make it so?
### Version

v0.40.0

**Comment by n1k0** [comment]
Not at this moment, and I'm not a firm believer in the related UX pattern. You can provide this feature by adding custom buttons and methods to your form wrapper component, which would reset the formData state when clicked.

Though if the patch is small and obvious enough, we may want to have this as a core feature, so feel free to send a PR if you come with something :)

**Comment by n1k0** [comment]
This could be addressed by reloading a form with default formData when a custom reset button is pressed by the user. I'm closing this.
