### ISSUE TITLE
UI orderable option is broken

### ISSUE THREAD

**Issue by pfrohner** [mozilla-services/react-jsonschema-form#362]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
### Description

"orderable" doesn't work as expected.
### Steps to Reproduce
1. Open playground, select "Arrays" example
2. Modify UISchema, add following code:

```
"listOfStrings": {
    "ui:options": {
      "orderable": false
    }
 },
```
#### Expected behavior

Up/down arrows shouldn't be there anymore.
#### Actual behavior

Up/down arrows are still there.
### Version

0.40.0

**Comment by leplatrem** [comment]
ping @olzraiti ;)

**Comment by olzraiti** [comment]
pong!

It's working for me locally on the `master` branch, but not on the live playground. Is the live playground using the version defined by the version number, or the latest commit? I'm guessing it's using the latest version number. The version number hasn't been updated since merging the orderable option.

**Comment by pfrohner** [comment]
after further investigation, we think this probably happens because the npm package hasn't been updated with this feature yet

version 0.40 was released 30th of august, but the orderable change was added only 6 days ago, so a new release would be greatly appreciated!

**Comment by wintercounter** [comment]
Any news when new version is going to be released on npm? I cannot even use GitHub url in my package.json because master lacks of dist.

**Comment by n1k0** [comment]
> Any news when new version is going to be released on npm?

We hjave a bunch of things ongoing, especially I'd like to iron out a few inconsistencies with the API, notably the custom widget options as we currently have two distinct ways to provide them in master atm (one will have to go).

**Comment by n1k0** [comment]
I'd expect this to be obvious, but any help would be highly appreciated if you'd like to help!

**Comment by nuclearspike** [comment]
+1 for looking forward to an NPM release with the addable/removable ui options.

**Comment by n1k0** [comment]
v0.41.0 has been released to npm.
