### ISSUE TITLE
Tab stop for Add button +

### ISSUE THREAD

**Issue by kav** [mozilla-services/react-jsonschema-form#365]
### Prerequisites
- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
### Description

When tabbing through a form that contains array schema the cursor does not stop on the plus button.

Also happy to PR this on a thumbs up
#### Expected behavior

I'd expect the + button to take focus and probably click on spacebar
#### Actual behavior

It doesn't
### Version

0.40.0

**Comment by kav** [comment]
It makes sense not to tab reorder and remove but add is a very common when filling out a form

**Comment by glasserc** [comment]
This sounds good to me, although @n1k0 is the final judge!

**Comment by n1k0** [comment]
Sounds good to me too. Would you want to work on a patch?

**Comment by kav** [comment]
Sure thing. The trivial fix of removing the tabstop leaves our tab ever so slightly poorly placed on the + button after adding an item. I'll look into a _sane_ solution to that. The ref chasing solution that seems to be common in react land feels terrible but a bit of tabstop number tracking and setting it correctly for the plus after add might do the trick.

**Comment by n1k0** [comment]
Released along [v0.41.2](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.41.2).
