### ISSUE TITLE
Enum options loading logic

### ISSUE THREAD

**Issue by ekeuus** [mozilla-services/react-jsonschema-form#377]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

I am trying to come up with the logic to give the user some many-to-many relation choices, but I am having a hard time with thinking of the logic to get the options to the schema. 

Should I be creating a new react component and have the options updated via state when the become available?

I am currently just using a const schema structure into which I tried to synchronously(dont judge, I know) requested data from the REST API. 

I've been trying to think of a neat way for a while now and can't come up with it. I did not find anything related in the documentation either.

```jsx
const schema = {
  title: "Add article",
  type: "object",
  required: ["fk_measurement_unit"],
  properties: {
    fk_measurement_unit: {
      type: "string",
      title: "Measurement unit",
      enum: [],//SelectOptionLoader.getEnums("articles/"),
      enumNames: []//SelectOptionLoader.getEnumNames("articles/")
    },
  }
};
```

**Comment by n1k0** [comment]
I'd probably store the schema in some component state and update it with the retrieved information:

```jsx
const schema = {
  type: "string",
  enum: [],
  enumNames: [],
};

function fetchResult() {
  return Promise.resolve({enum: [1, 2], enumNames: ["A", "B"]});
}

class MyForm extends Component {
  constructor(props) {
    super(props);
    this.state = {schema};
    this.fetchResult().then(this.onResultReceived);
  }

  onResultReceived = (result) => {
    const {enum, enumNames} = result;
    this.setState({
      schema: {...this.state.schema, enum, enumNames};
    });
  }

  render() {
    return <Form schema={this.state.schema} />
  }
}
```

Please Hope this helps.
