### ISSUE TITLE
Autocomplete for select

### ISSUE THREAD

**Issue by lutzhorn** [mozilla-services/react-jsonschema-form#380]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Is there a recommended way to use make a `select` (a `type: "string"` property with `enum`) provide autocomplete? The project [react-input-enhancements](https://github.com/alexkuz/react-input-enhancements#autocomplete) has components that look nice. Are there any plans to add such enhancements to reac-jsonschema-form?

**Comment by n1k0** [comment]
> Is there a recommended way to use make a select (a type: "string" property with enum) provide autocomplete?

Yes, writing a [custom widget](https://github.com/mozilla-services/react-jsonschema-form/#custom-widget-components).

> The project react-input-enhancements has components that look nice. Are there any plans to add such enhancements to reac-jsonschema-form?

No, you should do it in a custom widget.
