### ISSUE TITLE
Customize Orderable UI

### ISSUE THREAD

**Issue by dehli** [mozilla-services/react-jsonschema-form#382]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

I'd like to customize how adding new items (in an array) and reordering items is done. Currently it seems like you're locked into the arrows/plus button. Is this feature currently supported with custom field template (I don't think it is)? If not, I'll be trying to implement this and will use this issue to document the progress. 

Thanks, and let me know if you have any feedback/ideas!

**Comment by n1k0** [comment]
> - [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

Are you sure?

**Comment by n1k0** [comment]
Well, okay, this is admittedly tricky. Basically atm you'll indeed have to come with a custom `ArrayField` component.

**Comment by dehli** [comment]
Thanks! It makes sense to just use a custom `ArrayField` component, I didn't realize you could customize it (I'm not sure why, but I was just thinking about customizing the endpoints). 

And sorry! I did read through the documentation but I guess not close enough.

**Comment by dehli** [comment]
So the problem with implementing a custom `ArrayField` component is that lots of functionality is going to need to be rewritten that the default `ArrayField` takes care of. I'll try to come up with a solution that allows you easily customize the `ArrayField` and submit a PR.

**Comment by maartenth** [comment]
I think you need the functionality described in #354 :)

**Comment by dehli** [comment]
Thanks @maartenth!
