### ISSUE TITLE
Not able to install latest version on git hub using npm

### ISSUE THREAD

**Issue by himanshu0511** [mozilla-services/react-jsonschema-form#383]
### Prerequisites

- I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I am trying to use latest code in my project. But currently version 0.40 is being installed which is not pointing to latest code in master branch. I have also directly tried to install this plugin using git url as dependency. But that is only downloading pacakge.json and README.md. I can manually install it and use it but that would defeat the purpose of using package manager to set dependency and install everywhere.

### Steps to Reproduce
a) Case where package is being installed directly using npm
1. npm install react-jsonschema-form@latest --save
2. check the version of package in package.json and check the code inside that package, it will be what is in 0.40.0 tagged version not the latest master.

b) Case where directly using github url is only installing package.json and README.md not any other file
1. npm install --save https://github.com/mozilla-services/react-jsonschema-form#6551d5ec8ca2857135060bef9c572988fe60d6ed
2. check react-jsonschema-form folder in node_modules, you will find that it only has package.json, ReadMe.md and local node_modules.

#### Expected behaviour

Latest code should be updated on npm and whenever there is major change or minor change. version should be updated.

#### Actual behaviour

No new version is set and npm repo is not in sync with what is on github master.

### Version

0.40.0

Actual way it is written in package.json
dependency: {
"react-jsonschema-form": "^0.40.0"
}

**Comment by n1k0** [comment]
Please wait for the next release. Thanks for your understanding.

**Comment by himanshu0511** [comment]
But what about the other issue where I am using git url instead. After install it is showing package.json and README.md. And when next release is going to be take place.

**Comment by maartenth** [comment]
> After install it is showing package.json and README.md.

I had this problem too, and I couldn't find out why. When `npm install`ing the latest master branch from Github, it only installs those 2 files instead of the entire repo. I think it should be possible to install the latest development branch in a project instead of the latest release version, so it would be nice if someone with a better understanding of npm could fix that.

**Comment by himanshu0511** [comment]
I investigated this problem, found that this repo on github is that it just has source. If you build the project using command "npm run dist" you would be able to generate dist and lib folder. As they are missing in this git repo they are not getting downloaded when installed using git url.
To solve this maintainer of this repo, can add generated files as well to repo rather than ignoring it, then while installing it with git url we will get dist and lib folder as well.

**Comment by maartenth** [comment]
Ah I see, the problem is the `"files": ["dist", "lib"]` mention in `package.json`. A solution would be to fork this repo and remove the `"files"` rule from `package.json` for your own usage. (Then, of course, you are responsible for keeping up to date by merging new versions of this package to your fork.)
