### ISSUE TITLE
0.41.0 introduced some issues in Meteor

### ISSUE THREAD

**Issue by dulguun0225** [mozilla-services/react-jsonschema-form#385]
https://github.com/meteor/meteor/issues/8035

Dynamic require calls like this one (where the module identifier string is not a string literal) are not supported in client-bundled code, because it's hard/impossible to know at bundling time exactly what module is being imported.

Webpack works around this by including all modules matching a certain configuration option, but then you're potentially shipping unused modules to the client.

You can force certain specific modules to be included in the bundle by putting

require("react-jsonschema-form/lib/components/fields/SchemaField.js")
explicitly in your own code. Repeat for any other modules that might be imported by dynamic require calls at runtime.

The code in question appears to have been added two days ago, so I think this error was introduced by the release of react-jsonschema-form@0.40.0, not by the recent Meteor release.

**Comment by n1k0** [comment]
Released along [v0.41.2](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.41.2).
