### ISSUE TITLE
Use material-ui for the generated forms

### ISSUE THREAD

**Issue by almet** [mozilla-services/react-jsonschema-form#39]
Should we use this? The look and fill could improve a lot, but at the same time I wonder if that's really what this library should do.

https://github.com/callemall/material-ui

Thoughts?

**Comment by almet** [comment]
See https://www.google.com/design/spec/components/text-fields.html#text-fields-character-counter for an example of field.

**Comment by n1k0** [comment]
I really thing this lib shouldn't enforce using any css framework at all. But I understand it might please users to have something beautiful by default. Dilemma.

**Comment by almet** [comment]
Then the question could become "how do we let users specify the components they want", which might be something possible via what's described in https://github.com/mozilla-services/react-jsonschema-form#custom-widgets (I just actually discovered this).

Do you think this will be enough?

**Comment by n1k0** [comment]
I don't know, you might want to play a bit with it to know :)

What's sure, I don't feel at all like embedding a CSS framework in this project; I'd rather the DOM extension required mechanisms so users can provide their own elements custom tags and attributes, so custom widgets are probably the way to go, and we'll add anything missing if we can.

One thing is CSS frameworks usually heavily rely on a very specific HTML structures and semantics, class names, ids, etc., while React doesn't really offer really easy to use mechanisms to alter/extend/override these at a given specific node level. Kinda conflicting purposes.

**Comment by vincentfretin** [comment]
For material design, there is http://react-toolbox.com too.

**Comment by dimofte** [comment]
@almet, for a more opinionated package try [react-schema-form](https://github.com/networknt/react-schema-form). I think it's exactly what you're looking for: it uses the [material-ui package](https://github.com/callemall/material-ui) and the same json-schema standard (via [tv4](https://github.com/geraintluff/tv4))

**Comment by n1k0** [comment]
Following my [comment above](https://github.com/mozilla-services/react-jsonschema-form/issues/39#issuecomment-189204771). Feel free to reopen and discuss if you feel this is wrong.
