### ISSUE TITLE
Integrating  with other widgets such as react-select or react-tags

### ISSUE THREAD

**Issue by atkawa7** [mozilla-services/react-jsonschema-form#396]
I am new to this. I am wondering If I want to integrate with other libraries where do I start reading.

**Comment by n1k0** [comment]
Probably by [reading the docs](https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields).

**Comment by atkawa7** [comment]
For example I want to create a tag widget such as [react tagsinput](https://olahol.github.io/react-tagsinput/) but right I have no idea where and which part to start with. There is field, widgets, ui etc

**Comment by n1k0** [comment]
You need to write a custom widget to render your imported react tagsinput component. Did you actually read the docs? What's unclear?

**Comment by atkawa7** [comment]
Here is what I have done but one property is not showing up

```import React from 'react';
import TagsInput from 'react-tagsinput';
import 'react-tagsinput/react-tagsinput.css';

export default class SchemaTagField extends React.Component {
    constructor() {
        super()
        this.state = {
            tags: []
        }
    }

    handleChange(tags) {
        this.setState({
            tags
        }, () => this.props.onChange({
            [this.props.uiSchema['ui:field']]: this.state.tags
        }))
    }

    render() {
        return <TagsInput value={this.state.tags} onChange={this.handleChange.bind(this)}/>
    }
}

```
import React from 'react';
import Form from 'react-jsonschema-form';
import SchemaTagField from './SchemaTagField';

const schema = {
    type: 'object',
    required: ['genres', 'name'],
    properties: {
        genres: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    }
};

// Define the custom field component to use for the root object
const uiSchema = {
    'ui:field': 'genres'
};

// Define the custom field components to register; here our 'geo'
// custom field component
const fields = {
    genres: SchemaTagField
};

export default class Test extends React.Component {
    render() {
        return (
            <div className='col-md-4 col-md-offset-4'>
                <Form schema={schema} uiSchema={uiSchema} fields={fields}/></div>
        );
    }
}
```

**Comment by atkawa7** [comment]
@n1k0 Here is the code I am running. How do you make sure the rest of fields render with default widgets and then the custom field with your custom widget.
