### ISSUE TITLE
Suport for sub-forms

### ISSUE THREAD

**Issue by eskhool** [mozilla-services/react-jsonschema-form#40]
Is there a mechanism to support adding multiple sub forms? say to support one to many/many to many (or equivalent Nosql representation) relationships?
Any suggested path if someone to want to expand this project to do the same?

**Comment by almet** [comment]
Hi! Did you had a look at the "nested" section in the demo? http://mozilla-services.github.io/react-jsonschema-form/

**Comment by eskhool** [comment]
Facepalm. That's neat, thanks!

**Comment by n1k0** [comment]
Haha, you're welcome. I'm closing this.
