### ISSUE TITLE
Required field does not work with single field forms

### ISSUE THREAD

**Issue by vinhlh** [mozilla-services/react-jsonschema-form#404]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

With this definition, it should mark the form field `required`, right?
```js
module.exports = {
  schema: {
    title: "A paragraph question yo kk",
    description: "Should have a description field like this",
    required: true,
    type: "string",
    default:  ""
  }
};
```

@n1k0 You can confirm the expectation then I can work on this

### Steps to Reproduce

Create a form with above json schema.

#### Expected behavior

Should mark the field `required`

#### Actual behavior

Don't mark the field `required`

### Version

Latest 0.40.0

**Comment by n1k0** [comment]
The problem is that `required: true` at the field level has been deprecated in JSON schema v4... Not sure what to do here, as v4 doesn't expose any way to deal with single field value requirement. And I'm sure we want to start dealing with previous JSON schema spec version compatibility...

**Comment by n1k0** [comment]
We're not gonna support json-schema v3 and restrict our target support to v4 only.

**Comment by manuganji** [comment]
Hey, I'm wondering if you now have an answer for how to set required on a single field in the current v7?

**Comment by epicfaace** [comment]
@manuganji You can still just specify `required: ["field name"]` -- it's the same as with other properties. See https://json-schema.org/understanding-json-schema/reference/object.html#required-properties for more information.

**Comment by manuganji** [comment]
@epicfaace sorry for the confusion. My `schema` is comprised of just a single field and I want to set this field to be required. An example of my schema below.

```
{
  type: "number",
  enum: [1, 2, 3]
}
```

**Comment by manuganji** [comment]
So far I understand that I need to convert this into an object schema and follow the documentation that you linked to. The schema transforms to this.

```
{
  type: "object",
  properties: {
    numberField: {
      type: "number",
      enum: [1, 2, 3]
    }
  },
  required: ["numberField"]
}
```

**Comment by epicfaace** [comment]
Yeah, that's correct. I don't think JSON Schema v7 allows you to make a field required unless it's part of an object.

**Comment by manuganji** [comment]
Thank you for confirming, @epicfaace
