### ISSUE TITLE
How to customise Error List?

### ISSUE THREAD

**Issue by jmatsushita** [mozilla-services/react-jsonschema-form#405]
Hi there,

I'd like to customise the display of the error list but since it's not a widget it doesn't seem possible yet. Is there a workaround? Is that in the roadmap?

Cheers!

Jun

**Comment by n1k0** [comment]
You can tweak it by writing a [custom field template](https://github.com/mozilla-services/react-jsonschema-form#field-template) and formatting the `rawErrors` list.
