### ISSUE TITLE
<datalist> support

### ISSUE THREAD

**Issue by savvopoulos** [mozilla-services/react-jsonschema-form#406]
### Description

Hi, `<datalist>` is an extremely useful HTML feature that allows for suggest-like interfaces. Here is an example:
https://codepen.io/anon/pen/vymBmj

It would be really cool if react-jsonschema-form supported this. I guess this would go under uiSchema, for type=string fields.

For now, I have implemented it as a custom field, here:
https://github.com/savvopoulos/react-jsonschema-form
I've replaced the GeoPosition example with one that supports timezones.

If there's interest from the owners of react-jsonschema-form, I'd be happy to implement this inside of react-jsonschema-form.

![image](https://cloud.githubusercontent.com/assets/747519/20525367/039a2c7c-b0b7-11e6-84b0-4de3cf735a9f.png)

**Comment by Natim** [comment]
That sounds like a great feature indeed 👍 feel free to do a pull request.
i didn't know about this form feature.

**Comment by n1k0** [comment]
This looks awesome indeed! We need to figure out what are the jsonschema use cases and if/how we want to support them though.

As @Natim suggested, feel free to come with a PR!

**Comment by savvopoulos** [comment]
Sounds good. Re: jsonschema use cases, what did you have in mind?

This HTML element helps you select one element out of a (very long) list. Typically, you'd use it in place of a select, because scrolling through >20 items is annoying. So here's how I'd imagine it:

Example JSONSchema:
```
{
  "title": "A registration form",
  "type": "object",
  "properties": {
    "enumField": {
      "type": "string",
      "enum": [
        "foo",
        "bar",
        "fuzz",
        "qux"
      ]
    }
  }
}
```

Example UISchema:
```
{
  "enumField": {
    "ui:widget": "select"
  }
}
```

**Comment by Natim** [comment]
```
{
  "enumField": {
    "ui:widget": "datalist"
  }
}
```

**Comment by n1k0** [comment]
> Re: jsonschema use cases, what did you have in mind?

Well it seems like the input+datalist html widget would list the equivalent of a enum+enum but also allowing arbitrary strings to be entered; the purpose of an `enum` constraint is to actually restrict the field values to the ones from that list.

I'm trying to figure out what would be the right jsonschema matching this specific use case, as here the datalist seems to suit some autocomplete one than anything else.

**Comment by n1k0** [comment]
Maybe we should fill the datalist element with items from the `enum` constraint but rather from some specific option provided in the uiSchema?

**Comment by Natim** [comment]
In my understanding we should be able to use the same widget with type "string" or type "enum", the fact that the JSONSchema validates if the value is valid is another story.

But you are right that if we don't use enum we need a way to give the values.

**Comment by savvopoulos** [comment]
> but also allowing any arbitrary string to be entered
I see what you are saying. In my case (timezone selection) arbitrary input doesn't make sense, so use an enum*. You are right that, in other cases, e.g. search UIs, arbitrary input makes sense.

I don't know enough about JSON Schemas and your objectives about how to cover both. It seems to me that enum would be the right place to stick the options in; then we would need another field, making the enums required or optional.


* Actually, I don't. If somebody enters a random string, then the error message, which lists all possible enums, is annoying. So I ditched the enum and wrote a custom validator instead.

**Comment by n1k0** [comment]
It feels to me that the use of an input + datalist combination really fits in a custom field, to match very specific needs this library isn't willing to cover. Closing, but feel free to reopen if you strongly disagree with this decision.

**Comment by ianarawjo** [comment]
Yes! That worked like a charm! Thanks.
