### ISSUE TITLE
custom fields don't blend well with normal ones

### ISSUE THREAD

**Issue by savvopoulos** [mozilla-services/react-jsonschema-form#407]
### Description
Using custom fields with normal ones doesn't blend well.

### Steps to Reproduce
1. https://mozilla-services.github.io/react-jsonschema-form/
2. Click on "Custom"
3. In JSONSchema, enter one more property under `"properties"`:
```
    "Blah": {
      "type": "number"
    },
```

4. Notice that it doesn't appear on the left.
5. Replace the contents of UISchema with `{}`
6. Notice that there's now three text boxes on the left.

#### Expected behavior
I would have expected to be able to add more fields. It took me a while to understand that this is not the objective of this example:
```
// Define the custom field component to use for the **root** object
const uiSchema = {"ui:field": "geo"};
```
Perhaps this is a bit confusing and should be changed?

#### Actual behavior
Adding more fields to the custom example didn't work.

**Comment by n1k0** [comment]
This is because the sample `geo` custom component in this playground section is not designed to know about your `Blah` field.

**Comment by n1k0** [comment]
> Perhaps this is a bit confusing and should be changed?

Feel free to provide a PR with some contextual explanation in the field description if you feel that's really needed though.
