### ISSUE TITLE
Rendering fields for patternProperties 

### ISSUE THREAD

**Issue by andru** [mozilla-services/react-jsonschema-form#409]
I'm working with a schema which makes use of `patternProperties` for string localisations. Eg.

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://localhost:80/schema/01/taxon.json",
  "type": "object",
  "properties": {
    "common": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        "^([a-z]{2})([_-]{1}[A-Z]{2})?$": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}

```

This allows for a JSON object with arbitrary locale codes...

```json
{
  "en": "Hi",
  "en_US": "Sup",
  "en_GB": "Pip pip",
  "es": "Hola tío"
}
```

`react-jsonschema-form` 0.41.1 currently sees this as having no properties to render, and so just outputs a blank field. Is there any way around this?

**Comment by n1k0** [comment]
To be frank I wasn't even aware of `patternProperties`... We don't have use cases for it atm, but we're definitely interested in having support for this; would you be willing to work on this?

**Comment by Natim** [comment]
Hi @andru You are the first one bringing this usecase :)
It would be really nice if you could come up with a PR to support `patternProperties` 👍

**Comment by maartenth** [comment]
@andru This is stronly related to and a special case of `additonalProperties`, which is currently not supported either. Would be great to have this functionality.

For arrays, there are already add/remove/reorder buttons, which could be split out to a new component and reused for objects. An extra field for the object property name should then be added to the form, which I think is the most difficult part to get right. But not impossible of course. :)

**Comment by andru** [comment]
I'm playing around with this now to see if it's do-able within the time I
have available.

Current thoughts are to spin out a new field component
`PatternPropertyField` which is rendered by `ObjectField` and is similar in
functionality to `ArrayField`.

If anyone has any pointers or already has some thoughts on the best way to
implement this, let me know.

What were your thoughts for `additionalProperties`? I was under the
impression that's a `boolean` field just for schema enforcement. How would
the form take that into account?

On Wed, Nov 23, 2016 at 11:27 AM Maarten ter Horst <notifications@github.com>
wrote:

@andru <https://github.com/andru> This is stronly related to and a special
case of additonalProperties, which is currently not supported either. Would
be great to have this functionality.

For arrays, there are already add/remove/reorder buttons, which could be
split out to a new component and reused for objects. An extra field for the
object property name should then be added to the form, which I think is the
most difficult part to get right. But not impossible of course. :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla-services/react-jsonschema-form/issues/409#issuecomment-262478474>,
or mute the thread

**Comment by andru** [comment]
Oh, my bad. I see that `additionalProperties` [can also be a schema object](https://github.com/json-schema/json-schema/wiki/Additionalproperties),  so there's a lot of overlap between `patternProperties` and `additionalProperties`.

Maybe a component for a property with a user-defined name, shared by components for `patternProperties` and `additionalProperties`?

**Comment by andru** [comment]
Just dropping some notes on standards compliance here...

- The `additionalProperties` keyword may be either a `boolean` or an `object`. If `additionalProperties` is a boolean and set to `false`, no additional properties will be allowed.
- If `additionalProperties` is an `object`, that object must be a schema that will be used to validate any additional properties not listed in `properties`.
- `patternProperties` can be used in conjunction with `additionalProperties`. In that case, `additionalProperties` will refer to any properties that are not explicitly listed in `properties` and don’t match any of the `patternProperties`.
- The number of properties on an object can be restricted using the `minProperties` and `maxProperties` keywords. Each of these must be a non-negative integer.

**Comment by n1k0** [comment]
I'm still unsure we want 100% spec coverage, as this might involve **a lot** of work while we don't have these use case internally. Even with a full featured support that'd mean maintaining it, and mostly relying on actual users and implementers to do that job, which is never 100% guaranteed in my own experience.

What would be great is to have this kind of support ensured externally to the lib, but we'd need to introduce a rather complex hooking system...

**Comment by andru** [comment]
Ok. I'm going to pause for now then. I'm a bit short on time and don't want to put effort into preparing a controversial pull request.

If it's decided this is a missing feature, I'll happily pick it up again.

**Comment by n1k0** [comment]
Meanwhile you can probably write your own custom `ObjectField` field component and deal with `patternProperties` related logic there. The cool thing is if you get that working, it should then be trivial to eventually send a PR out of it, so we can decide if we want this part of the core or not  :)

**Comment by n1k0** [comment]
I think custom field implementation is the way to go for now. If anybody's willing to work on implementing proper support for this, feel free to reopen and send a PR.

**Comment by ktalebian** [comment]
@andru did you ever figure out how to do this?
