### ISSUE TITLE
Readonly on radio and checkboxes

### ISSUE THREAD

**Issue by crumblix** [mozilla-services/react-jsonschema-form#412]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I was surprised to find that I could still update radio buttons and checkboxes when they were set to readonly.

While the controls themselves may not support the property directly it seemed to me that that "disabled" was closer than nothing at all.  At least the user could update the data.

While disabled and readonly are subtly different, my suggestion is that using disabled is possibly better than doing nothing.

### Steps to Reproduce

1. [First Step]
Set a field using a RadioWidget or CheckboxesWidget to readonly.

#### Expected behavior
The user can't update those fields

#### Actual behavior
The user can still update the field.

### Version
Latest

Suggestion is to use "disabled" when the readonly flag is passed in to a control that doesn't support readonly inherently.

Fixes in my fork:
Commit: 41053bb3a08672cf78d70cff1dd6624c5a10b463 [41053bb]
Commit: 2573f73a40b21182ff4baa8126874a6639eaa7c5 [2573f73]
Commit: dda05d567ecdf09656538e8c40a9413b11e48300 [dda05d5]

Definitely made a meal of that one too.  Sorry for three commits instead of one!

**Comment by n1k0** [comment]
> While disabled and readonly are subtly different, my suggestion is that using disabled is possibly better than doing nothing.

I agree. Could you please send a PR with your changes so we can properly review and land them? Thanks!

**Comment by crumblix** [comment]
Will do :)

**Comment by n1k0** [comment]
Released in [v0.45.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.45.0).
