### ISSUE TITLE
Perf waste

### ISSUE THREAD

**Issue by vinhlh** [mozilla-services/react-jsonschema-form#424]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When I am working with object field with multiple sub-fields, then updating a field, 
Example: Change `Chunk` to `Chuck test blah blah record blah blah`
it creates a lot of waste rerender.
![](http://i.imgur.com/lSoJm3C.png)

If the form has more fields, and this cost will be much higher.

### Steps to Reproduce

1. Install `react-addons-perf` and `import Perf from 'react-addons-perf'`
2. In playground, select tab `Ordering`
3. Start Profiling.
4. Change `First name` from `Chunk` to `Chuck test blah blah record blah blah`.
5. Stop Profiling and see the results.

#### Expected behavior

So reduce these waste costs.

#### Actual behavior

Raise a lot of waste calculations.

### Version

0.40.0

**Comment by n1k0** [comment]
This is indeed a shame. Would you want to work investigating this?

**Comment by n1k0** [comment]
Could you please test latest master now #480 has landed? I bet it drastically improves the situation you describe here.

**Comment by vinhlh** [comment]
Not test yet, but it seems the PR could solve the problem @n1k0

**Comment by n1k0** [comment]
#489 is gonna drastically improve perfs as well methinks.
