### ISSUE TITLE
Validation is not performed on initialization when formData is undefined or null

### ISSUE THREAD

**Issue by ccancellieri** [mozilla-services/react-jsonschema-form#429]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Validation is not performed on initialization when formData is undefined or null even if the liveValidate property is set to true.

### Steps to Reproduce

1. [First Step]
 enable live validation so each character I digit is validated
2. [Second Step]
 passing an undefined (or null) data object into the formData property the form starts with no validation.

I'm providing a [sample JSFiddle](https://jsfiddle.net/mam4sje2/1/) demonstrating the issue.

#### Expected behavior

The validation should be performed also at the initialization when the form data is undefined or null.

#### Actual behavior

On initialization I don't have any object to pass to that property (formData) it will be generated by the form when onChange is called but the validation starts with no errors which seems an issue to me.

The validation is not called even if the property liveValidate is set to true it only works (correctly) on the first onChange.

### Version

react-jsonschema-form@0.38.1

**Comment by n1k0** [comment]
This is by design; `undefined` formData means no data is currently attached to the form, which means edition has not started yet, so there's no point at validating it.

If you want to perform data validation on form initialization, pass an empty object.
