### ISSUE TITLE
Option to hide a field?

### ISSUE THREAD

**Issue by chmac** [mozilla-services/react-jsonschema-form#43]
Is there an option we can pass to the ui schema that would result in a field being hidden?

**Comment by almet** [comment]
that's currently not implemented, but if you're willing to add one, don't hesitate!

**Comment by n1k0** [comment]
We should definitely add support for hidden fields (with static value). @chmac, would you want to start working on this?

**Comment by chmac** [comment]
@n1k0 :-) If you can point me in the right direction I'm happy to have a look, but we're using this package inside meteor which makes developing on it a little tricky. I'm not exactly sure where my `node_modules/` folder is to start messing with the source while the code is running...

**Comment by n1k0** [comment]
You should definitely clone this repo and work using the existing unit and DOM integration test suites available.

Basically the idea here would be to create a new kind of widget, eg. `HiddenWidget` which would simply hold the associated formData value it's attached to. Also we should add support for using it to override default widget used to render a given field using the `uiSchema` objecy and a `hidden` widget value for that field.

If that sounds super complicated no bif deal, you can either try or we'll take care of it. But if you want to work on this I'll provide guidance so you're not alone :)
