### ISSUE TITLE
Leverage the description schema prop for boolean checkboxes

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#435]
Checkbox fields don't display the description at all; we could at least use a tooltip.

**Comment by Reggino** [comment]
@n1k0 Would adding Jquery + Bootstrap JavaScript as (optional?) dependencies be an option to get something like [http://getbootstrap.com/javascript/#tooltips](this)? Or would you prefer a custom type of tooltip? 

Or would it be an option to show the description above the checkbox, like it is with regular text inputs?

**Comment by n1k0** [comment]
Just a `title` attribute would work I think.

**Comment by revolunet** [comment]
does https://github.com/mozilla-services/react-jsonschema-form/pull/498 fixes this ?

**Comment by n1k0** [comment]
Yes!
