### ISSUE TITLE
Suggestion: Abstraction of UI Framework

### ISSUE THREAD

**Issue by davistan** [mozilla-services/react-jsonschema-form#440]
Thanks for such wonderful library. However, noticed that the form is for bootstrap only.

We are currently making an ionic version but perhaps a suggestion that it can be adapter-style where it can switch to different fields / widgets based on config?

**Comment by n1k0** [comment]
We have [templates](https://github.com/mozilla-services/react-jsonschema-form#field-template) already, many have come with material-ui integration with this lib, so I think I can safely close this.
