### ISSUE TITLE
[Windows] "npm run dist" error on a clean install.

### ISSUE THREAD

**Issue by crumblix** [mozilla-services/react-jsonschema-form#445]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

On a clean install "npm run dist" is currently failing.

```
ERROR in ./utils.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/timers-browserify/main.js in D:\dev\temp\temp\react-jsonschema-form/src
 @ ./utils.js 1:0-54
```

This appears to be a dependency issue of some kind.  Replacing the entire `node_modules` directory with the `node_modules` directory from an earlier (and still working) version of react-jsonschema-form appears to work, so it's likely it will not be reproducible unless you start with a completely clean installation.  Running `npm run dist` on an installation a few weeks old will likely still work I think, you'll need to completely recreate your `node_modules`.

I've had a friend replicate it on his machine as well.

### Steps to Reproduce

(on Windows ... not sure if replicable elsewhere on other OS's)

```
git clone https://github.com/mozilla-services/react-jsonschema-form.git
cd react-jsonschema-form
npm install
npm run dist

ERROR in ./utils.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/timers-browserify/main.js in D:\dev\temp\temp\react-jsonschema-form/src
 @ ./utils.js 1:0-54
```
#### Expected behavior

`npm run dist` should not error.

#### Actual behavior

```
ERROR in ./utils.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/timers-browserify/main.js in D:\dev\temp\temp\react-jsonschema-form/src
 @ ./utils.js 1:0-54
```

### Version

Current.

**Comment by n1k0** [comment]
Damn, I don't have any Windows machine/vm at hand to investigate this. Would any Windows user be kind enough to work on fixing this?

**Comment by n1k0** [comment]
So it doesn't seem many people are hit by this issue, not it seems many want to help investigating this. I'm gonna close the issue, though feel free to reopen if you're willing to help :)

Thanks for your understanding.

**Comment by hauckwill** [comment]
I solved this on Windows by adding the following to the webpack config:

```javascript
resolve: {
  root: [
    path.join(__dirname, 'src'),
    path.join(__dirname, 'node_modules')
  ]
}
```

Unable to test on other platforms at this time.
