### ISSUE TITLE
On slow CPUs safeRenderCompletion needs to be set to make sure RJSF waits for setState before calling onChange

### ISSUE THREAD

**Issue by matiaslarsson** [mozilla-services/react-jsonschema-form#446]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I have custom widgets calling onChange only when the user is typing enter or unfocusing the text field to keep RJSF from updating the model for every key stroke.

Depending on CPU speed, submitting the form can result in the previous field value being submitted, probably due to the [utils.js setState function](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/utils.js#L463) only using the React setState callback functionality when `safeRenderCompletion` is true.

When the `safeRenderCompletion` prop is set on the `<Form>` component everything works as expected.

If I'm not doing something totally crazy here and this is expected behaviour maybe we should add something about `safeRenderCompletion` and this issue to the docs?

### Steps to Reproduce

1. Go to https://jsfiddle.net/matiasnu/gad1xm1L/
2. Turn on CPU throttling in Chrome (I'm using 50x, but the factor will most likely vary depending on your CPU)
3. Try updating the text field and clicking submit while keeping the text field focused. When not using `safeRenderCompletion` the submission will very often be the previous model state.
4. Turning off CPU throttling also makes the problem go away so it seems to be a timing issue.

#### Expected behavior

The submission should be the same as the model.

#### Actual behavior

On slow computers or CPU throttling activated the submission is often, but not always, the previous model value.

### Version

react-jsonschema-form@0.41.2

**Comment by n1k0** [comment]
> maybe we should add something about safeRenderCompletion and this issue to the docs?

Sure, would you want to update the docs about it in a PR?

**Comment by n1k0** [comment]
Could you please test again now that #480 has landed, which seems to have fixed #339 which looks very similar to your issue? Thanks.

**Comment by matiaslarsson** [comment]
Sorry for the late reply! #480 did not fix the issue unfortunately. Tried both RJSF 0.43 and 0.45. Will create a PR with updated docs warning about this issue.

**Comment by matiaslarsson** [comment]
@n1k0 docs PR submitted.

**Comment by glasserc** [comment]
@n1k0 Actually, would you mind explaining why we do this `setImmediate` hack? It seems like a racy footgun. If you explain it to me, then I wouldn't mind adding a comment to e.g. `setState` :)

**Comment by n1k0** [comment]
@glasserc this prevents components to try rendering synchronously while they both receive new props (triggering rerenders) and submitting change events, updating parent props, propagated to the same component. `setImmediate` basically postpones propagating the change in the next event loop tick or so. In my own testing, this really avoids blocking the UI, but there might be a better way.

And yes, this is a hack. If you have a better plan in mind, please file an issue with that plan!

**Comment by mrclay** [comment]
With safe off (i didn't know about until this moment), I've face tons of situations where I get false data/errors from Form onchange because it reports before it's ready. For some I've hacked by having some form components double-report their values on a timer.

With safe on, my forms (with live validation and the conditionals project applyRules) grind to a halt with keystrokes and changes that display new questions.

I wonder if there's a medium solution: an option to either allow component users to ask Form for an update (assuming it does has the correct value in internal state to report), or an option to have it call Form onchange on a timer.

**Comment by epicfaace** [comment]
@matiaslarsson I'm not able to test this, as it seems like I can only set CPU throttling up to 6x, not 50x. Any suggestions?

**Comment by epicfaace** [comment]
Closing this in favor of #1197.
