### ISSUE TITLE
How to plug spring-data-rest to react-jsonschema-form

### ISSUE THREAD

**Issue by kopax** [mozilla-services/react-jsonschema-form#447]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I am testing __spring-data-rest__ on a new spring installation.

I want to plug __spring-data-rest__ that provide jsonschema and entity (even with pagination) easely

- formData: by calling  __/api/managers/2__ endpoint
- schema: by calling __profile/managers__ endpoint (You must do with `Accept: application/schema+json` request header!)

Using a PostgreSQL database, I am serializing an Instant (jdbc) to Instant (java)

When I call endpoint __/api/managers/2__

    {
      "createdDate": {
        "content": "2017-01-21T08:12:12.429Z"
      },
      "lastModifiedDate": null,
      "createdById": null,
      "lastModifiedById": null,
      "active": true,
      "login": "me",
      "roleList": [
        "ROLE_MANAGER"
      ],
      "username": "me",
      "enabled": true,
      "authorities": [
        {
          "authority": "ROLE_MANAGER"
        }
      ],
      "accountNonExpired": true,
      "accountNonLocked": true,
      "credentialsNonExpired": true,
      "new": false,
      "_links": {
        "self": {
          "href": "http://localhost:8080/rest/managers/2"
        },
        "manager": {
          "href": "http://localhost:8080/rest/managers/2"
        }
      }
    }

This is a standard serialization from a controller when I call endpoint __/test__.

__I haven't customized__ spring-mvc jackson object mapper yet :

    {
      "id": 2,
      "version": 0,
      "createdDate": 1484986332.429,
      "lastModifiedDate": null,
      "createdById": null,
      "lastModifiedById": null,
      "active": true,
      "login": "me",
      "roleList": [
        "ROLE_MANAGER"
      ],
      "username": "me",
      "enabled": true,
      "authorities": [
        {
          "authority": "ROLE_MANAGER"
        }
      ],
      "accountNonExpired": true,
      "accountNonLocked": true,
      "credentialsNonExpired": true,
      "new": false
    }

and this is the `application/schema+json` of Manager.java

```json
{
  "title": "Manager",
  "properties": {
    "new": {
      "title": "New",
      "readOnly": true,
      "type": "boolean"
    },
    "lastModifiedDate": {
      "title": "Last modified date",
      "readOnly": false,
      "type": "string",
      "format": "date-time",
      "$ref": "#/definitions/instant"
    },
    "credentialsNonExpired": {
      "title": "Credentials non expired",
      "readOnly": true,
      "type": "boolean"
    },
    "active": {
      "title": "Active",
      "readOnly": false,
      "type": "boolean"
    },
    "login": {
      "title": "Login",
      "readOnly": false,
      "type": "string"
    },
    "roleList": {
      "title": "Role list",
      "readOnly": false,
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "enabled": {
      "title": "Enabled",
      "readOnly": true,
      "type": "boolean"
    },
    "authorities": {
      "title": "Authorities",
      "readOnly": true,
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "createdDate": {
      "title": "Created date",
      "readOnly": false,
      "type": "string",
      "format": "date-time",
      "$ref": "#/definitions/instant"
    },
    "lastModifiedById": {
      "title": "Last modified by id",
      "readOnly": false,
      "type": "integer"
    },
    "accountNonExpired": {
      "title": "Account non expired",
      "readOnly": true,
      "type": "boolean"
    },
    "createdById": {
      "title": "Created by id",
      "readOnly": false,
      "type": "integer"
    },
    "username": {
      "title": "Username",
      "readOnly": true,
      "type": "string"
    },
    "accountNonLocked": {
      "title": "Account non locked",
      "readOnly": true,
      "type": "boolean"
    }
  },
  "definitions": {
    "instant": {
      "type": "string",
      "properties": {
        "nano": {
          "title": "Nano",
          "readOnly": true,
          "type": "integer"
        },
        "epochSecond": {
          "title": "Epoch second",
          "readOnly": true,
          "type": "integer"
        }
      }
    }
  },
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

After reading [here](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/Form.js#L45), I have also tried to add a custom uiSchema: 

    {
      "ui:rootFieldId": "login"
    }

The error remain, I suspect this branch to be the cause

    if (obj1.hasOwnProperty(key) && isObject(right)) {
      acc[key] = mergeObjects(left, right, concatArrays);
    }

It only check if `isObject(right)` but not the `isObject(left)` so this function can be called with null object and will crash.

I am asking my self now: 

1. Is it standard to serialize date under a `content` sub key or is it spring-data-rest default configuration which is not compatible?
1. Is it possible to specify to __react-jsonschema-form__ that I use a sub key `content` for `createdDate` ?
1. Notice the __absence__ of the `id` attribute when calling the entity from the spring-data-rest URI, this because In HAL Links are used to reference related resources not ids and a HAL entity should always return a Link to itself, which serves as its unique identifier.
So my `id` field is not always an `id` but sometimes it can be `client_id` or an __url to it's repository__ while __react-jsonschema-form__ expect an id field at all time.  
My id is usually if it's from spring-data-rest endpoint
```json
"_links": {
    "self": {
      "href": "http://localhost:8080/rest/managers/1"
},
```
What would be the correct approach to bypass this restriction ?

### Steps to Reproduce

Prerequesite: a sample app with react-jsonschema-form installed

I have created a webpackbin [here](http://www.webpackbin.com/VkpQLE28G)

or if you want to play with spring-data-rest you can download a ready to go application

1. Clone repository : `git clone git@github.com:spring-guides/tut-react-and-spring-data-rest.git && cd tut-react-and-spring-data-rest.git && cd hypermedia`
2. If you wish to have a HAL browser like react-jsonschema-form playing (See this HAL browser [example](http://haltalk.herokuapp.com/explorer/browser.html#/), add this dependencies to the pom.xml : 

```xml
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-rest-hal-browser</artifactId>
    <version>2.5.6.RELEASE</version>
</dependency>
```

2. run `./mvnw spring-boot:run ` (you must have port 8080 available)
3. Go to `http://localhost:8080/api` and start playing with the api
4. Remember, to get the schemajson from the `/profile` endpoints instead of alps representation, you need to add the header `Accept: application/schema+json`

#### Expected behavior

Display a populated Form of my manager entity.

#### Actual behavior

Blank window and following javascript error : 

![image](https://cloud.githubusercontent.com/assets/1866564/22173753/bf49ad46-dffe-11e6-8a0a-503025f5646f.png)

### Version

0.41.2

**Comment by n1k0** [comment]
Woah that's a lot of information to process. I'll start with an observation, the schema looks strange wrt the `instant` definition, which declares a `string` type along some `properties`, which is usually used for the `object` type. The sample form data provided doesn't validate against the schema btw. I'm using http://www.jsonschemavalidator.net/ for checking, which says:

```
Found 4 error(s)
  Message:Invalid type. Expected String but got Object.
  Schema path: #/definitions/instant/type

  Message: Invalid type. Expected String but got Null.
  Schema path: #/definitions/instant/type

  Message: Invalid type. Expected Integer but got Null.
  Schema path: #/properties/createdById/type

  Message: Invalid type. Expected Integer but got Null.
  Schema path: #/properties/lastModifiedById/type
```

I don't know enough about the Spring framework to tell if that's a bug or them using a version of the json schema spec I'm not aware of, but that's definitely odd.

**Comment by kopax** [comment]
@n1k0 I have tried your link and this is strang the validation return me for the copy of the schema provided before : 

>  No errors found. JSON validates against the schema

What schema draft have you selected ? I have tried with draft v3 and v4.

**Comment by n1k0** [comment]
The schema is invalid as it declares a string type being an object. The error you get is because the lib tries to extract the `properties` definitions from a `string` one, which has none.

We could probably add a sanity check for this specific use case, but I suspect we'll then have to add many more for an infinity of other erroneous schemas. In your case, I'd recommend fixing the schema. There are online tools to help, like [this one](http://jsonschema.net/) or [this other one](https://bjdash.github.io/JSON-Schema-Builder/).   

> What back end do you use and what library to compute your json schema ?

At Mozilla and for the projects we use this lib for, we craft them by hand. I may sound tedious (actually it is), but it really helped understanding the spec and keeping control on our usage of it.

**Comment by kopax** [comment]
@n1k0 sorry to bother you again but I am still working on this issue.

> The schema is invalid as it declares a string type being an object. The error you get is because the lib tries to extract the properties definitions from a string one, which has none.

Is it still valid considering that my entity date store under an object key `content`  : 

```jsx
  "createdDate": {
    "content": "2017-01-21T08:12:12.429Z"
  },
```

I am afraid I can't change this : 

```
  "definitions": {
    "instant": {
      "type": "string",
      "properties": {
        "nano": {
          "title": "Nano",
          "readOnly": true,
          "type": "integer"
        },
        "epochSecond": {
          "title": "Epoch second",
          "readOnly": true,
          "type": "integer"
        }
      }
    }
  },
```

> We could probably add a sanity check for this specific use case, but I suspect we'll then have to add many more for an infinity of other erroneous schemas. In your case, I'd recommend fixing the schema. There are online tools to help, like this one or this other one.

The documentation on spring-data-rest is very poor, even if I handle the form client side, I will have to patch the request with the correct field.

I would probably start of a fork as I really want to see this work, would you mind help me a bit and show me how you would hack it using this example case ?

**Comment by n1k0** [comment]
For some reason this issue is now 404 through the github Web UI, hence why
I'm replying by email.

> Is it still valid considering that my entity date store under an object
key content :

Where's the `content` data substructure defined in your schema? There's an
obvious issue there.

> I would probably start of a fork as I really want to see this work, would
you mind help me a bit and show me how you would hack it using this example
case ?

I can't think of any better way to help you than insisting on having a
proper schema first, sorry :)

**Comment by kopax** [comment]
@n1k0 I see it will be too much work afterward.
I am working hard to get this api return a proper schema directly.
Meanwhile, I can implement a converter function that will be use to prepare the schema for react-jsonschema-form. 

What would a correct schema look like for this?

**Comment by n1k0** [comment]
> Should I just have this :
> ```json
> "lastModifiedDate": "2017-01-21T08:12:12.326Z",
> ```

Yes, and you can force using a datetime field by setting the `ui:widget` uiSchema property for this field to `date-time`.

**Comment by kopax** [comment]
My server return null values for my null fields of my entity. 
It appear react-jsonschema-form crash when values are null. I've read the doc and I am still not sure what to do in this situation.

**Comment by n1k0** [comment]
> My server return null values for my null fields of my entity.

Two things:

1. Your example schema doesn't reflect nullable types anywhere.
1. This library doesn't support `anyOf` just yet (which is often used to describe nullable fields), though ongoing effort is being made. Meanwhile, I'd highly suggest to avoid nullable fields, or to conditionally process the schema meanwhile.

> It appear react-jsonschema-form crash when values are null

If that means uncaught runtime exception, please provide a [SSCCE](http://sscce.org/) (I insist on the *Short* bit) so we can at the very least improve the situation by triggering a warning or something.

**Comment by kopax** [comment]
Well noted.

I am still trying to understand how does react-jsonschema-form can be tester on the link you provided me : http://www.jsonschemavalidator.net/

I have now managed my API to return the following schema : 

```
{
  "title": "Manager",
  "properties": {
    "createdDate": {
      "title": "Created date",
      "readOnly": false,
      "type": "string",
      "format": "date-time",
      "$ref": "#/definitions/instant"
    },
    "lastModifiedDate": {
      "title": "Last modified date",
      "readOnly": false,
      "type": "string",
      "format": "date-time",
      "$ref": "#/definitions/instant"
    },
    "lastModifiedById": {
      "title": "Last modified by id",
      "readOnly": false,
      "type": "integer"
    },
    "active": {
      "title": "Active",
      "readOnly": false,
      "type": "boolean"
    },
    "login": {
      "title": "Login",
      "readOnly": false,
      "type": "string"
    },
    "roleList": {
      "title": "Role list",
      "readOnly": false,
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "createdById": {
      "title": "Created by id",
      "readOnly": false,
      "type": "integer"
    },
    "enabled": {
      "title": "Enabled",
      "readOnly": true,
      "type": "boolean"
    }
  },
  "definitions": {
    "instant": {
      "type": "string",
      "properties": {
        "nano": {
          "title": "Nano",
          "readOnly": true,
          "type": "integer"
        },
        "epochSecond": {
          "title": "Epoch second",
          "readOnly": true,
          "type": "integer"
        }
      }
    }
  },
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

Using the following model : 

```
{
  "createdDate": "2017-02-02T15:05:12.631Z",
  "lastModifiedDate": "2017-02-02T15:05:12.631Z",
  "createdById": 1,
  "lastModifiedById": 1,
  "active": true,
  "login": "admin",
  "roleList": [
    "ROLE_MANAGER",
    "ROLE_ADMIN"
  ],
  "enabled": true,
  "_links": {
    "self": {
      "href": "http://localhost:8080/managers/1"
    },
    "manager": {
      "href": "http://localhost:8080/managers/1{?projection}",
      "templated": true
    }
  }
}
```

I have managed to unwrap the ISO date, I have No errors found. JSON validates against the schema.

I am trying to understand does react-jsonschema-form doesn't complain of the Instant reference definition.

> The schema is invalid as it declares a string type being an object. The error you get is because the lib tries to extract the properties definitions from a string one, which has none.

If I got correctly your explanation, unwrapping my value should not have been sufficient to remove the error. 

Why is it working now and should I care?

**Comment by n1k0** [comment]
I'm doing some repo gardening and issue triaging, and I think we've covered whatever needed to be covered with this specific issue. Feel free to reopen if you strongly feel otherwise. Thanks for your understanding.
