### ISSUE TITLE
Exception thrown while using recursive schema definition

### ISSUE THREAD

**Issue by b1r3k** [mozilla-services/react-jsonschema-form#452]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Current implementation is not able to handle recursive schema

### Steps to Reproduce

1. Make recursive schema like this:

```json
{
    "definitions": {
        "TPNode": {
            "title": "TPNode",
            "description": "TPNode",
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TPNode"
                    }
                }
            }
        }
    },
    "$ref": "#/definitions/TPNode"
}
```
2. Try to render

See fiddle: https://jsfiddle.net/b1r3k/dssabb76/2/

#### Expected behavior

Form should be rendered according to valid schema as done for example [here](http://jeremydorn.com/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKAKgBQDkVJtRlEAbCbEA40gGnAnQGMAnGAB2TVvokazRAE9uNLCBQAjAFYQ2iEM24cUEjslZkQcAIYBbSeXGSQ6RFzgBzEAF9mbABYxKYDhDi6xE2vo4OfVEVECQIQ0wcEAASTyhaAGIAekhYBD4MZMFSezy85jjoJNToeCRULJyaeyAAA=&value=N4IgdghgtgpiBcIQBoQGMAWBLANgEwCcYwEBtAXQF8gAAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_ehttps://jsfiddle.net/b1r3k/dssabb76/2/rrors=interaction)

#### Actual behavior

RangeError exception is being thrown

```
RangeError: Maximum call stack size exceeded
toIdSchema
webpack:///./~/react-jsonschema-form/lib/utils.js?:475:18
toIdSchema
webpack:///./~/react-jsonschema-form/lib/utils.js?:483:12
toIdSchema
webpack:///./~/react-jsonschema-form/lib/utils.js?:491:22
toIdSchema
webpack:///./~/react-jsonschema-form/lib/utils.js?:480:12
toIdSchema
webpack:///./~/react-jsonschema-form/lib/utils.js?:483:12
toIdSchema
webpack:///./~/react-jsonschema-form/lib/utils.js?:491:22
```

### Version

Current release (0.41.2)

**Comment by gpietro** [comment]
I still have this problem with version 1.0.0.

```
{
  "title": "Maximum call stack",
  "description": "Example to reproduce the error.",
  "$ref": "#/definitions/Person",
  "type": "object",
  "definitions": {
    "Person": {
      "properties": {
        "firstName": {
          "type": "string",
          "title": "First name"
        },
        "lastName": {
          "type": "string",
          "title": "Last name"
        },
        "address": {
          "title": "Hello",
          "type": "object",
          "$ref": "#/definitions/Address"
        }
      }
    },
    "Address": {
      "properties": {
        "street": {
          "type": "string",
          "title": "address2"
        },
        "resident": {
          "type": "object",
          "$ref": "#/definitions/Person"
        }
      }
    }
  }
}
```

**Comment by yuvi116** [comment]
did any one got the solution for recursive schema
