### ISSUE TITLE
Version mismatch with NPM & github repository 

### ISSUE THREAD

**Issue by nachiket-p** [mozilla-services/react-jsonschema-form#454]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Master branch is not matching current release. It is confusing and usually expected that master branch is latest and matching NPM latest.

### Steps to Reproduce
1. I am using latest 0.41.2, and tried to use ArrayFieldTemplate (_as visible in Demo Playground & Documentation on Github_)
2. It did not work, upon investigation I realize that NPM codebase (0.41.2) is not matching with Master (_which is also marked as 0.41.2_)

#### Expected behavior
Master branch should match with Version & updated in NPM

#### Actual behavior
Master branch is having same version 0.41.2 as NPM but codebase are different. 
Have a look at master branch commit history: 
https://github.com/mozilla-services/react-jsonschema-form/commits/master

### Version
0.41.2

**Comment by n1k0** [comment]
In this project, the master branch reflects ongoing development, and releases are available as [tags](https://github.com/mozilla-services/react-jsonschema-form/releases). While obvious to me, I'm gonna add a note about this in the docs. Thanks.
