### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by elisechant** [mozilla-services/react-jsonschema-form#455]
### Description
 
I'd like to take advantage of some fixes since last release (November 16), particularly https://github.com/mozilla-services/react-jsonschema-form/pull/448. Can you please make a release and publish to npm?

Latest release:
<img width="729" alt="screen shot 2017-01-29 at 9 30 38 am" src="https://cloud.githubusercontent.com/assets/2195815/22400325/afa2daf4-e605-11e6-9445-2fca12069305.png">

### Work around in the meantime

1. I clone master branch from git outside the project
2. `build:dist` and then port the distribution file inside my project

**Comment by n1k0** [comment]
I'm waiting for #450 to land and I'm doing a new release.

**Comment by elisechant** [comment]
could do 2 releases? but ok.

**Comment by n1k0** [comment]
Gonna do a release especially for you then. #450 isn't critical.

**Comment by n1k0** [comment]
[v0.42.0 is live](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.42.0).

**Comment by elisechant** [comment]
thank you @n1k0 you are the best 🏆
