### ISSUE TITLE
Feature request: subform. Or how to describe group elements

### ISSUE THREAD

**Issue by clu3** [mozilla-services/react-jsonschema-form#459]
Currently I wanna render a form which are displayed in 2 bootstrap columns

col-8: which will display some certain fields
col-4: which will display some certain fields

I can't figure out a way how to achieve this ? I was thinking the library should support some thing like subform, or something like that. Could you please give me some direction? 

Thanks a lot

**Comment by n1k0** [comment]
There's no support for CSS framework specific grid layouts, as it should remains agnostic as much as possible. You may be interested in creating custom field templates: https://github.com/mozilla-services/react-jsonschema-form#field-template
