### ISSUE TITLE
Array field buttons are not aligned correctly and fields are not showing up using bootstrap 4 (alpha 6)

### ISSUE THREAD

**Issue by zevenbergm** [mozilla-services/react-jsonschema-form#462]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Array field buttons are not aligned correctly and fields are not showing up using bootstrap 4 (alpha 6). Can you please point me in the right direction to solve this?

#### Expected behavior

![image](https://cloud.githubusercontent.com/assets/16295670/22761190/f9ddceb0-ee59-11e6-9375-c387fb75c97a.png)

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/16295670/22761258/45702f4e-ee5a-11e6-824d-dff00f5e4d7c.png)

### Version

0.42, bootstrap 4 (alpha 6)

**Comment by n1k0** [comment]
We currently don't have plans for supporting bootstrap 4. Would you be willing to work on this?

**Comment by epicfaace** [comment]
Merging this issue with #899.
