### ISSUE TITLE
Implementing Multi Step form or Wizard form?

### ISSUE THREAD

**Issue by bobony** [mozilla-services/react-jsonschema-form#464]
Is it possible to build wizard form using react-jsonschema-form. If possible could you please provide a simple example.

**Comment by n1k0** [comment]
It's been discussed several times in issues already. Basically you need to conditionally update the form schema depending on the submitted data. We may want to add a FAQ entry about this as this question keeps showing up regularly.

**Comment by n1k0** [comment]
Here's an example, hope it helps https://jsfiddle.net/sn4bnw9h/1/

**Comment by AKedar21** [comment]
> Here's an example, hope it helps https://jsfiddle.net/sn4bnw9h/1/

Above example is not working @n1k0 Would you please provide me some working example
Thank you

**Comment by epicfaace** [comment]
@AKedar21 that example was using a very old version of React. Here's an updated example: https://jsfiddle.net/gmz7qern/

**Comment by AKedar21** [comment]
> @AKedar21 that example was using a very old version of React. Here's an updated example: https://jsfiddle.net/gmz7qern/

Thanks @epicfaace For providing with the working fiddle

**Comment by christophsaile** [comment]
Hey @epicfaace @n1k0 with rjsf v6 being release is still the best approach to handle multi step forms?

**Comment by nico1996it** [comment]
> Hey [@epicfaace](https://github.com/epicfaace) [@n1k0](https://github.com/n1k0) with rjsf v6 being release is still the best approach to handle multi step forms?

I'm wondering the same, fiddle in the link also is not working again
