### ISSUE TITLE
Support optional objects

### ISSUE THREAD

**Issue by mfulton26** [mozilla-services/react-jsonschema-form#465]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Add support for not specifying an optional object property.

### Steps to Reproduce

1. Define a schema with a property of type object which is not required.
2. Render the schema on a react-jsonschema-form and attempt to not specify the optional object property.

https://jsfiddle.net/f2y3fq7L/19/

#### Expected behavior

Have some sort of checkbox or something to enable/disable specifying the optional object property.

#### Actual behavior

There is no apparent way to not specify the optional object property.

### Version

0.42.0

**Comment by n1k0** [comment]
Yeah, I've worked on a patch to make [fields collapsible in the past](https://github.com/mozilla-services/react-jsonschema-form/pull/271) but it was discarded in favor of theming; maybe we'd want to resurect it at some point, as this use case still seems valid to me.

**Comment by elisechant** [comment]
@mfulton26 would the example from the docs work for you here? https://jsfiddle.net/69z2wepo/68259/

**Comment by mfulton26** [comment]
I suppose although it does alter the schema and it seems like a lot of overhead if I have many optional objects.

**Comment by dropdevcoding** [comment]
In fact the form actually also validates wrong in this case which is very annoying. When defining an optional object inside the schema which has required fields the required fields always get validated although the schema would allow the whole object not to be there

**Comment by literarymachine** [comment]
I just had the same problem described here and in #331; a workaround seems to be to specify the property as type `array` with the `object` as its `items` and `maxItems` of 1: https://jsfiddle.net/z8b5s7t2/

**Comment by epicfaace** [comment]
Closing this in favor of #675
