### ISSUE TITLE
Support empty string text inputs and enum values

### ISSUE THREAD

**Issue by mfulton26** [mozilla-services/react-jsonschema-form#466]
The following saddens me:

> ### [The case of empty strings](https://github.com/mozilla-services/react-jsonschema-form#the-case-of-empty-strings)
>
> When a text input is empty, the field in form data is set to `undefined`. String fields that use `enum` and a `select` widget work similarly and will have an empty option at the top of the options list that when selected will result in the field being `undefined`.
>
> One consequence of this is that if you have an empty string in your `enum` array, selecting that option in the `select` input will cause the field to be set to `undefined`, not an empty string.

Can support be added to use a different "special" value as `undefined` or to place a checkbox or something next to the field to add/remove it?

**Comment by n1k0** [comment]
This issue has been discussed in #402, where we reached consensus.
