### ISSUE TITLE
Masked inputs

### ISSUE THREAD

**Issue by foundationx** [mozilla-services/react-jsonschema-form#467]
Is there anyway to mask inputs on forms created using this library? I have come up empty handed, and surprisingly I have not found this as a request.  Am I missing something or is it not an option?

**Comment by n1k0** [comment]
https://github.com/mozilla-services/react-jsonschema-form#hidden-widgets

**Comment by foundationx** [comment]
I don't understand,  what I am looking for is the ability to do something like as seen on the demo here http://digitalbush.com/projects/masked-input-plugin/

**Comment by n1k0** [comment]
Maybe next time link to this page in the description directly? That may save us some time, thanks.

So this is a very specific feature you may want to implement by yourself using a [custom widget](https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields).

**Comment by foundationx** [comment]
Yes, I should have,  I do think that this would be a great built in feature,   implemented into ui:options. 
thanks

**Comment by epicfaace** [comment]
@foundationx if you would like to make a PR for this feature, please go on ahead!
