### ISSUE TITLE
FieldTemplate => root

### ISSUE THREAD

**Issue by CedrikWinter** [mozilla-services/react-jsonschema-form#468]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Surely, I don't use it correctly... I'd like to use the Grid/Row/Col components from rect-bootstrap to have the `label` on the same line as the `input`.

### Steps to Reproduce

**1. `schema`**
```
const schema = {
  "name": "mail",
  "type": "object",
  "properties": {
    "description": {
      "type": "string",
      "title": "description"
    },
    "email_address": {
      "type": "string",
      "format": "email",
      "title": "address"
    }
  }
}
```
**2. `CustomFieldTemplate`**
```
function CustomFieldTemplate(props) {
  const {id, classNames, label, children} = props;
  console.log("label", label)
  return (
    <Row className={classNames}>
      <Col md={4}><label htmlFor={id}>{label}</label></Col>
      <Col md={8}>{children}</Col>
    </Row>
  );
}
```
**3. `Component`**
```
const Main = () => (
  <Form
    schema={testMail}
    FieldTemplate={CustomFieldTemplate}
  />
)
```
see https://jsfiddle.net/m0u2qn27/ for a complete test (whitout react-bootstrap, just bootstrap classes).

#### Expected behavior

Only 2 columns !

#### Actual behavior

It looks like there were 2 nested forms, the "good" form is in the 2nd column.

### Version

react-jsonschema-form@0.42.0 

### Thanks
And my apologizes for my bad frenchy english ;-)

**Comment by n1k0** [comment]
This looks more like a support request on {react-}bootstrap usage, and we don't feel qualified to address it, especially as we don't have this specific integration use case. You may want to reach out to the their respective user communities, or general CSS user groups.

**Comment by CedrikWinter** [comment]
I am really surprised by your answer... To me, it has nothing to have with **bootstrap**... Look at my forked jsFiddle : https://jsfiddle.net/zcy8v581/ .
I am maybe wrong, in that case would it be possible to have an example (jsfiddle ?) of the implementation of `FieldTemplate` attribute ?
Regards

**Comment by n1k0** [comment]
This is because you have the root object field label rendered on the left. Here's a simple example how to special case it https://jsfiddle.net/31qhdukj/1/

**Comment by CedrikWinter** [comment]
OK. thanks a lot. I don't understand where that ~root object comes from but anyway...
So to complete your answer, in my particular case _i.e._ with arrays, I have replaced the _simple_ `id==="root"` by `/^root(_listOfObjects(_\d+)?)?$/.test(id)`. Because my **schema** looks like 
```json
{
  "type": "object",
  "properties": {
    "listOfObjects": {
      "title": null,
      "type": "array",
      "items": {SPECIFIC_SCHEMA}
    }
  }
}
```
And now it works as I expected ! Nice :+1:
