### ISSUE TITLE
uiSchema for definitions

### ISSUE THREAD

**Issue by AnttiVikman** [mozilla-services/react-jsonschema-form#477]
Currently it seems there is no way to define ui options via uiSchema for the definitions. So where using definitions we can remove the repetition in schema, we are still forced to repeat ui options for each field in uiSchema.

Quick sample https://jsfiddle.net/9rwrn19d/1/

**Comment by n1k0** [comment]
This is indeed a current limitation. Note that meanwhile you can leverage good old JavaScript to avoid too much verbosity: https://jsfiddle.net/yx09e5gp/1/

But I agree it'd be better to natively support uiSchema for definitions.

**Comment by MatejMazur** [comment]
@n1k0 How would you solve uiSchema for a sample like [References in playground](https://mozilla-services.github.io/react-jsonschema-form/)?

**Comment by epicfaace** [comment]
Merging this into #701.
