### ISSUE TITLE
classNames with CSS Modules.

### ISSUE THREAD

**Issue by asifmom** [mozilla-services/react-jsonschema-form#479]
I am new to react and react-jsonschema-form

I am trying to add classNames in uischema using css modules as described in 

http://javascriptplayground.com/blog/2016/07/css-modules-webpack-react/

You can see the code at https://github.com/asifmom/react-css-modules-webpack.

However I am not able to set the classNames using the above method.

I may have missed something very basic and obvious.

Thanks in Advance

**Comment by n1k0** [comment]
This works at the lib level https://jsfiddle.net/gfwp25we/1/

We don't have time to investigate your webpack/css-modules integration issue, thanks for your understanding.
