### ISSUE TITLE
Object (and array ?) fields : classNames on the fieldset

### ISSUE THREAD

**Issue by cedricmessiant** [mozilla-services/react-jsonschema-form#49]
I would like to be able to set a className on the `<fieldset>` of my object fields.
My first guess was to try to use `uiSchema`'s `classNames` so maybe it is the way to go. 

What do you think about it ?

**Comment by n1k0** [comment]
Yes, I think specifying a `classNames` for the field is the way to go, and using a descendant selector for the style rule, eg. `.my-object-field > fieldset`. Would that solve your use case?

**Comment by cedricmessiant** [comment]
oh, sorry. The bug came from my custom `SchemaField` ! Thanks !
