### ISSUE TITLE
Using nested widgets

### ISSUE THREAD

**Issue by superartgun** [mozilla-services/react-jsonschema-form#492]
### Prerequisites

- I use in my project react-jsonschema-form.  I have a question.  

Can I use such that UI schemes ? :

```jsx
const uiSchema = {
  activities: {
    "ui:field": CustomParentComponent,
    // note the "items" for an array
    items: {
      requests: {
        "ui:field": CustomChildComponent,
      }
    }
  }
};
```
When I try to code such a scheme, is drawn only CustomParentComponent.  
I want to draw one component inside another component.

**Comment by n1k0** [comment]
What is that `requests`? Have you tried this?

```jsx
const uiSchema = {
  activities: {
    "ui:field": CustomParentComponent,
    items: {
      "ui:field": CustomChildComponent,
    }
  }
};
```

**Comment by superartgun** [comment]
@n1k0  Yes I tried it.  In this scheme occurs only render CustomParentComponent

**Comment by n1k0** [comment]
Doesn't https://jsfiddle.net/ymr6aeck/3/ solve your issue?

**Comment by superartgun** [comment]
@n1k0  Thank you. This solves my problem partially. I need to render the scheme with many levels of nesting. This is my scheme - https://jsfiddle.net/3gyh1u4w/.  I want to make a render my custom components at all levels of nesting.  Is it possible to render with 3-10 levels of nesting custom components ?

**Comment by n1k0** [comment]
I can't see why it wouldn't work. Did you try?

**Comment by superartgun** [comment]
@n1k0 This is code with 3 levels of nested components - https://jsfiddle.net/21964wcm/1/ and this is work. But I need the implementation in which the components do not know anything about ui:scheme. On the backend generated different schemes. The cliend side shall be automatically generated forms with different custom components. Component which one scheme - Parent  to another scheme may be Child.   If you have any ideas how this can be implemented using react-jsonschema-form I'll be happy. Thanks in advance for your time.

**Comment by glasserc** [comment]
If I understood your question correctly, you want the backend to generate different schemas, but the backend is ignorant of `uiSchema`. Can you write JavaScript to automatically generate a `uiSchema` from the JSON schema?

**Comment by glasserc** [comment]
This might also be related to #477.
