### ISSUE TITLE
how to identify that FieldTemplate function had passed normal field or any field of array

### ISSUE THREAD

**Issue by jariwalabhavesh** [mozilla-services/react-jsonschema-form#493]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

FieldTemplate is passing field data when rendering it, but is there anyway to idenify that what ever field data has been passed to FieldTemplate is normal form field or one of the field from array?

and can we change ui:options in fieldTemplate function?

**Comment by n1k0** [comment]
It's really unclear to me what the actual issue is here. Would you mind providing a jsfiddle reproducing the issue? Thanks.

**Comment by revolunet** [comment]
@jariwalabhavesh console log your `FieldTemplate` props and you'll get access to a lot, including uiSchema with your custom data ...
