### ISSUE TITLE
I want to supply different option to each select in array-field-template, is it possble?

### ISSUE THREAD

**Issue by jariwalabhavesh** [mozilla-services/react-jsonschema-form#494]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

I want to pass the different options to each select in array-field is it possible? beacuse we are providing single ui-scheme for each object in array?

For normal form field we can pass specific values to other form field, based on form onChange event. but how can we do that on array field template as well.

Suppose i have 2 select in each object of array

1. Country
2. State

On change of country i want to pass country data to specific state dropdown.(It is already achieved in normal form field without array), how can i pass specific country data to state widget in array template?

**Comment by n1k0** [comment]
I'm sorry I don't understand. Ideally, please provide a [jsfiddle](https://jsfiddle.net/n1k0/f2y3fq7L/) so I can better understand what is your issue.

**Comment by n1k0** [comment]
I'm gonna close this, feel free to reopen with further explanations.
