### ISSUE TITLE
Field level error validation should use correct bootstrap class

### ISSUE THREAD

**Issue by elisechant** [mozilla-services/react-jsonschema-form#501]
### Description

When there is a field error, `form-group` appends a `has-error` class when in fact this should be `has-danger` from Bootstrap 4 - https://v4-alpha.getbootstrap.com/components/forms/#defining-states.

`has-error` is correct for Bootstrap 3. 

### Steps to Reproduce

1. Generate a field level error
2.  Inspect classes of form-group

#### Expected behavior

should look like:

<img width="320" alt="screen shot 2017-03-02 at 10 33 12 am" src="https://cloud.githubusercontent.com/assets/2195815/23486325/9646f8aa-ff33-11e6-99aa-5d97b78d2069.png">

#### Actual behavior

but looks like:

<img width="270" alt="screen shot 2017-03-02 at 10 33 20 am" src="https://cloud.githubusercontent.com/assets/2195815/23486324/91a7b672-ff33-11e6-8f54-887eb5388eb4.png">

Need to string change to correct at: src/components/fields/SchemaField.js:183

### Version
0.43.0

**Comment by n1k0** [comment]
We don't officially support bootstrap 4, so the challenge if any is to keep full compatibility with version 3 in any case.
