### ISSUE TITLE
Validation on Null value "Is not of a type(s) string"

### ISSUE THREAD

**Issue by kentplaza** [mozilla-services/react-jsonschema-form#509]
### Description

Validation on type face problem when binding data from DB null.
The submit /post will not fire due to validation failed but if user simple enter some text and then erase it in the text box, the validation passed.  

### Way to produce
1. Binding Null data in to text box
  
![1](https://cloud.githubusercontent.com/assets/9535716/23830164/f74a8a82-073e-11e7-894f-88930d55bcbb.JPG)

2. Click on submit, error message will show.

![2](https://cloud.githubusercontent.com/assets/9535716/23830148/89d7d8e2-073e-11e7-9db6-c5b5de870062.JPG)

3. Type any text in text box and erase in by "backspace".
4. Click on Submit. Post fired.

**Comment by n1k0** [comment]
Indeed `null` is a specific jsonschema type not a string. Try casting your `null` into `undefined` to mark the field unfilled.

**Comment by kentplaza** [comment]
@n1k0 null is jasonschma type?

I try  set "type": "null" as below but i got "Unsupported field schema { "type": "null"..."

"ID_NUMBER": {
      "type": "null",
      "title": "IC Number",
      "pattern": "^$|^((\\d{2}((0[13578]|1[02])(0[1-9]|[12]\\d|3[01])|(0[13456789]|1[012])(0[1-9]|[12]\\d|30)|02(0[1-9]|1\\d|2[0-8])))|([02468][048]|[13579][26])0229)\\d{2}\\d{4}$",
      "messages": {
            pattern: "Invalid ic number format. (e.x: 811111111111)",
        }

**Comment by n1k0** [comment]
The `null` jsonschema type only accepts null values. You seem to be after a nullable string type, eg. `["string", "null"]` (where a provided value could either be a string or `null`), but this isn't supported in this lib (see #282).

**Comment by 1dolinski** [comment]
Thoughts on a form option to cast nulls to undefined?

**Comment by amiuhle** [comment]
I think there should be *some* supported solution for this, because `null` is a valid value if the field is not marked as required.

**Comment by n1k0** [comment]
> null is a valid value if the field is not marked as required.

If a field is not required, the object property should either be missing or set to the expected type:

![](http://i.imgur.com/ygWSu9L.png)

**Comment by o-nix** [comment]
So, I'm doing a `PATCH` operation from all the field values. If I set `null`s as `undefined`, I'm bypassing the validation but... I'm losing the fields for patching and the server thinks I'm just not sending any value for modification.

**Comment by n1k0** [comment]
This is a client side form library. What you send to your server should probably be post-processed. Also, if your server expects `null` or `string` values for example, you should type your schema accordingly, with a composite schema type like `["null", "string"]`, though that is not supported by this lib yet.

But maybe someone wants to work on a patch?

**Comment by amiuhle** [comment]
Derived from @1dolinski's comment, I'm currently filtering errors like this:

```javascript
transformErrors={errors => errors.filter(error => error.hasOwnProperty('instance'))}
```

If I have some time left towards the end of the week, I'll look into creating a PR to support `["null", "string"]`.

**Comment by crankycookie** [comment]
What was the outcome of this thread? Is the expectation to use
```transformErrors={errors => errors.filter(error => error.hasOwnProperty('instance'))}```

or is there support for `["null","string"]` types?

**Comment by danhodkinson** [comment]
+1 for support for `["null","string"]`

**Comment by atannerd** [comment]
+1 for support for ["null","string"]

**Comment by glasserc** [comment]
`["null", "string"]` seems like a duplicate of #465.
