### ISSUE TITLE
Problem on Field set "Not Mandatory" for Enum

### ISSUE THREAD

**Issue by kentplaza** [mozilla-services/react-jsonschema-form#511]
### Description
Problem on Field set **Not Mandatory** for Enum.
I defined a State using selection/enum but this field is not mandatory.

Problem when  user didt select anything and remain at "Choose an option". Validation fail on "type" and "is not a number of enum" as below.

![state](https://cloud.githubusercontent.com/assets/9535716/23833310/83a231f8-077e-11e7-969a-75ad4ecd87c7.JPG)

```js
//in the uischema
 "STATE": {
    "ui:placeholder": "Choose an option",
  }

//in the schema
"STATE":{
       "title": "State",
        "type": "number",
        "enum": [1,2,3],
        "enumNames": ["ALABAMA","TEXAS", "OHIO"],
        },
  } 
```

**Comment by n1k0** [comment]
Sorry I can't reproduce. See sample jsfiddle https://jsfiddle.net/n1k0/hq551777/1/

**Comment by kentplaza** [comment]
Hi  @Nicolas,
@n1k0, Isee this sample [https://jsfiddle.net/kentplaza/gtj2m6Lz/1/ ](url)

When the properties type: "number", the initial binding formdata is `null `or '' (empty string) will blocked in validation for submit. 

I think because `null `or '' is not number and people suggest to use 0 to represent as unselect.
In my case I cant simple use 0 for unselect

**Comment by n1k0** [comment]
You're initializing the name field with a string, which is not a number hence the validation error you get. This is all compliant with the JSON schema spec, I can't see what we could improve here, nor if it would actually be a very good idea.

**Comment by kentplaza** [comment]
I got the way to overcome this.. We gonna remove the null properties or set it undefined.
