### ISSUE TITLE
how to hidden object in uiSchema

### ISSUE THREAD

**Issue by doris1yu** [mozilla-services/react-jsonschema-form#514]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Object type still display in the UI even setting "ui:widget": "hidden" to properties
 

### Steps to Reproduce

1. 
module.exports = {
  schema: {
         title: "A registration form",
    description: "A Organization form example.",
    type: "object",
    required: ["OrgaizationID", "Site","OrganizationName","Legal_Name","Lifecycle_Status","Account_Type"],
    properties: {  "_id":  {
      "type": "object",
      "properties": {
        "_$oid": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "_$oid"
      ]
    },
    "_etag": {
      "type": "object",
      "properties": {
        "_$oid": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "_$oid"
      ]
    },
  },
}

2. [Second Step]
  uiSchema: {
 
    _id : {
      "ui:widget": "hidden",
    },

    _etag: {
      "ui:widget": "hidden",
    }
  },
3. [and so on...]
_id,  _etag still showing in UI

#### Expected behavior

_id,  _etag which is object type can be hidden in UI 

#### Actual behavior

_id,  _etag still display in UI

### Version

0.43.0

**Comment by doris1yu** [comment]
please take a look at the issues. Thanks.

**Comment by revolunet** [comment]
please make your issue readable by formatting the code, see https://guides.github.com/features/mastering-markdown

also, in your `schema` you're using properties `id` and `etag` while you use `_id` and `_etag` in the `uiSchema`.

**Comment by n1k0** [comment]
It's explained in the documentation https://github.com/mozilla-services/react-jsonschema-form/#hidden-widgets

![](http://i.imgur.com/6DCVQl7.png)
