### ISSUE TITLE
Multiple controls in a row

### ISSUE THREAD

**Issue by sandeepkesarkar** [mozilla-services/react-jsonschema-form#515]
### Prerequisites

- yes I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

I am trying to create a form which would require two or more textboxes to be displayed next to each other like in screenshot below. Would there be any way to do that?

![screen shot 2017-03-15 at 5 28 59 pm](https://cloud.githubusercontent.com/assets/4030004/23971601/fc9f56a8-09a4-11e7-9b71-8c7c73b4fa35.png)

**Comment by n1k0** [comment]
Use a field template.

**Comment by chatwithrajaram** [comment]
Thanks for your response. 
**Field Template** helped us to customize particular field/control only. 
I would like to design a **custom form layout** with place holders for every control.
Would there be any way to do that?

**Comment by n1k0** [comment]
I don't know, CSS maybe? https://jsfiddle.net/n1k0/bw0ffnz4/1/

**Comment by chatwithrajaram** [comment]
Thanks for your quick response. We are looking for something like **custom form layout** with control to be rendered at specific position.  Thanks again.

**Comment by n1k0** [comment]
That's not currently supported, neither we do have a use case for it. You can submit a PR if you're planning to work on this.
