### ISSUE TITLE
Support for immutable.js?

### ISSUE THREAD

**Issue by Reggino** [mozilla-services/react-jsonschema-form#523]
I noticed `formData` can not be provided as a [immutable.js Map](https://facebook.github.io/immutable-js/docs/#/Map). Is that something anyone is interested in?

**Comment by n1k0** [comment]
Isn't it just matter of ensuring providing the [#toJS](https://facebook.github.io/immutable-js/docs/#/Map/toJS) version of it? If not, are you suggesting we rewrite the entire project to leverage Immutable.js and add it as a requirement?

**Comment by Reggino** [comment]
Well, the latter may be nice, but probably not realistic... 

As was actually thinking of "duck typing" the immutable.js Map in the Form-component and calling `toJS()` automagically if a Map was detected, since i was under the impression immutable is pretty commonly used. 

But now i think of it, maybe it would give the impression other stuff (like `formValues`) would be returned as immutable-objects as well. I'll close it for now...
