### ISSUE TITLE
Custom ArrayField Template is not rerendering

### ISSUE THREAD

**Issue by VijayKrish93** [mozilla-services/react-jsonschema-form#526]
I use Custom Arrayfield component in my form.It is a functional component.My parent component state is triggered which allows my parent to re render but not the custom array field function.I need some references within my custom component function.After some inspection I came to a conclusion that it must be something within the formComponent .Quick help would be useful.Thanks
in advance

**Comment by glasserc** [comment]
Do you have a JSFiddle or anything like that that we could look at?
