### ISSUE TITLE
[Question] Redux Form

### ISSUE THREAD

**Issue by jpmelnik** [mozilla-services/react-jsonschema-form#528]
redux-form package is supported?

Thanks.

**Comment by n1k0** [comment]
no.

**Comment by nikordaris** [comment]
I started working on a less opinionated jsonschema visualizer, [react-jsonschema-vis](https://github.com/nikordaris/react-jsonschema-vis). Not as feature rich as this one yet but it was intended to support redux-form. I welcome contributors. The redux-form reactstrap component library implementation can be found here, [redux-form-jsonschema-reactstrap](https://github.com/nikordaris/redux-form-jsonschema-reactstrap).
