### ISSUE TITLE
Make custom widgets aware of their location in formData

### ISSUE THREAD

**Issue by lebek** [mozilla-services/react-jsonschema-form#531]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

It'd be useful if custom widgets were passed a prop describing their location in the formData (probably as an array, representing a key path). For example:
```javascript
const schema = {
  type: "object",
  properties: {
    foo: {
      type: "object",
      properties: {
        bar: {type: "string"},
        baz: {type: "string"}
      }
    }
  }
};

const uiSchema = {
  foo: {
    bar: {
      "ui:widget": (props) => {
        console.log(props.schemaPath) // outputs: ["foo", "bar"]
      }
    }
  }
}
```

Use case:
I have a custom widget that lets the use select from a list of entities _or_ create a new entity. If the user chooses to create a new entity they're sent to a new page with a different form. When they submit this second form, they're directed back to the first form where the newly created entity should be populated in the original field.

At the end of the flow we need to know where to put the new entity in the formData, which is difficult because the original custom widget never knew where it was.

Let me know if there's a way to implement this I haven't thought of (apart from passing a key path in `ui:options`). I'm happy to work on a PR for this if it makes sense.

**Comment by eeinowski** [comment]
idSchema can be useful for this in some scenarios.  For instance, if you want to know which array item you are working from, you can extract it from the idSchema using regex. Example: root_specimens_0 tells me that I'm working in the array Specimens at the index of 0.

**Comment by epicfaace** [comment]
@lebek Are you still having this problem? Did the idSchema solution work for you?

**Comment by suriya-p-rivet** [comment]
Hi @epicfaace ,
I am having a custom field called buttonField, in the buttonfield I can able to get the idSchema from props.
however, it is separated by `"_"`.
But in my object many property name also having `"_"` like `"external_link"`.
In this case how can I get the path for this field. Any suggestion, ?

**Comment by epicfaace** [comment]
> Hi @epicfaace ,
> I am having a custom field called buttonField, in the buttonfield I can able to get the idSchema from props.
> however, it is separated by `"_"`.
> But in my object many property name also having `"_"` like `"external_link"`.
> In this case how can I get the path for this field. Any suggestion, ?

As you saw, #688 is an approach to solve it. However, it requires some changes to fix backwards compatibility.

I'm going to close this issue for now as it's unrelated, but @suriya-p-rivet you should make a new issue about your particular problem and then we can work off of that to solve it!
