### ISSUE TITLE
enumNames is not in JSON Schema spec

### ISSUE THREAD

**Issue by dlax** [mozilla-services/react-jsonschema-form#532]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

react-jsonschema-form has implemented support for [labels in enum fields][] through the `enumNames` keyword following a [proposal](https://github.com/json-schema/json-schema/wiki/enumNames-%28v5-proposal%29) which then turned into issue json-schema-org/json-schema-spec#57 in which the proposal got refused. So the `enumNames` keyword does not appear and will probably not appear in JSON Schema specification format and react-jsonschema-form thus deviates from it.

[labels in enum fields]: https://github.com/mozilla-services/react-jsonschema-form/blob/v0.45.0/README.md#custom-labels-for-enum-fields

From json-schema-org/json-schema-spec#57, the recommended way to handle labels in enum is to use a `oneOf` with a set of schemas. So following the example from [documentation][labels in enum fields], it would be (in draft-v5):
```json
{
  "type": "number",
  "oneOf": [
    {"enum": [1], "title": "one"},
    {"enum": [2], "title": "two"},
    {"enum": [3], "title": "three"}
  ]
}
```
In draft-v6, a `const` keyword got added (see json-schema-org/json-schema-spec#139), so the example above could be simplified as:
```json
{
  "type": "number",
  "oneOf": [
    {"const": 1, "title": "one"},
    {"const": 2, "title": "two"},
    {"const": 3, "title": "three"}
  ]
}
```

### Version

0.45

**Comment by Natim** [comment]
Well let see how it turns out, because the usability of the current solution is much better.

**Comment by dlax** [comment]
> Do you think react-jsonschema-form should implement all of this specs? It sounds terrible to me.

Not sure what you mean by "all this specs", but I'd say it should rather implement something from the spec than something not from the spec (as `enumNames`). The fact that implementation on this side preceded adoption in JSON Schema format is rather unfortunate. At least the documentation could be clarified.

This description is indeed more verbose but it has the advantage of coupling tight the value and the title rather than relying on the order of two arrays. Another advantage is that is make use of an existing construct `oneOf`, which highlights the versatility of JSON Schema format.

Unfortunately (#52), `oneOf` is not supported by react-jsonschema-form.

**Comment by n1k0** [comment]
I'm surprised the spec evolves in a non-backward-compatible manner. Or would that mean we should support all draft versions of it?

So why I'm all in for having full support of latest spec draft, this one involves a bunch of work so help is badly needed. Also, as v4 is widely used it's no question we should keep supporting it anyway.

Meanwhile, any help would be greatly appreciated.

**Comment by dlax** [comment]
> I'm surprised the spec evolves in a non-backward-compatible manner.

On this particular point, it did not. `enumNames` has never been part of any version of the spec, the idea has just been proposed at some point but got rejected later on.

**Comment by glasserc** [comment]
I just looked up some stuff related to `enumNames` and I agree with @dlax. https://github.com/json-schema-org/json-schema-spec/issues/57 summarizes the JSON Schema folks' current thinking on the subject. The rjsf documentation for `enumNames` points to https://github.com/json-schema/json-schema/wiki/enumNames-(v5-proposal), which is clearly a proposal.

**Comment by glasserc** [comment]
Oops, I see those links are already in @dlax's summary at the top, sorry for the noise.

**Comment by eddyzhang1986** [comment]
I also need this support ,because I use "JSON.NET" as my server site jsonschema library.
That, this library use oneof 、anyof features instead of enum and enumName,
I think that's better .

**Comment by fbessou** [comment]
@eddyzhang1986, it has been merged in 3df0ab724e31b8742cc43465f699d1b2c9106649 :)

**Comment by eddyzhang1986** [comment]
@fbessou  thank you ,that feature is very cool

**Comment by dlax** [comment]
Closing as PR #581 is merged.

**Comment by nickgros** [comment]
We elected to revert this change and will simply deprecate for now.
