### ISSUE TITLE
Multiple Array Types

### ISSUE THREAD

**Issue by nwlieb** [mozilla-services/react-jsonschema-form#536]
I have two different kinds of arrays in my form which should be rendered differently. However, I cannot multiplex the ArrayField template because you do not pass the uiSchema as props to it (with which I would pass a 'ui:options' describing the array type).

Would it be possible to pass the uiSchema (or maybe there is another way to handle multiple custom array fields I'm not seeing).

### Version
v0.45.0

Thanks for the great library!

**Comment by n1k0** [comment]
> Thanks for the great library!

Thanks for the kind words. Should be fixed by #537.

**Comment by n1k0** [comment]
Released in [v0.46.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.46.0).
