### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by aduth** [mozilla-services/react-jsonschema-form#54]
Loving this component so far! However, in my own usage, and even in the demo site, there's a noticeable lag when attempting to enter text into fields at a reasonable typing speed. Enabling the "trace react updates" option in Chrome [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi), it becomes apparent that the entire form is re-rendered any time an input changes.

![render](https://cloud.githubusercontent.com/assets/1779930/13620579/d6810ebe-e55e-11e5-8e8a-356efe99b370.gif)

I haven't dug into the code, but it would seem reasonable to implement [`shouldComponentUpdate`](https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate) (perhaps simply with [`pure-render-mixin`](https://facebook.github.io/react/docs/pure-render-mixin.html)) to prevent rerendering of components not affected by the change in form values.

**Comment by Natim** [comment]
Thank you for this report :+1:

**Comment by n1k0** [comment]
If we want to properly implement shouldComponentUpdate, we'll have to rely on some immutable library like Immutable.js, which was something I tried to avoid.

But I agree the impact on performances on lower end machines might get really important, so we should do this upgrade.

**Comment by aduth** [comment]
>If we want to properly implement `shouldComponentUpdate`, we'll have to rely on some immutable library

Again, pardon my ignorance of the application and whether these suggestions have already been considered, but it's quite possible to perform shallow comparison (i.e. pure render) even with plain object properties, so long as you're careful not to mutate the original when updating.

```js
Object.assign( {}, original, { input: 'New Value' } );
```

Or, for deeply nested objects, consider pulling in [`lodash.merge`](https://lodash.com/docs#merge):

```js
merge( {}, original, { foo: { bar: { input: 'New Value' } } } );
```

**Comment by n1k0** [comment]
The problem is not with copying/merging nested objects, it's with comparing them to know if they've changed.

```js
({a: 1, b: {c: 2}}) === ({a: 1, b: {c: 2}}) // false
```

And `shouldComponentUpdate` needs to return a boolean to trigger a render when things have changed. So we need immutable data structures which don't carry identity as plain js objects do, so we can safely compare them and return the appropriate boolean value there.

Am I missing something obvious? I didn't have my first coffee of the day just yet.

**Comment by leplatrem** [comment]
Does this affect the demo only or the form rendering itself?

**Comment by aduth** [comment]
@leplatrem : I'm observing it in my own usage as well, but the demo was the easiest way for me to illustrate the problem.

**Comment by magopian** [comment]
It *may* be related to kinto-admin, but when viewing a page with a few hundred records (for the blocklist), the page is very laggy, unresponsive, and even freezes for a couple of seconds at the beginning.

**Comment by aduth** [comment]
Might be compounded with the fact that JSON schema validation is performed on every change:

https://github.com/mozilla-services/react-jsonschema-form/blob/afcb38e/src/components/Form.js#L51

**Comment by n1k0** [comment]
This is probably the very first thing to investigate as a solution https://facebook.github.io/react/docs/shallow-compare.html

**Comment by yogeshwar-woodside** [comment]
Hello, I am experiencing this issue with v4. 

It appears that entire form re-renders on any field change. We are particularly having large forms (30+ fields) and expected to have larger forms in future. This is causing performance bottleneck on mobile devices. What can be done?

**Comment by Sushil3663** [comment]
I have used a custom debounce of 2 seconds in onChange to improve type speed as a temporary solution
---   const debouncedOnChange = useDebounce(onChange, 2000);
