### ISSUE TITLE
The new feature ui:emptyValue issue

### ISSUE THREAD

**Issue by chenxiaomeng** [mozilla-services/react-jsonschema-form#543]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

when empty value set to null, validation should not report an error that type(s) not right

### Steps to Reproduce

[sample JSFiddle](https://jsfiddle.net/c_xm/fmrndo1x/3/) 

#### Expected behavior

when the empty value set to null, the validation should not report an error

#### Actual behavior

validation will report an error:
instance.name is not of a type(s) string

### Version

0.46.0

**Comment by n1k0** [comment]
Your schema requires an integer and a string, there's no way `null` can ever comply with these constraints. The `ui:emptyValue` option must comply with the expected schema type and can't magically bypass it.
