### ISSUE TITLE
Overriding core components styles

### ISSUE THREAD

**Issue by asaf** [mozilla-services/react-jsonschema-form#546]
Hey,

I'd like to perform minimal changes on the core widgets shipped with this package,
For example, I'd like to extend all components with my some CSS classes:

```javascript
import React, {PropTypes} from "react"
import _BaseInput from 'react-jsonschema-form/lib/components/widgets/BaseInput'

function BaseInput(props) {
    return <_BaseInput {...props} className='foo'/>
}
export default BaseInput
```
This won't work because `BaseInput` overrides the className field,

Do you find it okay to move the [inputProps](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/BaseInput.js#L23]) at the end of the list so default props could be overriden ?

Also, other components that don't inherit from `BaseInput` don't propagate properties, if you find this approach acceptable I can send some PR that make the core widgets extendable.

Thanks.

**Comment by n1k0** [comment]
Yeah that sounds reasonnable. Please send a PR :+1:

**Comment by developer-lindner** [comment]
@n1k0 What about removing bootstrap and implement something like decorators? so any could define the wrapping div's + classes they need for their chosen framework. Just my 2 cents...

**Comment by mravenash** [comment]
is there a sandbox for this? It will be helpful.

**Comment by epicfaace** [comment]
@mravenash yes, see https://react-jsonschema-form.readthedocs.io/en/latest/#tips-and-tricks
