### ISSUE TITLE
Hiding a schema object.

### ISSUE THREAD

**Issue by asaf** [mozilla-services/react-jsonschema-form#548]
### Description

UI Schema currently doesn't respect hiding an object,

Since we can't use `ui:widget` on the object level as it's not really a widget,

I can see two possibilities:

1. Put 'ui:widget: hidden' on every property, this is a bit annoying, it also means that the field wrapper should have a logic to skip rendering title and description if all fields are hidden.
1. We could introduce a new property such as `ui:visible`, just like we have `ui:order`,
but this is also a bit tricky, visibility means that data should be still there but hidden, so somehow we have to force 'ui:widget: hidden' for all sub-properties.

@n1k0 does any of this makes sense?

Thanks,
Asaf.

**Comment by glasserc** [comment]
Personally, I feel like the visibility of elements is outside the scope of rjsf. Can't you do this using CSS?

**Comment by asaf** [comment]
@glasserc And hiding a single element is not? :-)

Anyway I decided to extract a partial json schema out of a larger one at the end, so feel free to close this issue in case it doesn't make sense.

Thanks
