### ISSUE TITLE
Issue when running npm install: missing history

### ISSUE THREAD

**Issue by magopian** [mozilla-services/react-jsonschema-form#55]
node --version: v5.5.0
npm --version: 3.5.3

The error:
```
kinto-admin@0.5.1 /Users/mathieu/mozilla/kinto-admin
├── UNMET PEER DEPENDENCY history@^1.17.0
└─┬ node-fs-extra@0.8.1
  └── rimraf@2.2.8

npm WARN react-router@1.0.3 requires a peer of history@^1.17.0 but none was installed.
```

**Comment by n1k0** [comment]
We should add an explicit npm version in our package.json requirements, eg. `{ "engines" : { "npm" : "^2.14.7" } }`.

**Comment by magopian** [comment]
The issue is caused by npm v3. The solution is to downgrade to npm v2.

Your solution @n1k0 will display a warning (or block the installation if `"engineStrict": true` is added), but only for the installation of the package itself (not of its dependencies, check http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html).

**Comment by n1k0** [comment]
Displaying a warning sounds good enough to me. At list it's properly informative, and so much better than without it.

**Comment by travisdahl** [comment]
Is this still necessary? id rather not downgrade from versions 6 to version 2.
