### ISSUE TITLE
Array : when minItems=1 is specified, the user should not be allowed to removed the array item from the UI

### ISSUE THREAD

**Issue by asifmom** [mozilla-services/react-jsonschema-form#550]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

The UI should honor Array minItems and maxItems.

### Steps to Reproduce

1. On the playground, (https://mozilla-services.github.io/react-jsonschema-form/) select Arrays.
2. Modify the JSON schema fragment as shown below: 
` "type": "object",
  "properties": {
    "listOfStrings": {
      "type": "array",
      "minItems": 1,
      "title": "A list of strings",
      "items": {
        "type": "string",
        "default": "bazinga"
      }
    }`
3. Try deleting the items from the list of strings. You can delete all the items. You should not be able to delete items when the length reaches minItems.

However, you get validation error

**Comment by n1k0** [comment]
This behavior sounds fair to me. Validation happens when you submit the form, except if you enabled the `liveValidate` feature then it's fair to have validation errors while fiddling with the form in real time.

Maybe users want to delete a bunch of stuff to reenter some others. Preventing removing items is more likely to create confusion and/or frustration in my own experience. What's important to me is that we get proper validation when the form is submitted, which works just fine here.

**Comment by asifmom** [comment]
In my current app, we want the behavior of disabling the remove button when minItem is specified. Example when minItem=1 , delete button should be disabled when there is only on array item. Maybe there should one more configurable item in the UI configuration like disableminItemDelete:true. Let me know what do you think? and how to achieve this functionality

**Comment by revolunet** [comment]
One option could be to use CSS to achieve that 

hide the button when only one `.array-item` :

```css
.array-item:nth-child(1):nth-last-child(1) .array-item-remove {
   display:none;
}
```

**Comment by asifmom** [comment]
Actually, this was just one of the example. there are other instances where we have to disable add button when maxItem is specified. I was hoping as I framework, react-jsonschema-form should allow adding this functionality through UI configuration json. Let me know if this make sense from the framework perspective

**Comment by glasserc** [comment]
I agree with @n1k0 -- rjsf doesn't try to prevent the user from entering nonvalidating information, and I don't think it should start here.

**Comment by mfulton26** [comment]
There are some drawbacks to this approach but you can use a fixed `items` with `additionalItems`. Drawbacks include not being able to remove the fixed items nor order them (i.e. `items[0]` will always be `items[0]`).

Example [here](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJwZXJzb25zIjpbeyJuYW1lIjoiTWlja2V5IiwiYWdlIjo0Mn0seyJuYW1lIjoiTWlubmV5IiwiYWdlIjo0MX1dfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJkZWZpbml0aW9ucyI6eyJwZXJzb24iOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImFnZSI6eyJ0eXBlIjoiaW50ZWdlciJ9fX19LCJwcm9wZXJ0aWVzIjp7InBlcnNvbnMiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL3BlcnNvbiJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL3BlcnNvbiJ9fX19LCJ1aVNjaGVtYSI6e319).
