### ISSUE TITLE
Adding a new field in between based upon selected value from dropdown

### ISSUE THREAD

**Issue by roma13121990** [mozilla-services/react-jsonschema-form#551]
Hi,

I need to add a new field dynamically in between, once a specific value from the dropdown(existing field in the form) is selected.
Are there any such examples.Could you please guide me.

**Comment by revolunet** [comment]
maybe this example ? https://jsfiddle.net/69z2wepo/68259/

**Comment by roma13121990** [comment]
I have forked the above fiddle-  https://jsfiddle.net/p1450256/6qrLwjkb/

The task which I need to accomplish is that on selecting "Basic" from role dropdown, another new field should be added just below the role dropdown.

And there should be a state maintained at the same time as we are doing this inside an array.

**Comment by glasserc** [comment]
This sounds like #52, which we don't support right now (although a PR would be interesting).
