### ISSUE TITLE
Custom array item schema

### ISSUE THREAD

**Issue by ssh000** [mozilla-services/react-jsonschema-form#561]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Hello! 
I need help in a couple of questions.
There is an array of the objects with `type` property. Is there a way to change array item `schema` depending on the object `type`? 

### Steps to Reproduce

[Example](https://codepen.io/ssh/pen/qmqGQG?editors=0010)

### Version

`react-jsonschema-form@0.47.0`

**Comment by glasserc** [comment]
Hi, and thanks for your interest! At present, we don't support `anyOf`, which IMHO is the cleanest way to represent that. We're tracking it in #52 in case you would like to contribute a patch!
