### ISSUE TITLE
React PropTypes

### ISSUE THREAD

**Issue by TyFlashDeveloper** [mozilla-services/react-jsonschema-form#563]
Bonjour,

Have you planned to update your files for import PropTypes from "react-proptypes" with React last version, instead of last version, in order not to get warning in browser console ? 

Best regards,

Anthony

**Comment by n1k0** [comment]
It's been addressed in #549 and landed as v0.47.0. Anything we missed?

**Comment by fbessou** [comment]
There are still references to PropTypes from the `react` package in ArrayField.js and ObjectField.js .

**Comment by n1k0** [comment]
Released in [v0.48.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.48.0).
