### ISSUE TITLE
enum based on previously defined array of strings?

### ISSUE THREAD

**Issue by clearly** [mozilla-services/react-jsonschema-form#565]
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description
Is it possible, without any "outside" coding of schema manipulation, to define the elements of an enum to be the values form a previously define array of strings?

**Comment by n1k0** [comment]
No, and we don't have plans for implementing something like this in the near future.
