### ISSUE TITLE
Schemas with Arrays broken in IE

### ISSUE THREAD

**Issue by taroghion** [mozilla-services/react-jsonschema-form#570]
### Description

Rendering arrays throws error in Internet Explorer (tested with IE 11)

### Steps to Reproduce

1. Open the demo page (https://mozilla-services.github.io/react-jsonschema-form/) in IE 11.

#### Actual behavior

In the console an error is thrown: 

> SCRIPT5007: Object Expected
> bundle.js (33,23699)

When trying to use an array in the schema of my own project, I can see this is being caught in the `findSchemaDefinition` function in utils.js and the error message is 

> 'Symbol' is undefined
Looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator it looks as if Symbol.iterator isn't supported in IE.

Would the fix be to polyfill Symbol.iterator?

### Update

I've tried to add the polyfill es6-symbol to my project, but this still does not work.

**Comment by glasserc** [comment]
Hi, sorry for the delay in looking at this! It looks like our `for .. of` loop is being transformed into using `Symbol.iterator`. Yes, I guess polyfilling `Symbol.iterator` should be the fix. Patches welcome. How did you try to add `es6-symbol` to your project?

**Comment by taroghion** [comment]
Thanks for getting back to me. Apologies, I forgot to update this thread, but I managed to get a polyfill working. I ended up adding the Babel polyfill which implements all additional ES6 methods.

**Comment by glasserc** [comment]
Great!

**Comment by dnbr2002** [comment]
Just adding here for clarification because I had the same issue.  You will need the babel-polyfill to resolve the issues with arrays when using this form.  This link will help you get it added to your project.  https://babeljs.io/docs/usage/polyfill/
