### ISSUE TITLE
Updating formData from onChange using safeRenderCompletion does not work

### ISSUE THREAD

**Issue by vamsiampolu** [mozilla-services/react-jsonschema-form#571]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

SSCE: I am providing a [webpack bin as an example](https://www.webpackbin.com/bins/-KjMdh6ZvAN6PZbb2kLl)

### Description

The form in the example is trying to update an input when the value of a select within the form has been updated. I have added safeRenderCompletion prop so that I can return the value from the `onChange` and have it applied as next `state` of the `Form` component.

When I use `onChange` on the `Form`, I check for the value of the select and update formData and return the state of the form, however the state is not updated and remains much the same.

I believe that ObjectField.setPropertyValue might be triggered after the change of the application state in order to override the value I have set for formData.

[Expected Behaviour]

As per my understanding, the state of the `Form` in the example goes from:

```js
{
   note: void 0,
   gender: void 0
}
```

to: 

```js
{
   note: void 0,
   gender: 'male'
}
```

where I return the next state:

```js
{
    note: 'Hey Man',
    gender: 'male'
}
```

[Actual Behaviour]

where I believe Object.setPropertyValue might be taking over:

```js
{
   note: void 0,
   gender: 'male'
}
```

**Comment by vamsiampolu** [comment]
It looks like the library uses `setState` with a callback when `safeRenderCompletion` is set, which looks like:

```js
  if (safeRenderCompletion) {
    instance.setState(state, callback);
  }
```

The React docs suggest that:

There is no guarantee that calls to `setState` will run synchronously,
as they may eventually be batched together.  You can provide an optional
callback that will be executed when the call to setState is actually
completed.

There is another version of setState where:

When a function is provided to setState, it will be called at some point in the future (not synchronously). It will be called with the up to date component arguments (state, props, context). These values can be different from this.* because your function may be called after receiveProps but before shouldComponentUpdate, and this new state, props, and context will not yet be assigned to this.

Is there any reason to prefer the setState with a callback instead of setState with a function in this case?

**Comment by glasserc** [comment]
Hi! Is this related to #513? I don't really understand your webpack bin, it seems like you expect the return value of `onChange` to affect the state of the form, but as far as I can tell, it shouldn't. `formDataProp` seems to be updated correctly and doesn't revert to its old state (I investigated this by adding `formDataProp` to the console.log in Hello.js:81. Is returning a new state from `onChange` a typical React idiom, and why would it update the component's state?

**Comment by vamsiampolu** [comment]
@glasserc I  understood the problem a little better, once I thought about it a little, I felt that it is not  a good idea to be able to hijack another component's `setState` method. I used `setState` on a wrapper component around the Form for changes to `formData` and `uiSchema`
