### ISSUE TITLE
Custom array widget.

### ISSUE THREAD

**Issue by asaf** [mozilla-services/react-jsonschema-form#573]
Hey,

I would like to render a custom component such "multi select component) for a specific array type,
The component would have to know how to generate the  JSON portion for that array,

Does it make sense to skip the complex ArrayField logic and just render a widget in case `ui:widget` is set on the array level? other alternatives?

Thanks.

**Comment by glasserc** [comment]
The current ArrayField implementation doesn't support a custom widget. As far as I can tell from the documentation, widgets are mainly intended for single fields, and arrays are much more complicated than that. It's possible to override ArrayField with your own custom field type using `ui:field`, and I think that's probably the best choice considering how complicated ArrayField is and how many things it supports.

**Comment by asaf** [comment]
@glasserc Thanks, I managed by adding a custom ui:field.

Closing.

**Comment by danrot** [comment]
Is there no plan to support this? I think using a field instead is a bit tedious, since it doesn't show a label by default... And maybe it also skips some other functionality?

**Comment by glasserc** [comment]
Sorry, I don't really understand what support is missing. We don't have any plans to support overriding an "array widget" because handling arrays requires a certain amount of complexity. Could you elaborate on what you have in mind?

**Comment by danrot** [comment]
If you don't plan to support it, that's fine. I just think it's a little bit cumbersome to already implement a custom field for that, because certain features like using a label are then harder than necessary. But I have already decided to solve that in another way anyway.

**Comment by asaf** [comment]
Yea, multi values are tricky as their characteristic vary based on their visual layouts, when it comes to arrays we usually found ourself overriding the entire Field in different ways.

**Comment by glasserc** [comment]
I should also mention that you can override how an array field is rendered by using the ArrayFieldTemplate option described [here](https://github.com/mozilla-services/react-jsonschema-form#array-field-template). Depending on what "Custom array widget" means, that might or might not be suitable for your needs.
