### ISSUE TITLE
Automatically trigger render when uiSchema has changed

### ISSUE THREAD

**Issue by danziamo** [mozilla-services/react-jsonschema-form#585]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hello,
Is it possible to properly handle uiSchema change?
For example, if i click a custom button on a Top form, where i change "ui:readonly" property to true and back, to false.
React locks view only after i try to edit formData, like in this provided example that might be related to my problem
https://jsfiddle.net/69z2wepo/68259/
React doesn't hide textbox when you disable checkbox, it hides it only when you try to input data.

Thank you

**Comment by n1k0** [comment]
You have to put your uiSchema into state.
