### ISSUE TITLE
When the value of an array field is null, an error occurs

### ISSUE THREAD

**Issue by ngduc** [mozilla-services/react-jsonschema-form#592]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When the value of an array field is null, an error occurs:

![image](https://cloud.githubusercontent.com/assets/639189/26516730/105bd4d6-4240-11e7-99d9-31b70394f44a.png)

Code location:
https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/ArrayField.js#L305

### Steps to Reproduce

1. pass formData with an array field's value as null
2. react-jsonschema-form will give that error

#### Expected behavior

null array field value should be transformed to empty array [] to avoid this type of error.

#### Actual behavior

JS error occurred

### Version

v0.48.2

**Comment by LucianBuzzo** [comment]
This appears to no longer be an issue, see [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZXF1ZXN0IjpbbnVsbF19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsicmVxdWVzdCI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIn19fX0sInVpU2NoZW1hIjp7fX0=).
