### ISSUE TITLE
wysiwyg Editor 

### ISSUE THREAD

**Issue by silverboyir** [mozilla-services/react-jsonschema-form#595]
Hi
I'm new in react , how i can use a  wysiwyg editor plugin with this form plugin ?
thanks

**Comment by glasserc** [comment]
Hi @silverboyir, thanks for your interest. Unfortunately we've never used a WYSIWYG editor plugin with this library so we can't really offer guidance on how to do it. We also don't really have a lot of time available to answer React questions. Maybe a better place to go for help would be one of the places shown on https://facebook.github.io/react/community/support.html ? Thanks and good luck :)

**Comment by n1k0** [comment]
As a side note, if what you need is a wysywig editor for some string field, have a look at [custom widgets](https://github.com/mozilla-services/react-jsonschema-form/#custom-widget-components). Basically the idea would be to wrap an existing wysiwyg react component like [quill](https://zenoamaro.github.io/react-quill/) or [ory](https://github.com/ory/editor).
