### ISSUE TITLE
setImmediate is not a function

### ISSUE THREAD

**Issue by eddyzhang1986** [mozilla-services/react-jsonschema-form#597]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

[Description of the bug or feature]

setImmediate is not a function

### Steps to Reproduce

1. [First Step] use chrome run the test

2. [Second Step] setImmediate is not a function
![test123](https://cloud.githubusercontent.com/assets/6470398/26622724/e1ba530a-461d-11e7-851f-d97c6bf843d5.png)

3.  maybe the code setImmediate  should be window.setImmediate
   
![test33](https://cloud.githubusercontent.com/assets/6470398/26623446/4f182c22-4620-11e7-9f42-f6b888ff5dfa.png)

#### Expected behavior

no warnning

#### Actual behavior

setImmediate is not a function

### Version

"react-jsonschema-form": "^0.48.2",
"setimmediate": "^1.0.5",
and I also import "setimmediate";

**Comment by eddyzhang1986** [comment]
![wrong](https://cloud.githubusercontent.com/assets/6470398/26622635/a767c8ea-461d-11e7-9193-ea08959a7c21.jpg)
attache image

**Comment by eddyzhang1986** [comment]
I use the props 'safeRenderCompletion' to fix this problem.
am I right?
any other suggestions?

**Comment by glasserc** [comment]
Hi, thanks for using react-jsonschema-form. `safeRenderCompletion` is mainly meant for use in testing. I don't think that's the right fix.

What version of Chrome are you using? Do you see the problem on the [playground](https://mozilla-services.github.io/react-jsonschema-form/), or just in your app? I don't see this bug, even using Chrome (I'm using 56.0.2924.87).

**Comment by eddyzhang1986** [comment]
@glasserc  sorry for  relay delay,
My chrome version is  58.0.3029.110 (64-bit),
this problem seems only apear on this version,

let me show you a live demo,
By the way, the offical demo does not apear this problem.


thank you very much for support me.

**Comment by eddyzhang1986** [comment]
Hi, @glasserc  
This is my repo https://github.com/eddyzhang1986/antd-jsonschema-form
This is my demo https://eddyzhang1986.github.io/antd-jsonschema-form/
I do noting with this project
Then I get this problem .

**Comment by n1k0** [comment]
Even in Chrome and Firefox, your demo gives this error in the console when entering a value in the input text field:

> Uncaught TypeError: setImmediate is not a function

It seems this bug is related with the way you're building your code.

**Comment by eddyzhang1986** [comment]
@glasserc @n1k0 
I have solved this problem.
I use these webpack config code 

  externals: {
    react: {
      root: "React",
      commonjs: "react",
      commonjs2: "react",
      amd: "react"
    }
  },

to splice react lib from the "bundle.js"
and than this problem disapear.

**Comment by n1k0** [comment]
I don't have a clue why declaring react as an external dependency solves this specific issue, but it makes sense overall. I have a hunch this is really related to webpack and its expectations, not really rjsf, so I'm gonna close this issue. But please reopen if you think there's a bug we can fix here.

**Comment by eddyzhang1986** [comment]
@n1k0  OK, Thanks a lot for your help.
