### ISSUE TITLE
Question: hide/show functionality for large forms?

### ISSUE THREAD

**Issue by gdbassett** [mozilla-services/react-jsonschema-form#598]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I have a rather large schema (roughly 150 potential values to input).  Is it possible to condense the form in either an accordion or a hide/show manner to make navigation easier?  Is this something that could be added to a form generated with the existing library or would the library itself require updating?

**Comment by glasserc** [comment]
Hi, thanks for your question. #304 was meant to allow use cases like this but I don't really know what is possible using existing libraries or what you would need to do to use them together with RJSF.

**Comment by glasserc** [comment]
See also https://github.com/mozilla-services/react-jsonschema-form/issues/268, which I finally just found again.

**Comment by acouch** [comment]
It would be awesome if this could be included in UISchema. Maybe ``ui:order`` could contain a grouping field so you could do something like:

```yml
ui:order:
- field1
- field2
  group:
    - field 3
    - field 4
- field5
```

If this is something the maintainers would accept I could take a crack at it.

**Comment by EvertLagerberg** [comment]
@glasserc How would I use Field Template to achieve this?

**Comment by gdbassett** [comment]
I'm in the same boat as @EvertLagerberg.  I don't know how to use Fix #284 to collapse empty sections and ignore required fields in them.  I had expected https://github.com/mozilla-services/react-jsonschema-form/pull/542 would address it, but it still seems to be pending feedback from the author.  If it's possible to address this with #284, it may be helpful if someone can document a quick blog post or such showing how to do it.

**Comment by glasserc** [comment]
There's no specific setting or configuration that #304 permits. However, with your own field template, you can write any kind of HTML you like, including one that collapses according to user input. If someone took the time to do this, an example in the docs would be great!

**Comment by fantapop** [comment]
@EvertLagerberg were you able to acheive this yet?

**Comment by loganvolkers** [comment]
@fantapop Here's an example using a custom `ObjectFieldTemplate`: https://codesandbox.io/s/0y7787xp0l

**Comment by fantapop** [comment]
Thank you for taking the time to put that together!

**Comment by neilyoung** [comment]
@fantapop Looks good, but produces tons of warnings, mostly because of this:

index.js:1449 Warning: Each child in an array or iterator should have a unique "key" prop.

**Comment by fantapop** [comment]
@neilyoung maybe you meant to tag @loganvolkers

**Comment by neilyoung** [comment]
@fantapop Right, sorry, fixed

**Comment by loganvolkers** [comment]
Thanks for pointing that out @neilyoung.

Feel free to contribute a forked version. The example I shared was proof of
concept, not production supported code, so even if I patch that, there may
be other things that affect it, especially considering the high rate that
the ObjectFieldTemplate API is being updated.

Good luck!

**Comment by neilyoung** [comment]
Long time ago, but I found an easier way by utilising `react-jsonschema-form-extras`.

https://codesandbox.io/s/bold-williamson-23hwo

HTH

**Comment by vhcoder** [comment]
Hello we looked at both these options.... we cannot find a way to support dependencies. Does anyone have an example for this? 
Thanks.
VRH
