### ISSUE TITLE
ErrorSchema in a UI Field manipulation

### ISSUE THREAD

**Issue by wilsonsergio2500** [mozilla-services/react-jsonschema-form#603]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

How do I set the errorSchema of a UI field, say for instance if I would like to have a custom error in the ui: field level or a custom validation. I notice that I do have access to this object errorSchema.

### Steps to Reproduce

1. Create ui:field
2. Wire an on change event say for a given input field or custom component.
3. Set the validate of this component to false this.props.onChange(value, {validity: false })
4. Populate an erroSchema specific to this field if an internal validation occur
5. Clear erroSchema if no error occured

#### Expected behavior

Errors in the ui schema to be present on validation or in the error list of  my form component.

#### Actual behavior

I do understand that I could pass the validate to the form component. However, I was hoping to have the error more contextual to the ui:field level. This way I could bring as many ui field components as desired and impel cohesive validation behavior across the application.

### Version

Current

**Comment by wilsonsergio2500** [comment]
So this is what I ended up doing. Hope that It helps some one if they would like to follow this approach

- create a list of validators  in the properties level at the schema
- wrap the form into a component and access the schema
- Iterate through the validators and enforce validation

So in the schema we end up with something like
```
properties: {

            email: {
                title: 'Email',
                type: 'string',
                validators: [{
                    validate: (value: string) => {
                        return Helpers.ValidateEmail(value);
                    } ,
                 message : 'email invalid'
             }]
```
And.. in the form wrapper

```
validatorWrapper(props: any, errors: any) {

        let schemaprops = (this.props.schema.properties as any[]);

        for (let propItem in schemaprops) {
            let obj = schemaprops[propItem];
            let validators = (obj.validators as any[]);
            if (!!obj.validators && validators.length > 0) {
                validators.forEach((item: any, index) => {

                    let value = props[propItem];
                    let IsValid = item.validate(value);

                    if (IsValid == false) {

                        errors.addError(item.message); 
                       
                    }

                });

            }
        }

        return errors;

       
    }
```
Thus, 

` <Form schema={this.props.schema} uiSchema={this.props.uiSchema} validate={this.validatorWrapper.bind(this)} ...`

What I like about this approach is that it emulates angular-formly, where a custom validation could be specified at the property level of the json declaration

**Comment by glasserc** [comment]
I'm glad you could find a way to solve your problem. Unfortunately, JSON Schema doesn't support the definition of arbitrary validations at arbitrary levels of the schema, so we aren't really interested in supporting this use case explicitly. Thanks for documenting your solution!

**Comment by amitvchaudhary** [comment]
Hi @glasserc , How to have custom message at field level?

I want to pass custom errors for each field separately in the schema. For example, I have 3 fields:

Textbox: First Name (Required msg: Please enter the first name)
Textbox: Last Name (Required msg: Please enter the last name)
Selectbox: No. of Employees (Required msg: Please select the value) 

As you can see, I have different controls and I need separate custom messages for 'required' validation.

Any suggestions?

**Comment by jonra1993** [comment]
Hello @glasserc did you find a solution. I am trying to use this lib with material ui in multi-language. But the default validation language is always in english.

**Comment by epicfaace** [comment]
You can use `transformErrors` for this purpose: see https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#custom-error-messages
