### ISSUE TITLE
Bug: "ui:emptyValue": "" defeats setting a field as required

### ISSUE THREAD

**Issue by bebbi** [mozilla-services/react-jsonschema-form#605]
### Description

Setting `"ui:emptyValue": ""` for a string type entry in the UISchema makes an empty string fail to trigger a validation error even if it's in the `required` list of the JSONSchema.
But a value of "" does not fulfill the 'required' condition.

[Description of the bug or feature]

### Steps to Reproduce

1. Go to playground https://mozilla-services.github.io/react-jsonschema-form/
2. Remove Chuck. Nothing happens.
3. Add first name again.
4. Remove the line `"ui:emptyValue": ""` in the UISchema, first name.
5. Remove Chuck, a warning will display.
#### Expected behavior

Step 2. triggers error.

#### Actual behavior

Step 2 no error.

### Version

as deployed to playground tonight.

**Comment by glasserc** [comment]
This is the intended behavior of `emptyValue` -- see https://github.com/mozilla-services/react-jsonschema-form/pull/539. What is your use case?

**Comment by bebbi** [comment]
I don't worry about empty string vs undefined so much at this stage.
But the demo strikes me as having a bug: I can't see a why a string field that looks empty (and in fact even seems to represent an empty string) wouldn't fail a validation for being a required field.
But that's what firstName behaviour seems to be in the demo.
I don't see an explanation for this in the referenced ticket - if there is one, it seems counter-intuitive at least?

**Comment by glasserc** [comment]
`required` doesn't check whether the string has contents, only whether it's present or not. Without `emptyValue`, we interpret an empty input field as a missing field. With `emptyValue`, we interpret an empty input field as the empty string `""`. Only the first will fail `required`. Some use cases want an empty string to fail `required` and some want it to be substituted with an empty string, so `emptyValue` lets the programmer distinguish the two (apparently identical from the HTML/user perspective) cases.

I'm sure the documentation is lacking here, so if you have ideas on how to improve it, feel free to send a PR!

**Comment by bebbi** [comment]
Thanks for the clarification!
