### ISSUE TITLE
New package to make react-jsonschema-form collaboratively editable with ShareDB

### ISSUE THREAD

**Issue by houshuang** [mozilla-services/react-jsonschema-form#608]
_Apologies for posting here, but I did not know where else, and I hope the community will find this useful._ 

As part of our project to build a platform for authoring collaborative learning exercises [FROG](https://github.com/chili-epfl/FROG), we had the need for **collaboratively editable forms**. We use react-jsonschema-forms very extensively in our tool, and we were lucky enough to find a student (Dario Anongba) who wanted to work on making R-JS-F work with collaborative editing, using ShareDB. This will be integrated in our tool, but he's also released his work as an independent package, [collab-react-components](https://github.com/chili-epfl/collab-react-components) (which also includes easy React components for collaborative text area and Quill editor). 

We hope this would be useful to the community, and would love feedback about the API design, the implementation etc. I also wanted to express my appreciation of the R-JS-F community, the tool is amazingly helpful to us, and the design means that we were able to plug true collaborative editing into a great tool, instead of building a half-baked form generator ourselves.

Would it make sense to link to this package from somewhere, like the wiki?

**Comment by glasserc** [comment]
That sounds really cool! I don't have the time or the expertise to provide feedback on the design, but I think we should absolutely link to it from the wiki and maybe even the README.

**Comment by revolunet** [comment]
Thanks for sharing these awesome projects !

maybe the occasion to add a "related projects" section to the README ?

**Comment by epicfaace** [comment]
It doesn't look like https://github.com/chili-epfl/collab-react-components is actively under development at this point, but we definitely should add a section for "related projects."
