### ISSUE TITLE
FormData Nested Property - Want to display more than one property on Field Template

### ISSUE THREAD

**Issue by razazaidisd** [mozilla-services/react-jsonschema-form#609]
I know this is an enhancement, if anyone can help me on this I will be really thankful.

### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing an [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
I have a formData with Nested Properties, wanted to render a flag beside each Input field. 

![react-jsonschema form issue](https://user-images.githubusercontent.com/6624130/26981439-7b14619e-4d35-11e7-8d50-f7bea0998875.png)

As you can see above I have 3 values, one Input value, second flag and third is language.

### Steps to Reproduce
Ideally, I'm providing a [sample JSFiddle](
https://jsfiddle.net/razazaidisd/bw0ffnz4/12/) 

#### Expected behavior
Form Component should accept nested property Object, would be great to have the ability to show multiple values from that Object.

#### Actual behavior
Error: **Invalid nestedProp object field configuration: Cannot convert undefined or null to object**

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by glasserc** [comment]
Your `age` schema is type `object` but has no `properties`, which react-jsonschema-form doesn't know how to handle.
