### ISSUE TITLE
How to use nested attributes

### ISSUE THREAD

**Issue by sunnybogawat** [mozilla-services/react-jsonschema-form#610]
I want to create a form which would give the formdata in following format. 
```json
{
	"request": {
		"unit": {
			"name": "example123.com",
			"extensible_attributes": {
				"customername": "sample customer",
				"customerguid": "123",
				"Unit_Type": "xyz"
			},
			"ns_group": "",
			"email": "ddd@fff.com"
		},
		"notes": [{
			"body": "sssssssss"
		}],
		"requester": {
			"firstname": "firtname",
			"lastname": "lastname",
			"email": "user@email.com"
		},
		"customer_guid": "123"
	}
}
```

Is there any documentation to create a nested form?

**Comment by LucianBuzzo** [comment]
@sunnybogawat This is just a case of constructing the corresponding JSON schema - this should work in your case:
```json
{
  "type": "object",
  "properties": {
    "request": {
      "type": "object",
      "properties": {
        "unit": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "extensible_attributes": {
              "type": "object",
              "properties": {
                "customername": {
                  "type": "string"
                },
                "customerguid": {
                  "type": "string"
                },
                "Unit_Type": {
                  "type": "string"
                }
              }
            },
            "ns_group": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            }
          }
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "body": {
                "type": "string"
              }
            }
          }
        },
        "requester": {
          "type": "object",
          "properties": {
            "firstname": {
              "type": "string"
            },
            "lastname": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            }
          }
        },
        "customer_guid": {
          "type": "string"
        }
      }
    }
  }
}
```

See [this playground link ](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZXF1ZXN0Ijp7InVuaXQiOnsibmFtZSI6ImV4YW1wbGUxMjMuY29tIiwiZXh0ZW5zaWJsZV9hdHRyaWJ1dGVzIjp7ImN1c3RvbWVybmFtZSI6InNhbXBsZSBjdXN0b21lciIsImN1c3RvbWVyZ3VpZCI6IjEyMyIsIlVuaXRfVHlwZSI6Inh5eiJ9LCJuc19ncm91cCI6IiIsImVtYWlsIjoiZGRkQGZmZi5jb20ifSwibm90ZXMiOlt7ImJvZHkiOiJzc3Nzc3Nzc3MifV0sInJlcXVlc3RlciI6eyJmaXJzdG5hbWUiOiJmaXJ0bmFtZSIsImxhc3RuYW1lIjoibGFzdG5hbWUiLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIn0sImN1c3RvbWVyX2d1aWQiOiIxMjMifX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJyZXF1ZXN0Ijp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVuaXQiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImV4dGVuc2libGVfYXR0cmlidXRlcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJjdXN0b21lcm5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJjdXN0b21lcmd1aWQiOnsidHlwZSI6InN0cmluZyJ9LCJVbml0X1R5cGUiOnsidHlwZSI6InN0cmluZyJ9fX0sIm5zX2dyb3VwIjp7InR5cGUiOiJzdHJpbmcifSwiZW1haWwiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImVtYWlsIn19fSwibm90ZXMiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYm9keSI6eyJ0eXBlIjoic3RyaW5nIn19fX0sInJlcXVlc3RlciI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJmaXJzdG5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJsYXN0bmFtZSI6eyJ0eXBlIjoic3RyaW5nIn0sImVtYWlsIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJlbWFpbCJ9fX0sImN1c3RvbWVyX2d1aWQiOnsidHlwZSI6InN0cmluZyJ9fX19fSwidWlTY2hlbWEiOnt9fQ==) for a working example.
