### ISSUE TITLE
Unsupported field schema

### ISSUE THREAD

**Issue by gastonche** [mozilla-services/react-jsonschema-form#611]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

I am trying to generate forms for a schema onthe playground but i keep getting an error, and I am unable to solve the error. The schema is tested valid on jsonschemalint.com the error i get is 
```javascript
Unsupported field schema { "definitions": { "address": { "type": "object", "properties": { "street_address": { "type": "string" }, "city": { "type": "string" }, "state": { "type": "string" } }, "required": [ "street_address", "city", "state" ] } }, "allOf": [ { "$ref": "#/definitions/address" }, { "properties": { "type": { "enum": [ "residential", "business" ] } } } ] }.
```

the json I am trying to use is 
```javascript
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }
  },
  "allOf": [
    {
      "$ref": "#/definitions/address"
    },
    {
      "properties": {
        "type": {
          "enum": [
            "residential",
            "business"
          ]
        }
      }
    }
  ]
}
```
I don't understand what is wrong. I intend to use this library for my project
### Steps to Reproduce

1. visit [https://mozilla-services.github.io/react-jsonschema-form/](https://mozilla-services.github.io/react-jsonschema-form/)
2.enter the obove schema in place of the json schema
3.replace the ui-schema and formData contents with { }

Ideally, I'm providing a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJhZGRyZXNzIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InN0cmVldF9hZGRyZXNzIjp7InR5cGUiOiJzdHJpbmcifSwiY2l0eSI6eyJ0eXBlIjoic3RyaW5nIn0sInN0YXRlIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInN0cmVldF9hZGRyZXNzIiwiY2l0eSIsInN0YXRlIl19fSwiYWxsT2YiOlt7IiRyZWYiOiIjL2RlZmluaXRpb25zL2FkZHJlc3MifSx7InByb3BlcnRpZXMiOnsidHlwZSI6eyJlbnVtIjpbInJlc2lkZW50aWFsIiwiYnVzaW5lc3MiXX19fV19LCJ1aVNjaGVtYSI6e319) demonstrating the issue.

#### Expected behavior

I expected the playground to generate forms from the schema

#### Actual behavior

Gives this error instead:
```
Unsupported field schema { "definitions": { "address": { "type": "object", "properties": { "street_address": { "type": "string" }, "city": { "type": "string" }, "state": { "type": "string" } }, "required": [ "street_address", "city", "state" ] } }, "allOf": [ { "$ref": "#/definitions/address" }, { "properties": { "type": { "enum": [ "residential", "business" ] } } } ] }.
```

**Comment by tappleby** [comment]
I ran into this issue as well, it was caused by the enum definition without a `"type": "string"` set, looks like its a known issue: #66.

**Comment by epicfaace** [comment]
@gastonche It looks like the problem is that you are trying to use `allOf`, while `allOf` is not supported by this library yet. Tracking progress on that in #52.
