### ISSUE TITLE
uiSchema: "ui:title" does not work for all widget/field types

### ISSUE THREAD

**Issue by Michall** [mozilla-services/react-jsonschema-form#615]
### Description
Basically the basic behavior of customizing generated labels seems to not work well.
"ui:title" in uiSchema does not work consistently for all types (namely boolean, custom components, titles of array and object)

Am I missing something?

Example:
https://jsfiddle.net/f2y3fq7L/34/

#### Expected behavior

uiSchema { prop { "ui:title": "Some Custom Title" } } should change the label text for all default and custom components, and for object and array
#### Actual behavior

uiSchema { prop { "ui:title": "Some Custom Title" } } does not show custom title for custom components, and for default components, and for title of object and array

### Version
^0.48.2

**Comment by bebbi** [comment]
I've just come across the same issue. It looks like this was implemented in #587 but only for `SchemaField` and none of the others.
I just worked on a PR that I will reference here for ObjectField, but I'm an absolute beginner on this lib and not sure what I'm doing, I hope someone with more experience can check the PR and take this over for the remaining fields?

**Comment by bebbi** [comment]
cc @stepek and @n1k0

**Comment by n1k0** [comment]
Close dby #619.
