### ISSUE TITLE
Feature Request: Set Default Boolean Widget

### ISSUE THREAD

**Issue by narthollis** [mozilla-services/react-jsonschema-form#620]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

It would be very useful to be able to change the default widget type for boolean fields.
Currently boolean fields default to `checkbox` which is fine, other than that with html5 validation enabled, you can no submit a form with unchecked requried `checkbox`s.

This feature would provide some mechanism to change the default widget value at a form level. 

### Version
0.49.0

**Comment by narthollis** [comment]
For anyone else looking for something like this, my current work arround follows:
```javascript
const uiSchema = {};
 for (const propertyName of Object.keys(schema.properties)) {
        const property = schema.properties[propertyName];

        if (property.type === 'boolean') {
            uiSchema[propertyName] = { 'ui:widget': 'radio' };
        }
    }
```

**Comment by knilink** [comment]
[Customizing the default fields and widgets](https://github.com/mozilla-services/react-jsonschema-form#customizing-the-default-fields-and-widgets)

So, it can be

```jsx
import RadioWidget from 'react-jsonschema-form/lib/components/widgets/RadioWidget';
function render() {
  return <Form
             widgets={{CheckboxWidget:(props)=>console.log('These are built-in widgets you can override:',Object.keys(props.registry.widgets)) || <div>
               <label className="control-label" htmlFor={props.id}>{props.label}</label>
               <RadioWidget {...props}/>
             </div>
               }}
             ...
         />
}
```

**Comment by sbusch** [comment]
This issue could be closed IMO

**Comment by domharrington** [comment]
I solved this for nested properties by overriding the SchemaField and adding a custom schema field which modifies `ui:widget` on the fly if it comes across a boolean:

```js
const React = require('react');
const PropTypes = require('prop-types');

const BaseSchemaField = require('react-jsonschema-form/lib/components/fields/SchemaField').default;

function SchemaField(props) {
  if (props.schema.type === 'boolean') {
    props.schema.enumNames = ['true', 'false'];
    return <BaseSchemaField {...props} uiSchema={{ 'ui:widget': 'select' }} />;
  }
  return <BaseSchemaField {...props} />;
}

SchemaField.propTypes = {
  schema: PropTypes.shape({
    type: PropTypes.string,
    enumNames: PropTypes.array,
  }).isRequired,
};

module.exports = SchemaField;
```

```jsx
<Form
  fields={{
    SchemaField,
  }}
/>
```
