### ISSUE TITLE
Bug in native datetime widget in playground

### ISSUE THREAD

**Issue by mplis** [mozilla-services/react-jsonschema-form#622]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

There are two bugs:
1. The native datetime widget alters the displayed time after it's completely filled out
2. After the native datetime widget is filled out, attempting to alter the time results in unusual behavior. For example, if attempting to increment the hour by 1, it instead increments by 5.

It appears that once the datetime widget is filled out or altered, the datetime is immediately cast to UTC (which is expected per #496), but the date and time in the widget are not shown in local time, causing unexpected behavior.

### Steps to Reproduce

1. Open [playground](https://mozilla-services.github.io/react-jsonschema-form/) and go to "Date & time" tab
2. Fill out the native datetime widget and notice that the time jumps several hours once you fill out all parts of the widget
3. Attempt to alter the time and notice that the displayed time isn't what you expect

#### Expected behavior

Date and time in the native datetime widget should be displayed in the user's local time.

#### Actual behavior

Date and time in the native datetime widget are being displayed in UTC.

### Version

Whatever version is in the playground

Chrome: v59.0.3071.109

My current timezone is EST.

**Comment by jeromenerf** [comment]
Same problem here. 

Defaulting to "alt-datetime" format as a workaround for now.

**Comment by mmmveggies** [comment]
Quite unfortunate as this bug makes `datetime-local` unusable.

[`fromJSONDate`](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/DateTimeWidget.js#L4-L6) is incorrectly returning a GMT string for to the `value` property should be the local interpretation, something akin to
```js
const pad = (p, n) => String(n).padStart(p, 0)

function fromJSONDate(jsonDate) {
  if (!jsonDate) {
    return ''
  }

  // required format of `"yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS"
  // this should be in the format of *local* time, not GMT

  const date = new Date(jsonDate)

  const yyyy = pad(4, date.getFullYear())
  const MM = pad(2, date.getMonth() + 1)
  const dd = pad(2, date.getDate())
  const hh = pad(2, date.getHours())
  const mm = pad(2, date.getMinutes())
  const ss = pad(2, date.getSeconds())
  const SSS = pad(3, date.getMilliseconds())

  return `${yyyy}-${MM}-${dd}T${hh}:${mm}:${ss}.${SSS}`
}

// paste in console to test
const jsonDate = new Date().toJSON()
console.log(jsonDate)
console.log(fromJSONDate(jsonDate))
```
