### ISSUE TITLE
Change the UI lib Bootstrap to another

### ISSUE THREAD

**Issue by rafaelmaruta** [mozilla-services/react-jsonschema-form#626]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

There was another topic about but it was closed. I'd like to use another UI lib, the [https://ant.design/](https://ant.design/). How can I replace Bootstrap? The Ant Design has its owns components.

**Comment by eddyzhang1986** [comment]
I'm developing a lib what you want,but I haven't finished it yet.are you interesting with my project
https://github.com/eddyzhang1986/antd-jsonschema-form

**Comment by rafaelmaruta** [comment]
Perfect!

**Comment by divan** [comment]
I'm also interested in using Gridforms UI for this project. If anyone working on it, please post it here.

**Comment by asifmom** [comment]
@eddyzhang1986 why a separate project? Can't we have a pluggable ui library in react-json-form?

**Comment by n1k0** [comment]
@asifmom we can if you contribute it, thanks

**Comment by ShawnShiFan** [comment]
combine material-ui ？

**Comment by epicfaace** [comment]
There is now a way to include custom themes -- see #1222
