### ISSUE TITLE
Pattern on readme issue

### ISSUE THREAD

**Issue by davesierra** [mozilla-services/react-jsonschema-form#628]
In readme section 'Custom error messages' the pattern validation example doesn't seem to work.
`pattern: "\d*"`
Still allows me to submit with letters, etc.

I googled another example and this works: 
`pattern: "\^(0|[1-9][0-9]*)$",`

Here's a fiddle (original forked from [revolunet](https://jsfiddle.net/user/revolunet/fiddles/)):
https://jsfiddle.net/wknpLkmn/

**Comment by n1k0** [comment]
From my tests, the right pattern to use is `"^\\d*$"`, which also means categories need to be double-escaped. Would you mind updating the docs with these information? Thanks!
