### ISSUE TITLE
Removing properties from schema (as demonstrated in "conditional fields" example) does not remove field from rendered form

### ISSUE THREAD

**Issue by LyraelRayne** [mozilla-services/react-jsonschema-form#638]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Removing a property from (a clone of) the schema does not remove the field from the form

### Steps to Reproduce

1. Open the "conditional fields" example linked to from the project page (https://jsfiddle.net/69z2wepo/68259/)
2. Tick the box to cause the "Name" field to be displayed
3. Untick the box

#### Expected behavior

The name field should disappear

#### Actual behavior

The name field doesn't disappear

### Version

0.49.0

**Comment by Natim** [comment]
I guess it is because you are adding it if it is `checked` but no removing it if it is `unchecked`.

**Comment by Natim** [comment]
See https://jsfiddle.net/69z2wepo/83017/

**Comment by LyraelRayne** [comment]
I didn't write the code, it's an example from https://github.com/mozilla-services/react-jsonschema-form#tips-and-tricks (so I presumed that it was meant to work as-is).

The code example does actually remove them, but it does it by mutating the schema.properties instead of replacing it with a modified clone. 

https://jsfiddle.net/69z2wepo/83018/ is a working version of the original example. I would suggest that you guys update the example link to the fixed version.

**Comment by Natim** [comment]
@LyraelRayne would you like to send a pull-request with that modification?

**Comment by LyraelRayne** [comment]
I'm not really sure how to go about that (never done one on github). Do I have to make a fork or something?

**Comment by LyraelRayne** [comment]
Quick question: Do I have to keep the fork around once the pull request is merged?

**Comment by Natim** [comment]
Nope :)

**Comment by LyraelRayne** [comment]
Thanks. That was all a lot less scary than it seemed ;)
