### ISSUE TITLE
multipleof not working for updown widget

### ISSUE THREAD

**Issue by adarshks** [mozilla-services/react-jsonschema-form#639]
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

I want to set the number to increment and decrement by 2 , and i set it in the multipleof atribute in the uischema, but it still changes by 1, can anybody help me, please.. 

[Description of the bug or feature]

### Steps to Reproduce

This is the uischema i used
Id:{
            "ui:widget": "updown",
            "multipleof":2,
        },

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

Value should change by 2

#### Actual behavior

Value changes by 1 in the default format

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by n1k0** [comment]
These constraints must be expressed in the schema, not the uiSchema https://github.com/mozilla-services/react-jsonschema-form#for-number-and-integer-fields
