### ISSUE TITLE
Passing onChange event to select input?

### ISSUE THREAD

**Issue by mishingo** [mozilla-services/react-jsonschema-form#641]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Im looking to pass an onChange event to a specific select input (enum). I checked out the custom widget but it doesn't support the input. What options do I have at the moment?

### Version

0.49.0

**Comment by asmirnov69** [comment]
I also get to situation when I need to be able to have onChange event specific to input element.
E.g:
```
let form_schema = {
    title: "Test",
    type: "object",
    properties: {
        t_choice: {type: "string", enum: undefined, enumNames: undefined, default: undefined, element_onChange: (e) => {console.log("custom onChange:", e)}},
    }
};
```

It looks like trivial change in the code of SelectWidget.js will do the trick:

```
      onChange: function onChange(event) {
        var newValue = getValue(event, multiple);
        _onChange(processValue(schema, newValue));
          if (schema.element_onChange) {  // N.B: my addition is this if and call of element_onChange
              schema.element_onChange(newValue);
          }
      } },
```

**Comment by glasserc** [comment]
If I understood correctly your proposed change @asmirnov69, it would involve adding an `element_onChange` property to a schema, even though this property is not supported by JSON Schema. For this reason I'm not excited about it.

@mishingo, no, we do not support any per-field `onChange`. We only support `onChange` on the form itself. Perhaps you could use that to detect changes in the field you care about, and do something with it?

**Comment by rambabusaravanan** [comment]
`onChange` function provides formdata. But it would be good if I get the element that caused the change as second param. In case we need to perform some actions on change of particular element, we could not find a way.

Scenario: upon autocomplete (our custom component) selection, the selected id needs to be set to next input element.

One may can suggest to set formData onChange as below, but this will cause re-render entire component for every data change in the form. I expect the below should happen only upon name change.
```jsx
handleChange({formData}) {
  formData.userId = getUserIdByName(formData.name);
  this.setState({ formData }); // I want this only upon name change
}

render() {
  return <Form schema={this.schema}
    formData={this.state.formData}
    onChange={this.handleChange} />
}
```

@glasserc @mishingo @asmirnov69 can you please suggest any way to implement my scenario?

**Comment by gr8pathik** [comment]
@rambabusaravanan We are also facing the same issue. Did you found any solution for this?

**Comment by rambabusaravanan** [comment]
Currently no.

Wondering whether this popular library has no such feature which is mostly used or like I'm unaware.

**Comment by HongwooKim** [comment]
No onChange support for per field ?
