### ISSUE TITLE
Question - how do i add a plain div with text in the form?

### ISSUE THREAD

**Issue by chrisjlee** [mozilla-services/react-jsonschema-form#647]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

How would one just add a plain div in my form that is connected to the redux store (that isn't the title and description defined in the json file)? Or say i wanted to have the route parameter injected into the form template?

e.g. `<div>hello {match.params.id}</div>`

Is the best approach is to modify use a custom template itself ?

**Comment by spacebaboon** [comment]
It's a bit of a hack, but I did this by having an empty object in the form schema, with a matching custom field type in the uiSchema which renders the div. 

form schema:
```
...
"Information": {
                "type": "object",
                "properties": {}
              }
...
```
ui schema:
```
...
 "Information": {
                "ui:field": "markupBlock",
                "webStringKey": "info.markup.block"
              }
...
```

webStringKey is a key in a message bundle with the div contents.

**Comment by chrisjlee** [comment]
Does the webStringKey allow for react elements to be passed in? (from your example, it doesn't so far).

**Comment by spacebaboon** [comment]
@chrisjlee you're right - we use it just for rendering some markup that we pull out of a message bundle. A message bundle is just a file with a bunch of key=value entries that we use to internationalise the content. the server sends the files we need based on chosen language. the value in this case is the HTML markup to be displayed.

I think your custom field could receive an identifier for the React elements - i.e. JSX (?) - in your Redux store and just put into the field's render method.

**Comment by adamcbuckley** [comment]
For anyone else coming here from Google, this is my example working of how to add paragraph text to Reach JSON Schema Form.

### JSON Schema
```
{
  "title": "My form title",
  "description": "My form description",
  "type": "object",
  
  "properties": {
    "para1": {
      "type": "object",
      "properties": {}
    },
    "para2": {
      "type": "object",
      "properties": {}
    }
  }
}
```

### UI Schema
```
{
  "para1": {
    "ui:title": "",
    "ui:description": "Hello world!"
  },
  "para2": {
    "ui:title": "",
    "ui:description": "How you all doing?"
  }
}
```
