### ISSUE TITLE
max and min for dates

### ISSUE THREAD

**Issue by simakwm** [mozilla-services/react-jsonschema-form#656]
How do I set min and max props for date fields?
I'd like to use live validation for it.

**Comment by joshourisman** [comment]
I was able to do it by creating a custom widget component to use. In my case, I have a form in which the user is entering travel dates, so it's necessary that those dates be in the future. So I have this widget:

```
const TravelDateWidget = props =>
  <BaseInput
    type="date"
    min={moment().format('YYYY-MM-DD')}
    {...props}
    onChange={value => props.onChange(value || undefined)}
  />;

TravelDateWidget.propTypes = {
  onChange: PropTypes.func.isRequired,
};
```

which I then assign to my uiSchema object:

```
      Object.assign(uiSchema, {
        travelStartDate: {
          'ui:widget': TravelDateWidget,
        },
      });
```

It gets the job done, though there may be a better way…

**Comment by simakwm** [comment]
@joshourisman This will do the trick for me. Thanks a lot.

**Comment by donalmurtagh** [comment]
@joshourisman is there any chance you could make a jsfiddle demo of this?
