### ISSUE TITLE
ui:title not working for objects

### ISSUE THREAD

**Issue by paulinate** [mozilla-services/react-jsonschema-form#665]
Hi!

First of all, thank you for this great library :)
I am migrating an old angular project that was using https://github.com/json-schema-form/angular-schema-form which is a similar project as this one.

So far so good, I really liked the power we have in order to customize things with react-jsonschema-form. Only thing I've been unable to do so far is making the titles of object types work properly. My use case is as follows. 

I do not want to specify a 'title' property into my schema objects, as I expect to reuse the same schema with multiple styling options (uiSchema) so the titles of objects may change. I thought that I could use the 'ui:title' option, but it seems this is only working for labels, not for 'legends' which is the case with objects. So I then tried to use a Custom Title Field, but the props do not have uiSchema being passed on, so I couldn't find a way to fetch the proper 'ui:title: from there.

Am I missing something, or this is just something that is not supported for the time being?
Thanks!

**Comment by n1k0** [comment]
Fixed by #676

**Comment by paulinate** [comment]
Great, many thanks! :+1:
