### ISSUE TITLE
missing "prop-types" module issue

### ISSUE THREAD

**Issue by gusberry** [mozilla-services/react-jsonschema-form#667]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Using library in a project with **react version lower then 15.5** and **no prop-types** results in a missing module error

#### Expected behavior

`prop-types` is listed in `dependencies` or in `peer-dependacies`

#### Actual behavior

`prop-types` is listed in `devDependencies`

### Version

0.47.0

**Comment by n1k0** [comment]
Ah indeed, could you please update the package.json file to move it accordingly and send a PR? Thanks!

**Comment by gusberry** [comment]
so looks like the issue is fixed in 0.49
closing it, sorry
