### ISSUE TITLE
onSubmit return initial formdata

### ISSUE THREAD

**Issue by vincentlee248** [mozilla-services/react-jsonschema-form#672]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
I am trying to use onSubmit prop but i found out that the formdata passed in as an arg is the initial formdata. And the status is set to be initial instead of submitted. Wonder where i did wrong. below is the code example 

```js
onSubmit={(formData) => {
  this.save(formData);
}
```

### Steps to Reproduce

1. use onSubmit and pass a call back to it
2. console log the formdata
3. it's the same as initial one, no change being updated accordingly

#### Expected behavior

return the data with change
#### Actual behavior
return data with no change applied

### Version
latest version

**Comment by n1k0** [comment]
Can't reproduce, could you please try to update [this jsfiddle](https://jsfiddle.net/n1k0/f2y3fq7L/) to demonstrate the issue? thanks.

**Comment by vincentlee248** [comment]
I guess you can close the issue. Can't really reproduce on jsfiddle I am using redux on my porject. I guess that might be the problem.But i am seeing the correct behavior on onChange prop. Anyway, thank you for the quick response.
