### ISSUE TITLE
Decimal numbers ending in zero

### ISSUE THREAD

**Issue by spacebaboon** [mozilla-services/react-jsonschema-form#674]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
A field with type `number` does not validate when the entered value is a decimal ending in a 0, as it is stored in `formData` as a string.
This means that, e.g. `2.1` validates correctly as a number but `2.0` fails with an error '`instance.number is not of a type(s) number'`.

### Steps to Reproduce

1. In the Playground, Numbers tab, enter `2.1`. No error.
2. Change the number to `2.0`. Error is shown.

#### Expected behavior
`2.0` (and any decimal numbers ending in a `0`) validate correctly as numbers.

This is more complex than I initially thought, and I'm not sure what to suggest as a fix. 
As soon as a number ends in a . or a `0`, it is returned as a string. A number will be represented as simply as possible, e.g. `2.0` as a number is just `2`. But in order to input numbers like `2.01` with live validation on, you need to stop this behaviour, otherwise `2.0` would immediately be rewritten as `2` as soon as the user hits the `0`.
Json Schema only has `integer` and `number` data types, `decimal` is not (yet) supported.
I wonder if the `uiSchema` could include something like a format string, a number of decimal digits, or a decimal flag. That way, the field input could still be displayed in a certain way (maybe using `toFixed(n)`) but upon validation, the form could send the value as a number. 

### Version
0.49.0

**Comment by spacebaboon** [comment]
angular-schema-form handles this nicely. it looks like formdata is the number, but the input field is just a text input. change the Name field's type to number:
http://schemaform.io/examples/bootstrap-example.html

**Comment by glasserc** [comment]
We explicitly treat strings with a decimal point and a 0 at the end as strings -- see src/utils.js. This behavior is because the JS Number type does not support distinguishing between `2` and `2.0`, and we need to preserve exactly what the user entered in the input field. I'd be happy to review solutions to this problem, but I don't have any myself.
