### ISSUE TITLE
ui:title not working for arrays

### ISSUE THREAD

**Issue by davidMcneil** [mozilla-services/react-jsonschema-form#677]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
The ui:title field is not applied to array fields.

### Steps to Reproduce
[Link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJsaXN0T2ZTdHJpbmdzIjpbImZvbyIsImJhciJdLCJtdWx0aXBsZUNob2ljZXNMaXN0IjpbImZvbyIsImJhciJdLCJmaXhlZEl0ZW1zTGlzdCI6WyJTb21lIHRleHQiLHRydWUsMTIzXSwibmVzdGVkTGlzdCI6W1sibG9yZW0iLCJpcHN1bSJdLFsiZG9sb3IiXV0sInVub3JkZXJhYmxlIjpbIm9uZSIsInR3byJdLCJ1bnJlbW92YWJsZSI6WyJvbmUiLCJ0d28iXSwibm9Ub29sYmFyIjpbIm9uZSIsInR3byJdLCJmaXhlZE5vVG9vbGJhciI6WzQyLHRydWUsImFkZGl0aW9uYWwgaXRlbSBvbmUiLCJhZGRpdGlvbmFsIGl0ZW0gdHdvIl19LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiVGhpbmciOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkRlZmF1bHQgbmFtZSJ9fX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJsaXN0T2ZTdHJpbmdzIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiYmF6aW5nYSJ9fSwibXVsdGlwbGVDaG9pY2VzTGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkEgbXVsdGlwbGUgY2hvaWNlcyBsaXN0IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiZm9vIiwiYmFyIiwiZnV6eiIsInF1eCJdfSwidW5pcXVlSXRlbXMiOnRydWV9LCJmaXhlZEl0ZW1zTGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6IkEgbGlzdCBvZiBmaXhlZCBpdGVtcyIsIml0ZW1zIjpbeyJ0aXRsZSI6IkEgc3RyaW5nIHZhbHVlIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9LHsidGl0bGUiOiJhIGJvb2xlYW4gdmFsdWUiLCJ0eXBlIjoiYm9vbGVhbiJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InRpdGxlIjoiQWRkaXRpb25hbCBpdGVtIiwidHlwZSI6Im51bWJlciJ9fSwibWluSXRlbXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsInRpdGxlIjoiQSBsaXN0IHdpdGggYSBtaW5pbWFsIG51bWJlciBvZiBpdGVtcyIsIm1pbkl0ZW1zIjozLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9UaGluZyJ9fSwibmVzdGVkTGlzdCI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6Ik5lc3RlZCBsaXN0IiwiaXRlbXMiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJJbm5lciBsaXN0IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9fX0sInVub3JkZXJhYmxlIjp7InRpdGxlIjoiVW5vcmRlcmFibGUgaXRlbXMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19LCJ1bnJlbW92YWJsZSI6eyJ0aXRsZSI6IlVucmVtb3ZhYmxlIGl0ZW1zIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJsb3JlbSBpcHN1bSJ9fSwibm9Ub29sYmFyIjp7InRpdGxlIjoiTm8gYWRkLCByZW1vdmUgYW5kIG9yZGVyIGJ1dHRvbnMiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6ImxvcmVtIGlwc3VtIn19LCJmaXhlZE5vVG9vbGJhciI6eyJ0aXRsZSI6IkZpeGVkIGFycmF5IHdpdGhvdXQgYnV0dG9ucyIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjpbeyJ0aXRsZSI6IkEgbnVtYmVyIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjQyfSx7InRpdGxlIjoiQSBib29sZWFuIiwidHlwZSI6ImJvb2xlYW4iLCJkZWZhdWx0IjpmYWxzZX1dLCJhZGRpdGlvbmFsSXRlbXMiOnsidGl0bGUiOiJBIHN0cmluZyIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoibG9yZW0gaXBzdW0ifX19fSwidWlTY2hlbWEiOnsibGlzdE9mU3RyaW5ncyI6eyJ0aXRsZSI6Ikxpc3Qgb2YgU3RyaW5ncyIsIml0ZW1zIjp7InVpOmVtcHR5VmFsdWUiOiIifX0sIm11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidWk6d2lkZ2V0IjoiY2hlY2tib3hlcyJ9LCJmaXhlZEl0ZW1zTGlzdCI6eyJpdGVtcyI6W3sidWk6d2lkZ2V0IjoidGV4dGFyZWEifSx7InVpOndpZGdldCI6InNlbGVjdCJ9XSwiYWRkaXRpb25hbEl0ZW1zIjp7InVpOndpZGdldCI6InVwZG93biJ9fSwidW5vcmRlcmFibGUiOnsidWk6b3B0aW9ucyI6eyJvcmRlcmFibGUiOmZhbHNlfX0sInVucmVtb3ZhYmxlIjp7InVpOm9wdGlvbnMiOnsicmVtb3ZhYmxlIjpmYWxzZX19LCJub1Rvb2xiYXIiOnsidWk6b3B0aW9ucyI6eyJhZGRhYmxlIjpmYWxzZSwib3JkZXJhYmxlIjpmYWxzZSwicmVtb3ZhYmxlIjpmYWxzZX19LCJmaXhlZE5vVG9vbGJhciI6eyJ1aTpvcHRpb25zIjp7ImFkZGFibGUiOmZhbHNlLCJvcmRlcmFibGUiOmZhbHNlLCJyZW1vdmFibGUiOmZhbHNlfX19fQ==)

#### Expected behavior
The ui:title should be applied to array fields.

#### Actual behavior
The ui:title is not applied to array fields.

### Version
0.49.0

**Comment by n1k0** [comment]
Fixed by #678.
