### ISSUE TITLE
'FieldTemplate' needs to be implemented into @types to prevent errors

### ISSUE THREAD

**Issue by janpauldahlke** [mozilla-services/react-jsonschema-form#679]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
Typescript support:
Property 'FieldTemplate' does not exist on type ...

#### Image
[!image](http://i.imgur.com/vcsL6Li.png)

### Steps to Reproduce
1. use FieldTemplate in a React-Typescript Project on Form
2. typescript throws error on missing interface
3. checking /node_modules/@types/react-jsonschema-form/index.d.ts shows that FieldTemplate is not exposed there.

#### Expected behavior
no Typesript error on using FieldTemplate Attribute

#### Actual behavior
Typescript compiler throws error (but, FieldTemplate is react-usable)
Property 'FieldTemplate' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Form> & Readonly<{ children?: ReactNode; }> & Read...'.

### Version
"_id": "@types/react-jsonschema-form@0.43.1",

**Comment by n1k0** [comment]
There's no official support for typescript in this lib. Maybe you're using type definitions from elsewhere? You should probably file an issue there.
