### ISSUE TITLE
How to insert HTML tags into "title", "description"?  

### ISSUE THREAD

**Issue by kamanwu** [mozilla-services/react-jsonschema-form#687]

**Comment by zek0faws** [comment]
Hi,
Have you read the doc ?
https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields

**Comment by kamanwu-oicr** [comment]
Thanks for reply my question.

"Custom descriptions" works for me.  BUT "Custom titles"  NOT.

Just use the example in this README.md.    

```
const schema = {
  title: "<a href='#'>Todo</a>",
  type: "object",
  properties: {
    done: {type: "boolean", title: "<a href='#'>Done?</a>", default: false}
  }
};

const CustomTitleField = ({title, required}) => {
  const legend = required ? title + '*' : title;
  return <div id="custom" dangerouslySetInnerHTML={{ __html: legend }} />;
};
```

the schema.title works, BUT  schema.properties.done.title DOES NOT work.

**Comment by n1k0** [comment]
Why don't you just [use JSX](https://jsfiddle.net/636Le5jt/1/)?

**Comment by herzaso** [comment]
Using JSX makes the json invalid.
Consider fetching the schema from the server, how would you do it?

**Comment by n1k0** [comment]
I'd probably avoid retrieving raw HTML strings from a server by pure XSS paranoia, but if this is what you really want, I'd probably transform these client-side into JSX with a lib like [htmltojsx](https://www.npmjs.com/package/htmltojsx) or similar. Also, I'm terribly uncomfortable supporting or encouraging use of `dangerouslySetInnerHTML` with this lib.

**Comment by kamanwu-oicr** [comment]
Hello n1k0,  
Thanks for the reply.  I do not want to use JSX, The reason has been mentioned by herzaso.
I am not saying to put dangerouslySetInnerHTML in this lib.  I am saying that:  CustomTitleField cannot customize all title fields, at least, the behavior is different from CustomDescriptionField.
Anyway, I will try to avoid to put HTML in title fields.

**Comment by KMontag42** [comment]
Try this: https://github.com/mozilla-services/react-jsonschema-form#custom-widget-components

You can define the `"ui:widget"` in JSX without invalidating the JSON going to the server using that pattern.

I just did this to put tooltips next to the titles of inputs.

Another solution would be to use the `"ui:help"` option, and then use CSS to style the help text as you want.

**Comment by glasserc** [comment]
Perhaps this is related to #408.

**Comment by ferbs** [comment]
@n1k0 htmltojsx doesn't seem to offer enough XSS protection for user-submitted content.

My project renders user JSON to forms, and I'd like to support html elements like glyphicons in titles/descriptions/labels, images in checkbox fields, etc. 

Using dangerouslySetInnerHTML seems like a workable solution if the html is [sanitized](https://www.npmjs.com/package/sanitize-html).

[Custom field templates](https://github.com/mozilla-services/react-jsonschema-form#field-template) will get me most of the way there, but can you suggest the best way to handle content embedded deeper in the field? (like the checkbox label, but for any arbitrary field type.)

A hack does come to mind, updating the DOM after the field renders, but I'd rather avoid that.

**Comment by epicfaace** [comment]
> Thanks for reply my question.
> 
> "Custom descriptions" works for me. BUT "Custom titles" NOT.
> 
> Just use the example in this README.md.
> 
> ```
> const schema = {
>   title: "<a href='#'>Todo</a>",
>   type: "object",
>   properties: {
>     done: {type: "boolean", title: "<a href='#'>Done?</a>", default: false}
>   }
> };
> 
> const CustomTitleField = ({title, required}) => {
>   const legend = required ? title + '*' : title;
>   return <div id="custom" dangerouslySetInnerHTML={{ __html: legend }} />;
> };
> ```
> the schema.title works, BUT schema.properties.done.title DOES NOT work.

This particular issue does seem to be a duplicate of #408 as @glasserc said. Closing this issue as a duplicate.
