### ISSUE TITLE
Allow to set multiple properties from a single [custom] field

### ISSUE THREAD

**Issue by ojab** [mozilla-services/react-jsonschema-form#690]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Right now `props.onChange(value)` in custom field sets single `formData` property to that `value`. 
It will be handy if there will be an option to merge passed `value` into `formData` instead of changing single property, i. e. given
```js
const schema = {
  type: "object",
  required: ["lat", "lon"],
  properties: {
    lat: { type: "number" },
    lon: { type: "number" },
    xxx: { type: "number" },
    yyy: { type: "number" }
  }
}
```
and something like:
```js
const uiSchema {
  lat: { "ui:field": "geo", "ui:mergeData": true }
}
```
we could call `props.onChange({ lat: 1, lon: 2 })` from `geo` field and set both `lat` & `lon` in `formData` (or additional prop can be passed with a such setter?).

With this interface it would be possible to implement self-contained and reusable conditional field sets without fiddling with schema/uiSchema (i. e. use custom field for one of the properties and hide the others).

**Comment by glasserc** [comment]
Sorry, I don't understand. Right now the geo component calls `this.props.onChange(this.state)`. Doesn't this combine both `lat` and `lon` in the way you'd like? Which onChange are you talking about, and who is calling it now?

**Comment by ojab** [comment]
geo component changes one object field w/ `lat` & `lon` properties, so it's still a single field.

Anyway, I think that more proper way is post-processing of `formData`, so let's close this.

**Comment by vtquy98** [comment]
> geo component changes one object field w/ `lat` & `lon` properties, so it's still a single field.
> 
> Anyway, I think that more proper way is post-processing of `formData`, so let's close this.

Hi Ojab, can you explain what you did for that case?
Thank you!

**Comment by ojab** [comment]
hmm, AFAIR moved to post-processing `formData`? I. e. do something ether in the `onChange` or `onSubmit`. But it was some time ago and I changed a workplace/project since then, so cannot really answer, sorry.
