### ISSUE TITLE
Add support for RegEx field validation

### ISSUE THREAD

**Issue by Eric24** [mozilla-services/react-jsonschema-form#692]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Add support for regex validation.

#### Expected behavior

When included, validate field content against the regex and fail if the regex fails. This would allow very powerful field validation, leveraging the regex functionality already built into JS; things like phone numbers, GUIDs, account numbers, postal codes, etc.

**Comment by zek0faws** [comment]
In the [documentation](https://github.com/mozilla-services/react-jsonschema-form#custom-validation), there's a part where you can set a [custom validation](https://github.com/mozilla-services/react-jsonschema-form#custom-validation).

So [here's](https://jsfiddle.net/zek0faws/ts1kr4mv/) a working fiddle with what you want

**Comment by Eric24** [comment]
Actually, I just realized that json-schema does already support this. The validation property is called "pattern", so I didn't find it when I was searching for "regex validation".
