### ISSUE TITLE
Allow widgetMap modification similar to widgets/fields

### ISSUE THREAD

**Issue by ojab** [mozilla-services/react-jsonschema-form#704]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

It will be handy if one could add new `format` or replace existing one with different widget, so widget could be set directly in `schema` instead of `uiSchema`.

**Comment by glasserc** [comment]
Adding a "widget" concept to the `format` field would needlessly break compatibility with JSON Schema.
