### ISSUE TITLE
Unable to disable the Submit Button 

### ISSUE THREAD

**Issue by vincentsixty** [mozilla-services/react-jsonschema-form#705]
I want to be able to to not have a submit input show up even and just handle my form using the onchange handler. 

 However, if one isn't provided a default one is placed on the screen , which can not be removed and whose location can not be controlled.

Is there a way to disable the submit button from appearing ?  

### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by zek0faws** [comment]
Using a class to hide the button ?

<button type="submit" className="hidden">Submit</button>

**Comment by glasserc** [comment]
This isn't documented, but it seems that you can pass a `children` prop to the `Form` instance, which will show in place of the submit button.

**Comment by YingXue** [comment]
> This isn't documented, but it seems that you can pass a `children` prop to the `Form` instance, which will show in place of the submit button.

Hi, I am not able to use children to replace submit button
`<Form
                schema={this.state.schema as any}
                formData={this.state.formData.properties.desired}
                children={<br/>}
            />`
Can you help taking a look if I am doing it wrong?

**Comment by glasserc** [comment]
@YingXue, it is hard to help without an example to look at.

**Comment by llamamoray** [comment]
@YingXue I'm doing this exactly as the documentation describes and it's working: https://github.com/mozilla-services/react-jsonschema-form#form-action-buttons 

Here's an example https://jsfiddle.net/ermLcpd4/

**Comment by Eshh** [comment]
> > This isn't documented, but it seems that you can pass a `children` prop to the `Form` instance, which will show in place of the submit button.
> 
> Hi, I am not able to use children to replace submit button
> `<Form schema={this.state.schema as any} formData={this.state.formData.properties.desired} children={<br/>} />`
> Can you help taking a look if I am doing it wrong?

instead of <br /> just give '  ' one spcae between quotes , worked for me to hide Submit button with space

**Comment by zhaoyao91** [comment]
```
<Form>
  <Fragment />
</Form>
```

**Comment by SeanNexusVisa** [comment]
Giving it a disabled button is also a way.

```
<Form schema={schema} iSchema={uiSchema} formData={formData}>
    <Button disabled variant="contained" style={{ marginTop: "24px" }}>
        SUBMIT
    </Button>
</Form>
```

**Comment by fregante** [comment]
The modern way should be:

```jsx
<Form
  uiSchema={{
    "ui:submitButtonOptions": { norender: true },
  }}
/>
```
