### ISSUE TITLE
Update react peerDependency to 16.x.x

### ISSUE THREAD

**Issue by neoel** [mozilla-services/react-jsonschema-form#709]
React has received an upgrade, update the peerDependency.

I've created https://github.com/nerdalize/react-jsonschema-form to just update the peerDependency. But I'd like some proper validation :).

**Comment by glasserc** [comment]
Hi, I'd be interested to look at a PR. If the tests pass, I think it's pretty safe to upgrade.

**Comment by ronanmulvaney** [comment]
May be worth considering how React-Router manages it's dependency on React yet doesn't constrain the major version upgrade - https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json

**Comment by hedleysmith** [comment]
Just to add that we've been using react-jsonschema-form with React 16 and it's working fine
