### ISSUE TITLE
Render without form tag?

### ISSUE THREAD

**Issue by zbyte64** [mozilla-services/react-jsonschema-form#71]
I want to use this project to extend existing forms but I cannot render the `Form` component inside another form. The two solutions I see is to convert the existing form code into schema json and merge it with the user supplied schema OR have the option to render without the form tag. Merging the fields should work but there are cases where the existing form layout would be difficult to represent with ui schema and jsonschema (examples: an "advanced" section which collapses down, code editor with codemirror, and embedded previews next to fields). It seems having control over whether to render the form tag would be more robust.

**Comment by zbyte64** [comment]
If I sent a pull request that implemented `Fieldset` which acts like `Form` but without the form specifics, would it be accepted (assuming all contributing guidelines is followed)?

**Comment by n1k0** [comment]
> If I sent a pull request that implemented Fieldset which acts like Form but without the form specifics, would it be accepted (assuming all contributing guidelines is followed)?

If usage remains backward compatible and the code is good, definitely yes :)

**Comment by fermuch** [comment]
why don't you just use the component `SchemaField`?

Checkout how it is being used here: https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/Form.js

**Comment by zbyte64** [comment]
Yes, I ended up using `SchemaField` and copying over all the `Form` methods except `onSubmit`. As to why not to do this: it is not DRY. Trying to factor out the common logic to another component either meant inheriting the common component or rendering a new sub-component which broke allot of unit tests that do internal state checks.

**Comment by derekdon** [comment]
Any update on the best approach to this? Would like to drop a react-jsonschema-form powered fieldset into an existing form.

**Comment by epicfaace** [comment]
This was fixed by #1345!
