### ISSUE TITLE
Passing down props to custom fields 

### ISSUE THREAD

**Issue by vincentsixty** [mozilla-services/react-jsonschema-form#712]
1# Say I have a custom Field Row like this :       const fields = {geo2: field_row, TitleField: CustomTitleField  };

2#:
and my form looks this : 

```
 <Form 
                     
                    schema={schema}
                    uiSchema={uiSchema}
                    formData={form_data}

                    onSubmit={({ formData }) =>
                        console.log('submitted formData', formData)}


                    onBlur={(id, value) =>
                        console.log(`Touched ${id} with value ${value}`)}
                    onFocus={(id, value) =>
                        console.log(`Focused ${id} with value ${value}`)}
                    FieldTemplate={CustomFieldTemplate}
                    onError={log('errors')}
                    fields={fields}>
```

Question : 

 How can I Pass down A bunch of props into the custom "field_row" component from the parent ? 

 when I looked into the props currently provided it only allows for the following ones that are passed down from Form : 

props
{name: "fields", required: false, schema: {…}, uiSchema: {…}, errorSchema: {…}, …}autofocus: falsedisabled: falseerrorSchema: {}formContext: {}formData: [{…}]0: {field_object: {…}}length: 1__proto__: Array(0)idSchema: {$id: "root_card_0_row_fields"}name: "fields"onBlur: ƒ ()onChange: ƒ (value, options)readonly: falseregistry: {fields: {…}, widgets: {…}, ArrayFieldTemplate: undefined, definitions: {…}, FieldTemplate: ƒ, …}required: falseschema: {type: "array", items: {…}}uiSchema: {ui:field: "geo2", classNames: undefined}__proto__: Object

**Comment by zdraganov** [comment]
Any progress on that? I'm  looking for the same thing right now.

**Comment by snirp** [comment]
Why was this closed without further comment? Has this been answered elsewhere?

**Comment by sbusch** [comment]
I think that was closed by author because of a double post, see continued discussion at <https://github.com/mozilla-services/react-jsonschema-form/issues/713>
