### ISSUE TITLE
Error when sending "dictionnary kind" property

### ISSUE THREAD

**Issue by alb3ric** [mozilla-services/react-jsonschema-form#719]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
  Hello,

When I'm sending a schema with a dictionary, I get an error : 
_Invalid root object field configuration:Cannot convert undefined or null to object._
 
**Schema :** 

```
"VirtualDirectories": {
      "title": "My virtual directories",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
```

**Data :**

`
"VirtualDirectories": {
    "Binaries": "bin",
    "Components": Comp",
    "Logs": "Tmp"
  }  
`
### Steps to Reproduce

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJWaXJ0dWFsRGlyZWN0b3JpZXMiOnsiQmluYXJpZXMiOiIuIiwiQ29tcG9uZW50cyI6IkNvbXBvbmVudHMiLCJMb2dzIjoiVG1wIn19LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDQvc2NoZW1hIyIsInRpdGxlIjoiVGVzdCIsInR5cGUiOiJvYmplY3QiLCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInJlcXVpcmVkIjpbIlZpcnR1YWxEaXJlY3RvcmllcyJdLCJWaXJ0dWFsRGlyZWN0b3JpZXMiOnsidGl0bGUiOiJS6XBlcnRvaXJlIHZpcnR1ZWxzIiwidHlwZSI6Im9iamVjdCIsImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjp7InR5cGUiOiJzdHJpbmcifX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX19

#### Expected behavior

I would expect to have a list similar to dictionary (key, value).

#### Actual behavior

Error : Invalid root object field configuration:Cannot convert undefined or null to object.

### Version

0.51.0

Thanks in advance for your help!

**Comment by glasserc** [comment]
There is one simple problem to fix and a hard problem to fix.

The easy problem is that you need to wrap child properties in a `properties` field, so something like:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Test",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "VirtualDirectories"
  ],
  "properties": {      //  <--- I added this
    "VirtualDirectories": {
      "title": "Répertoire virtuels",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
```

The second problem is we don't really support use of objects as dictionaries in the way I think you want to. We just don't support it at all. We don't even look at the `additionalProperties` field as far as I can tell. Instead, you could maybe use an array of objects, like in the Nested example in the playground.

I would be interested in reviewing a PR for open-ended objects like the one I think you want, but we don't really have time to implement it ourselves.

**Comment by alb3ric** [comment]
Thanks for your answer.
I think i'm going to go with an array of object. The thing is that I would like to render the two fields of my object on one line. What's the best way to do it?

Schema would be : 
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "blablalbal",
  "type": "object",
  "required": [
    "VirtualDirectories"
  ],
  "properties": {
    "VirtualDirectories": {
      "title": "Virtual directories",
      "type": "array",
      "items": {
        "$ref": "#/definitions/VirtualDirectory"
      }
    }
  },
  "definitions": {
    "VirtualDirectory": {
      "type": "object",
      "required": [
        "Name",
        "Physical"
      ],
      "properties": {
        "Name": {
          "type": "string"
        },
        "Physical": {
          "type": "string"
        }
      }
    }
  }
}
```

And I would like it to be like this : 

Name : [          ] Physical : [                ] [-]
Name : [          ] Physical : [                ] [-]
Name : [          ] Physical : [                ] [-]

Thanks in a advance for your help.

**Comment by glasserc** [comment]
You might need to add CSS in order to change the formatting of the array or the fields of each object. You can also add CSS classes using the `uiSchema` field. You can also define a custom field or widget if you need to generate custom HTML. See the `geo` example in the playground "Custom" tab for an example.
