### ISSUE TITLE
Is it possible to validate either schema or uischema? 

### ISSUE THREAD

**Issue by alexbra** [mozilla-services/react-jsonschema-form#725]
I'm currently developing an app, which allows to receive a post request and save react-jsonschema-form json object in a database. 

Is it possible to validate json object (schema or uischema) before I save it to a database? 

Thank you.

**Comment by glasserc** [comment]
I think the ajv library will validate that the schema is valid, but we don't have anything that defines a valid `uiSchema`. It would be cool to have a JSON Schema that defines valid `uiSchema`s but we don't have anything like that yet. Of course, such a schema wouldn't validate that the `uiSchema` matches your JSON Schema, but I'm not even sure such a thing is possible in the general case.

**Comment by alexbra** [comment]
Thanks, it works for me!
