### ISSUE TITLE
Passing errors down to Widgets

### ISSUE THREAD

**Issue by llamamoray** [mozilla-services/react-jsonschema-form#727]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Is there any reason why the StringField, NumberField, BooleanField etc don't pass the error schema down to the widgets they render?

I have implemented most of the input components with a custom component library which can display errors as part of their functionality. It would be neater to show errors using these controls rather than displaying errors separately using a Field Template. Is there any fundamental reason that the errors aren't passed down to the widgets?

**Comment by iplus26** [comment]
![image](https://user-images.githubusercontent.com/6082721/33238270-46092802-d2c5-11e7-831b-338a7d091222.png)
+1 This looks really wired. Is implementing all the input components (which is really not elegant) is the only way to avoid that?

**Comment by llamamoray** [comment]
@glasserc is there any reason why you wouldn't want this implemented? 

I'm considering putting aside some time to implement, but want to make sure that it will be considered to be merged into the project.

**Comment by glasserc** [comment]
I think showing errors near their source is definitely better. I don't know what the reasoning was for having them all together at the top. Be careful to also handle errors that do not have a specific location (such as violations of "required", although I'm not sure if that's still an issue).

**Comment by Vandell63** [comment]
Hey there, Thx for this awesome project. But i try to implement my custom field with the materialUI React. But even i created a custom field i have to passing down errors array messages to my children ( Children props from my custom field template ) because material ui input field need an error context ( error && error message ). How can we do this ?

**Comment by llamamoray** [comment]
@glasserc I've created a PR #826 which passes the raw errors down through the SchemaField, down to the widgets. This does not change any of the behaviour of the current implementation, but will allow people who are using custom widgets to display errors where they see fit.

**Comment by llamamoray** [comment]
@iplus26 the first part of what you require has been merged in #826 so the fields are receiving raw errors. As I have entirely custom fields this covers my use case, however if you still require the default bootstrap controls to display errors differently you'll need to create a PR. 

@glasserc when do you plan to do the next release?

**Comment by glasserc** [comment]
I've tried to cut version 1.0.1, please tell me if that provides what you need.

**Comment by llamamoray** [comment]
@glasserc Just tried it out and working as expected. Thanks

**Comment by mihanizm56** [comment]
@llamamoray yes, the show of the errors is working, but when I get errors from backend and set them to the form through the extraErrors prop as was written in doc after the field was changed, error is still there. Please, tell me how I can fix it, cant find the info about that case
