### ISSUE TITLE
NPM-published version 0.51.0 uses 'jsonschema' not 'ajv'

### ISSUE THREAD

**Issue by restdbio** [mozilla-services/react-jsonschema-form#733]
### Description

I need some of the features in the 'ajv' jsonschema validator (localization). The package.json you have published to NPM is using 'jsonschema' even though the package version is the same (0.51.0)

### Version

0.51.0 (github)  <>  0.51.0 (npm)

**Comment by glasserc** [comment]
Version 0.51.0 doesn't use the ajv library.

**Comment by restdbio** [comment]
The package.json of the current version (0.51.0)  lists these dependencies:

  "dependencies": {
    "ajv": "^5.2.3",
    "lodash.topath": "^4.5.2",
    "prop-types": "^15.5.8",
    "setimmediate": "^1.0.5"
  },

While the version you have published to NPM (which is also 0.51.0) looks like this:

"dependencies": {
    "jsonschema": "^1.2.0",
    "lodash.topath": "^4.5.2",
    "prop-types": "^15.5.8",
    "setimmediate": "^1.0.5"
  }

**Comment by glasserc** [comment]
ajv didn't make version [0.51](https://github.com/mozilla-services/react-jsonschema-form/blob/v0.51.0/package.json#L42-L47). It made it into 0.52.

**Comment by restdbio** [comment]
Great, thanks 👍
