### ISSUE TITLE
Problem with nested object having a required property

### ISSUE THREAD

**Issue by asaf** [mozilla-services/react-jsonschema-form#740]
Hey guys,

A schema [with nested object](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJkaXNwbGF5TmFtZSI6ImZvb29vbyJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDQvc2NoZW1hIyIsImRlc2NyaXB0aW9uIjoiU2FtcGxlIE9iamVjdCIsImlkIjoiZm9vIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsibmVzdGVkIjp7InByb3BlcnRpZXMiOnsiZGlzcGxheSI6eyJ0aXRsZSI6ImRpc3BsYXkiLCJ0eXBlIjoic3RyaW5nIn0sInZhbHVlIjp7InRpdGxlIjoidmFsdWUiLCJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJ2YWx1ZSJdLCJ0eXBlIjoib2JqZWN0In0sImRpc3BsYXlOYW1lIjp7InRpdGxlIjoiZGlzcGxheU5hbWUiLCJ0eXBlIjoic3RyaW5nIn19fSwidWlTY2hlbWEiOnt9fQ==) that has a required property causes _validation error_

It also adds the `nested` property as an empty object even though it is not touched (try just changing the `display` field),

This behavior blocks the form to be submitted although it's valid,

Thanks,

Asaf.

**Comment by glasserc** [comment]
There is a PR addressing this issue at #682, although I believe it still needs work. (Closing this as duplicate.)
