### ISSUE TITLE
Inline Form Components?

### ISSUE THREAD

**Issue by alexblickenstaff** [mozilla-services/react-jsonschema-form#745]
Is it possible for form elements to be in the same line? On the live playground, I see the Custom example accomplishes this, but I wanted to know if there is a built-in way to do this.

**Comment by revolunet** [comment]
You have to play with CSS. The tips'n'tricks section in the README can help : https://github.com/mozilla-services/react-jsonschema-form#tips-and-tricks

**Comment by epicfaace** [comment]
Yes, it's a CSS solution. Closing this for now, but @alexblickenstaff let me know if you have additional questions.

**Comment by CaelumTerrae** [comment]
Where is the new tips & tricks section? It seems to have been removed once the readme was updated.

**Comment by Weiyi-Feng** [comment]
Hi, the tips & tricks section seems to have been removed once the readme was updated, where is the new place for it?

**Comment by epicfaace** [comment]
Not sure, but the old version can be found here https://github.com/rjsf-team/react-jsonschema-form/tree/v0.50.1#tips-and-tricks
