### ISSUE TITLE
yarn.lock should not be in .gitignore

### ISSUE THREAD

**Issue by jdbevan** [mozilla-services/react-jsonschema-form#749]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

yarn.lock is in .gitignore which means that builds are not deterministic. See https://yarnpkg.com/en/docs/yarn-lock

**Comment by epicfaace** [comment]
This change was done in #485. @n1k0 @Reggino what was the justification for adding yarn.lock to .gitignore?

**Comment by epicfaace** [comment]
Actually, looks like it's because we already have a `package.lock`, so developers are supposed to use npm to install dependencies, not yarn. That's why we don't have a `yarn.lock`.
