### ISSUE TITLE
Any Of , One OF Array Or Object Does Not Work

### ISSUE THREAD

**Issue by vincentsixty** [mozilla-services/react-jsonschema-form#751]
const schema =
       {
            "oneOf": [
                {"$ref": "#/definitions/singleObject"}, // plain object
                {
                    "type": "array", // array of plain objects
                    "items": {"$ref": "#/definitions/singleObject"}
                }
            ],
            "definitions": {
                "singleObject": {
                    "type": 'object',
                    "additionalProperties": false,
                    "properties": {
                        "author": {
                            "type": 'number',
                            "required": true
                        }

                    }
                }
            }
        };

        const formData = [{author: 2}];

**Comment by vincentsixty** [comment]
any one ?

**Comment by joshgagnon** [comment]
As per the docs, oneOf etc is not supported.  This is deal breaker for me.

**Comment by glasserc** [comment]
Duplicate of #52.
