### ISSUE TITLE
Question: Ordering 

### ISSUE THREAD

**Issue by vincentsixty** [mozilla-services/react-jsonschema-form#752]
Say I have a  Json Object 1, Json Object 2, and then JsonObject 1 in my JSON data file. 

 my schema and ui schema file have ui field maps for both Object 1 and Object 2 mapped.

However, The code only works if the JSON data file , follows the order of the schema file. e.g.

Object 1 and then Object 2

if object 2 if first or there is a Object 2 and Object 1 and Object 2 , then it won't work.

Why?

**Comment by revolunet** [comment]
can you please provide a minimal example on codesandbox.io ?

**Comment by epicfaace** [comment]
Closing this for now; @vincentsixty if you have a code example or more information, please feel free to comment.
