### ISSUE TITLE
Handle fixed items arrays

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#76]
From the [spec](http://json-schema.org/latest/json-schema-validation.html#anchor37):

> The value of "items" MUST be either an object **or an array**. If it is an object, this object MUST be a valid JSON Schema. **If it is an array, items of this array MUST be objects, and each of these objects MUST be a valid JSON Schema.** 

```json
{
  "type": "array",
  "items": [
    {"type": "integer"},
    {"type": "boolean"},
    {"type": "string"}
  ]
}
```

Sample record:

```json
[
  -64586948,
  true,
  "dolor"
]
```

Note: This is a rather strange use case, and should be treated as P2.

**Comment by rhgb** [comment]
I've experienced the same issue trying to define parameters like:

cookies used with npm package "cookie":

```json
[
    ["token", "dGVzdAo=", {
        "path": "/",
        "maxAge": 1000
    }]
]
```

or http headers:

```json
{
    "headers": [
        ["Cache-Control", "no-cache"]
    ]
}
```

**Comment by n1k0** [comment]
These are indeed legit use cases. Do you want to work on this? :)

**Comment by rhgb** [comment]
Yes, I'll take some time to get familiar with existing code first :smile:
