### ISSUE TITLE
liveValidate validate the whole form instead of the input

### ISSUE THREAD

**Issue by ugogo** [mozilla-services/react-jsonschema-form#770]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hey guys 👋 
I'm running into a weird case.
I have a form with `noHtml5Validate` and `liveValidate` props to `true`, when I'm triggering an error into one of the inputs (set a text, then removing it), the whole form is validated and all the errors appear.

NB: This issue should be related to the same problem, but there are no answers since October
https://github.com/mozilla-services/react-jsonschema-form/issues/512

You can find a JSFiddle here: https://jsfiddle.net/pznfb825/1/

#### Expected behavior

Only the related input should be validated

#### Actual behavior

The whole form is validated

### Version

1.0.0

**Comment by epicfaace** [comment]
Closing in favor of #512. Feel free to submit a PR to fix this.

**Comment by adityadhawan22** [comment]
Any fixes for this issue?
