### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by WLCPereira** [mozilla-services/react-jsonschema-form#779]
I'm working with an object array. Something like this:

     {
          "ToDo":[ 
                  {"task": "task1", "done": true},
                  {"task": "task2", "done": false},
                  {"task": "task3", "done": true},
            ]
     }

Is there a schema that I can use a 'select' element to select one of the tasks and the checkbox listen if this task is done?

**Comment by glasserc** [comment]
No, RJSF does not offer any kind of "select an element from this array" capability, because such a thing is not really part of JSON Schema.
