### ISSUE TITLE
Only TIME field support

### ISSUE THREAD

**Issue by sandeepspoton** [mozilla-services/react-jsonschema-form#786]
It is better to have TIME field like other fields.

**Comment by edi9999** [comment]
What exactly do you mean ?

**Comment by sandeepspoton** [comment]
Right now  there is no any data type input field which takes only TIME as input. (E.g we want time picker )

see this we want similar to this : https://www.npmjs.com/package/react-times

**Comment by edi9999** [comment]
Have a look at this : https://github.com/mozilla-services/react-jsonschema-form#custom-component-registration

```
const MyTimeWidget = (props) => {
  return (
     // Your code using react-times
  );
};

const widgets = {
  time: MyTimeWidget
};

const uiSchema = {
  "ui:widget": "time"
}

render((
  <Form
    schema={schema}
    uiSchema={uiSchema}
    widgets={widgets} />
), document.getElementById("app"));
```

**Comment by sandeepspoton** [comment]
Thanks i will check it.

**Comment by glasserc** [comment]
I would be willing to review a PR that added support for the `time` format without adding dependencies, but because HTML5 does not offer an `input[type="time"]`, I suspect this is not going to happen.

**Comment by edi9999** [comment]
I think this kind of code could be put in a Wiki page, or maybe in a separate community-driven repository.

**Comment by amit-kanojiya** [comment]
Is input type time available now?
