### ISSUE TITLE
How can send props into the custom selector field.

### ISSUE THREAD

**Issue by shashi20170925** [mozilla-services/react-jsonschema-form#791]
### Prerequisites
N/A
### Description
I have a parent component parentComponent which has 3 form controls 
1. textbox 2. test box( basic widget components)
3 rd one is the custom field(custom selector) which needs dynamic values that needs to be passed from the parentComponent.  

I could ideally make an api call in the custom component itself but i need same api call in the parent for other validation.

considered 2 options. 
1. Making api call 2 places--which is not best approach as far as performance is concerned.
2. save in the cache(don't like the option as i don't want to save lot of info in the cache)

if there is way i can make api call in the parent and send it to the custom selector component would be great.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by glasserc** [comment]
Our recommended approach for these sorts of things is to make the fetch up front before rendering rjsf, and instantiating the custom component with the loaded data when you render it.
