### ISSUE TITLE
Render the form using a DOM element other than <form>

### ISSUE THREAD

**Issue by dapicester** [mozilla-services/react-jsonschema-form#792]
I am using this to render dynamic complex field in my huge form. Actually I don't need to directly submit the generated form because I handle it externally, and in fact I also hide the submit buttons. 

Everything seems to work fine so far, but I get the following warning in the console:
```
Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.
```
I wonder if it could be possible to generate the form without using a `<form>` element, eventually allowing the user to specify some other DOM element, say a `<div>`.

Any feedback on this?

**Comment by arahansen** [comment]
I would also like to use a custom component to handle how to define my `form` element. Similar to how `FieldTemplate` is handled. If I opened a PR with this functionality, is that something the team would consider?

**Comment by epicfaace** [comment]
> I would also like to use a custom component to handle how to define my `form` element. Similar to how `FieldTemplate` is handled. If I opened a PR with this functionality, is that something the team would consider?

Sure, feel free to add a PR.

**Comment by epicfaace** [comment]
This was added in #1345.
