### ISSUE TITLE
Making fields dependent on checkbox

### ISSUE THREAD

**Issue by oskaryil** [mozilla-services/react-jsonschema-form#795]
I haven't been able to figure this out yet. I want to "unrequire" a couple of fields if a checkbox is checked. So if the user fills in visiting address and then checks the "same as above" checkbox, they should not have to fill in the mail address as well.

![image](https://user-images.githubusercontent.com/16903955/34414229-61c09b70-ebe8-11e7-942f-106a1e65373c.png)

**Comment by cdtinguria** [comment]
This [section](https://github.com/mozilla-services/react-jsonschema-form#property-dependencies) in docs might help.
also, you can add remove the fields from schema based on 'onChange' event of the checkbox.

**Comment by edi9999** [comment]
See also the "Property Dependencies" example in the playground : https://mozilla-services.github.io/react-jsonschema-form/

I'm closing this but if you have issues implementing them, ping me

**Comment by BradyEdgar94** [comment]
Any luck on this?

**Comment by epicfaace** [comment]
@BradyEdgar94 see https://react-jsonschema-form.readthedocs.io/en/latest/usage/dependencies/#property-dependencies

**Comment by benjaminbours** [comment]
Well this is not exactly working. The example and the documentation are showing an example in case of an input text. When you try to accomplish this on the online playground, here is the behavior.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/8804297/134766598-14879251-b267-4743-869d-4d6421cbee21.gif)

As you can see, when it has never been checked, the behavior is ok, but when you uncheck it, I expect the field not to be required anymore. While it is still.

**Comment by epicfaace** [comment]
Since this issue is pretty old, can you make a new issue to track this problem?

**Comment by benjaminbours** [comment]
Here is #2564
