### ISSUE TITLE
Symbol is undefined in IE11

### ISSUE THREAD

**Issue by rahul1059** [mozilla-services/react-jsonschema-form#798]
IE11 doesn't support Symbol and error is displayed in console whenever form has any validation error.
I don't want to add huge babel-polyfill for this. Is there any way to fix it quickly.
![image](https://user-images.githubusercontent.com/5712189/34603342-98e6583c-f229-11e7-98f1-fd5a81a562fd.png)

**Comment by Natim** [comment]
I would be glad if you could investigate this error and start suggesting a fix for it.

**Comment by edi9999** [comment]
It seems to be in the bundle.js file without a test for typeof Symbol === "function" beforehand : 

```
...
for(var l,u=n[Symbol.iterator]();!(i=(l=u.next()).done);i=!0){var c=l.value;if(c=c.replace(/~1/g,"/").replace(/~0/g,"~"),!o.hasOwnProperty(c))throw new Error("Could not find a definition for "+e+".");o=o[c]}
...
```

Line 29, Character 29661

**Comment by KiranChaudhariJM** [comment]
This solution will work for sure, it worked for me when I encountered the error: 'Symbol' is undefined in IE . It worked earlier in Chrome and Firefox but IE was throwing this error.It took me few hours to find this solution.
I am using the latest React at this time react "react": "^16.5.0" on windows machine.

    1. Install babel-polyfill
    npm install --save-dev babel-polyfill
    In package.json, it should have the following entries

    "devDependencies": {
        "babel-core": "^6.26.3",
        "babel-loader": "^8.0.2",
        "babel-polyfill": "^6.26.0",
        "babel-preset-react": "^6.24.1"
      }

    2. In index.js, add
    
        import babelPolyfill from 'babel-polyfill';

Problem should get solved
