### ISSUE TITLE
how to implement checkboxes from object data

### ISSUE THREAD

**Issue by francisrod01** [mozilla-services/react-jsonschema-form#800]
### Description

It's not possible to set a labels from checkbox object data.
If I try to modify the data object, the field becomes a dropdown.

### Steps to Reproduce

I can't reproduced this but I can show a screenshot of what I'm trying to do.

![image](https://user-images.githubusercontent.com/4691768/34641055-35d759a0-f2e5-11e7-9e29-4731811716eb.png)

#### Expected behavior

You should have more control on the type of field here.

```js
...
myCheckboxArray: {
  type: "array",
  minItems: 1,
  items: {
    type: "object",
    any: [
      {"value1": "Label 1"},
      {"value2": "Label 2"},
    ]
  }
...
```

#### Actual behavior

Actually checkbox fields have just a value, this is too simple but it doesn't help me at all.

### Version

* react: `16.2.0`
* react-jsonschema-form: `1.0.0`

**Comment by francisrod01** [comment]
Oooww I got it! :)

in my `myCheckboxArray` field I put the `enum` and `enumNames`, good it helps a lot.

```js
myCheckboxArray: {
    type: "array",
    title: "Period",
    minItems: 1,
    items: {
        type: "string",
        enum: props.getWeekDaysShort(),
        enumNames: this.props.getWeekDays()
    },
    uniqueItems: true
},
...
```

The result is below:

![image](https://user-images.githubusercontent.com/4691768/34644982-7ba4846e-f329-11e7-875a-4ed4a3a39c05.png)

**Comment by xyy7260** [comment]
@francisrod01  hi， Excuse me, how to select the corresponding check box to display related content?
option 1 => numberComponent
option 2=> inputComponent
option 3 => arraysComponent
