### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by edi9999** [mozilla-services/react-jsonschema-form#805]
Currently this is just a list of PR that should be accepted for the v2 version (they have breaking changes).

1. https://github.com/mozilla-services/react-jsonschema-form/pull/767 (breaking-change)

However, any big topic that can't be implemented in v1 could be discussed in this thread too.

**Comment by eberkund** [comment]
Perhaps making the templates framework agnostic can be something to focus on in v2?

i.e. Bootstrap v4, Material UI, etc.

**Comment by epicfaace** [comment]
Closing this as some of the V2 issues have been added to this project: https://github.com/mozilla-services/react-jsonschema-form/projects/1

**Comment by edi9999** [comment]
Ok, good idea !
