### ISSUE TITLE
Netlify support?

### ISSUE THREAD

**Issue by SKempin** [mozilla-services/react-jsonschema-form#813]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Can you please provide clarification if the form supports Netlify? In order to do so a `netlify` attribute has to be added to the `<form>` attributes but this is not actually rendered.

### Steps to Reproduce

1. Add `netlify` to `<Form>`  attributes.  - [See Netlify docs](https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/)

#### Expected behavior

`netlify` attribute rendered as a form attribute.

#### Actual behavior

`netlify` attribute is not rendered. 

### Version

1.0.0

**Comment by edi9999** [comment]
You can add a className when you instantiate your Form, for example : 

```
render((
  <Form schema={schema}
        onChange={log("changed")}
        onSubmit={log("submitted")}
        className="netlify"
        onError={log("errors")} />
), document.getElementById("app"));
```

I think that should be enough for you to support netlify.

**Comment by glasserc** [comment]
Also, the documentation in the link says you can't just add a `netlify` attribute to a React form. Even if that were enough, you could probably do that best by using a template or a widget.

**Comment by SKempin** [comment]
Adding a className is not what the documentation stipulates, and this doesn't solve the issue. I'm going to conclude that this is not compatible with Gatsby.

**Comment by MarcCoet** [comment]
oh and the ability to set `name` attributes on individual fields is needed too.
