### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by eloypnd** [mozilla-services/react-jsonschema-form#82]
There is some issue with `deeper` dependency `buffertools`. I get the following error message when trying to browserify:

```
Error: Cannot find module 'buffertools' from '.../node_modules/deeper
```

Therefore I can't get the JS bundle.
> I am using `react-jsonschema-form@0.17.1` with
- `node@5.1.1`
- `babel-core@6.6.5`
- `babelify@7.2.0`
- `browserify@13.0.0`

**Comment by n1k0** [comment]
I had to deal with that as well, and solved it in the webpack configuration by [ignoring this import](https://github.com/mozilla-services/react-jsonschema-form/blob/c07fbf1aacc0d7a416b7be0fb0542e6c8c132621/webpack.config.prod.js#L13).

You may want to do the same in your browserify configuration. You may also want file an issue to their repository, as I think they shouldn't do what they do, or at least the way they do.

**Comment by cguedes** [comment]
@n1k0 Tnks for the hint on this. 

Shouldn't this note be on some README.md section (i.e. Troubleshooting)?

**Comment by cguedes** [comment]
For people that use browserify the solution is to use the `ignore` method of browserify with 'buffertools':

~~~javascript
    var bundler = browserify({ ... yourconfig ... }).ignore('buffertools')
~~~

**Comment by n1k0** [comment]
> Shouldn't this note be on some README.md section (i.e. Troubleshooting)?

You're most definitely right. I'm also considering switching to another similarily scoped lib, but can't find anything as tiny as "deeper"; eg. switching to lodash isEqual bumps the build from 61kb to 68 :/

**Comment by cguedes** [comment]
Yes, that would be the best approach. In the meanwhile, we should add the README.md. I will PR that for you.

**Comment by n1k0** [comment]
> I will PR that for you.

That's awesome. On my end I have an idea to solve the problem in the deeper lib itself as described in https://github.com/othiym23/node-deeper/issues/3#issuecomment-206232232; gonna work a PR.

**Comment by cguedes** [comment]
@n1k0  PR created: https://github.com/mozilla-services/react-jsonschema-form/pull/124

**Comment by nuclearspike** [comment]
Thanks for the ".ignore('buffertools')" tip! I was completely stuck on this one and that fixed it!
