### ISSUE TITLE
Maximum call stack exception on circular refs

### ISSUE THREAD

**Issue by gpietro** [mozilla-services/react-jsonschema-form#820]
### Description
I'm using version 1.0.0 and I get maximum call stack exception with circular refs.

### Steps to Reproduce
Schema example to reproduce the error

```
{
  "title": "Maximum call stack",
  "description": "Example to reproduce the error.",
  "$ref": "#/definitions/Person",
  "type": "object",
  "definitions": {
    "Person": {
      "properties": {
        "firstName": {
          "type": "string",
          "title": "First name"
        },
        "lastName": {
          "type": "string",
          "title": "Last name"
        },
        "address": {
          "title": "Hello",
          "type": "object",
          "$ref": "#/definitions/Address"
        }
      }
    },
    "Address": {
      "properties": {
        "street": {
          "type": "string",
          "title": "address2"
        },
        "resident": {
          "type": "object",
          "$ref": "#/definitions/Person"
        }
      }
    }
  }
}
```

**Comment by epicfaace** [comment]
Reproducible fiddle: https://jsfiddle.net/epicfaace/fjasqxdb/

Obviously circular messages should not be supported -- what behavior are you expecting? Perhaps the form should show an error message in the form itself, rather than just on the console instead?

**Comment by gpietro** [comment]
Hi, I should get back at it to answer you. I don't actually remember what I was trying to do at that time. I'll open another issue if the case. For now we can close this one.
