### ISSUE TITLE
validation error when using format property

### ISSUE THREAD

**Issue by locales-wellington** [mozilla-services/react-jsonschema-form#837]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Introduction of ajv validation prevents form submission when using unknown 'format' property

### Steps to Reproduce

https://jsfiddle.net/hdp1kgn6/1/

Add format: "textarea" to description and try and submit form

#### Expected behavior

I can add custom fields  which will format ui based on format property in data and not prevent submission

eg.

```
description: {type: "string". format: "textarea"}
```

```
const fields = {
 customField: CustomFieldComponent
}
const uiFields = { desc: { 'ui:field': 'customField'  };
```
#### Actual behavior

Error on form submission (ajv validation)
Uncaught Error: unknown format "textarea" is used in schema at path "#/properties/description"

### Version

1.0.x

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by locales-wellington** [comment]
7.2 "Implementations MAY add custom format attributes."
AJV allows the addition of custom formats [https://github.com/epoberezkin/ajv#formats](https://github.com/epoberezkin/ajv#formats) so it seems that it would be sensible to allow implementations using react-jsonschema-form to add these?

I am using ajv with react-jsonschema-form 0.51 and the 1.0.0 release breaks my implementation by not allowing that option.

**Comment by glasserc** [comment]
You can already add widgets for any format you like as part of the registry.

**Comment by locales-wellington** [comment]
But not custom formats in the schema correct? Because that will fail validation. For example: I have a schema that includes a format 'markup' for a string to display a markup editor. I should be able to add that custom format to the validator (ajv) so I don't get a validation error. The validator ajv that has been added provides that option so it seems odd that the react-schema-form api would not?

**Comment by glasserc** [comment]
Yes, someone using rjsf should be able to interact with the ajv validator directly. See #783, #794.

**Comment by locales-wellington** [comment]
Ah, righto - thanks :)
