### ISSUE TITLE
Add schemaPath to transformAjvErrors

### ISSUE THREAD

**Issue by dosborne** [mozilla-services/react-jsonschema-form#838]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I'm using rjsf in a project and require custom messages that are part of the schema.  For example:

> const schema = {
  title: "react-jsonschema-form demo",
  type: "object",
  required: ["name"],
  properties: {
    name: {
      type: "string",
      minLength: 3,
      myCustomErrors: "You really should fill in your name"
    },
    description: {type: "string"},
  }
};

Here myCustomErrors defines custom error messages.  So when running rjsf validation I provide a transformErrors function, which is called with the error messages generated by rjsf.  I need a way to map the error into the schema so that I can extract the proper error message.  Looking at the source this should be as easy as updating validate.js to add the schemaPath to the error message structure.

Something like the following:
```  return errors.map(e => {
    const { dataPath, keyword, message, params, schemaPath } = e;
    let property = ``${dataPath}``;
    // put data in expected format
    return {
      name: keyword,
      property,
      message,
      params, // specific to ajv
      stack: ``${property} ${message}``.trim(),
      schemaPath
    };
  });
```
 

### Steps to Reproduce

Here's a [sample JSFiddle](https://jsfiddle.net/f2y3fq7L/61/) demonstrating that validation doesn't have the schemaPath.

#### Expected behavior

I need to have access to the schemaPath

#### Actual behavior

I don't have access to the schemaPath

### Version

1.0.1

**Comment by doncesarts** [comment]
Hi @dosborne , I do agree that the schema path should be added to the transformErrors function, but a work around for this issue that worked for me  could be the following:

1.- Customize the  transformErrors messages. 
2.-Create `CustomFieldTemplate` https://github.com/mozilla-services/react-jsonschema-form#field-template
`
function CustomFieldTemplate(props) {
  const {id, classNames, label, help, required, description, errors, children} = props;
  return (
    <div className={classNames}>
      <label htmlFor={id}>{label}{required ? "*" : null}</label>
      {description}
      {children}
        <ErrorInline id={id} schema={schema} errors={errors} />
      {help}
    </div>
  );
}
`
3.-Create a custom `ErrorInline` that will work as a wrapper of the Errors returned by AJV, pass the id, schema and errors.  Here iterate over the list of errors of each and update them as needed , you will have access to the schema.
