### ISSUE TITLE
Chained dropdowns - form won't update correctly after schema update

### ISSUE THREAD

**Issue by homemdasneves** [mozilla-services/react-jsonschema-form#840]
### Prerequisites

- I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

[Description of the bug or feature]
I'm trying to nest a couple of dropdowns. The problem is that, after the interaction with the main dropdown, the depended dropdown won't update. If I further interact with the main dropdown, the dependent updates according to previous selection. If I further interact with dependent dropdown, the first selection will fail, but on the second interaction the update to the correct state will happen.
I'm kind of starting with react right now, but this seems more related with the form lifecycle. 

### Steps to Reproduce

1. [First Step]
- select a country: city list won't update, but it should 
2. [Second Step]
- select the other country: city list updates to the previously selected country. From now on it will always list the cities of the previously selected country. When we try to select the city, we can't but that will (somehow) make the city list get in sync with the country list

I'm providing a [sample JSFiddle](https://jsfiddle.net/homemdasneves/vdnkn4ga/2/) 

#### Expected behavior

The dependent dropdown (city), should show the cities of the selected country.

#### Actual behavior

The dependent dropdown (city), won't show the cities of the selected country.

**Comment by homemdasneves** [comment]
Got it working using the same solution as stated [here](https://github.com/mozilla-services/react-jsonschema-form/issues/758), the deep clone did the trick.

**Comment by UtkarshVIT** [comment]
Can you please share your solution? Not being able to do a deep copy

**Comment by eyesmoker** [comment]
Can you please share your solution? Not able to get this working.

**Comment by epicfaace** [comment]
I think you have to do a deep clone.

**Comment by jmaister** [comment]
> I think you have to do a deep clone.

What do you do with the cloned formData after modifying it ?

**Comment by epicfaace** [comment]
@jmaister something like this: https://jsfiddle.net/5wgq2noj/
