### ISSUE TITLE
"should be equal to one of the allowed values" for async field

### ISSUE THREAD

**Issue by weasteam** [mozilla-services/react-jsonschema-form#841]
### Description

I created an Async Select widget out of [react-select](https://jedwatson.github.io/react-select/), this select widget can download/update options based on user input.

### Steps to Reproduce

[Default enum]  -> jsonschema -> Display Select with custom widget -> User type words to search -> The Select update the options -> User choose a new option -> "should be equal to one of the allowed values"

#### Expected behavior

The new options are allowed.

Please let me know:
1. How can I remove this validate
2. Or, how can I added the new options downloaded from async function and make them allowed at the widget level (field).

#### Actual behavior

`Error: should be equal to one of the allowed values`

### Version

"react-jsonschema-form": "^1.0.0",

**Comment by elboletaire** [comment]
I'm having this same issue when trying to create a custom checkbox object which allows an `other` field (with a text input on it, so you can put any text).

Same question here. Can this validation be removed?

**Comment by elboletaire** [comment]
The validation doesn't come from react-jsonschema-form, but from [ajv](https://github.com/epoberezkin/ajv/blob/1c702d639cbf1d97dd8d44822bcaac43b3c4dc6f/lib/dot/errors.def#L102), which, I guess, makes it harder to disable.

**Comment by weasteam** [comment]
After many tests, I think I found the solution:

1. Create function `transformErrors` to remove errors of `should be equal to one of the allowed values`
```
    transformErrors=(errors) =>{
        console.log(errors);
        var e = [];
          errors.map(error => {
            if (error.message !== "should be equal to one of the allowed values"){
                e.push(error)
            }
          });
          console.log(e);
          return e;
    }
```
2. Pass the `transformErrors` to form:

```
<Form
    schema={this.state.schema}
    onChange={this.handleChange}
    formData={this.state.formData}
    transformErrors={this.transformErrors}
/>
```

That is it. It will ignore all validation.

**Comment by weasteam** [comment]
A second option updates the form schema with the new enum. This solution is field specific.

```
    handleChange = (data)=>{
        console.log(data)
        data.formData.name = "bb";
        var e = [
            "option #0",
            "option #1",
            "option #2",
        ];
        e.push("bb")
        this.setState({
            schema: {...this.state.schema,
                properties:{...this.state.schema.properties,
                    name:{...this.state.schema.properties.name,
                        enum:e
                    }
                }
        
            }
        });
        this.setState({formData:{name:"bb"}});
    }
```

**Comment by glasserc** [comment]
I think if the schema can allow arbitrary values, then `enum` isn't really right for this field. Modifying the schema is I guess one option, but maybe you should just override that one widget using uiSchema and provide a select widget that has an initial set of values instead of using `enum` to provide those values.
