### ISSUE TITLE
Access files parts (name, base64 content)

### ISSUE THREAD

**Issue by mnlbox** [mozilla-services/react-jsonschema-form#861]
Hi I add a file field to my form with `"format": "data-url"` and it's return file form me like this:
```
 "image": "data:image/png;name=13.png;base64,iVBORw0KGgoAAAANSUhEUgAAAvoAAAA6CAIAAABOCmofAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3.....
```
I need to get filename and file base64 content separately is it possible?
for example I need get **13.png** and **iVBORw0KGgoAAAANSUhEUgAAAvoAAAA6CAIAAABOCmofAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3.....** in above data.

**Comment by glasserc** [comment]
Parsing data-url syntax is outside the scope of rjsf.
