### ISSUE TITLE
Invalid value passed to array field with defined items structure, breaks the form

### ISSUE THREAD

**Issue by kandl** [mozilla-services/react-jsonschema-form#865]
### Description

Passing invalid value to the array field, which has defined items structure (if not defined, its working ok) breaks the form.

### Steps to Reproduce

1. Define schema
```
{
  "title": "Example",
  "type": "object",
  "properties": {
    "some_array": {
      "title": "Some array",
      "type": "array",
      "items": {
        "title": "Item",
        "type": "string"
      }
    }
  }
}
```
2. Pass invalid value
```
{
  "some_array": "invalid_value"
}
```

Shared playground example:
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzb21lX2FycmF5IjoidGVzdCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJFeGFtcGxlIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic29tZV9hcnJheSI6eyJ0aXRsZSI6IlNvbWUgYXJyYXkiLCJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0aXRsZSI6Ikl0ZW0iLCJ0eXBlIjoic3RyaW5nIn19fX0sInVpU2NoZW1hIjp7fX0=

#### Expected behavior
Displays "Unsupported field schema for field..." message as usually.

#### Actual behavior
Form is not displayed, throws error "Uncaught TypeError: o.map is not a function"

### Version
1.0.1

**Comment by llamamoray** [comment]
@kandl this looks like the same issue I reported in #863 

On my PR branch #864 the error is being handled correctly:
![image](https://user-images.githubusercontent.com/2970147/37201363-6386a336-237f-11e8-9d6b-a23dd4a4d41f.png)

@glasserc Please could you take a look at my PR for this fix?

**Comment by glasserc** [comment]
Closed by #864.

**Comment by llamamoray** [comment]
@kandl you are correct, this is slightly different compared to #864 

What is your use case here? why are you trying to set a string value on an array field?

This error bubbles up to the instantiating form component and you can handle it in a similar way to the way the playground does (a try catch):

https://github.com/mozilla-services/react-jsonschema-form/blob/0ac3dec5d41d30dcafe8588d9a5a079582982290/playground/app.js#L194-L200

If you're using React 16 you can use the `componentDidCatch` lifecycle method in your parent component do display the error in a sensible manner.

**Comment by kandl** [comment]
@llamamoray I want to be safe if user of my app is importing some json which is invalid by the schema.
I want to show error messages for those invalid fields, not to break the whole form.

As you can see, if I pass object to a string field, its ok, it just shows the error message:
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0IjpbXX0sInNjaGVtYSI6eyJ0aXRsZSI6IkV4YW1wbGUiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InRpdGxlIjoiVGl0bGUiLCJ0eXBlIjoic3RyaW5nIn19fSwidWlTY2hlbWEiOnt9fQ==

Passing string to object field also shows error message "should be object".
It would be nice if this behavior would be same for all types of fields, including array fields.

I implemented this functionality by custom SchemaField, but I'm not satisfied with this solution because of future maintanance. It would be much better to have option to display some "InvalidValue" widget, or at least consistent error message for those invalid fields :)

I know about componentDidCatch, but its not failing on validation - it's failing on mapping the string value, so it probably doesn't help me.

Still, thanks a lot for your comments and PR!
