### ISSUE TITLE
Cannot create multiselect custom field

### ISSUE THREAD

**Issue by Armondel** [mozilla-services/react-jsonschema-form#868]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hello there, I desperately need your help!
Is there are any possibilities to create custom multi-select field?

### Version

1.0.1

**Comment by edi9999** [comment]
You can create a multi select like this : 

```
    const schema = {
      type: "array",
      title: "My field",
      items: {
        enum: ["foo", "bar", "fuzz"],
        type: "string",
      },
      uniqueItems: true,
    };
```
