### ISSUE TITLE
All of the validation error messages should start with a capital letter

### ISSUE THREAD

**Issue by Cobote** [mozilla-services/react-jsonschema-form#877]
### Description

All of the validation error messages should start with a capital letter.

### Steps to Reproduce

1. Using the playground validation page
2. Enter invalid text

#### Expected behavior

pass1: Should NOT be shorter than 3 characters
age: Should be number
pass2: Passwords don't match.

#### Actual behavior

pass1: should NOT be shorter than 3 characters
age: should be number
pass2: Passwords don't match.

### Version

1.0.2

**Comment by llamamoray** [comment]
I believe these errors come from the ajv library, but should be an easy change in this library to capitalise the first letter of error messages.

Otherwise you can handle it using the transformErrors prop:
https://github.com/mozilla-services/react-jsonschema-form#custom-error-messages

**Comment by LucianBuzzo** [comment]
I'm closing this issue as the issue involves a different library and a workaround has been provided.
