### ISSUE TITLE
Does it Support patternProperty? If not then when will?

### ISSUE THREAD

**Issue by Shairp** [mozilla-services/react-jsonschema-form#901]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

given an Schema like this:
{
      "type": "object",
     "properties": {
      "Test": {
         "type": "object",
      "title": "Enter text",
       "patternProperties": {
         "^[a-zA-Z0-9]+$": {
          "type": "string",
          "title": "ddddddddddd"
        }
      }
    }
  },
  "additionalProperties": false,
  "uniqueProperties": true
}

#### Expected behavior
a Textbox that I can enter a string that matches the pattern above.

#### Actual behavior

I am getting this Error:
Invalid Test object field configuration:Cannot convert undefined or null to object.

Link: [example](http://localhost:8080/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJUZXN0Ijp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkVudGVyIHRleHQiLCJwYXR0ZXJuUHJvcGVydGllcyI6eyJeW2EtekEtWjAtOV0rJCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJkZGRkZGRkZGRkZCJ9fX19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInVuaXF1ZVByb3BlcnRpZXMiOnRydWV9LCJ1aVNjaGVtYSI6e319)

### Version
1.0.3

**Comment by glasserc** [comment]
No, patternProperty is not supported yet. PRs welcome.

**Comment by Shairp** [comment]
Ok, so can you recommend on JsonSchema -> HTML form that support it?

**Comment by ktalebian** [comment]
@glasserc is this still not supported? I've opened a Question https://github.com/rjsf-team/react-jsonschema-form/issues/1514
