### ISSUE TITLE
Same level json data have different font size

### ISSUE THREAD

**Issue by bgyu** [mozilla-services/react-jsonschema-form#911]
### Prerequisites

- [X ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Same level json data shows different size of font

### Steps to Reproduce
The following is my json data:
``` json
{
  "Indicative Price": 100,
  "QI Restriction": "My QI restriction",
  "WMAS Suspension": true,
  "BOR Sub-Account": {
    "Cash account": true,
    "Margin Long account": false,
    "Margin Short account": true
  },
  "GEOCode to PRCode": [
    {"GeoCode": "VIC", "RRCode": "22"},
    {"GeoCode": "NSW", "RRCode": "test"},
    {"GeoCode": "SA", "RRCode": "44"}
  ]
}
```
Font size of "Indicative Price" is smaller than "BOR Sub-Account" and "GEOCode to PRCode".
This indicates that if an item has sub item, then it will get bigger font size.
#### Expected behavior
Data in the same level has the same font. Upper level has bigger font, lower level has smaller font.
In this case "Indicative Price" should have the same font size as "BOR Sub-Account" and "Cash account" should have smaller font size than "BOR Sub-Account".

#### Actual behavior
"Indicative Price" has the same font size as "Cash account", which is smaller than "BOR Sub-Account".

### Version
``` json
 "dependencies": {
    "bootswatch": "^3.0.0",
    "generate-schema": "^2.6.0",
    "react-jsonschema-form": "^1.0.3"
  }
```

**Comment by glasserc** [comment]
By default, a field which is an object gets a `TitleField` and other fields get a `Label`. See https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/ObjectField.js#L15 and https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/fields/SchemaField.js#L116. These labels are not in any way related to the depth of the field in the JSON Schema. You can of course override this display however you like using the standard template stuff we expose.
