### ISSUE TITLE
How to access a FileWidget's input ref?

### ISSUE THREAD

**Issue by donalmurtagh** [mozilla-services/react-jsonschema-form#912]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
In [this JSFiddle example][2], I've created a form that consists of a single `<input type="file">` field.

An instance of a [FileWidget][3] component is used to render this field, and as you can see in [the source code][4], this stores a ref to the `<input>` element in `this.inputRef`.

I would like to use this ref to manipulate the input field, but I can't figure out how to access the ref from the `componentDidMount` method of `MyForm`?

The source code of the component in the JSFiddle example is:
```javascript
    class MyForm extends React.Component {
      constructor(props) {
      	super(props);   
        this.uiSchema = {};
        this.schema = {
          "title": "Files",
          "type": "object",
          "properties": {
            "file": {
              "type": "string",
              "format": "data-url",
              "title": "Single file"
            },
          }
        }
      };
    
      componentDidMount() {
        // How can I get access to the FileWidget's inputRef property here?
      }
    
      render() {
    	return (
          <Form    
            schema={this.schema} 
            uiSchema={this.uiSchema}
            liveValidate />
        )
      }
    };
```

  [1]: https://github.com/mozilla-services/react-jsonschema-form
  [2]: https://jsfiddle.net/v4dhkku7/1/
  [3]: https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/FileWidget.js
  [4]: https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/FileWidget.js#L98

**Comment by glasserc** [comment]
I don't think there's any way to get access to any widget directly through the form. The widget is only instantiated as a local variable. I guess that goes well with the React philosophy of just rendering a tree of DOM objects. One thing you might be able to do is override the widget with something that has access to a global store of input refs (or, for #921, InputReaders).

**Comment by donalmurtagh** [comment]
Actually, I did find a way to achieve this

```javascript
export default class MyForm extends Component {

  constructor(props) {
    super(props);

    // replace the default FileWidget with one that captures a reference to itself and stores it in this.fileWidget
    this.widgets = {
      FileWidget: (props) => (
        <FileWidget {...props}
                    ref={ref => {this.fileWidget = ref;}}/>
      )
    };
  }
  componentDidMount() {
    // Use the FileWidget ref to access a ref to the <input type="file"> element
    // https://github.com/mozilla-services/react-jsonschema-form#file-widget-input-ref
    const fileInputElement = this.fileWidget.inputRef;

    // If the user elects to upload a file, the 'accept' attribute specifies that only image files may be selected.
    // If the user elects to take a photo, the 'capture' attribute will default a mobile device to the front-facing (non-selfie) camera
    fileInputElement.setAttribute('accept', 'image/*');
    fileInputElement.setAttribute('capture', 'environment');
  }

  render() {
    return (
      <Form widgets={this.widgets} {...this.props}/>
    );
  }
}

**Comment by glasserc** [comment]
Yes, that's what I described. Great. Closing.
