### ISSUE TITLE
Not able to show errors for custom fields

### ISSUE THREAD

**Issue by ssolanki** [mozilla-services/react-jsonschema-form#914]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I am trying to show errors for custom field or custom widget using the library but I am not getting any errors after I clear the data for required field

### Steps to Reproduce

Check this fiddle where I am rendering description as a custom field.

[JSFiddle](https://jsfiddle.net/sahilsolanki07/hdp1kgn6/277/)

### Version

1.0.3 installed with yarn

**Comment by glasserc** [comment]
I guess what's going on is you aren't using the `BaseInput` code path that converts from empty strings back to `undefined`. See for instance https://github.com/mozilla-services/react-jsonschema-form/blob/57061cbd18da30c57a230970a39bdeacd2130ea0/src/components/widgets/BaseInput.js#L26-L28

I guess this isn't a great API/isn't very reusable but I don't really have a good idea what would be better.
