### ISSUE TITLE
Playground's bootstrap version upgrade

### ISSUE THREAD

**Issue by ynevet** [mozilla-services/react-jsonschema-form#915]
Are you going to upgrade the bootstrap CSS to its latest version in the **playground** code? it's currently v3.3.6 which is relatively old in comparison with the latest version (**v4.1.1**):
[https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css](https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css)

Thank you!

**Comment by glasserc** [comment]
Closing as duplicate of #899.
