### ISSUE TITLE
Collapsible form groups based on ALL empty fields

### ISSUE THREAD

**Issue by ivanthemeh** [mozilla-services/react-jsonschema-form#920]
I am curious if anyone is aware of an easier way to make the formGroups in a form collapsible if the inputs in that group are all empty? Please and thanks! I have looked through the docs and havent found anything helpful...other than the enctype attribute but not much docs on that..

**Comment by glasserc** [comment]
No support currently exists in rjsf for collapsible anything. Defining a good UI for such a feature is outside the scope of rjsf given the limited maintenance resources we have available for it. The intended design is that users can add their own functionality to a form by defining a FieldTemplate, which could define its own UI for hiding and showing sections of a form or whatever else makes sense in the project.

I've opened a PR to add this topic to the FAQ (#924).
