### ISSUE TITLE
Example of adding custom array item

### ISSUE THREAD

**Issue by ivanthemeh** [mozilla-services/react-jsonschema-form#923]
### Prerequisites

- [√] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

I am new to JSON and React and am learning quickly.. however I am having trouble understanding some of the concepts in this package and others.. If someone has time I would love and be so thankful to see an example of a robust array field that adds form groups with inner arrays so that I can add a form group to a tab and add items inside the form group with input.. like having an array field with two input fields for type, and name and when the onAddClick function runs it would add a new item with the name as header, the type as the type of field (text,textarea,radio,arrays..etc..) and the the field so that I can edit it. If anyone has time to help me out with this or point me in the right direction I would appreciate it.

**Comment by glasserc** [comment]
It sounds like what you want is a generic form-building library. rjsf isn't intended to help with building arbitrary forms. rjsf has a very specific job, which is to turn a JSON Schema into a form for editing objects that conform to it. The playground has, in the `Arrays` example, a nested array. This might be enough of an example to show you what rjsf is meant for.
