### ISSUE TITLE
Get access to global formData of the form on a custom Field

### ISSUE THREAD

**Issue by remoideas** [mozilla-services/react-jsonschema-form#925]
How can i get the global formData of all the form on the props of custom Field? 

When I show the props of the custom field i get the formData but only of the current field, i need the entry formData of all the form. 

Thanks.

**Comment by doncesarts** [comment]
Hi @remoideas ,
Could you please explain your scenario ? 
Why would you need the complete formData for a field ? 

There could be a work around but without context it is hard to help. 

Regards

**Comment by isychev** [comment]
@remoideas you can user formContext for share formData

**Comment by JamieDixon** [comment]
@isychev Thank you for this answer. I was struggling with the same issue and this really helped.

```
<Form
formContext={formData}
...
 />
```
