### ISSUE TITLE
Validation Attributes

### ISSUE THREAD

**Issue by agatlin** [mozilla-services/react-jsonschema-form#935]
The documentation provides examples of validation attributes like minLength. However, there does not appear to be a comprehensive list of available validation attributes. Can someone please point me in the right direction for this so I can know what is available natively from within this package?

**Comment by doncesarts** [comment]
Hi @agatlin The validation engine of react-jsonschema-form is AJV . 

You can find more info here at AJV github page , https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md

Regards

**Comment by epicfaace** [comment]
Hope that helped @agatlin  -- closing this issue
