### ISSUE TITLE
JSON schema and data conflict breaks the app

### ISSUE THREAD

**Issue by ketysek** [mozilla-services/react-jsonschema-form#937]
Hi,
we use your library in our app and one of our use case is to provide an option to edit json data. But when user fills the json with some unknown properties and save it, the app crashes and it's not possible to fix it without erasing the wrong json data from database. How can I solve this?

**Comment by glasserc** [comment]
I don't really understand your use case. The point of react-jsonschema-form is that you define what properties are allowed and it generates a form allowing you to edit those fields. How are you allowing users to fill in unknown properties? What kind of app is it? How does the app crash?

**Comment by epicfaace** [comment]
@ketysek I'm closing this issue as it's been a while, but if you have more information please feel free to comment!
