### ISSUE TITLE
Disable type validation on a field

### ISSUE THREAD

**Issue by xero88** [mozilla-services/react-jsonschema-form#948]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Is there a way to disable validation of the type on a specified field ?

**Comment by xero88** [comment]
see https://github.com/mozilla-services/react-jsonschema-form/issues/949#issuecomment-396537108

**Comment by abhisawesome** [comment]
<Form  noValidate={true} schema={yourSchema}/>

if noValidate is true it will not validate the form type
