### ISSUE TITLE
alt-date widget doesn't support yearsRange option.

### ISSUE THREAD

**Issue by rohitbishnoi** [mozilla-services/react-jsonschema-form#956]
Looks like the cdn link given in the documentation doesn't contain the fix, I can see that the https://github.com/mozilla-services/react-jsonschema-form/pull/917 is already merged and this feature is already there in master branch.

It is also not working on the live playground at[https://mozilla-services.github.io/react-jsonschema-form/]( https://mozilla-services.github.io/react-jsonschema-form/
)

**Comment by keul** [comment]
@rohitbishnoi that's because no new release on this lib has been done after the merge or #917, while documentation is always "up-to-date" (although this can be confusing indeed).

**Comment by rohitbishnoi** [comment]
Can we do something about this?

Looks like that the package version is also not updated, https://github.com/mozilla-services/react-jsonschema-form/blob/e0192b75d24024370d52a43293931c8ddd769752/package.json#L3

The current version is 1.0.3 in the master branch which contains the fix but the CDN link for the same version is not updated https://github.com/mozilla-services/react-jsonschema-form/blob/e0192b75d24024370d52a43293931c8ddd769752/package.json#L3
