### ISSUE TITLE
Annoying live validation with numeric prefixes

### ISSUE THREAD

**Issue by Y-Less** [mozilla-services/react-jsonschema-form#958]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When live validation is enabled, typing in a negative number will flash up a warning for a moment when typing in negative numbers.  I.e. after having typed only the `-` of `-2`, the live validation will complain that the input should be an integer, despite the fact that that is a valid integer prefix.

The same goes for typing `.` in front of a number.  For a moment the warning flashes up then vanishes, which can be very annoying depending on the type of warning issued.

### Steps to Reproduce

1. Add an integer field.
2. Press `-`.
3. Press another number.

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

Ignore `-` and `.` when they are the only characters in an integer or number field, defer checking that they are the only character till form submission instead.

#### Actual behavior

Flashing warnings.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
It's worth noting that this issue doesn't come up when `ui:widget` is set to `updown`.

**Comment by glasserc** [comment]
This is part of a larger constellation of issues about how we handle numbers. See #674. It's also kind of a problem with how live vaildation works -- it probably doesn't really make sense to validate until we get a `blur`.
