### ISSUE TITLE
Cannot render a form for a valid JSON schema

### ISSUE THREAD

**Issue by pkosiec** [mozilla-services/react-jsonschema-form#963]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The form shows an error for a part of valid JSON schema

### Steps to Reproduce

Provide the folllowing JSON schema (from https://github.com/Azure/open-service-broker-azure):

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "firewallRules": {
      "description": "Firewall rules to apply to instance. If left unspecified, defaults to only Azure IPs",
      "items": {
        "description": "Individual Firewall Rule",
        "properties": {
          "endIPAddress": {
            "description": "End of firewall rule range",
            "type": "string"
          },
          "name": {
            "description": "Name of firewall rule",
            "type": "string"
          },
          "startIPAddress": {
            "description": "Start of firewall rule range",
            "type": "string"
          }
        },
        "required": [
          "name",
          "startIPAddress",
          "endIPAddress"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "location": {
      "description": "The Azure region in which to provision applicable resources.",
      "type": "string"
    },
    "resourceGroup": {
      "description": "The (new or existing) resource group with which to associate new resources.",
      "type": "string"
    },
    "sslEnforcement": {
      "default": "",
      "description": "Specifies whether the server requires the use of TLS when connecting. Left unspecified, SSL will be enforced",
      "enum": [
        "",
        "enabled",
        "disabled"
      ],
      "type": "string"
    },
    "tags": {
      "additionalProperties": {
        "type": "string"
      },
      "description": "Tags to be applied to new resources, specified as key/value pairs.",
      "type": "object"
    }
  },
  "type": "object"
}
```

#### Expected behavior

Rendering the whole form

#### Actual behavior
Rendering the form until the `tags` key appears
```
Invalid tags object field configuration:Cannot convert undefined or null to object.

{"additionalProperties":{"type":"string"},"description":"Tags to be applied to new resources, specified as key/value pairs.","type":"object"}
```

This part is problematic:
```
"tags": {
  "additionalProperties": {
    "type": "string"
  },
  "description": "Tags to be applied to new resources, specified as key/value pairs.",
  "type": "object"
}
```
Commenting it makes the error disappear.

### Version

1.0.3

**Comment by derberg** [comment]
Hi @glasserc , @graingert , @edi9999 
Is this project still being actively developed. We noticed there are many issues without maintainers comments. If you do not have time we would be glad to support and make a pull request for above, but we first need to actually make sure it makes sense or we should rather do fork or research a replacement

**Comment by edi9999** [comment]
If you make a pull request I will review it and merge it if ok. rjsf is in fact not actively maintained.

**Comment by mjasinski5** [comment]
Hello guys :) I wanted to implement this feature in the next days but... wait for it - someone did it before me 👍  Opened today :) We would be super-grateful for review this PR ;)
https://github.com/mozilla-services/react-jsonschema-form/pull/1021

Looks nice, I tested this on our schema&case and it worked fine :)

**Comment by christianclent** [comment]
I'm inside your head...

**Comment by mjasinski5** [comment]
Yea dude its creepy, from now on I will intensively think about features I need and then all I have to do, is waiting :D
Now I know that reading The Power of Your Subconscious Mind by Joseph Murphy paid off 🕺

**Comment by epicfaace** [comment]
@pkosiec @derberg is this still an issue in the latest version?

**Comment by derberg** [comment]
@epicfaace yeap, this is fixed, I think we did some additional PRs for this topic afaik. Tags are handled super nice by the lib
