### ISSUE TITLE
Default widget for number fields

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/react-jsonschema-form#966]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Default widget for numbers seems to be text fields.

### Steps to Reproduce
```js
const Form = JSONSchemaForm.default;
const schema = {
  title: "react-jsonschema-form demo",
  type: "object",
  properties: {
  	rate: {type: "number"},
    percent: {type: "number"}
  }
};
const uiSchema = {
  percent: {
    "ui:widget": "range"
  }
};

ReactDOM.render(<Form schema={schema} uiSchema={uiSchema}/>, 
             document.getElementById("main"));
```

#### Expected behavior

I would expect the serialized value to be an integer or float

#### Actual behavior

Currently the value is quoted as string

**Comment by yankeyhs** [comment]
Hi I want to place class to input instead of it's parent element, But Nothing is documented for this.

check PFA 
red part className I want in green part too.
![Screenshot 2019-12-03 at 1 19 40 AM](https://user-images.githubusercontent.com/13916018/69995983-1b357080-1577-11ea-9e42-72865e0e8612.png)

**Comment by epicfaace** [comment]
@yankeyhs we can't do this now -- you'd have to make your own custom widget in order to do so.
