### ISSUE TITLE
Don't work "readOnly" attribute from Schema

### ISSUE THREAD

**Issue by mrrotberry** [mozilla-services/react-jsonschema-form#976]
### Prerequisites

- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Don't work "readOnly" attribute from Schema, but "ui:readonly" from uiShema work.

I would be very grateful for the response from knowing people what could be the problem.

### Steps to Reproduce

Examle Schema:

```
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "firstName"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
      "readOnly": true
    }
  }
}
```

You can try this Schema on playgroung - https://mozilla-services.github.io/react-jsonschema-form/

### Version

"react-jsonschema-form": "^1.0.3",

**Comment by nathfy** [comment]
A work around that does work is the `"ui:readonly": true` option on the `UISchema` for an element. Eg on https://mozilla-services.github.io/react-jsonschema-form/ amend:

```"firstName": {
    "ui:autofocus": true,
    "ui:emptyValue": "",
    "ui:readonly": true
  },```

**Comment by mrrotberry** [comment]
Why not manage this option in the schema?

**Comment by mrrotberry** [comment]
This realization, if I'm not mistaken, was in here - [link](https://github.com/mozilla-services/react-jsonschema-form/pull/888/commits/006043eb2bb45b2c4f92b4cab63c915942465d48)

**Comment by faissalMT** [comment]
Any updates on this?

**Comment by mrrotberry** [comment]
Unfortunately, I`m waiting too.

**Comment by epicfaace** [comment]
Yep, we should implement the `readOnly` keyword in the schema because it's in the [JSON Schema specification](https://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3). I'd welcome a PR that does this -- any takers @nathfy @faissalMT @mrrotberry ?

**Comment by epicfaace** [comment]
Actually, looks like there's already a PR that implements it #888 -- it just needs to be updated with the docs
