### ISSUE TITLE
Use ui:widget: 'hidden' widget type in array fields

### ISSUE THREAD

**Issue by mike391** [mozilla-services/react-jsonschema-form#977]
### Prerequisites

- [X ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Currently 'hidden' widget types only work for sting, integer, boolean and number fields.  Array needs a hidden widget type as well.

#### Resolved behavior

ui:widget: 'hidden'   should be able to be used for 'array' type fields.

**Comment by lukaskuzmiak** [comment]
+1

**Comment by gerswin** [comment]
+1

**Comment by koosham** [comment]
@epicfaace This feature (hidden arrays) doesn't work with Material UI.

**Comment by epicfaace** [comment]
@koosham could you please make a new issue for that? Thanks!
