### ISSUE TITLE
Array items gets is marked required by default

### ISSUE THREAD

**Issue by gadzet** [mozilla-services/react-jsonschema-form#979]
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
[Description of the bug or feature]

As you can see in the fiddle, array fields are required by default. I was not able to find how to disable it. 

### Steps to Reproduce

https://jsfiddle.net/hdp1kgn6/458/

#### Expected behavior

Fields ar not marked required by default.

#### Actual behavior

Fields are required

### Version

current

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
@gadzet , this is by design -- see the JSON schema spec: https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

Basically, when an array of objects is passed to the `items` property, it requires all those objects to be present. If you want to have an array which doesn't have required items, use an object for the `items` property, like this:

```
const schema = {  
   "type":"object",
   "properties":{  
      "data":{  
      	 "title": "Hello",
         "type":"array",
         "items":{  
               "title":"name",
               "type":"string"
            }
      }
   }
};
```

**Comment by glasserc** [comment]
Nice work solving this @epicfaace !

**Comment by hbjastad** [comment]
@epicfaace / @glasserc, I have the same problem with array items getting marked required. But in the proposed solution, there is just one item - how does this look when the array has multiple items?

**Comment by epicfaace** [comment]
@hbjastad the proposed solution allows for any number of items with the schema `{ "title":"name", "type":"string" }`.

**Comment by hbjastad** [comment]
Yes, got it working with 
      "properties": {
        "prop1": {
          "type": "string",
          "title": "Prop 1"
        },
        "prop2": {
          "type": "string",
          "title": "Prop 2"
        }
}

Thank you, @epicfaace
