### ISSUE TITLE
TypeError: Cannot read property 'definitions' of undefined  

### ISSUE THREAD

**Issue by ceu** [mozilla-services/react-jsonschema-form#980]
![2018-07-18 6 09 54](https://user-images.githubusercontent.com/13114273/42875261-e4ce0b30-8ab5-11e8-8275-2ae747cee409.png)

**Comment by pieplu** [comment]
More details of the code that trigger this bug would be good if you want that ticket usefull.

**Comment by epicfaace** [comment]
I'm closing this, but if you have more information on your issue @ceu , feel free to add a comment.
