### ISSUE TITLE
Investigate and choose a CSS framework

### ISSUE THREAD

**Issue by magopian** [mozilla-services/react-jsonschema-form#99]
Following our decision to not support theming (see #98 and [rationale](https://github.com/mozilla-services/react-jsonschema-form/issues/91#issuecomment-201236773)), we also decided to use a CSS framework to have better styling.

Some options:
- bootstrap
- material-ui (see #39)
- zurb foundation

Once a solution has been chosen, use it, and document the fact that we're using it (and that it's thus very simple to re-use themes/css/js to change the look and feel, layout, behaviour...).

**Comment by n1k0** [comment]
Bootsrtap has been selected.
