### ISSUE TITLE
Autocomplete Attribute doesn't work

### ISSUE THREAD

**Issue by CamDHall** [mozilla-services/react-jsonschema-form#995]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
The documentation states the form attribute for autocomplete is supported, but it doesn't work out of the box. Applying autocomplete="off" to the Form component does not turn autocomplete off in chrome.
[Description of the bug or feature]

### Steps to Reproduce

1. Create a basic form with a couple of text fields. 
2. Submit the form. 
3. Test the form to see if autocomplete is in use, in the chrome browser.

#### Expected behavior

The form inputs should be clear when first rendered

#### Actual behavior

Input fields are populated with text

### Version
1.0.9

**Comment by loganvolkers** [comment]
I wired up [an example](https://codesandbox.io/s/1px3prro4) of setting `autocomplete` and it does set the HTML5 property.

![image](https://user-images.githubusercontent.com/1157086/44745981-0dfd1c80-aabe-11e8-863a-fdfd7cad8c58.png)

It may be that the browser you're using is not respecting this, or that there is a browser extension that ignores the HTML attribute. I'm not an expert on autocomplete, but [there is a good explanation on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) that explains all the differences.

> For most modern browsers (including Firefox 38+, Google Chrome 34+, IE 11+) setting the autocomplete attribute will not prevent a browser's password manager from asking the user if they want to store login fields (username and password), if the user permits the storage the browser will autofill the login the next time the user visits the page. See The autocomplete attribute and login fields.

![image](https://user-images.githubusercontent.com/1157086/44746108-4dc40400-aabe-11e8-8df5-8ba256a9f5f2.png)

**Comment by epicfaace** [comment]
Thanks @loganvolkers . @CamDHall I'm closing this issue; but if you have any questions/problems feel free to leave a comment.
