### ISSUE TITLE
Validation for custom widget components

### ISSUE THREAD

**Issue by lucaspalencia** [mozilla-services/react-jsonschema-form#999]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When created a custom widget the default validation for required fields stop working

### Steps to Reproduce

1. Create a `TextWidget`:
```
import React from 'react'
import InputMask from 'react-input-mask'

const TextWidget = props => {
  if (props.schema.maskType === 'time') {
    return (
      <InputMask className='form-control' id={props.id} label={props.label} required={props.required} type='text' value={props.value} mask='99:99:99' formatChars={{'9': '[0-9]'}} maskChar={null} onChange={(e) => props.onChange(e.target.value)} />
    )
  }

  return (
    <input className='form-control' id={props.id} label={props.label} required={props.required} placeholder={props.placeholder} type='text' value={props.value} onChange={(e) => props.onChange(e.target.value)} />
  )
}

export default TextWidget
```
2. Import and add this widget to form:
```
const schema = {
    type: 'object',
    required: ['name', 'startTime', 'endTime'],
    properties: {
        name: {type: 'string', title: 'Nome'},
        startTime: {type: 'string', maskType: 'time'},
        endTime: {type: 'string', maskType: 'time'}
    }
}

const widgets = {
    TextWidget
}

<Form
    schema={schema}
    widgets={widgets}
    formData={myFormData}
    liveValidate
    showErrorList={false}
>
```

#### Expected behavior

I expect the default validation for required fields to appear when I do not fill anything on the fields.

#### Actual behavior

The default validation for required fields does not appear.

### Version

1.0.3

**Comment by dmethvin-gov** [comment]
Did you really mean to override the [default `TextWidget`](https://github.com/mozilla-services/react-jsonschema-form/blob/51d403ab448326183f58b5cc7c2c750c200f0242/src/components/widgets/TextWidget.js) I wouldn't think that is a good idea, it wraps `BaseWidget` and redefining it no doubt messes with some important expectations in the current code. The README [describes how to define alternative (custom) widgets](https://github.com/mozilla-services/react-jsonschema-form#alternative-widgets).
